### ISSUE TITLE
Video.js not working in IE11

### ISSUE THREAD

**Issue by syammohanmp** [videojs/video.js#1021]
Please check your website homepage in IE11. Its not working. I think that IE11 not support HTML5 video tag. Your library now placed html5 video tag instead of .swf file into the document  in IE11.

**Comment by bwatkins79** [comment]
I know this is way old, but I had the same error happen to me. It turned out I needed to add the mime types for the file formats used to IIS

**Comment by wasif1024** [comment]
Main issue is that it does not works properly in simple .html file in IE

**Comment by Soviut** [comment]
A client was experiencing the same issue with IE11 in Windows 7 with videos I had stored on S3.

It turns out the Content-Type on S3 were set to `binary/octet-stream` so I changed them to `video/mp4`. Interestingly, webm videos were already set correctly to `video/webm`.

![video-mime-type](https://cloud.githubusercontent.com/assets/226882/12307982/b4cbfad2-ba10-11e5-935e-f4c6fd75aaef.png)

**Comment by dzivalli** [comment]
Got feedback from customer that video doesn't play in ie 11, installed windows 7 and ie 11 and have got a bunch of errors in js console even on videojs.com site. Screenshots attached.
![3](https://cloud.githubusercontent.com/assets/8066888/12313693/b1f6a600-ba1e-11e5-814a-49d7a9af1c1f.png)
![2](https://cloud.githubusercontent.com/assets/8066888/12313691/b1f055de-ba1e-11e5-86ab-39296022aeb2.png)
![1](https://cloud.githubusercontent.com/assets/8066888/12313692/b1f0e742-ba1e-11e5-98ee-27325050bbe3.png)

**Comment by dpurrington** [comment]
2018. Still happening.

**Comment by gkatsev** [comment]
What is "still happening"? This particular issue has been closed since 2014 and I just tested videojs.com and it is working fine on IE11 in Win7, Win8.1, and Win10, granted via browserstack, but it still gives a pretty good indicator. I've also previously seen it work on actual windows machines.

If you have an issue with Video.js and IE11 can you open a new issue with details around what is happening? Please be as detailed as possible while filling out the issue template, please. Even better if you can provide a reduced test case for us to take a look at.

Thanks.
