### ISSUE TITLE
dispose() method removes the video element from HTML

### ISSUE THREAD

**Issue by smohadjer** [videojs/video.js#1023]
I can't find any method in the API docs that would allow me to reset changes done by video.js so that DOM would be exactly as it was before video.js is initialized. Usually destroy() method of plugins does so, but all I could find here was a dispose() method which seems to remove the video element from the markup as well. The video element was not inserted by video.js and should remain accessible (via browser's native HTML5 video player) after video.js player is destroyed.

**Comment by tamlyn** [comment]
Another use case into the mix: the responsive site I'm working on uses VideoJS at larger screen sizes but the native player at smaller sizes. The site is designed to bind/unbind behaviours as the breakpoint is crossed (which happens when an iPad is rotated, for instance). Ideally I would init VJS when switching to large layout and uninit it when switching to small. 

I know I can work around this but it means making an exception to the way all other components on the site are designed and it feels messy.

**Comment by mmcc** [comment]
@tamlyn rather than init / dispose the player when switching back and forth, would it be easier to turn on / off native controls?

**Comment by elbecita** [comment]
I have similar scenario where I use videojs as a fallback, but would like to restore the original video element in some cases. It is this still a functionality wanted? If so, I could make a PR that would store the original html element when videojs is initialized, and restore it with a new method in the API, like restore or reset.
Will that be useful or is it something similar already?

**Comment by RobertLowe** [comment]
Re-open? This would be nice when switching from say a video (hls) to a `MediaStream` smoothly, I noticed videojs does a lot of `requestAnimationFrame` needlessly when using `URL.createObjectURL(stream)` or attaching a stream via `srcObject`. Seems the player hasn't moved forward to work with WebRTC nicely?
