### ISSUE TITLE
Could use a good way to get the current tech name

### ISSUE THREAD

**Issue by dominic-p** [videojs/video.js#1234]
It would be nice if there was a reliable way to get the current tech. It could be as simple as exporting `player.techName`, and I could throw together a pull request, if that would help.

This came up when working on the Google Analytics plugin. See the [issue here](https://github.com/mickey/videojs-ga/issues/4).

**Comment by NekR** [comment]
So what is the problem of not exporting tech info? Will break something? Or you care about few bytes. This strange that everytime when people wants to do some hacks with videojs they need ask you to implement them in videojs itself.

I do not like what videojs uses native fullscreen on android and particularly, in my case, that fullscreen is not useful. So I changed behavior of it to use full-window instead, but I cannot do it with minified version because tech info is not exported.

Can you please remove support of native fullscren on Android Stock Browser?

**Comment by NekR** [comment]
```
player.supportsFullScreen()
video.js:23 VIDEOJS: Video.js: supportsFullScreen method not defined for Html5 playback technology.
TypeError: undefined is not a function {stack: (...), message: "undefined is not a function"}
```
This also seems nice. One method on player is exported, but same method on tech not.

**Comment by heff** [comment]
@NekR the problem has already been explained, but in version 5.0 we are moving away from closure compiler (variable mangling) so you will be able to do whatever you want.

You should open a new issue for the fullscreen discussion.

**Comment by AlicanC** [comment]
Or maybe you could use a bad way to get the current tech name:
```javascript
var getTech = function getTech(vjsPlayer) {

  for (var key in vjsPlayer) {
    if (vjsPlayer[key] instanceof videojs.MediaTechController) {
      return vjsPlayer[key];
    }
  }

};

var getTechName = function getTechName(vjsPlayer, tech) {

  if (!tech) {
    tech = getTech(vjsPlayer);
  }

  for (var key in videojs) {
    if (typeof videojs[key] === 'function' && (videojs[key].prototype instanceof videojs.MediaTechController)) {
      if (tech instanceof videojs[key]) {
        return key;
      }
    }
  }

};

var a = videojs('mainPlayer');

var tech = getTech(a);
var techName = getTechName(a);

console.log(tech, techName); // [object Object], "Youtube"
```

**Comment by gjutras** [comment]
We found one use case.  We want to check the flash player version if they're playing flash and show an upgrade warning if they're using flash player prior to 12.  I'll be using the examples above to get it.  But there is another use case for why.
