### ISSUE TITLE
Dynamically change RTMP source

### ISSUE THREAD

**Issue by bmeine** [videojs/video.js#1399]
I'd like to be able to dynamically change the RTMP src of the player so I can implement a rough adaptive bitrate solution over RTMP. The problem is when I try to set the src it freezes. Below is a jsfiddle with a simplified version just using a timer to change the src. I actually tried a few different suggestions I'd found, but none worked. This seemed like the most likely solution, but I could be completely wrong...and probably am :)

http://jsfiddle.net/Gkzqw/2/

Any idea why this is happening?

**Comment by Obbi89** [comment]
Additionally to that (maybe related) I added a button to the videojs controls which allows to switch streams on my streaming server; but changing sources simple doesn't do anything.

Setup: nginx + arut/rtmp-nginx-module ; live setup; obs-studio

If I do player.src({src: "rtmp://ip/live/streamname", type: "rtmp/flv"}); window.setTimeout(function() { player.load(); }, 2000) it works somehow. Seems it is not loading media correctly or crashing while loading.
If you need some more information or a demo i could try to provide one.

**Comment by gkatsev** [comment]
In videojs 5, we're no longer doing the super compression, so, it should be better.
Also, if this is still an issue, a PR would be welcome but it's unlikely that any of the core members will work on it due to the decline of Flash in recent years. Because of this, I'm going to close this issue but we would still be open for bug fix PRs.
