### ISSUE TITLE
Dev Vs Prod

### ISSUE THREAD

**Issue by tomul** [videojs/video.js#1491]
Hi,
I'm trying to use videojs 4.7 with support for youtube (https://github.com/eXon/videojs-youtube). While using the development version of videojs (video.dev.js), it works, but if i use the minified (video.js) version it breaks in IE10 (windows 7) for a youtube video, when clicking the fullscreen button.  The tech has the required methods, but `supportsFullScreen()` is never called. Instead it just throws an error: Object doesn't support property or method 'Ea'. If i add a method ``` videojs.Youtube.prototype.Ea= function() {
    return false;
  };```` it works, but i don't think this should be the fix. Using videojs 4.8, with the proper modifications for videojs-youtube, doesn't fix it, the same error is shown.
Please check: http://jsbin.com/waliv/1/edit

Thank you

**Comment by rodincave** [comment]
Hi, we have a similar issue with our videojs tech plugin ( it's a plugin to integrate peer-to-peer video streaming, you can see it working here: http://www.streamroot.io/demo?url=http%3A%2F%2Fakamai.streamroot.edgesuite.net%2Fvodorigin%2Ftos.mp4%2Fmanifest.mpd )

The issue is that you can't really create a Tech with the videoJS plugin API, and so all the other techs seem to only work with the unminified dev version of videojs, and crash with the minified version.

I am not sure the issue is exactly the same, or if I should open another issue concerning custom techs creation and videojs minifying ?

**Comment by heff** [comment]
@rodincave we'll be addressing this to some degree in 5.0, by not mangling object properties. Otherwise we would need to get more specific about which APIs are needed and not available in the minified version.

**Comment by rodincave** [comment]
Thanks, I'll have to recheck the error to confirm this, but from our code I would say that what we are missing is the access to MediaTechController. 

you can take a look at our tech provider here:
http://files.streamroot.io/release/1.0/wrappers/videojs/streamroot.wrapper.js

**Comment by norlin** [comment]
Hi, have the same issue with minified videojs version.
> Object doesn't support property or method 'Ea'

Referencing to the `this.tech.supportsFullScreen()` in player.js (uncompressed code)

**Comment by mmcc** [comment]
Now that we've moved away from Closure Compiler (#1586) this shouldn't be an issue in Master.
