### ISSUE TITLE
timeupdate event is fired even when video is stalled due to buffering

### ISSUE THREAD

**Issue by jpfranco** [videojs/video.js#1641]
So this is a bit tricky to reproduce. I think the easiest way is to use Network Throttling on Chrome dev tools' mobile emulator (3G setting seems to work best), and this fiddle which prints the event object every time the event is fired:

http://jsfiddle.net/z1vqrs8y/2/

If you just let the video play without interfering, everything will work as expected. The event will stop firing every time that playback stalls. However, once you seek to another time you'll notice that the event will keep on being fired even when playback stops due to buffering.

The event object seems to be much smaller when the event is fired while playback is stalled:

![screen shot 2014-11-04 at 2 55 47 pm](https://cloud.githubusercontent.com/assets/1322503/4909902/6f72d242-6478-11e4-8d13-4cdb7c2af0ac.png)

This is how it usually looks:

![screen shot 2014-11-04 at 2 55 59 pm](https://cloud.githubusercontent.com/assets/1322503/4909910/7b4116f6-6478-11e4-833e-7e5a477720a1.png)

Btw, earlier today I commented on #1431 which seems to also occur only after seeking. Maybe it's all related to stuff not being properly reset after seeking?

**Comment by gkatsev** [comment]
I believe this is fixed in videojs 5. We no longer attach the `play`/`pause` events for `manualTimeUpdatesOn` to the player.

**Comment by danavangard** [comment]
gkatsev, you mentioned "_I believe this is fixed in videojs 5. We no longer attach the play/pause events for manualTimeUpdatesOn to the player._"

But for me at least, before videojs 7.11.4 up to the latest version, the "`timeupdate`" still keeps running _after_ the player gets paused. I manage to replicate this annoyance by using a custom slider of `input type range` whose focus or click dynamically pauses the player ( `videojs.pause()` ) immediately before seeking with the slider's "`input`" event ( `videojs.currentTime(slider.val())` ). This only happens if the player was _playing_ prior to seeking with the slider. If I would stop the player via a custom button ( `videojs.pause()` ), then go to my slider and move the handle, the "`timeupdate`" event will stop after I release the slider handle.

I gather in the former manner the slider, while the video is playing, being a `range input`, _trips_ the "`timeupdate`" event while sliding, which "`timeupdate`" gets stuck and doesn't stop on its own this way once the slider is not used anymore. This means "`timeupdate`" is running in the background while other code is being used, which makes for erratic seeking behavior which must be avoided in my application.

Any thoughts on how I can detach the "`timeupdate`" event from my slider?

**Comment by danavangard** [comment]
> I believe this is fixed in videojs 5. We no longer attach the `play`/`pause` events for `manualTimeUpdatesOn` to the player.

But for me at least, before videojs 7.11.4 up to the latest version, the "`timeupdate`" still keeps running _after_ the player gets paused. I manage to replicate this annoyance by using a custom slider of `input type range` whose focus or click dynamically pauses the player ( `videojs.pause()` ) immediately before seeking with the slider's "`input`" event ( `videojs.currentTime(slider.val())` ). This only happens if the player was _playing_ prior to seeking with the slider. If I would stop the player via a custom button ( `videojs.pause()` ), then go to my slider and move the handle, the "`timeupdate`" event will stop after I release the slider handle.

I gather in the former manner the slider, while the video is playing, being a `range input`, _trips_ the "`timeupdate`" event while sliding, which "`timeupdate`" gets stuck and doesn't stop on its own this way once the slider is not used anymore. This means "`timeupdate`" is running in the background while other code is being used, which makes for erratic seeking behavior which must be avoided in my application.

Any thoughts on how I can detach the "`timeupdate`" event from my slider?
