### ISSUE TITLE
Consider making triggerReady async

### ISSUE THREAD

**Issue by gkatsev** [videojs/video.js#1667]
The internal function triggerReady should probably be made async itself, trigger the actual handlers should be sync.
There's already a place in the code-base where there are issues encountered from it: https://github.com/videojs/video.js/blob/caf44a4ad3a2b885bbff03fc9f092e231c57bbc3/src/js/tracks.js#L61-L69 and I've encountered the same issue with related tracks work.

**Comment by heff** [comment]
@gkatsev if you want to respond to my comments here we could try to change this for 5.0. Otherwise it might wait awhile.

**Comment by heff** [comment]
Had another thought on the performance issue here, and as long as the tech isn't reliant on the ready event, this shouldn't inhibit fast load. Confirming and adding to 5.0.

**Comment by gkatsev** [comment]
Also, this would make the two techs work closer to each other.

**Comment by dmlap** [comment]
Dissenting (but possibly unrealistic) opinion: HTML guarantees synchronous `<video>` readiness. I think we should be aiming for that level of simplicity for video.js users.

**Comment by gkatsev** [comment]
If we can make flash load in synchronously, I'd be 100% for that. But whatever route we choose, it should be the same regardless of what tech is loaded.

**Comment by heff** [comment]
Yeah wow, good point @dmlap, this is a conflict of probably our two biggest principles.
- The player should work just like the video element
- Techs should work the same as each other

If everything was synchronous then we wouldn't need a ready event. So I still think this is the right direction for this feature.

We still have #1728 and the web component direction where we might push harder on synchronicity, since you'll be working directly with an element. We already do, and can do more of a few things:
- Return default values for player properties before the tech is ready
- Queue method calls like `play`, that are async in nature, while the tech is loading

You can't do everything synchronously on the video element (e.g. set currentTime), so that helps.
