### ISSUE TITLE
Control bar layout issues when player width is small

### ISSUE THREAD

**Issue by OwenEdwards** [videojs/video.js#1733]
I understand that support for the <audio> tag is not complete (#537), but just wanted to flag that the control bar does not layout correctly (I'm using Chrome Version 39.0.2171.71 on Win 7) when playing audio. Specifically, the Mute button gets dropped below the control bar unless the width is specified; see this from @tim-peterson's demo at http://tim-peterson.github.io/videojs-playlist/.

![video.js <audio> controbar layout issue](https://cloud.githubusercontent.com/assets/2245205/5371529/26185f0a-7fed-11e4-9638-28023d0f806d.png)

Also, if the "poster" is not present in the HTML, it seems like the window size should just be the controlbar size, and the Fullscreen button should be omitted.

**Comment by mmcc** [comment]
FWIW, the new base theme layout doesn't have this issue. I'm kicking around the idea of player size, so we can automatically hide elements when a player goes below a certain width. Think similar to media-queries, but we basically have to implement them ourselves since we only care about the width of the player component and not `window`.

**Comment by mmcc** [comment]
This should be fixed in the most recent skin.
