### ISSUE TITLE
Captions (or subtitles) rendered behind the control bar when playing <audio>

### ISSUE THREAD

**Issue by OwenEdwards** [videojs/video.js#1735]
While trying captions with audio (see http://jsbin.com/kudeme), I notice that the captions (or subtitles) slide under the controlbar after some time when not hovering over the controls. I don't know if this happens with video too (I'm guessing it's something to do with the controlbar disappearing during video playback, and this being prevented for audio playback?), but it makes the captions basically unusable with audio.

**Comment by OwenEdwards** [comment]
@heff I don't have examples, other than the [JSBin demo](http://jsbin.com/kudeme) I threw together. I looked around at other players, and MediaElement.js handles it differently (see http://jsbin.com/qitude), but I didn't find an ideal solution. It's really not clear where audio captions should be rendered if there isn't a poster image (or if the poster image is small, etc); I asked @cgiffard about [Captionator](https://github.com/cgiffard/Captionator), and [he](https://twitter.com/cgiffard/status/542542584715812864) [said](https://twitter.com/cgiffard/status/542542688042508288) "It’s been ages since Captionator has been actively maintained [...] I speculated that you’d give the user an option to specify a custom div, into which the caption elements would be rendered."

The use case came from a colleague in the accessibility world, and I'm imaging something like this page: [Ozymandias by Percy Bysshe Shelley : The Poetry Foundation](http://www.poetryfoundation.org/learning/guide/238972#poem), with the audio player and the text connected. Or like this video: [Stephen Fry Kinetic Typography - Language - YouTube](https://www.youtube.com/watch?v=J7E-aoXLZGY). But, at that point, you're really talking about a 'transcript' rather than 'captions', as in [OzPlayer](http://www.accessibilityoz.com/ozplayer/).

This seems to really fall between the cracks in the [HTML5 Audio element spec](http://www.w3.org/wiki/HTML/Elements/audio) and the [HTML5 WebVTT spec](http://dev.w3.org/html5/webvtt/). I wonder if @silviapfeiffer has some thoughts.

**Comment by silviapfeiffer** [comment]
So, since audio elements by default don't have a display area, there is no space to render the captions. Thus, you need to use a video element to get the captions displayed. In that case, even if there is no video track, you get the poster's dimensions or the default video dimensions to render the captions. The behaviour of the controls need to be the same though, independent of whether you have a video track or not.

**Comment by OwenEdwards** [comment]
@silviapfeiffer interesting, so a video element must _always_ handle all of the features of an audio element in a given User Agent (e.g. supported codecs)? If not, wouldn't there would be some loss of functionality if  page author played an audio track with a video element to support WebVTT subtitles/captions?

And, just to clarify, if an audio element is authored with an associated track element (for subtitles/captions) but does not have a display area, then the UA will ignore the track and not display a CC control? Does that comply with [UAAG 2.0](http://www.w3.org/TR/UAAG20/)?

**Comment by silviapfeiffer** [comment]
@OwenEdwards I guess so - hadn't really thought of it in that way.

As for UAAG 2.0 compliance for audio: does UAAG 2.0 require the display of captions for audio? IIRC it was sufficient to have a transcript - and seeing as a deaf person doesn't get any additional information from playing back a audio file (like a visual track), reading a transcript is more useful.

Note that the content of the track element of a audio element still gets exposed via the TextTrack API, so the JS developer can do with it what they want. I think therefore the controls could still expose a CC button, since you can still activate/deactivate the track. There's just no default rendering area.

**Comment by OwenEdwards** [comment]
@silviapfeiffer in UAAG 2.0 "[Guideline 1.1 - Provide access to alternative content](http://www.w3.org/TR/UAAG20/#gl-access-alternative-content)", specifically "1.1.1 Render Alternative Content", it requires that a UA renders "any type of recognized alternative content", and defines "[alternative for time-based media ... includes alternatives for audio such as captions](http://www.w3.org/TR/UAAG20/#def-conditional-content)".

The HTML5 and WebVTT standards seem to say that this is valid:

``` html
<audio controls>
    <source src="demo.mp3"/>
    <source src="demo.ogg"/>

    <track kind="captions" src="demo.vtt" srclang="en" label="English" default></track>
</audio>
```

but you're saying that a UA wouldn't render the captions without additional JS; I'm just not clear where that falls in UAAG 2.0 and WCAG 2.0.

Certainly, at this point we're blurring the line between transcript and captions, but I don't see that there's a way in HTML5 to syntactically associate a transcript in-page with the audio element. This in turn has accessibility and metadata/search implications; it seems like it ought to at least raise some kind of validator warning!

**Comment by silviapfeiffer** [comment]
Register a bug if you think so.

Also, markup for transcripts has been under discussion at the W3C but not been resolved.
