### ISSUE TITLE
mp4's Don't Play on iPad

### ISSUE THREAD

**Issue by marypearson** [videojs/video.js#1776]
My mp4's don't play on iPad.  Please see new website at http://maryswebsites.ca/

I have a sprout/leaf growing for the logo with grass growing underneath.  It works fine on my Mac but not on iPad.  I have tried using conversion programs to convert specifically for iPad but to no avail.  

Would appreciate any help.

Thank you!

**Comment by mmcc** [comment]
Is there a specific page on the website that I need to go to for the video? Are you trying to use a video for your logo? I would suggest not going that direction since mobile devices wouldn't play very nice with that approach. Pretty much all mobile devices block preloading (due to bandwidth concerns), and that's not even getting into the troubles around inline playback.

Good luck! If you'd like to keep the animation aspect, you might want to consider showing an animated GIF (just keep size in mind).

**Comment by marypearson** [comment]
Thank you.  I have tried it as logo and then tried it in sidebar widget.  At this point I have removed it and am going to try another template but it is the same for all my videojs websites.  Please view http://awesomewebsites4u.com/ or http://longfarms.ca/ or http://mapenterprises.info/  None of them work on iPad.  Thank you.

**Comment by mmcc** [comment]
Yeah, that's the kind of usage that is simply always going to give you trouble on a mobile site. Sadly there's nothing we can really do about this, so I'd honestly avoid autoplaying, inline videos on mobile devices (you can use something like [media queries](https://developer.mozilla.org/en-US/docs/Web/Guide/CSS/Media_queries) to hide the videos on mobile devices if it's messing up your layout).

**Comment by tomorrowbetter** [comment]
iPad only support MP4 encoded with H.264 or MPEG-4.
If the MP4 encoded with other code, we will failed to play MP4 on iPad, in this case, we had better convert MP4 to iPad more supported MPEG-4 MP4 or H.264 MP4
Step by step guide at http://www.idealshare.net/ipad-ipod-iphone/convert-mp4-to-ipad.html
