### ISSUE TITLE
How to setup rtmp flv framerate

### ISSUE THREAD

**Issue by yurevich1** [videojs/video.js#1808]
My input framerate is 5 fps. But the player show it as 25 fps. how to fix it? Audio stream works normally. Video stream fast show 5 frames after that freeze for a second. Is it possible to setup?

**Comment by mmcc** [comment]
I don't know enough about RTMP playback in the SWF, but I believe the default is set to 30 for the SWF, so if you're actually seeing 25 fps, that implies that the player is adjusting to what it thinks the stream is. Could it be an issue with your RTMP stream's metadata?

Regardless, I think this issue is probably a better fit for the [SWF repo](https://github.com/videojs/video-js-swf). Mind opening an issue there?
