### ISSUE TITLE
"FC subscribe" support for Edgecast RTMP?

### ISSUE THREAD

**Issue by egasimus** [videojs/video.js#1846]
From [JW Player support](http://support.jwplayer.com/customer/portal/articles/1430358-using-rtmp-streaming):
>**FC Subscribe**
>When streaming RTMP live streams using the Akamai, Edgecast or Limelight CDN, players cannot simply connect to the live stream. Instead, they have to subscribe to it, by sending a so-called FC Subscribe call to the server. JW Player includes support for this, using the RTMP subscribe option: *[...]*

I currently find myself replacing a JWPlayer-based installation with Video.js. One of the requirements involves displaying a RTMP stream hosted at Edgecast. I am soon to try the [suggested solution on StackOverflow](http://stackoverflow.com/questions/25297161/video-js-does-not-subscirbe-to-the-live-stream):

> I compiled video-js-swf manually and modified the RTMPVideoProvider implementation to call FCSubscribe during the NetStream initialization.
>_nc.call("FCSubscribe", null, _src.streamURL);

I wonder why an option for this isn't already implemented from VJS, though. Any thoughts?

**Comment by heff** [comment]
Hi @egasimus, sorry for the delayed response. RTMP support in Video.js has been built entirely by community contributors over time. If there's a specific feature you're looking for we welcome any pull requests. Otherwise I couldn't really tell you why it hasn't been an issue before.

If you're still interested we should open an issue on [the swf project](https://github.com/videojs/video-js-swf). Closing this one for now.
