### ISSUE TITLE
Safari won't play mp4 if avi is also listed

### ISSUE THREAD

**Issue by szabgab** [videojs/video.js#1851]
For historical reasons I had 4 copies of my video (ogv was the original and I converted it to avi a while ago, recently I also converted it to .webm and .mp4) In the player all 4 were listed as options in the order of avi, mp4, ogv, webm  and Safari refused to play.

Once I removed the avi version of the file, Safari also started to work.

(Using version 4.11 of video.js)

I don't think this needs to be fixed, but maybe this information could be added to the docs.
Or maybe having it here is enough.

**Comment by heff** [comment]
Thanks for letting us know @szabgab. Did you by any chance see any errors when this was happening, or any chance of setting up a live demo, e.g. [a jsbin](http://jsbin.com/axedog/edit)?

My initial though is Safari is saying it can support the AVI but then chokes on it because of some internal file issue.

**Comment by heff** [comment]
Closing as this doesn't require changes to the core project, but feel free to continue to discuss.
