### ISSUE TITLE
Remove lang/zh.js file from build

### ISSUE THREAD

**Issue by Globulopolis** [videojs/video.js#1878]
According to latest changes in language files I suggest remove zh.js file from build because he not needed anymore.

PS! For more info see PRs https://github.com/videojs/video.js/pull/1729 and https://github.com/videojs/video.js/pull/1841

**Comment by heff** [comment]
Interesting. I don't know why that would still be in the dist. There's no zh.json in [the lang folder](https://github.com/videojs/video.js/tree/master/lang). There must be something with our language build step.

@seniorflexdeveloper can you tell what might be going on here (since you originally put together the grunt task)?

**Comment by gkatsev** [comment]
It's in the dist: https://github.com/videojs/video.js/tree/v4.12.0/dist/video-js/lang
@heff maybe you still had the file locally when making the build?

**Comment by heff** [comment]
...that's probably what it was​

**Comment by seniorflexdeveloper** [comment]
@heff - I'm not sure what language that is. It's definitely not in our standard array. Also the grunt task just normalizes the JSON -> JS process and src/dest locations.

**Comment by heff** [comment]
Yeah, I think the issue here is that we need to add a step in the dist process that clears out any existing files.
