### ISSUE TITLE
Player reports duration short by 1-2 seconds

### ISSUE THREAD

**Issue by anushyakumar** [videojs/video.js#1882]
The following players report the total duration of the video to be 1-2 seconds shorter.
This is especially noticeable on short videos; 

(8.5s video, duration 7) http://players.brightcove.net/1534342421001/c87e616f-fb0b-47b9-a65c-68592e639197_default/index.html?videoId=3766959033001
(5.9s video, duration 4) http://players.brightcove.net/1872491397001/b9d6b77a-e8aa-4935-8812-822ed63b02f8_default/index.html?videoId=3843617566001
(815.1s video, duration 814) http://players.brightcove.net/1872491397001/b9d6b77a-e8aa-4935-8812-822ed63b02f8_default/index.html?videoId=3454447936001

**Comment by mmcc** [comment]
From a little spot checking, it looks like this is due to the manifests having an incorrect duration.

For example, the rendition manifest from the 8.5 / 7 video:

```
#EXTM3U
#EXT-X-TARGETDURATION:10
#EXT-X-MEDIA-SEQUENCE:0
#EXTINF:7,
/* Segment URL */
#EXT-X-ENDLIST
```
I'm not sure if there's much the player can do here if the manifest is incorrectly reporting itself. Either way, this issue probably belongs to the [contrib-hls project](https://github.com/videojs/videojs-contrib-hls).
