### ISSUE TITLE
Closing tag isn't supposed to be on <source> elements

### ISSUE THREAD

**Issue by baloneysandwiches** [videojs/video.js#1906]
Nit: Looking at setup.md. According to <a href="http://www.w3.org/TR/html-markup/source.html">spec</a> it should be:

    <source src="http://video-js.zencoder.com/oceans-clip.mp4" type='video/mp4'>
not

    <source src="http://video-js.zencoder.com/oceans-clip.mp4" type='video/mp4' />

No closing slash. "The source element is a void element. A source element must have a start tag but must not have an end tag." Since the setup page is a pretty well-consulted reference point I think it's good to get this right and not spread XMLism where it will simply later need to be unlearned. Thoughts?

**Comment by mmcc** [comment]
So, just to nit right back, technically this is valid. The source tag is a [void element](http://www.w3.org/html/wg/drafts/html/master/#void-elements).

> Then, if the element is one of the void elements, or if the element is a foreign element, then there may be a single U+002F SOLIDUS character (/). This character has no effect on void elements, but on foreign elements it marks the start tag as self-closing.

In HTML5, therefore, `<source />` === `<source>` (threequal for the JS love).

So, return-nit aside, since it doesn't matter either way, I'm not opposed to changing it. :) I'm going to close this since it's not an issue per say, but feel free to submit a PR to update the docs (preferably with more than *just* that change, so maybe dig up some others). Thanks for the help!!

**Comment by heff** [comment]
Old IE doesn't know the source tag is supposed to be self closing so it
puts everything after it inside of it.

**Comment by gkatsev** [comment]
Heh, of course, oldIE ruins it for everyone.
