### ISSUE TITLE
Guidelines on video.js vs video.dev.js

### ISSUE THREAD

**Issue by ksheurs** [videojs/video.js#1910]
Are there any guidelines on the usage of these two? I'd like to use video.js in production, but I find a lot of the plugins I use fail on references like `vjs.*`, `videojs.Flash.formats`, and `this.options_`.

Is it possible to do any custom work with video.js?

**Comment by mmcc** [comment]
Honestly, if you have your own build pipeline I would just use the dev version since presumably you'll be doing minification on your end anyway. What plugins are you using that are relying on `vjs` and `options_`?

Long term, we're doing away with closure compiler in 5.0, so hopefully this won't be a problem much longer! (#1586)

![soon](http://i2.kym-cdn.com/photos/images/newsfeed/000/117/008/soon_honey_beer_bottle.jpg)

**Comment by ksheurs** [comment]
Cool that works!

1) https://github.com/vidcaster/video-js-resolutions uses `vjs`.

2) I'm doing the following to let HLS play in Flash via https://github.com/mangui/video-js-swf: 
`if (!Modernizr.hls) { videojs.Flash.formats['application/x-mpegurl'] = 'M3U8'; }`

3) Lastly, I'm doing the following to do some custom work around resolutions. I couldn't find another way to find all of the set sources for videojs.
`this.options_['sources']`

Open to suggestions on all of these. Thanks!

**Comment by gkatsev** [comment]
You can get the options via the `options()` method that is exported.

**Comment by ksheurs** [comment]
Nice, thanks.
