### ISSUE TITLE
can videojs support srt format for subtitle

### ISSUE THREAD

**Issue by shivamg705** [videojs/video.js#1956]
Can videojs support srt format for subtitle,Actually i have tried to show subtitle using following lines.

 &lt;track kind="captions" src="English.srt" srclang="en" label="English"></track>
  &lt;track kind="subtitles" src="English.srt" srclang="en" label="English"></track>

but i am not able to show subtitle with video.

**Comment by zang** [comment]
Srt format works with vjs already, try download an example to try.

**Comment by shivamg705** [comment]
I have downloaded an example of video from http://www.videojs.com/downloads/video-js-4.12.5.zip and copy it and past in apache2 server and extract it then put a srt file along with demo.html after that change src="english.srt" in track tag but i am not able to see subtitle on player.

Can you send a example where subtitle is displayed by srt format.

**Comment by hartman** [comment]
BubblesJS seems to have a VideoJS plugin for SRT: http://bubbles.childnodes.com

**Comment by OwenEdwards** [comment]
I think support for SRT was dropped in VideoJS 4.12, with the addition of [vtt.js](https://github.com/gkatsev/vtt.js/tree/shim-build). Previous versions of VideoJS supported SRT; I'm not sure if dropping support was intentional, or if it's going to be fixed, but it certainly seems like a backward-compatibility issue.

**Comment by heff** [comment]
We haven't intentionally supported SRT since we implemented VTT a long time ago. If it worked before 4.12 it was purely from the similarities in the formats. But if that's what you're looking for it sounds like [versions less than 4.12](https://github.com/videojs/video.js/releases/tag/v4.11.4) or BubbleJS might be options.

**Comment by OwenEdwards** [comment]
So __SRT files happened to work with versions of VideoJS up to 4.11__, even though they weren't officially supported, but __SRTs no longer work in 4.12__ (because of the use of vtt.js, which greatly improves support for WebVTT files). This isn't specifically documented, and unfortunately, __vtt.js doesn't report an error, so the SRT files are silently ignored__.

Several plugins include SRT files, so updating them to 4.12 requires that the captions/subtitles are converted to VTT format. Resources include http://www.webvtt.org/, https://github.com/captioning/captioning/wiki#convert-a-subrip-file-srt-into-a-webvtt-file-vtt and https://atelier.u-sub.net/srt2vtt/.

**Comment by bhartendukumar12** [comment]
How to add captions in 360 videos.
Track features works fine in all video id except "videojs-panorama-player"
The moment i change the video id from "videojs-panorama-player" to any other name the 360 video feature stops working and caption feature start working.

Basically track tag is not working in 360 videos.

I will be very helpful for any suggestions....
