### ISSUE TITLE
Enhance eventEmitter to be able to send data with an event

### ISSUE THREAD

**Issue by carpasse** [videojs/video.js#1979]
It would be great if we could send data whenever we trigger an event within the player.

Just like jquery
https://api.jquery.com/trigger/
or node do
https://nodejs.org/api/events.html#events_emitter_emit_event_arg1_arg2

**Comment by heff** [comment]
I've pushed back on this in the past since you don't get this with the video element, and we're trying to mimic the video element workflow exactly so they're interchangeable. Also I thought making listeners get the values from the player instead of event data ensured the accuracy for timing data, but with javascript's single threadedness there's probably little chance of getting data that's out of sync.

I'd be interested in getting additional opinions, but either way I can see the value in this just for plugins that want to use that feature, so I'd be ok with moving forward with it.

**Comment by gkatsev** [comment]
It would be nice to have the data in the event itself rather than having to go look for it in a "canonical place". We've already taken advantage of the event object itself to send extra metadata along. Would be nice to make it official or have an official way of sending extra data long.

**Comment by heff** [comment]
Cool, this is confirmed then. I don't think this would be API breaking so we might prioritize it after 5.0 tasks, though feel free to start on it anyway.

I'm assuming we'd follow the Node API over the jQuery version? (slight difference in passing additional args)

I like the note in the AirBnB guide about [passing a data hash](https://github.com/airbnb/javascript#events), but that's probably more of a usage details.

**Comment by gkatsev** [comment]
Yep, I prefer node's API for this.
I'm ok with following that style for events and yeah, it's just a stylistic change. Functionally, it shouldn't matter.

**Comment by cladera** [comment]
Hi,

I just posted a [Pull Request](https://github.com/videojs/video-js-swf/pull/157) in video-js-swf project. It consists in broadcast onCuepoint rtmp event to the external interface, i.e. Flash tech.

What I want to accomplish is to do something like:

```
videojs('my-video', {}, function(){
   player.on('cuepoint', function(e. [cuepoint]){
      //Do whatever with timed metadata received 
   });
});
````
video-js.swf communicates with the player using <code>vjs.Flash.onEvent</code> (falsh.js L313), the problem is <code>onEvent</code> does not include arguments sent by swf when calls <code>player.trigger()</code> making my feature useless. 

I hacked this modifying <code>vjs.Flash.onEvent</code>:

```
// Trigger events from the swf on the player
vjs.Flash['onEvent'] = function(swfID, eventName, data){
  var event = {
    type: eventName,
    data: data
  };
  var player = vjs.el(swfID)['player'];
  player.trigger(event);
};
````

But, I ended up in this issue and realised It might be not the way to deal with this, Am I right? What do you think?

**Comment by heff** [comment]
@cladera  The 'official' way to do timed events is using WebVTT and tracks, though I'm not sure exactly how that should work with RTMP. In general we try to avoid exposing features that only work with a single tech, and instead try to abstract them in some way that can work with multiple techs. In this case it would be WebVTT. So I think the RTMP cue points would need to be translated into a metadata track somehow that plugins could consume like any other track. Does that makes sense?

At the same time I believe we green-lighted sending data with events for version 5.0, so that could possibly help too.

**Comment by cladera** [comment]
@heff RTMP implements <code>onCuepoint</code> as a way to "inject" data synced with a **LIVE** stream. This [article](http://www.adobe.com/devnet/adobe-media-server/articles/metadata_video_streaming.html) gives further details about the technique (the author uses onEventData instead of onCuepoint, but it is the same). 

I don't see WebVTT working with this paradigm, mainly, because RTMP live stream has no timeline where VTTCues could be created on. Live cuepoints just happen, there is no init and end time. The most representative example are slide changes. That's why my first approach was to trigger them as an event, similar to "loadedmetadata" rather than text track cues. However, I'll dig in WebVTT a bit more.

Sometimes, I feel LIVE video has been forgotten in all this HTML5 revolution :( . 

P.D.: Perhaps we are are going out of this topic. Should I create a new issue?

**Comment by heff** [comment]
@cladera yeah, a new issue would be appropriate, specifically around what the equivalent for cue points should be now.

**Comment by heff** [comment]
@carpasse any interest in implementing this one for 5.0? It should just require adding an arg in a few places.
- [events.trigger](https://github.com/videojs/video.js/blob/2bf0be72f3b1a3bd5b8421bb5ccda7dae6cf13cc/src/js/events.js#L281)
- [component.trigger](https://github.com/videojs/video.js/blob/2bf0be72f3b1a3bd5b8421bb5ccda7dae6cf13cc/src/js/component.js#L679)

**Comment by carpasse** [comment]
@heff Yep I will try to do the PR tomorrow or the day after at the latest.

**Comment by heff** [comment]
Great!

**Comment by dmlap** [comment]
@cladera in videojs-contrib-hls, we mapped in-stream data, like `onCuepoint` over RTMP, to an [in-band metadata track](https://html.spec.whatwg.org/multipage/embedded-content.html#text-track-in-band-metadata-track-dispatch-type). It's not supported natively by any browser I'm aware of but it does seem like the HTML5 mechanism for this sort of signaling.

**Comment by cladera** [comment]
@dmlap, I already knew about your great job with videojs-contrib-hls. I'll take a look how you guys deal with in-stream data. 

Thanks!!

**Comment by carpasse** [comment]
@heff For some reason I don't understand 'contrib' failed to create the PR. 
It is a bit odd. It printed 
```
-----> undefined
```
and it gave no feedback about what was the problem.
In the end I had to do the PR manually: https://github.com/videojs/video.js/pull/2163
Sorry for the inconvenience.

**Comment by heff** [comment]
@carpasse sorry about that. I've never seen that but contrib does have some rough edges. Would you be up for submitting an issue on the [contrib repo](https://github.com/contrib/contrib) and helping me figure out the root of it?

**Comment by carpasse** [comment]
@heff I have created the issue https://github.com/contrib/contrib/issues/22 although I don't know if I can give you any more feedback that what I wrote on the issue.

**Comment by heff** [comment]
This issue should be closable now. @carpasse let me know if you think otherwise.
