### ISSUE TITLE
Initialize the plugins before the components

### ISSUE THREAD

**Issue by carpasse** [videojs/video.js#1980]
Hi guys.

I use the plugins to get the data needed for the controls of the player. 
I usually use the plugins to get the data and have a separation between the business logic and the UI (Components) therefore I would like to propose that we initialize the plugins before we initialize the components.

What do you think??

**Comment by carpasse** [comment]
Another possibility would be to enhance the build phase of a component to specify dependencies to a list of plugins

**Comment by heff** [comment]
Yeah, I think initializing plugins before controls is a good idea. Some plugins need the controls to be there already when they're loaded, however those plugins could now wait for the `ready` event, whereas today there's no option for plugins that need to modify the controls ahead of time. 

I'd be interested to know @dmlap and @gkatsev's thoughts on this since they've had the most experience building plugins. For instance, if the ready event will work for that.

Confirming for 5.0 unless we hear differently. This would be a pretty big API breaking change for plugins so we would need to figure it out quickly if we want to get it in.

The dependencies issue is one we've been talking about off an on, and might be worth opening another issue for. We're running into it more and more. Basically, everything in the video.js ecosystem is a peer dependency, even video.js itself, and npm peer dependencies aren't so great, so it's been a challenge figuring out the best approach.

**Comment by heff** [comment]
Closed by #2094
