### ISSUE TITLE
jwplayer vs videojs

### ISSUE THREAD

**Issue by futurehendrix** [videojs/video.js#1983]
Hello,

I'd really like to switch to videoJS, but am having a hard time finding on the web if there is ANYTHING that videoJS can't do, that jwplayer does

So if you could tell me, then that would help me narrow down whether I should use videoJS or not. I would really like to though. I tried it a year ago and it worked good except for some reason I had a guy on windows xp telling me the video playback was choppy or weird (Can't remember how he described it). It could have just been that I implemented it wrong somehow? Not sure

But then when I switched/paid for jwplayer dreadfully, that same person (on xp) told me the videoplay back was fine now and worked great

So I just worry about problems like that happening, let me know if there is something jwplayer does that videoJS cant do, if so what?

I think it had something to do with videoJs not having flash support 1 year ago? or maybe you did? I just remember taht xp person telling me when they right clicked on the video it was flash options, but that the video play back was terrible

**Comment by futurehendrix** [comment]
My main concern is video play back. Is there anyone that would be lucked out if i go with videoJS? any platforms? that they wouldnt luck out on jwplayer?

**Comment by heff** [comment]
Video.js is a free, community-build product and we rely on the community a lot for help with features. In the last year community contributions and plugins have both doubled compared to the previous four years of the project combined, so you might find it's a different project than the last time you tried it.

For video playback specifically, it depends what formats you're trying to use, but Video.js has always relied on HTML5 video first, which has been improving in comparison to Flash. And you always get faster player load times with HTMl5. Which formats are you using?

(closing since this doesn't require any changes, but feel free to keep commenting)
