### ISSUE TITLE
Android 4.1.x - video-js does not load mp4

### ISSUE THREAD

**Issue by endrjuskr** [videojs/video.js#1986]
I tried to open http://lv8.tv/the-salvation-official-us-release-trailer-1-2015-mads-mikkelsen-eva-green-movie-hd-12x6ony0l5cy.html?v=4.11.4 provided in #975 in WebView on Android 4.1.2 and video didn't load at all.

Here is how it looks:

![error](https://cloud.githubusercontent.com/assets/2611549/6867051/60c14348-d47e-11e4-8dc4-fe8923ff5384.png)

I also tried with my own site and apply CSS fix mentioned in #975, but it didn't help.

Do you have any idea, how to solve it?

**Comment by carpasse** [comment]
Hi @endrjuskr 

Do you get any log error?
Can you please add post the html template and the js you use to add videojs to the page and to initialize it?

I am using videojs on android 4.1 and it is playing fine.

**Comment by endrjuskr** [comment]
Are you opening site with vide-js in `WebView` ?

I didn't get any log error.

On 31 March 2015 at 11:56, Carlos <notifications@github.com> wrote:

> Hi @endrjuskr <https://github.com/endrjuskr>
>
> Do you get any log error?
> Can you please add post the html template and the js you use to add
> videojs to the page and to initialize it?
>
> I am using videojs on android 4.1 and it is playing fine.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/videojs/video.js/issues/1986#issuecomment-88020046>.
>



-- 
Pozdrawiam,
Andrzej Skrodzki

**Comment by carpasse** [comment]
Sorry I missed the link.

I have taken a look at the video and it seems that when you are in mobile, you change the source from mp4 to m3u8 which is HLS

![screen shot 2015-03-31 at 13 29 48](https://cloud.githubusercontent.com/assets/1588321/6918004/45d690fe-d7aa-11e4-8826-f7dc5493c334.png)

Are you using the HLS plugin (https://github.com/videojs/videojs-contrib-hls)  to display the videos??

**Comment by endrjuskr** [comment]
Here is a [link](http://mostiv.republika.pl/index_lesson.html?url=course/content/course_00000/learningunit1/script_00001.emt.xml&pageNo=1), with my embedded video-js which I am trying to open.

**Comment by endrjuskr** [comment]
@carpasse But, how can I open mp4 instead of HLS? From Android 4.4 WebView is using native browser and it looks fine.

**Comment by carpasse** [comment]
@endrjuskr in this new link you serve a mp4 video source in both desktop and mobile. 
You do have an error with some Android object not being defined. But that should not be the problem.

What differs is the way you initialize the player on desktop you use data-setup but on mobile not. I imagine you are initializing the player with js.

I don't think the problem is the source but how you initialize the player. On your link, the player is not being properly initialize for mobile. You can see there is no skin and that it loads the default player video controls.

I would review the the way you initialize the player on mobile (since it is obfuscated I can not see how is done). Are you passing the proper options.

Also it seems that mp4 is only partially supported on android 4.1 http://caniuse.com/#search=mp4
This may also be a problem ( although I don't think so)

Does the player gets property loaded when you load the page with android 4.1's native browser instead of loading it through a webview???

**Comment by endrjuskr** [comment]
It is loaded correctly on native browser.

I will try to change video-js version to not obfuscated and let you know.

**Comment by mmcc** [comment]
@endrjuskr can you confirm whether or not this can be closed?
