### ISSUE TITLE
Happy 2000th issue!!! -- A video is worth 2000 issues

### ISSUE THREAD

**Issue by heff** [videojs/video.js#2000]
Just over a year after #1000 we've doubled the number of issues compared to the previous 4 years of the project combined (issues include features, questions, PRs, and other discussions, not just bugs :bowtie:).

This is right inline with every other stat we're seeing:
- Downloads from videojs.com grew 50% to 30,000 per month
- The CDN-hosted version grew 100% to [**2 billion**](https://www.youtube.com/watch?v=cKKHSAE1gIs) player loads per month
- **Project contributors grew 300%, from 47 to 156**
- [Community plugins](https://github.com/videojs/video.js/wiki/Plugins) grew 100% to 55, including videojs-IMA3 built by Google

Even with all that growth we've managed to **reduce** the number of open issues (with some fluctuation), so big thanks to everyone who's helped move issues along (across all @videojs org projects), the top 3 being:
- @mmcc ([699 issues](https://github.com/search?utf8=✓&q=commenter%3Ammcc+user%3Avideojs&type=Issues&ref=searchresults))
- @gkatsev ([609 issues](https://github.com/search?utf8=✓&q=commenter%3Agkatsev+user%3Avideojs&type=Issues&ref=searchresults))
- @dmlap ([333 issues](https://github.com/search?utf8=✓&q=commenter%3Admlap+user%3Avideojs&type=Issues&ref=searchresults))

And a shout out to @eXon for closing hundreds of issues on the most popular non-videojs-org project, [videojs-youtube](http://github.com/eXon/videojs-youtube).

We're busily working towards a 5.0 release and making some big improvements, so if you want to help influence where things are going or just help out, now is the time to find the issues you care about and get plugged back in.

![tumblr_njsbzl7vnd1tlb56zo1_400](https://cloud.githubusercontent.com/assets/166/6955485/2149d23e-d893-11e4-99dc-e8cc0ad619b1.gif)

Cheers! :tada: :fireworks: :birthday: :fish_cake: :corn:
@heff

**Comment by mmcc** [comment]
@heff ([1,395 issues](https://github.com/search?utf8=%E2%9C%93&q=commenter%3Aheff+user%3Avideojs&type=Issues&ref=searchresults))

**Comment by eXon** [comment]
Wow it's mindblowing how much work you guys did.

VJS 5.0, probably just another too good to be true april fool ;)

Definitively going to take a look at where this is going. VJS is by far the best video player and I hope it continues to improve like it did last year :+1:. Not to metion how awesome the community is.

**Comment by mmcc** [comment]
@eXon We're going to be bugging you about 5.0 reeeeaal soon. :) We want to do more to foster the plugin ecosystem, so that's where we're putting a lot of our focus for the next version. Maybe we can do a hangout at some point and talk through what we've got planned / get your feedback?

Anyway, thanks for all the help with the YouTube and Vimeo plugins, who knows how many people have found their way here because of those. :clap:

**Comment by eXon** [comment]
@mmcc Thank you for the kind words. VJS was a no brainer for me at that time because the API made it so easy to write the YouTube plugin.

I have a great deal of ideas to improve the plugins, the techs as well as VJS overall. I will take a look at the new stuff and throw some ideas on the wall in the upcoming weeks and then of course we can do a hangout =]
