### ISSUE TITLE
Breaking apart files

### ISSUE THREAD

**Issue by mmcc** [videojs/video.js#2010]
Placeholder for tracking changes related to breaking apart files such as lib and any other file with multiple components within.

**Comment by heff** [comment]
I think I can include breaking up the Components in #1993, though it might make it hard to read the specific ES6 Class diffs if a lot of things are in new files.

**Comment by heff** [comment]
#1993 broke up component classes into their own files. Still need to address lib.

**Comment by dmlap** [comment]
### Remaining
- [ ] Break up lib.js into sensible categories
- [ ] Wrap in util.js into that work

**Comment by dconnolly** [comment]
I can take this.

**Comment by heff** [comment]
@dconnolly did you get anywhere with this that I could take a look at? I started taking a pass at this myself.

**Comment by heff** [comment]
Is there a common way of naming utility library functions when they're pulled into a script individually, so that it's clear they've been pulled in?

For example pulling in createEl from the `dom.js` util library. I don't love that I might use `createEl()` somewhere in the code and it looks like any other function that may have been created in that file. Especially in the case of createEl and Component where we're creating a `component.createEl()` function that uses createEl internally. It gets ambiguous.

ping @gkatsev, @mmcc, @dmlap

**Comment by dconnolly** [comment]
@heff I did not, spent most of my time on videojs/videojs.com#5.0

**Comment by heff** [comment]
@dconnolly Cool, no worries. Thanks.

**Comment by heff** [comment]
Closed by #2139
