### ISSUE TITLE
this.requestFullScreen(); does not work.

### ISSUE THREAD

**Issue by CosmicWebServices** [videojs/video.js#2013]
The command ```this.requestFullScreen();``` does not exist!

**Comment by mmcc** [comment]
We *really* need more information than this.

But, since we're talking about requesting fullscreen, I can guess. You need to call `requestFullscreen` from within an event handler for security reasons. That means it needs to be triggered by some sort of user event, such as a click or a key press.

Also, just to note, `requestFullScreen` (camel cased "FullScreen") is deprecated to be inline with the actual spec. Moving forward make sure to use `requestFullscreen`.

Just for completeness, here's a [working example](http://jsbin.com/gudoco)
