### ISSUE TITLE
Control Bar freezes after 2 seconds in iOS Safari

### ISSUE THREAD

**Issue by blakedoyle** [videojs/video.js#2026]
When i view my video in iOS Safari, all of the elements on the Control Bar freeze.  The progress bar stops and the counter stops counting, the pause / play button still works but it does not update the font.  Anybody heard of this?

**Comment by mmcc** [comment]
Is this on an iPhone or an iPad? Custom controls (is it playing inline)? Are you trying to do this in an emulator?

**Comment by blakedoyle** [comment]
On an iPad with the videojs controls (modified styling to prevent the fade out). With Chrome for iOS the control bar updates fine.  

here is the modified CSS,  

.vjs-default-skin.vjs-has-started.vjs-user-inactive.vjs-playing .vjs-control-bar {
  display: block;
  visibility: visible;
  opacity: 1;
  /* transition */

  -webkit-transition: none !important;
  -moz-transition: none !important;
  -o-transition: none !important;
  transition: none !important;
}

**Comment by mmcc** [comment]
Just tested and so far I'm unable to reproduce with [this example](http://jsbin.com/soviza). The only difference (that I know of) is that I'm setting the `inactivityTimeout` to 0 rather than modifying the CSS, but everything is functioning as expected in Safari and Chrome.

I'm going to close this, but if you can put together a reduced test case just ping this and we'll reopen.
