### ISSUE TITLE
How know video is compatible ?

### ISSUE THREAD

**Issue by ychoucha** [videojs/video.js#2047]
Hello,

wel i m looking to show video with videojs, but i don't understand how we know video is compatible.

i m using vlc to convert video.

i have tried the converter VIDEO -H.264 + MP3 (MP4)  --> I have video but no sound.
i have tried the converter Theora + Vorbis (OGG) ---> I have nothing no video no sound
i have tried the converter VP80 + vorbis (webm) ---> I have nothing no video no sound

i also tried to show a video com from my android phone a "3gp" format video  and no sound no video.

can u please help me to understans how make a video compatible, please ?

**Comment by mmcc** [comment]
All of those combinations should work in Chrome, so something else must be going on. I've never used VLC to actually convert video, but I've had good luck with [Handbrake](http://handbrake.fr). Make sure to use the settings for web optimization, but otherwise it's pretty straight forward.

To be terribly honest I just run things through [Zencoder](http://zencoder.com), but I'm spoiled by the employee discount.
