### ISSUE TITLE
What Encoding Should I Use?

### ISSUE THREAD

**Issue by TekkGuy** [videojs/video.js#2064]
Ok, I have one question regarding encoding...

I have a video that doesn't play in VideoJS. I am trying to convert it to an encoding format that is supported. However I have tried several formats without success... I am at a loss...

I am using a free utility (Free MP4 Video Converter v5.0.57(301)), I tried the following settings:
Video Container: MP4
Video Codec: H264_MAIN
Frame Rate: 30fps
Bitrate: 1 Mbit/s
Width: 960
Height: 640
Audio Format: AAC
Sample Rate: 44100 Hz
Channels: Stereo
Bitrate: 128 Kbit/s

The above setting doesn't work... I don't know what I should be setting to get my converted video to function. Any suggestions?

Below is a screenshot of the settings available:
![freemp4videoconverter_settings](https://cloud.githubusercontent.com/assets/4238402/7300794/5d2b7df0-e9ac-11e4-8502-f56bed7828bc.png)

**Comment by gkatsev** [comment]
I think those settings should generally work. Have you tried leaving the video in the browser window for a long time? Supposedly, some encoders put all the video metadata at the end of the file so the browser needs to download the whole file before it can actually play it. You definitely want an encoder that will put the metadata at the beginning. For example [handbreak](https://handbrake.fr/) has a "web optimized" option.

I'm going to close this issue because it doesn't require any action on the project's side but please feel free to continue asking questions here and we'll answer them.
