### ISSUE TITLE
Expose a list of the player public API events and methods

### ISSUE THREAD

**Issue by eXon** [videojs/video.js#2101]
I am working on a polymer that wrap video.js and expose the public API in a Web component way. Also possibly working on a Angular/react.js/ember version.

To expose the API, I had to create a constant with all the events and the methods that the player have by using the doc. It was not hard to do, but I think it will be very unpratical to maintain. What would be very helpful is to expose all the events and the methods within video.js so that if something change, it doesn't break those wrappers. It would be way easier to make them compatible with any version of video.js as it evolve.

Here is an example of what we would need:

``` javascript
videojs.API_PLAYER_EVENTS = ['durationchange', 'ended', ...];
videojs.API_PLAYER_METHODS = ['addTextTrack', 'autoplay', ...];
```

Do you guys think it is a good idea? Do you have a better (potentially automated) way?

**Comment by gkatsev** [comment]
I'm not opposed to it but I think that once a list is made it actually won't be too hard to maintain because we're much more committed to following semver in 5.0 and beyond.
That means that new publicly facing methods should only ever come in minor version bumps and methods could only be removed/broken in major version bumps. So, everything should continue working as long as your component depends on something like `^5.0.0`.
Also, some of the events (not the videojs-specific events) are available on `videojs.Html5.Events`, or thereabouts.

On a related note, our soon-to-be linter complains about how we document events in the code
```
/**
 * Some JSDoc comment
 */
Player.prototype.onended;
```
so we should figure out a better way of documenting these events.

**Comment by heff** [comment]
Some related projects in case you haven't seen them:
https://github.com/addyosmani/video-js (doesn't expose any API really, just makes video.js work as an element)
https://github.com/heff/x-playlist (my playlist plugin, not video.js related by might be interesting)

At first glance I don't love having to maintain a list of events and functions even internally. That feels like it will be another situation like the exports we had with closure compiler, where we were constantly forgetting to add them. Maybe once I see more of what you're doing I'll have a different opinion.

**Comment by eXon** [comment]
Maybe we could find a way to generate them using a jsdoc tag.

**Comment by eXon** [comment]
@heff For the Web component I think it will be way easier to expose the player instance instead of trying to replicate the whole API. I've managed to get it working pretty easily.

You can see my first version of [videojs-webcomponent](https://github.com/eXon/videojs-webcomponent) it is something like 10 lines of code with polymer and a bundled file with vjs js/css included =]

**Comment by eXon** [comment]
I'm about to replicate the same kind of wrapper for Angular/React/Ember. I don't think I will be using the webcomponent in them like we discussed in #2006. It is harder to skin the player inside the shadow DOM because the default skin has to be bundled inside.

**Comment by gkatsev** [comment]
I think that with our heavy updates to our jsdoc, if we still want this, I would say to generate it from the jsdocs.
