### ISSUE TITLE
Chapter Menu is Not Working in 4.12

### ISSUE THREAD

**Issue by stuartmcgarrity** [videojs/video.js#2131]
If I specify video-js  version 4.7 to 4.11 I see the chapter menu (bubble icon on control bar), but if I specify 4.12 the chapter menu is not there.

For example, change the video-js version in this example: http://jsbin.com/gotoma/4/edit?html,output

Stuart

**Comment by heff** [comment]
We did a major overhaul on the track support in the most recent version, and it's possible we missed an issue. I'm on a plane so not in the best place to test things right now, but I see a few things.

- An error reading "Cross-origin text track load denied by Cross-Origin Resource Sharing policy"
It's possible the CORS settings need to be changed on the chapters file. We switched to using the browsers built-in track support, so that could be part of the change.

- The chapters file in that example has varying timestamp formatting. The first cue uses a decimal. Others have two or three trailing zeros. I'm not sure what specifically of that might be wrong, but we switched VTT parsers (either uses the browser or VTT.js parsing), so what we have now might be pickier.
```
Chapter 1
 00:00:00:00 --> 00:00:02.000
Introduction

Chapter 2
 00:00:04:000 --> 00:00:08:00
Building a Model
 
 Chapter 3
 00:00:10:000 --> 00:00:12:00
Simulating the Model 

 Chapter 5
 00:00:14:000 --> 00:00:16:00
Conclusions
```

@gkatsev any thing else that might have change how chapters work?

**Comment by stuartmcgarrity** [comment]
I made the timestamps consistent, but it still doesn't seem to work in video-js 4.12.

However the chapter menu sometimes appears with the Brightcove player: http://jsbin.com/yelaje/3/edit?html,output , but the chapters are duplicated. Its seems unreliable.

**Comment by gkatsev** [comment]
I think the issue here might be related to the `crossorigin` property of the video element. See #1888.

**Comment by stuartmcgarrity** [comment]
I tried setting the property of the video element:

<video id="example_video_1" class="video-js vjs-default-skin"
crossorigin="anonymous"
  controls preload="auto" width="640" height="264"

Is that correct?

The video failed to load in all browsers. In IE the poster did not load and
in Chrome there was an error message on the poster.

**Comment by gingerpad** [comment]
Did this issues ever get resolved. I have spent the morning trying to get chapters working in 4.12 to no avail.

However stumbling across this post, I tried 4.11 and chapters showed up straight away.

Is there a bug in 4.12 that is stopping chapters working as I am resistant to revert back to a 4.11 version for a customer that has been using 4.12

**Comment by christophelimpalair** [comment]
+1. Subtitles work but I cannot get Chapters to work

**Comment by OwenEdwards** [comment]
@gingerpad & @christophelimpalair, have you tried using the un-minified `video.dev.js`, instead of `video.js`? As @heff mentioned, there are CORS issues if the files are cross-domain and the formatting is more strict with the new VTT parser; but given that @christophelimpalair mentions that subtitles *do* work, I thought it might be relevant that I personally found that chapters don't seem to work with the minified version of video.js in 4.12.

**Comment by gkatsev** [comment]
Closing this for now. @chemoish is working on revamping our chapters support in https://github.com/videojs/video.js/pull/2804
