### ISSUE TITLE
Playback issues with Firefox 37 and above

### ISSUE THREAD

**Issue by robotman321** [videojs/video.js#2158]
Hey guys and gals,

I run a small site that delivers videos from a LAMP stack server to the VideoJS front end. As of Firefox 37 we have been getting numerous reports that audio tends to drop out randomly with h264 (mp4) videos. It could range from less than a minute to 5 minutes, but it consistently drops.

I have a feeling that it's a firefox related issue, as I can downgrade to firefox 36, and everything works fine, i'm really just looking to see if anyone has experienced this issue. We're currently running 4.12.5 of VideoJS.

Things we have done in an attempt to remedy the situation: (some will not apply to VideoJS, just listing everything)
- Update Apache and confirmed the proper mp4 mime type is enabled, no effect.
- Checked for windows updates that were applied after or around the FF 37 update, no effect.
- Updated VideoJS to 4.12.5 from 4.9.X, no effect.
- Rolled back Firefox to 36, effective, resulted in the videos working properly again.

We have an ongoing thread here: http://bit.ly/1KcOWs2 but you'd need to log in to view the content (sorry..)

Thank you!

**Comment by RowanH** [comment]
Did you find a solution to this? I might have a related issue. FF 38, and I'm seeing a video stop at 38 seconds in, when looking at the inspector it's just as it's trying to load a new byte range from S3 - the video stalls while audio is still playing, gets the new content from S3 but at this point the player effectively crashes.. 

Working fine on IE/Chrome.

**Comment by robotman321** [comment]
Sadly we haven't, we've been playing around with different encoding profiles, trying to fine tune it for FF but nothing seems to work.

**Comment by heff** [comment]
This could be related to Firefox supporting MP4s in html5 video now, but I'm not sure the exact version where that happened. Mac was more recently than windows. Before that it would play through Flash pretty consistently. Firefox could also just be updating their video pipeline over time.

You might try running a file through [zencoder](https://zencoder.com/). It's not free but it does a bunch of work to clean up MP4s.

Otherwise you could force Flash by doing 
```
videojs.options.techOrder = ["flash"];
```

**Comment by RowanH** [comment]
I did quite a bit of digging - it was happening in FF 38, but fixed in FF 41. I tested FF 39 and it was still broken, didn't test FF40. 

I'm using Amazons Elastic Transcoder so I would think (hope) the encoded .mp4 file was good. This happened consistently on FF38/Win and FF38/Mac. If you looked at the network traffic you should see the browser requesting a series (4-5 or so) of smaller chunks, then request a large chunk - as it was closing on the 38 second mark, now it might be an edge case that it hasn't received the chunk fully in time for playback and/or got it ready to view that is causing the video drop out. Other videos that were of different length didn't appear to have an issue. Now FF did fix a security vulnerability in FF 38 so, this may be related or a red herring?  (https://www.mozilla.org/en-US/security/advisories/mfsa2015-55/) 

In the end I gave up and changed my pipelines to encode a .webm and .mp4 version, specifying the webm first then falling back to mp4. Doesn't fix the root problem, but does solve it for my users.

**Comment by mmcc** [comment]
I'm not sure what to do with this one to be terribly honest. It doesn't seem like something we can fix on our end, but I don't want to close it if it's still an issue. Is there something here that needs to be reported to Bugzilla?

**Comment by gkatsev** [comment]
Is there any details that are worse sending over to firefox? If it's fixed in ff41 maybe there's no action required.
