### ISSUE TITLE
Add an Audio Description icon to the V5 icon font

### ISSUE THREAD

**Issue by OwenEdwards** [videojs/video.js#2165]
Since support for text tracks is already present in V4.12, including partial support for 'description' tracks, at some point in V5 we'll be adding support for Audio Description (through a text track, and potentially through other means).

To prepare for this, can we add an audio description icon to the font, similar to the CC icon, based on the one here:

http://www.ryerson.ca/accessibility/tools/access_symbols.html

and:

http://www.acb.org/adp/ad.html#symbols

I don't know how to create the fonts, otherwise I'd do a PR myself. @mmcc?

**Comment by mmcc** [comment]
@OwenEdwards this seems reasonable to me! Our current font is a subset of the [Material UI font](https://github.com/mmcc/material-ui/tree/master/src/less/material-design-fonticons/fonts) along with at least one custom icon of ours.

Basically the work flow right now would be upload the current SVG icon font to [Icomoon](https://icomoon.io/), pull in the new icon, and re-export. I started to try and do some work around just having an automated build process with a folder of SVGs, but as it turns out, fonts are hard.

**Comment by OwenEdwards** [comment]
Thanks @mmcc! I can get the basic AD icon in there (see my [plugin to support switching a video with description already added](http://ictasolutions.github.io/videojs-described-video/), which addressed #1875. But the icon doesn't seem to be the same size as the ones in the main font, so combining it into the main font doesn't work. Any suggestions? Like you say, fonts are hard!

**Comment by mmcc** [comment]
Hrm...this might get a little tricky... Best case scenario is that we can get an SVG and upload that to Icomoon, because then they'll at least do most of the work around resizing for us. Unfortunately, I don't see an SVG version of those icons anywhere, so we might have to do it ourselves :(

I can take a wack at it with Sketch. I'm not a pro, but I've at least got some basic icon guides that I can use.

**Comment by OwenEdwards** [comment]
I can get you an SVG of the icon! I'll email it...

**Comment by mmcc** [comment]
Looks like the SVG you gave me isn't playing nice with our build tool ![icon](https://cloudup.com/cCK1dFKvsO1+) :(

**Comment by mmcc** [comment]
I'll see if I can fix it and let you know

**Comment by OwenEdwards** [comment]
Yikes! Can you use the original `ad.ai` from [Adobe Illustrator (AI) Black on White](http://www.acb.org/adp/images/logos/ad.ai), and export as SVG from Adobe Illustrator, or convert it at https://cloudconvert.com/ai-to-svg?

**Comment by mmcc** [comment]
I had to fix it manually in Sketch, but it's been added to the new [videojs-font](/videojs/font) project! It looks a tiny bit pixelated, so if someone else with more SVG-foo than me wants to take a stab, feel free.

**Comment by mmcc** [comment]
@OwenEdwards There's a pull request open if you want to take a look: videojs/font#1

**Comment by mmcc** [comment]
This has been pulled in, so an `npm install` followed by `grunt` should do the trick.
