### ISSUE TITLE
Video loading breaks on 8th instance

### ISSUE THREAD

**Issue by mr-reamer** [videojs/video.js#2248]
If I insert more than 7 videos, the 8th won't play. If i comment out video 1, video 8 starts working.

I have created a JSBin example here:
http://jsbin.com/povuzolexi/1/edit?html,output

tested in Mac Chrome Version 43.0.2357.81 (64-bit)
and Mac Firefox 38.0.5

**Comment by mister-ben** [comment]
I see this on Chrome but not Firefox (same versions). I think this is Chrome's limit of 6 http connections to the same domain. Your first player is playing from vjs.zencdn.net, but all the rest are contiki-downloads.s3.amazonaws.com, so the 8th player is the 7th connection to the same domain.

If you change at one of the other players loading that content to preload="none", the last player also works because the connection is not started. http://jsbin.com/regobi/1/edit

In Firefox the connection limit is user-configurable, but should default to something higher. network.http.max-connections-per-server under about:config.

**Comment by mmcc** [comment]
Am I reading [this](https://code.google.com/p/chromium/issues/detail?id=12066) correctly as the limit being *across tabs*? TIL, thanks for the info @mister-ben.

**Comment by mr-reamer** [comment]
Thanks for the help, much appreciated. This has resolved it for me.

FYI I actually tested my proper page in Firefox, which had 10 videos all served from contiki-downloads.s3.amazonaws.com, and I did encounter the same issue.
