### ISSUE TITLE
Extending html5 tech: Custom loading state ( pause, trigger loading and resume on custom condition )

### ISSUE THREAD

**Issue by tghosgor** [videojs/video.js#2257]
Hello,

To simplify the situation, I would say that I'm using html5 filesystem api to provide the video (modifying the file on the fly). However, there may be a situation that video file is incomplete/corrupt and I need to pause the video and put it into the loading state (showing indicator and keeping it paused and such) until I resolve the corruption with the server and reload the video file and seek it to the appropriate position.

Now, I would rather do this internally inside a custom tech instead of force-pausing the video and trying to keep it paused until it is allowed to resume again from outside.

I couldn't see anything about putting the player to `buffering` state inside html5 or maybe I missed it. Is there a way to do this inside the tech? If it is not directly supported by tech, how do you think I should implement it (loading indicator, preventing the video from resuming and such)?

Thanks.

**Comment by eXon** [comment]
Extending the Html5 tech is probably your best bet. When you need to put the player in loading state, you can do `this.trigger('waiting')`. Then, when it is ready to play, you can seek your video to the `this.currentTime()` and do `this.trigger('canplay')`.

Let me know if you have any trouble :)

(if you are on VJS 4, you need to do `this.player.trigger(...)` instead of `this.trigger(...)`)

**Comment by tghosgor** [comment]
Thanks. I can override and block tech.play() and listen for timeupdate events to pause and put to 'waiting' state with the methods you said.

I can interrupt .play like I said but I can't interrupt seeking apparently. The video seeks to an invalid location and I get decoding error from the native video element.

Is there a way to block seeking in tech like .play method or I should start looking through and modify some underlying stuff?

**Comment by tghosgor** [comment]
I think I should expand the last part: I need to limit the seekable part by returning a time range in `seekable` yet I want to be notified of seek requests so that I can correct the problem and call `this.setCurrentTime()`.

**Comment by gkatsev** [comment]
In your tech, you could override `setCurrentTime` in the tech to prevent seeking when not necessary. You can also override methods like `seekable` and `duration` and whatever else is needed.
Your best bet is to look at the implementation of the existing techs like the main tech (https://github.com/videojs/video.js/blob/master/src/js/tech/tech.js) and the html5 tech (https://github.com/videojs/video.js/blob/master/src/js/tech/html5.js).
Also, you may want to look at a project like videojs-contrib-hls which does a lot of complicated stuff around seekable.
Hope that helps. Closing since it's unlikely we'll need to make changes to core, but we can re-open or open new issues if so. We can still continue discussion here, if necessary.
