### ISSUE TITLE
Video doesn't play in native browser for Android 4.1.1/4.1.2 

### ISSUE THREAD

**Issue by chandnidesai7** [videojs/video.js#2330]
Video doesn't play in native browser for Android 4.1.1/4.1.2 (Tablets)

**Comment by apadhye** [comment]
Chrome plays fine. This issue is only seen in the stock browser.

**Comment by gkatsev** [comment]
I think the issue here is that in native android browsers, button presses still propagate to the video element itself; thus, if you click on the play button, it plays the video, but then the video element itself gets the click event and toggles the playback state itself. Given that we've just played it, it thinks it should pause itself, so, the video ends up being paused.

**Comment by gkatsev** [comment]
We default to native controls on the native android browser, so, hopefully, this is fixed: https://github.com/videojs/video.js/pull/2499
Closing for now. Can reopen if still an issue.
