### ISSUE TITLE
5.0 rc: dimensions in IE8/9 not honored

### ISSUE THREAD

**Issue by nickygerritsen** [videojs/video.js#2336]
At least in IE8/IE9 the dimensions of the `<video>` element are not honored if one loads a CSS file with a specific width/height for the player div later than the player itself. We use this to dynamically load skins and this does now not work.

What happens is that the player always uses the dimensions defined in the skin css if you load it later.

It seems this is the case because the javascript adds these dimensions as a stylesheet on the class `.[id]+dimensions`, but the skin adds them on the element on the ID. Thus both selectors have the same specificity and thus the browser is free in choosing one. Apparently IE8/IE9 chooses the css that is loaded later and thus our skin breaks.

One fix would be to also add `'#' + this.id()` to the CSS selector, but I'm not sure if that is what you want?

**Comment by heff** [comment]
The goal with the new dimensions handling in 5.0 was to have them work just like the video element width/height attributes. If you set them and nothing else they'll control the dimensions, but they're easily overridden by CSS. It's different from v4 but closer to how the video element works.

Are you saying that it works differently in IE8/9 than in other browsers? If so could you set up an example? You can start from this jsbin.
http://jsbin.com/sofiwu/edit?html,js,output

**Comment by nickygerritsen** [comment]
It works differently in IE8/9 if you load the CSS later than the JS.

I have modified your jsbin to reflect this. This will load the CSS after 1 second.
In IE8/9 the video will be the size as specified in the CSS, but in other browsers it will be the size as specified on the <video> element.

See: http://jsbin.com/borodayulo/edit?html,js,output

**Comment by mmcc** [comment]
So I think this is probably something we should fix anyway, but part of the thought behind the 5.0 skin is that the base theme would *always* be there, with additional skinning done on top of that rather than recreating the entire skin. For use case, this is an important distinction because I would say the ideal way of doing this would be to load the base skin "normally", then dynamically load any custom skins overriding that base.

**Comment by heff** [comment]
There was actually a previous comment around this when the dimensions were being updated.
https://github.com/videojs/video.js/pull/1952/files#r30721712

So we could remove the default dimensions from the stylesheet, but there might be a flash of no dimensions and reflow without them. Not sure if there's a better option.

**Comment by nickygerritsen** [comment]
I guess we should still make some decision about what to do here? For us it indeed works if we remove the default dimensions from the skin, but I'm not sure if that is what one would want.

**Comment by heff** [comment]
Here's a version of the jsbin that can be loaded in ie8 still. And I can confirm that the sizing is different in IE8. http://output.jsbin.com/levoki/1

So the requirements to reproduce this are:
- width/height attributes are used
- The skin has to be loaded after video.js player is initialized
- IE8/9

@nickygerritsen can you go into more detail on why you're loading the skin after the player is initialized? That doesn't seem like the best practice. Dynamically loading *other* skins seems like a reasonable use case, but I'm not sure why other skins would include width/height for the player.

Thinking about this more, if we reverse this and put the default styles in the script instead of the CSS, then in IE8/9 I think the default styles would then override other user CSS.

Right now, if you set a width/height using CSS and *do not* set width/height attributes on the video tag, the script does nothing and the CSS wins. In order to not have the default width/height in the video.js CSS we would need to include it in the script and add it when the player loads, **even when no width/height dimensions are use**. I *think* that means that our default dimensions would override user CSS dimensions in IE8/9 always, which seems like a worse situation than what we're describing here.

1. User sets width/height in CSS that loads first
```
.video-js { width: 100px; height: 50px; }
```
2. Player loads and has to at least add default dimensions using the script injected style tag, even though no width/height dimensions were used.
```
.[player-id]-dimensions { width: 300px; height: 150px; }
```

In IE8/9 I think this breaks.

**Comment by nickygerritsen** [comment]
After some discussion we decided that for us it is easier that we remove the width and height from the CSS, thereby forcing users to add a width and height on the video element.

For me this issue is thus no longer needed and I think that the current approach can stay for when you load the stylesheet synchronously.

**Comment by mmcc** [comment]
Cool! Thanks for letting us know. Ping this thread if you have any thoughts on this later.
