### ISSUE TITLE
Android 4.x behaves unusual when switches to full screen mode 

### ISSUE THREAD

**Issue by chandnidesai7** [videojs/video.js#2346]
Device : Android 4.x mobile devices
Browser : Chrome

**Comment by gkatsev** [comment]
Looks like this is because we have `position: fixed` on the div.
https://github.com/videojs/video.js/blob/dfd481037e19c2af546ccbc706b7fb42db1c7125/src/css/components/_layout.scss#L89-L101
This has been around since the 3.0 skin https://github.com/videojs/video.js/commit/442696cfc2be6ac51b2cf63d1256abc519f57668#diff-c93a2fc6d6c2d3dfeb4f1a481e73c96dR28

I'll investigate whether we can safely remove this but it's causing issues on 4.x android devices in chrome.

**Comment by gkatsev** [comment]
And I just updated the chrome on my device and no longer have any issues around it...

**Comment by gkatsev** [comment]
@chandnidesai7 when you get the chance, can you make sure to update chrome and testing again?

**Comment by gkatsev** [comment]
Looks like on 4.0.x, google has stopped updated chrome, so, the latest is 42 which has the problem.

**Comment by gkatsev** [comment]
Fixed by #2357.
