### ISSUE TITLE
Videojs passing url parameters to Wowza

### ISSUE THREAD

**Issue by glennolsen** [videojs/video.js#2347]
I am trying to use a stream protection package that needs a parameter passed to Wowza for user authentication. 

rtmp://[wowzaip]:1935/iftalive/stream1/?token=CvAufVQARSE9WLTgjJmI9MzU8hueIY2nGLJXzxU8

The token does not appear to pass. Syntax incorrect? Not supported?

Glenn

**Comment by mmcc** [comment]
I don't think we explicitly don't support this (at least on the JS side), since it appears that we just pass the entire [end of the string](https://github.com/videojs/video.js/blob/77a96bea6fa1015c08367c0c58fbf66c2d47dc1f/src/js/tech/flash-rtmp.js#L22-L41) when parsing out the stream / connection. It might get stripped out on the [swf side](/videojs/video-js-swf), but to be terribly honest, RTMP support doesn't get as much love as it needs. Want to try and dig in on the SWF side and see what you can find?

**Comment by mmcc** [comment]
Closing this since I think it's more relevant to the SWF repo.

**Comment by glennolsen** [comment]
Thanks Matt, I am using Wrench from StreamToolbox and by moving the token
parameter before the stream identifier it works

rtmp://[wowza}:1935/app/?t=secret/stream1

I have more robust testing to do, but the dev pointed me at his faq for a
JWPlayer reference.

Glenn
