### ISSUE TITLE
mp4 video can be 'seeked' in fedora firefox, but not in win 7 firefox

### ISSUE THREAD

**Issue by propertunist** [videojs/video.js#2385]
as you can see in this example video: https://www.ureka.org/file/view/17365/me-being-covertly-censored-on-google
the video.js player is successfully buffering video and allowing the video to be 'seeked' in firefox 39 in fedora 22, but the same video cannot be 'seeked' using firefox 39 in win 7. i have tested this on multiple machines and the results are the same.
in previous tests of video.js i had similar outcomes, except that i wasn't able to get mp4s to seek at all, in any browsers - so this is actually an improvement for me!

**Comment by mmcc** [comment]
You've got something on your end that's causing weird seeking issues. Any click at all resets the video back to 0.

![screenshot](http://g.recordit.co/MNvET9Uui7.gif)

**Comment by propertunist** [comment]
this works perfectly for me in fedora 22. have you tested in that OS?

**Comment by bclwhitaker** [comment]
Are you delivering the video file from a server that can accept byte range requests?

**Comment by propertunist** [comment]
i am using nginx 1.9.3.
i haven't specifically tested for byte-range requests for a while. if the video seeking works flawlessly in fedora 22, that to me suggests that the basic mechanics of seeking are supported ok by the server.

**Comment by bclwhitaker** [comment]
I don't think your server is setup to handle the range requests typically made when seeking by most browsers (maybe your fedora client doesn't add them?).  If seeking wasn't working for mp4, there would probably be a lot more people asking about it.

These two commands should be returning 206 response codes and not have the same number of bytes in the response since they have different ranges specified in the "Range" request header:

```
$ curl -sL -w "%{http_code} %{size_download} %{url_effective}\\n" 'https://www.ureka.org/file/download/17365/censored%20on%20google.mp4' -H 'Accept-Encoding: identity;q=1, *;q=0' -H 'Accept-Language: en-US,en;q=0.8' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.134 Safari/537.36' -H 'Range: bytes=0-' -H 'Accept: */*' -H 'Referer: https://www.ureka.org/file/view/17365/me-being-covertly-censored-on-google' -H 'Cookie: Elgg=htbujjg4khfj7qr1s9nbban653; _pk_id.1.e8a2=30087d194778be65.1437418823.1.1437418823.1437418823.; _pk_ses.1.e8a2=*' -H 'Connection: keep-alive' -H 'Cache-Control: max-age=0' --compressed -o /dev/null
```
200 **35392380** https://www.ureka.org/file/download/17365/censored%20on%20google.mp4

```
$ curl -sL -w "%{http_code} %{size_download} %{url_effective}\\n" 'https://www.ureka.org/file/download/17365/censored%20on%20google.mp4' -H 'Accept-Encoding: identity;q=1, *;q=0' -H 'Accept-Language: en-US,en;q=0.8' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.134 Safari/537.36' -H 'Accept: */*' -H 'Referer: https://www.ureka.org/file/view/17365/me-being-covertly-censored-on-google' -H 'Cookie: Elgg=htbujjg4khfj7qr1s9nbban653; _pk_id.1.e8a2=30087d194778be65.1437418823.1.1437419181.1437418823.; _pk_ses.1.e8a2=*' -H 'Connection: keep-alive' -H 'Range: bytes=66110-' --compressed -o /dev/null
```
200 **35392380** https://www.ureka.org/file/download/17365/censored%20on%20google.mp4

Might want to check this nginx property:
http://nginx.org/en/docs/http/ngx_http_core_module.html#max_ranges

**Comment by propertunist** [comment]
thanks for the info. i have never set the max_ranges directive and didn't even know it existed. i searched the relevant files on my server and there are no hits for 'max_ranges' - so i think it will be set to the default value of 'unlimited'.
i do have some code in my site's nginx config file from when i was previously playing with this to get mp4s and flvs to stream correctly with video.js (over a year ago).
however, i just activated that to test the outcome and it made no difference (so i have deactivated it again). here's that code anyway:

```
location ~* \.(mp4|mp4a)$ 
	location ~* \.mp4$ 
	location ^~ /file/download/ 
	{
		mp4;
		mp4_buffer_size 4M;
		mp4_max_buffer_size 20M;
		gzip off;
		gzip_static off;
#		limit_rate_after 10m;
#		limit_rate 1m;
		# here you add response header "Content-Disposition"
		# with value of "filename=" + name of file (in variable $request_uri),
		# so for url example.com/static/audio/blahblah.mp3 
		# it will be /static/audio/blahblah.mp3
		# ----
		#set $sent_http_content_disposition filename=$request_uri;
		    # or
		#add_header content_disposition filename=$request_uri;

		# here you add header "Accept-Ranges"
		set $sent_http_accept_ranges bytes;
		add_header accept_ranges bytes;
		# tell nginx that final HTTP Status Code should be 206 not 200
		return 206;
	}
```
the browser i am using in fedora is the same version number of firefox as i am using in win 7, so i would be surprised if they handled much differently.

**Comment by propertunist** [comment]
anyone able to offer any additional info on this error?

**Comment by mmcc** [comment]
@propertunist So to be clear, are you trying to stop end-users from seeking? 

Using OS X for all of these:
Chrome 44: Attempting to seek results in my original gif. Resets playback to 0 and resumes playback
Firefox 39: Attempting to seek pauses the video during mouse down (but plays on mouse up)
Safari 8.0.6: Does not play back at all.

I don't know why I didn't notice this before, but I realized it when every browser was forcing a download when going directly to the file rather than playing back inline. You're returning the header `content-disposition:attachment; filename="censored on google.mp4"`, which I'm going to guess has everything to do with the issues you're seeing.

Hopefully that helps, but to be blunt, this kind of question doesn't really belong with this issue tracker. This is very much a better fit for a broader support forum such as [StackOverflow](http://www.stackoverflow.com).

**Comment by propertunist** [comment]
@mmcc i see - ok; i will look into that attachment setting tomorrow. i don't recall ever seeing that value mentioned anywhere - most likely it is being set by the elgg framework i am using here. thanks a lot for the tip. (i am not trying to stop users from seeking, no).

**Comment by propertunist** [comment]
having now looked into this promising code change in the header - alas, the result is that the player is still responding exactly the same as before the change for me here in firefox.
however, i see that when i play the video as a raw mp4 in the browser, the same issue exists as with video.js - so clearly the problem is not video.js.

**Comment by mmcc** [comment]
Gah! I felt pretty confident that would help, huge bummer that it didn't. Sorry I couldn't be more helpful :(

**Comment by propertunist** [comment]
no problem! i have opened a thread at the nginx forum

**Comment by propertunist** [comment]
i found the solution to this. i had not coded support for partial content into the PHP file that streams the video files in my app. i though that this would be magically handled by the server, but apparently not. i found the appropriate PHP class and this was fixed in less than a minute :)

**Comment by heff** [comment]
Great! Glad you found the fix.
