### ISSUE TITLE
a mailing list is missing

### ISSUE THREAD

**Issue by ZeeD** [videojs/video.js#2459]
This is totally not code related, but I'm having problems trying to customize the videojs library... and I don't know who to ask help!

Maybe I'm missing something, but I cannot find a forum, a newsgroup, a mailing list where *users* of the videojs can ask questions.

Can you point me to the correct place to ask questions and search for previously answered ones?

**Comment by gkatsev** [comment]
Asking a question in an issue here is always an option. While we try to limit issues to actual code issues, we will still generally try to help.
There's also, supposedly, a large community of videojs users on stack overflow. I know some of the other videojs contributors frequent SO as well.
Also, there's always IRC if you want some real-time help. It's #videojs on irc.freenode.net.

Going to close this since there isn't really anything we need to do for the project itself but please continue the discussion here if there's anything else :)
