### ISSUE TITLE
Since 5.0.0-rc60: Pause/Play functionality on click doesn't work any more

### ISSUE THREAD

**Issue by moay** [videojs/video.js#2504]
Since the update to 5.0.0-rc60, I cannot play/pause the video by clicking somewhere on the video-element any more. Used to work, now it doesn't on chrome, firefox and safari on mac. The issue is independent of the used media format, fails on both mp4 and webm.

**Comment by forbesjo** [comment]
This bug also affects touch devices, once the control bar fades away there's no way to bring it back.

**Comment by moay** [comment]
Confirm on chrome mobile (Android Lollipop)

**Comment by heff** [comment]
Added to the 5.0 milestone. We need someone to dig and and find out what changed.

**Comment by gkatsev** [comment]
This is because #2499 made `usingNativeControls` call `addTechControlsListeners` because there are some cases where it wouldn't get called otherwise. In some cases, `addTechControlListeners` would get called twice and so two handlers would get called which would cancel each other out.
Working on a fix. First, I'll make sure that `addTechControlsListeners` always removes the listeners before re-adding. Then, I'll see whether there's a way to simplify when `addTechcontrolsListeners` get added.

**Comment by gkatsev** [comment]
Fixed by #2511.
