### ISSUE TITLE
"fullscreen-video-js" is not added to the body class

### ISSUE THREAD

**Issue by TheRiddler1982** [videojs/video.js#2524]
Hi al,

I've got the following problem using your HTML5 video player with AutoOptimize using Chrome-Engine -based browsers (Chrome/Opera) and Safari.

So here is what I've observed (scroll down on https://ziin.de where the video is embedded):
I've uploaded two screenshots from Chrome 44 (OS X 10.10.5):

When called with https://ziin.de/?ao_noptimize=1 (disable AutoOptimize):
https://ziin.de/Chrome-Disabled.jpg
Menu is hidden, slider is hidden, control buttons are visible

When called with https://ziin.de/:
https://ziin.de/Chrome-Enabled.jpg
Menu is visible, Slider is visible and the control buttons are invisible

Please have a look

What I found out until now;
* this does not happen in Firefox
* this is not a CSS, but a JS problem (confirm by briefly disabling JS optimization)
* problem is that "fullscreen-video-js" is not added to the body class
* I don't see errors in the browser console (which would simplify things)

How do I have to modify the video.js to make this work? I need AutoOptimize to get my Pagespeed up to over 30 points!

Thanks,
Sven

**Comment by mmcc** [comment]
Which version of video.js are you using and is it the minified or dev version?



—

**Comment by TheRiddler1982** [comment]
Hi,

I am using version 4.12.3. My functions.php states:

wp_enqueue_script( 'video-js', get_stylesheet_directory_uri() . '/js/video-js/video.js' );

which resolves to ziin.de/wp-content/themes/ziin/js/video-js/video.js

It doesn't relate to the AutoOptimize. I was able to trigger the same behavior with disabled plugin, too.

I've also tried the newest version (besides style crashes) but it didn't to the trick either (video.js version).

Thanks,
Sven

**Comment by mmcc** [comment]
It'd be best if you can put together a reduced test case. Mind throwing
together a JSBin (http://JSBin.com/axedog/latest/edit)?

**Comment by TheRiddler1982** [comment]
Hi,

sorry, I don't have the technical expertise to make the JSBin :-(. Can you debug it on my website directly with Google Dev Tools or the Firefox equivalent? I don't mind giving you FTP oder Wordpress Backend access if that helps.

Will it work for you?

Thanks,
Sven

**Comment by TheRiddler1982** [comment]
I tried to copy my website start page code into the JSBin. But the full screen button was not working which is actually the problem that not all of the menu items are hidden.

The funny thing is that when I add the class "fullscreen-video-js" to the body element, all elements which should hide gets hidden. For some reason the event of the full screen button doesn't trigger the change of the body element. But I am not an expert in JS and CSS. Sorry :-(

**Comment by heff** [comment]
(Nice skin design! Looks cool.)

You might see if using the `video.dev.js` version works better for you. You can download it from the releases page.
https://github.com/videojs/video.js/releases/tag/v4.12.14

If that works, then just stick with that version until video.js version 5.0.

Otherwise I don't know that there's much we can do to help. I don't know what AutoOptimize is, but it's screwing with the javascript. We already do a ton of optimization on video.js, so it's not going to improve much. You might try keeping video.js separate from that process or submitting a bug to AutoOptimize, because it shouldn't be doing something that breaks a script.

Going to close because I don't think there's anything we can change in the code to help this, but feel free to continue to discuss.

**Comment by TheRiddler1982** [comment]
Hi, thanks for the compliment :-)

I was able to fix the problem by excluding the video.js from optimization. I have no idea what crahses it but now the fullscreen works!

Thanks!

**Comment by heff** [comment]
Awesome! Glad you got it figured out.
