### ISSUE TITLE
The video could not be loaded, either because the server or network failed or because the format is not supported.

### ISSUE THREAD

**Issue by raidpipe** [videojs/video.js#2575]
hello all i am having a website where i am hosting videos but the problem is that sometimes the video player behaves un usual.

i am using video.js player which is opensource html5 player

inspite of video being availabe on the server i get this error

"The video could not be loaded, either because the server or network failed or because the format is not supported."

the format is mp4 and the same video can be played on other laptop this error comes randomly

you may see the video player at this url http://www.reurl.in/ab8647946 the video may play or may not play. because the error comes randomely

**Comment by mmcc** [comment]
The good news is, the video played back fine for me every time! The bad news is, that's not terribly helpful for debugging. Looks like this is a YouTube rip, so I think we can assume the source is fine for that specific video.

However, looking through other videos on RaidPipe, it appears that they're all different (varying h.264 profiles, etc, etc), so I wouldn't be surprised if some of them have spotty support. I'm going to close this because I don't think it's a Video.js issue, but more information would be helpful: What devices? Operating system? Browser? Video.js version? Any specifics might he helpful.
