### ISSUE TITLE
video.js 5.0 - Component functions are missing in IE8

### ISSUE THREAD

**Issue by forbesjo** [videojs/video.js#2612]
Using rc90 it looks like all components except Component are missing functions in IE8

<img width="1364" alt="screen shot 2015-09-17 at 1 25 37 pm" src="https://cloud.githubusercontent.com/assets/7529098/9940764/a80ba3ac-5d3f-11e5-99c3-9d05d0adb278.png">

**Comment by heff** [comment]
wat? How is the player still loading?

**Comment by heff** [comment]
Ok I see what you mean now, and basically we shouldn't be documenting/relying on the class methods on Button etc. that are inherited from Component. Babel uses  `subClass.__proto__ = superClass` to make classes inherit class methods, and `__proto__` isn't supported in IE8. This includes `Button.extends` which probably is confusing since that's how 4.x did inheritance, but we should be using the videojs.extends function now externally and es6 classes internally.

Gonna close this but let me know if there's something else we should be doing here.

**Comment by forbesjo** [comment]
Makes sense, for the compatibility script I'll instead map Button.extend to videojs.extends with a deprecation warning.

**Comment by heff** [comment]
Perfect, thanks!
