### ISSUE TITLE
Video Control bar

### ISSUE THREAD

**Issue by rpitre** [videojs/video.js#2663]
Is there a way to decouple the control bar from the video element. In our application the video element is used to extract frames but we do not use it to display them, we use a custom WebGL viewer  . So we would like to be able to place the control bar anywhere in the dom and have the video element hidden. We do realise that we would have to write a plugin to make this work.

**Comment by gkatsev** [comment]
The control bar just takes a "player" object, so, you could instantiate your own control bar and pass it in a proxy player. This proxy player should just be an object with the various methods that the control bar uses like `play`, and `pause`, and `requestFullscreen`, and `volume`. Of course, it depends on which controls you have showing in the control bar.
I'm going to close this issue since it won't require any changes to videojs, but if you have any questions, feel free to keep asking. Also, stack overflow will probably be a good place to get more concrete help with this. Or come by IRC.
