### ISSUE TITLE
No vjs-load-progress is Firefox 41.0.1

### ISSUE THREAD

**Issue by tanuu** [videojs/video.js#2679]
I just updated to Firefox 41.0.1 Windows 7 and see the  .vjs-load-progress background color is not appearing. It happens with both vjs.zencdn.net/5.0.0/video.js and with one I use for publishing my videos, v4.6.4.

Works OK in Chrome and IE11.

**Comment by mmcc** [comment]
Can you confirm you're seeing the appropriate events with a native video element? This sounds like a browser bug to me.

**Comment by tanuu** [comment]
Sorry what is the native video element?

**Comment by tanuu** [comment]
If you mean Firefoxs inbrowser native video player, yes load progress is there. Checking now my videos in videojs in Firefox, some videos display the load progress, some not, and some that do not later do, and viceversa.

**Comment by mmcc** [comment]
Sorry, I'm not following. I was referring to the actual events themselves not just the UI of the native player (since we rely on the events). But, even with the native UI, are you saying that play progress is working with some videos and not others? Or just generally sporadically working?

This is sounding more and more like a browser bug we're not going to be able to do much about. Might want to open an issue on [Bugzilla](https://bugzilla.mozilla.org/), but we need to nail down exactly what the regression is first.

**Comment by tanuu** [comment]
It is sporadic in videojs in Firefox 41.0.1. I agree it is probably the browser, it started with the update yesterday.

**Comment by mmcc** [comment]
Hrm that's really odd about it being sporadic. It definitely makes it harder to debug than if it just didn't work at all :(

For what it's worth, I don't see this issue in 43.0a2 (Aurora channel), so hopefully this is just a temporary regression.
