### ISSUE TITLE
PlaybackRate additional opportunities?

### ISSUE THREAD

**Issue by kukrik** [videojs/video.js#2733]
Before the playbackRate is plugin, is now inside the core. It is very good to have more than one rate as in this instance '' ..., "playbackRates": [0.5, 1, 2, etc]".

Sometimes you may encounter situations where there is only a need, such as the rate of two: "..., "playbackRates": [0.5, 1]" Then it would be good to implement playbackRate toggle. I thought of something similar - active or non-active, click the "Slow" or a single icon...

Is it possible to have some opportunities to do this? Any thoughts and suggestions are welcome.

**Comment by gkatsev** [comment]
You should be able to make a plugin that adds a button to the control bar that toggles between two playback rates. You can call [`Player#playbackRate`](http://docs.videojs.com/docs/api/player.html#MethodsplaybackRate) to set the playback rate from your plugin when the button is toggled.
This is unlikely to get added into Core directly since we already have the playbackRates menu.
If you have anymore questions, feel free to ask.
