### ISSUE TITLE
[version 5] In Chrome, setting currentTime closer than a second from the actual current time does not work

### ISSUE THREAD

**Issue by Billybobbonnet** [videojs/video.js#2749]
Hello,

I used to provide a pseudo frame-by-frame feature using the keyboard arrows. I have used the hotkeys plugin for that both in version 4 and version 5.

In version 4, doing something like `player.currentTime(player.currentTime() + seekStep);` with a seekStep of e.g. 0.066 (15fps) worked fine.

In version 5, **when using chrome only** (FF works fine) it "rewinds" the video (in other terms, it plays it at high speed for approximatively 0.5 sec) from a random point to another random point, both being at one or less seconds from the previous current time. The time display works fine, meaning it never actually comes back one second before when moving forward to the next frame, but the displayed frame can be from the previous second. Of course I tried it with several videos, the same ones in v4 and v5.

I am not sure to be clear so don't hesitate to request more details if necessary.

**Comment by gkatsev** [comment]
What video type are you using? And do you know if it ends up running in flash or html5?
Does it still currently work in the same chrome version with version 4?
I wonder whether it's a browser bug or a videojs bug.

If you have a working example, that would be awesome as well.

**Comment by Billybobbonnet** [comment]
I am using mp4 videos and I end up with the HTML5 player. 

It still currently works in the same chrome version with version 4

You can easily reproduce the issue with a videojs v5+ in an up to date chrome browser, if you add the hotkeys plugin with the following settings (taken directly from my code):

```javascript
videojs('video_player',
  {
    controls: true,
    loop: false,
    autoplay:true
    }
  }, function() {
    this.hotkeys({
      volumeStep: 0.1,
      seekStep: 0.033, //we assume 15fps for the image per image steps
      enableMute: true,
      enableFullscreen: true
    });
```

Compare the behavior with Firefox and you will see what I mean.

Tell me if I can be of any help.

**Comment by gkatsev** [comment]
That's super weird since the code for that didn't really change between [v](https://github.com/videojs/video.js/blob/v4.12.15/src/js/media/html5.js#L227-L234) [4](https://github.com/videojs/video.js/blob/v4.12.15/src/js/player.js#L691-L696) and [v](https://github.com/videojs/video.js/blob/master/src/js/tech/html5.js#L318-L325) [5](https://github.com/videojs/video.js/blob/master/src/js/player.js#L1273-L1278)

**Comment by Billybobbonnet** [comment]
By the way, even if I set a larger seek step, I still have the "rewind/fast forward" effect. i.e. for 5 sec I still see an accelerated/partial version of what's in-between.

I triple checked and indeed, v4 works fine as opposed to v5. Maybe check if it could be related to https://github.com/videojs/video.js/issues/2672

**Comment by gkatsev** [comment]
Hi, it's been a while. Is this still a problem with latest Video.js's? I guess a workaround would also to talk directly with the Video.js tech rather than through the player for this super precise movement.
Going to close this for now but feel free to open a new one or ping us here to re-open if there are still issues.
