### ISSUE TITLE
Missing inline volume control for 5.0.2

### ISSUE THREAD

**Issue by ctd1500** [videojs/video.js#2765]
The inline volume controls are not available in the default skin.
According to #1553 and the [migration guide](https://github.com/videojs/video.js/wiki/5.0-Change-Details#volume-menu-is-the-new-default-see-1553), it should be a simple CSS change to display inline volume without the sliding menu.
The CSS change given in the [blog post](http://blog.videojs.com/post/121061752226/its-here-50-release-candidates) doesn't work because the mute / inline volume control isn't in the DOM.

**Comment by mmcc** [comment]
It's still a simple CSS change to show inline volume all the time, the blog post you're referencing is from the very first release candidate and things changed since then. The current volume menu button can be used to create other volume control flavors with just CSS or configuration on init.

For example, here's a simple CSS change to display inline volume without the sliding menu:

```
.video-js .vjs-menu-button-inline {
  width: 12em;
}

.vjs-menu-button-inline .vjs-menu {
  display: block;
  opacity: 1;
}
```

**Comment by OwenEdwards** [comment]
@mmcc I'm trying to work through what *is* supported for volume control in V5.0, since the [migration guide](https://github.com/videojs/video.js/wiki/5.0-Change-Details#volume-menu-is-the-new-default-see-1553) doesn't cover all the options.

The CSS you gave always displays the inline volume slider.

Also, the `volumeMenuButton` can take options `inline` and `vertical`. Setting inline to `false` and vertical to `true` creates a vertical volume slider which only displays on mouseover or hover, but drops *down* from the mute button, so it is hardly visible with the default videojs CSS (on the simple-embed example, at least). The Brighcove player seems to have it in the right place. Otherwise, the default values of inline as true and vertical as false work as desired, but no other combination makes any sense.

This all related to trying to get the Captions and Subtitles menus (and ultimately the Descriptions menu) to be accessible for screen reader and keyboard users; I'm trying to understand what the volume 'menu' is trying to support/achieve, since it doesn't support keyboard access correctly either, and fixing the menus breaks the volume control!

**Comment by richardbushell** [comment]
Same question, is there any way to get the Vertical Volume Slider working in vjs5.x?
