### ISSUE TITLE
Subtitles position (<track/>)

### ISSUE THREAD

**Issue by anonym24** [videojs/video.js#2779]
It's bad position for subtitles when you don't use original html5 controls for video in Chrome
http://anonym24.github.io/video.js-subs-test/ - here screenshots and video example
Is it possible to add some margin-top?

**Comment by gkatsev** [comment]
We had a discussion around it in https://github.com/videojs/video.js/issues/2193. It was fixed by @chemoish in https://github.com/videojs/video.js/pull/2702. It's released as videojs 5.1.0. 5.1.0 is available in the [release tab on github](https://github.com/videojs/video.js/releases/tag/v5.1.0) or on npm (`npm install video.js@next`) or on bower. We haven't published it to the CDN yet to make sure that everything is good to before pushing to the CDN.

**Comment by anonym24** [comment]
Thanks

**Comment by gkatsev** [comment]
No problem.
