### ISSUE TITLE
Videojs treat WEBM as livestream

### ISSUE THREAD

**Issue by fuqet** [videojs/video.js#2792]
For some reason whenever i use webm video.js thinks it is a live stream and disables the timeline of the video.. How can I fix it?

Thank you?

**Comment by fuqet** [comment]
Any ideas?

**Comment by mmcc** [comment]
We'd need to see an example, but normally this points to an issue with either the file itself or how it's being delivered. VJS will show the live UI if the [duration of file is infinity](https://github.com/videojs/video.js/blob/f2fa8f86870ed52ee47a891ced97d4af25bf0814/src/js/player.js#L1325-L1329).

#1573 is potentially related as well.

**Comment by fuqet** [comment]
Here is the link

http://evids.eu/home/video/4219836602

some videos are fine but videos above a minute duration are treats as LIVE.

**Comment by mmcc** [comment]
If you're serving WebM, why do you have the content type set to mp4?

Regardless, I'd be willing to bet a *lot* on this being an issue with how you're serving the file. Folk trying to serve media dynamically via PHP invariably have a terrible time. If you load the file directly via a static server do you see the same issue?

Closing this because all signs are pointing to this being an issue with how the file is served, but we can continue to help diagnose.

**Comment by fuqet** [comment]
The problem was with conversion mp4 to webm.. thanks for your help.
