### ISSUE TITLE
Hello,how can i use videojs to play m3u8 ?

### ISSUE THREAD

**Issue by victoryboss** [videojs/video.js#2855]
i find the plugin 'videojs-contrib-hls',but it does not support ie8, 
then i change my way , by flash videojs (www.flashls.org/videojs/flash_demo.html),
it is very nice ,but i can not select sharpness with m3u8 playlists.

**Comment by gkatsev** [comment]
contrib-hls doesn't support ie8 or ie9 because they don't have the javascript features that are necessary for it to function.
As for flashhls, I don't know if it has APIs for bitrate selection. If it does, it would need some kind of plugin for videojs to have a menu that allows you to choose them. Either way, you should open an issue against that project regarding this question.
Closing, but if you have any other questions, feel free to ask.
