### ISSUE TITLE
Scrubbing events

### ISSUE THREAD

**Issue by Soviut** [videojs/video.js#2862]
It would be really handy to have events fired on scrubbing start, changing time/seeking and ended. Ideally, they should be cancellable to prevent scrubbing (for example, during an ad or online learning modules).

I realize that `seeking` and `seeked` events exist, but they act differently than the custom `scrubbing()` API within videoJS.

**Comment by zcoding** [comment]
+1

**Comment by vhmth** [comment]
Right now, because we `<iframe>` our video player, if you start scrubbing, drag outside of the iframe, and then release your mousedown click outside of the iframe, the player still thinks it's in scrubbing mode and will continue to scrub when you hover back into the iframe. I'm not sure how this is currently implemented, but it would be useful if a release of your mouse click would register with the player even when it leaves the iframe.

Here's a video of me showing this behavior:

https://www.useloom.com/share/a926189010af4c4aa072207553d7d098

and the website to test:

http://www.vinay.sh/

**Comment by gkatsev** [comment]
We don't have events but using Middleware in v6 and v7, you can intercept `setCurrentTime` and know when the user is seeking. You can (until we make this be a mediator mw) just return `currentTime` to "prevert" the seek.

**Comment by gkatsev** [comment]
Oh, here's a link to middleware docs: http://docs.videojs.com/tutorial-middleware.html
