### ISSUE TITLE
createEl doesn't called.

### ISSUE THREAD

**Issue by yoonsy** [videojs/video.js#2898]
Hello, I am using videojs 4.11.4.

I created MyButton extended `videojs.Button` like below.

```js
videojs.MyButton = videojs.Button.extend({
  init: function(player, options){
    videojs.Button.call(this, player, options);
    this.on('click', this.onClick);
  },

  createEl: function() {
    var el;

    el = videojs.Button.prototype.createEl('div', {
      className: 'vjs-my-button',
      innerHTML: '<div>my button</div>'
    });

    return el;
  },

  onClick: function() {
    alert("MyButton!");
  }
});
```

and register it to plugin.

```js
videojs.plugin('my_button', function(config) {
  this.controlBar.addChild('MyButton');
});
```

and excuted videojs.

```js
videojs('player', { 
  plugins: {
    my_button: {}
  }
})
```

videojs made my_button, **but with default button.**
```html
<div class="vjs-control " role="button" aria-live="polite" tabindex="0">
  <div class="vjs-control-content">
    <span class="vjs-control-text">Need Text</span>
  </div>
</div>
```

After debugging, I realized `videojs.MyButton.prototype.createEl` was not called.

When I changed `video.js` to `video.dev.js`, it works what I expected.

What I am doing wrong?

Note.
I should not use videojs 5.x.

**Comment by gkatsev** [comment]
> Note.
> I should not use videojs 5.x. 

Can you elaborate on this note?

Basically, the issue is that in videojs 4.x we used google's closure compiler in Advanced Compilation mode that mangled names heavily. `createEl` is unfortunately one of those items that were mangled.
It's unlikely that we'll release a patch release of videojs 4.x to fix this issue. The recommended approach would probably to upgrade to vjs 5. Otherwise, to use `video.dev.js` and then minify the file yourself.

**Comment by yoonsy** [comment]
OK! Thank you for fast response :)
