### ISSUE TITLE
Canvas element in videojs controls

### ISSUE THREAD

**Issue by chaitanyya** [videojs/video.js#2941]
Is it possible to push a canvas element in videojs controls? If yes, how?

I want the canvas to cover the entire video player and it should also work on fullscreen. Can you please tell me how can I push it into the controls?

**Comment by gkatsev** [comment]
Yep, the control bar is just a DOM element, so, you could just `appendChild` to it whatever elements you want. You can also make a [custom Component](http://docs.videojs.com/docs/guides/components.html) and then added it the controlBar via [`addChild`](http://docs.videojs.com/docs/api/control-bar.html#MethodsaddChild).
You can also overlay any element on top of the video. You'll probably want to add the element to the wrapper div that videojs creates and then set the `width` and `height` to `100%` via css (though, since it's canvas, you'll also probably want to set the `width` and `height` attributes on the canvas element directly because of how it works).

This question may be better fit for [Stack Overflow](http://stackoverflow.com/questions/tagged/video.js), where you're most likely to get a quick response for the specifics of how to do what you need. If you do post to Stack Overflow or if a post already exists, please link to it here.

Hope that helps, thanks.
