### ISSUE TITLE
iOS video player no longer showing control-bar when vjs-user-active class applied

### ISSUE THREAD

**Issue by KempfCreative** [videojs/video.js#2968]
The behavior of the videojs player used to work so that as long as a user taps on the video section and toggles the vjs-user-active class, the control bar would become visible on iOS. This appears to be no longer working.

While the iOS default player will take over the video player when the video is actually playing, when the focus is active on the video element and the video is not playing, the container should have the vjs-user-active class applied, and the control bar should remain active.

If we are looking at this from a perspective of providing a good UX, the goal should be to have the control bar remain on the screen all of the time, so that users are aware of the length of the video and can tell what sort of committment they are getting into before playing the video, as well as informing them of their available playback options when using videojs.

Please let me know if you would be interested in a PR to add this much needed functionality, or if you need more information as to the issue I am reporting.

**Comment by gkatsev** [comment]
Last I checked, tapping on the video area will toggle the showing of the control bar. This is in line with the native control bar functionality on iOS.
We do not want to have the control bar always showing because the control bar is inside the bounds of the player and thus can hide parts of the video.

Thanks.
