### ISSUE TITLE
Width/height getters not working as expected on player component

### ISSUE THREAD

**Issue by jpfranco** [videojs/video.js#2974]
Hey guys, I'm not sure whether this is the intended use case, but I seem to be getting unexpected results when calling ```.width()``` or ```.height()``` on the player component. On the other hand, doing this with the control bar returns the expected dimensions.

You can reproduce this with the player on videojs.com by typing this into the dev tools console:

```
videojs.players['preview-player'].width()
```

The above returns 0, but works fine when referencing the control bar:

```
videojs.players['preview-player'].controlBar.width()
```

**Comment by gkatsev** [comment]
This is because the `width()` and `height()` methods on the player itself are analogous to the `width` and `height` properties on the video element itself. Those properties will return what the element has been configured with. We've had some discussion about this in https://github.com/videojs/video.js/issues/2282 and came to the conclusion to leave `width()` and `height()` on `player` as it is.
In #2282, we also had some though about adding `player.currentWidth()` but decided against doing so in the meantime since using `getComputedStyle` isn't a lot more work.
Hope that helps. Thanks.

**Comment by jpfranco** [comment]
Oh ok, I see. Sorry, those issues didn't come up on my search results for some reason. I'll use ```getComputedStyle``` as suggested. Thanks

**Comment by gkatsev** [comment]
Np. Yeah, I had to dive deep in there to find that issue since I knew it existed. Had some trouble finding it myself.
