### ISSUE TITLE
RTMP - WOWZA - RTSP live streaming

### ISSUE THREAD

**Issue by Arussil** [videojs/video.js#2978]
Hi,

i'm working on a live streaming platform with channels provided by a provider, i have a rtmp streaming url that's the wowza server of the provider and a stream name that's something like "rtsp://domain:port//channel/channelId_rtsp.sdp?ticket=user_ticket", i can't find a way to use it with video.js rtmp support, i don't even know if it's possible. The stream work with various flash player and i would like to know if video.js can use something like this (with only flash support) or if i have to find another solution (we use video.js for static video too). Thanks in advance.

**Comment by sgarbesi** [comment]
+1

**Comment by coral** [comment]
@Arussil video.js does not natively support RTMP due to the protocol is designed. Browsers doesn't allow for free TCP sockets like Flash, hence hard to implement. What you could do if you're crazy is write a websocket wrapper and push the video out that way, or just repackage it to HLS & DASH server side, fragment it and serve it as HTTP to video.js

**Comment by gkatsev** [comment]
videojs does has super simple RTMP support however we're unlikely to be expanding any effort because we consider flash to be older technology and not the future of the web.
@mister-ben do you know if this is possible? I don't really know much about the RTMP support.

**Comment by mister-ben** [comment]
Live RTMP should work and has where I've tried it. Bear in mind that every RTMP server implementation does something or other differently, so it's hard to say every possible stream will work.

RTSP is a very different protocol. The RTMP support doesn't help with RTSP at all.

I'm curious, since Wowza can output HLS and you can have all the Flash-less goodness of HLS playback through MSE with videojs-contrib-hls, why do folks want to use RTSP?

**Comment by Arussil** [comment]
I can't really give you an answer, as we just implement what the provider is giving us. The funny thing it's we get a different stream based on user agent, so on mobile devices we get an http stream which i simply use with video.js and for desktops and such we get the RTSP. In the end we decided to serve the RTSP content with a flash player. I'm just hoping Flash will die soon for real so we can avoid such awful solution.

**Comment by gkatsev** [comment]
Sounds like this isn't something that videojs can fix.
You should tell your provider to start giving you HLS everywhere and use videojs-contrib-hls :P

**Comment by Arussil** [comment]
That's the first thing i tried :D
