### ISSUE TITLE
Mute toggle stops working

### ISSUE THREAD

**Issue by Lumbendil** [videojs/video.js#3036]
If I press the mute toggle multiple times, it arrives to a point to which it stopps working.

Tested on Ubuntu with both Chrome and Firefox.

Additional info: It seems it gets stuck into such a position because volume gets set to 0, thus making the toggle unoperative. I've found this because when muted without the bug, calling `player.volume()` returns the volume if it was unmuted, while if it gets bugged, `player.volume()` reports a 0, thus the toggle does nothing.

**Comment by gkatsev** [comment]
That's really weird. The mute toggle should not ever be setting the volume to 0. What version of videojs are you using? Also, would you happen to have a reduced test case?

**Comment by Lumbendil** [comment]
I'm using the latest tagged version. I don't have much of a reduced test
case, other than spamming the mute toggle really fast until it happens. My
guess is that doing that the tech receives a "mute" signal when the player
is being muted, thus messing it up.

2016-01-26 17:45 GMT+01:00 Gary Katsevman <notifications@github.com>:

**Comment by gkatsev** [comment]
I just ran the following test locally in the sandbox and it worked just fine.
```js
var i = 1000;
function loop() {
  player.controlBar.volumeMenuButton.el_.click(); 
  if (i--) {
    setTimeout(loop, 1); 
    console.log(i); 
}}
loop();
```
Unfortunately, unless you'll be able to get exact steps to reproduce or a working testcase there's nothing we can do.

**Comment by FDiskas** [comment]
Same for me. videojs version 4.12.15
try something like this
```js
var player = videojs('video-player');
player.volume(0.5);
player.muted(true);
player.muted(false);
alert(player.volume());
```
And result will be `0` but must be `0.5`
Same problem on `5.6.0` version

**Comment by gkatsev** [comment]
Just tried it with 5.6.0 and did not see this issue:
```js
player.volume()
// 1
player.volume(0.5)
player.volume()
// 0.5
player.muted()
// false
player.muted(true)
player.volume()
// 0.5
player.muted(false)
player.volume()
// 0.5
```

**Comment by FDiskas** [comment]
and flash version to?

**Comment by gkatsev** [comment]
So, I think we've finally been able to track down the issue, thanks to @imbcmdth. If when you're clicking on the mute toggle, you move the mouse slightly, it'll end up changing the slider. This is because the slider is a child of the mute button in the normal control and we want users to be able to use more than just the 4 pixels of the volume slider itself for sliding the volume up and down. We just have to be stricter about not allowing the volume to change when the mouse is being moved on top of the mute toggle itself. May be a bit tricky but should definitely be doable.

**Comment by gkatsev** [comment]
@Lumbendil @FDiskas this should be fixed in the 5.8.8 release. Please try it out.

**Comment by FDiskas** [comment]
Confirmed

**Comment by gkatsev** [comment]
Awesome, thanks @FDiskas!

**Comment by mizmaar3** [comment]
I still can reproduce it on videojs v.5.20.4 @gkatsev according to you its fixed in 5.8.8 !

here: https://googleads.github.io/videojs-ima/examples/simple/
Wait for preroll ad, after clicking on `Volume Bar` the mute toggle does not work.

**Comment by gkatsev** [comment]
Can you elaborate on where you're clicking and what you mean by "does not work"?
For me, trying to do what this bug called for no longer occurs. So, if I click and drag the mute button it will not change the volume level but just mute/unmute the player. Clicking on the volume level does not prevent the mute toggle from toggling whether the player is muted or not. Also, in the latest version, a volume level of 0 is separate from a muted state so it's easier to tell that something weird is going on.
In Video.js version 6, we even combined muted state and volume 0 because from a UI and user perspective, it's better to have them be equivalent. So, dragging the volume to zero mutes the player as the same as clicking on the mute toggle. Unmuting puts you back to where you previously had the volume at.

**Comment by mizmaar3** [comment]
Im using videojs-ima (google plugin to play vast/vpaid) and unfortunately they still support videojs 5.20.x so cant blame videojs really but if its fixed in 5.8.x I dont expect the issue in 5.20.x or may be its different that above mentioned issue.

I can reproduce that easily (im using chrome btw) its not about dragging mute button, instead if you drag or click on `Volume Level Bar` once and then click on `mute icon` the mute icon does change Volume Level to 0 but video does not mute neither the `unmute icon` change to `mute icon`. If you manually click on far left to the `Volume Level Bar` to make it 0 then video does mute.

Hope I explained it correctly now :)

**Comment by gkatsev** [comment]
that is a different bug then. also, is this during the ad? if so, in the example you've given the ad has its own controls so it's probably a bug with the ad or videojs-ima.

**Comment by mizmaar3** [comment]
yes its during the ad so most probably I shud report it to videojs-ima. 
Thanks for clarification @gkatsev 👍

**Comment by gkatsev** [comment]
you're welcome.
