### ISSUE TITLE
How can i prevent video.js from putting styles in head

### ISSUE THREAD

**Issue by sirakoff** [videojs/video.js#3051]

**Comment by hartman** [comment]
Right now you can't. I'm another person who isn't entirely too happy with this either. I've stripped the defaults from my player already, and was also thinking of stripping the 'per video' styles. I like styles, but this whole strategy seems a little bit 'over the top' to me.

I might consider making an official patch to make this behavior configurable.

**Comment by gkatsev** [comment]
There isn't a way to do it right now.
Can you please elaborate on why? Style elements are meant to go in the HEAD, also, this makes it easier for users to use the cascading of css to make defaults or other styles be user override-able without having them resort to crazy hacks or using `!important`.
Thanks.

**Comment by sirakoff** [comment]
I use virtual-dom for manipulating the title in the head tag, but because the styles are inserted at the beginning, virtual-dom isn't able to diff properly.

**Comment by mmcc** [comment]
I'm confused about what this thread is talking about. If the discussion is about the base theme getting inserted in the head, you just need to set `VIDEOJS_NO_BASE_THEME` to `true` before loading Video.js.

**Comment by gkatsev** [comment]
Oh, totally didn't remember that variable. We probably should make sure that all of the style elements we put into the head element respect that property then. The [style-defaults](https://github.com/videojs/video.js/blob/master/src/js/video.js#L102-L117) doesn't. I don't think the `style-el` does either.

**Comment by mmcc** [comment]
Yeah I think those styles should probably go in [base-styles](https://github.com/videojs/video.js/blob/master/src/js/base-styles.js).

**Comment by sirakoff** [comment]
`VIDEOJS_NO_BASE_THEME = true` didn't solve the problem. I solved it by manually adding the style tags at the end of the head tag.

Thanks!.

**Comment by gkatsev** [comment]
So, looks like the `base-styles` feature was never hooked up. Which is why users are still required to add the CSS manually.
However, we still end up making two more style elements and adding them to the HEAD, specifically, the `style-defaults`, and `player-dimensions`. Both of those should respect the `VIDEOJS_NO_BASE_THEME` property and *not* add an element when it is set.
In addition, I believe that the `player-dimensions` feature, specifically the portion of using the video dimensions as default player dimensions, isn't well liked and should get an option to disable that feature.

I'll be working on those now.

**Comment by gkatsev** [comment]
A PR for this is now available, see #3093.

**Comment by gkatsev** [comment]
This has been fixed via #3093.
