### ISSUE TITLE
live streaming not working .

### ISSUE THREAD

**Issue by sarathvs123git** [videojs/video.js#3056]
Hi,

         Is there a working example for live streaming .
  I tried below example code . But it showing error 'The media could not be loaded, either because the server or network failed or because the format is not supported.'
```
       <video id="my-video" class="video-js" controls preload="auto" width="640" height="264"
   data-setup="{}">
    <source src="rtmp://myserver:1935/live/myStream&mp4:path/to/BigBuckBunny.mp4" type="rtmp/mp4">
  </video>
<script src="http://vjs.zencdn.net/5.5.3/video.js"></script>
```

**Comment by mmcc** [comment]
From what I see, what should work. Can you put up an example on [JSBin](http://jsbin.com/axedog/latest/edit)? Including a link to the source you're using would also help a great deal for debugging.

I'm closing this because it feels more like a question than an issue, and if it's an issue we'll probably want to open a new one on the [swf](/videojs/video-js-swf).
