### ISSUE TITLE
VideoJS throws error in Windows 10 with IE or Edge when seeking within a Vimeo direct link source

### ISSUE THREAD

**Issue by anthonystauffer** [videojs/video.js#3092]
The following page has a interactive demonstration of this bug:
[http://anthonystauffer.s3.amazonaws.com/videojs/videojs-error.html](http://anthonystauffer.s3.amazonaws.com/videojs/videojs-error.html)

### Setup

Semi-Private videos hosted on Vimeo are accessible via an API. The API provides direct links to the various files (with different resolutions) for use in 3rd party players. Those URLs contain various parameters like an OAuth token and profile ID.

### The Bug
When using IE or Edge browsers on Windows 10, when such a URL is fed to VideoJS via the src() API method, the video appears to load and play just fine. 

But when you click on the progress bar, attempting to seek to a later part of the video, VideoJS throws an error.

I've confirmed that this does NOT happen when a video from another location (without parameters in the URL) is used. In addition, this does not happen with Firefox, Chrome or Safari on Windows or OSX.

**Comment by mister-ben** [comment]
First, thanks for providing a lot of detail.

These Vimeo videos also error when seeking on Edge and IE in a plain video element, giving a 'decode error'. That would indicate a issue lower down rather than something video.js could cause or fix.

The actual video encoding doesn't seem to be the problem though -- download one and serve it from a bog standard Apache server, and it will play and seek fine.

But I did notice the Vimeo CDN URLs have [HSTS headers](https://developer.mozilla.org/en-US/docs/Web/Security/HTTP_strict_transport_security) on the responses. These tell the browser it should connect over HTTPS. That should just be handled by the browser, but it looks like somethings's broken in IE/Edge when a second request is made when you seek.

If you change your Vimeo source URLs from HTTP to HTTPS, they work.

**Comment by anthonystauffer** [comment]
Ah, this is more devious than I expected. It turns out that the URL that Vimeo provides (even if it's an HTTP URL), redirects to their CDN, which in turn forces it to HTTPS. So there is apparently no way to get a non-HTTPS link to a video from their API. I've reported it to them, hopefully they'll fix it.
