### ISSUE TITLE
video js is aborting playback while playing m3u8 playlist in chrome where as in other browsers it plays fine

### ISSUE THREAD

**Issue by jequin** [videojs/video.js#3108]
I am using videojs for playing a m3u8 VOD stream. Everything works fine untill tested in chrome. 
videojs aborts playback saying browser does not support. 
The media files which are in the playlist (m3u8) are `.ts` format. 
```
<script>
myPlayer.src({
          //myPlayer is my object for <video>
          type: $scope.videos[tracker].srcType,
          src: "ideal_link.m3u8"
        });
myPlayer.play();
</script>
```
For html
```
<video id = "example video">
</video>
```
here is the screenshot for error `http://prntscr.com/a3f6sk`

**Comment by gkatsev** [comment]
That is because chrome, indeed, doesn't support HLS playback.
It'll work in chrome on mobile devices but not on desktop browsers.
You can try using [contrib-hls](https://github.com/videojs/videojs-contrib-hls) for desktop playback (assuming it is [set up properly](https://github.com/videojs/videojs-contrib-hls#hosting-considerations)).
Hope that helps.

**Comment by jequin** [comment]
i am indeed using contrib-hls and yes it is set up correctly.

**Comment by gkatsev** [comment]
Ah, that is important information to include. It sounds like the issue is that the plugin can't play it in chrome because chrome is very strict about codecs and if we tell it one thing and then give it another it errors out.
Can you open this issue against the contrib-hls project? Also, would you be able to provide a sample m3u8 and ts segments? It'll be very hard for us to reproduce and fix without sample content.

**Comment by jequin** [comment]
Okay i can produce one.. I am opeing the same in contrib-hls
