### ISSUE TITLE
button css class

### ISSUE THREAD

**Issue by campones** [videojs/video.js#3192]
for the pause play button and full screen you have been introducing a `<button class  .. >` instead of the `<div class="vjs-fullscreen-control vjs-control "> `

the problem is this is overwrited by the website template as the button is often designed on his own in the template class. personally I have a bootstrap template and I had blue player button.. First I thought this was the actual design of the v5's player till I realized those css class were actually conflicting.. 

https://i.gyazo.com/2a032910ef4786018fcbc705704dbb6a.png

**Comment by mmcc** [comment]
If you search through the issues, you'll find a few threads talking about why we decided to go with buttons instead of divs, but the tl;dr is that they're simply the right choice here. We've tested with other frameworks as well and not seen issues with specificity (the Video.js home page even uses Bootstrap), but if you find a specific instance where dropping Video.js in a default framework ends up with this, let us know (along with a reduced test case so we can see what's going on).

**Comment by campones** [comment]
Well I just show you this specific instance.. I didn't invent the screenshot.. the framework is a joomla website with a t3 framework template

**Comment by mmcc** [comment]
> if you find a specific instance where dropping Video.js in a default framework ends up with this, let us know (*along with a reduced test case so we can see what's going on*).

Sorry, I wasn't implying that you were making it up, but a screenshot is useless for us to help debug something.
