### ISSUE TITLE
The media could not be loaded, either because the server or network failed or because the format is not supported.

### ISSUE THREAD

**Issue by leven0106** [videojs/video.js#3203]
My web program was originally used to play mp4 Flash video, but need to get the playback progress, this implementation has been unable to meet the demand. 

So intend to use video.js to achieve, but when playing video prompts media could not be loaded The because either the server or network failed or because the format is not supported". 

My flash code：
![1](https://cloud.githubusercontent.com/assets/8336343/14006984/6b907a94-f1ad-11e5-8fa2-c7e86242aeba.png)
Video.js code：
![2](https://cloud.githubusercontent.com/assets/8336343/14006999/910a44da-f1ad-11e5-8ad4-2411b3cf85d6.png)
File download method：
![3](https://cloud.githubusercontent.com/assets/8336343/14007049/ef621972-f1ad-11e5-8a4b-d2d385d3c623.png)

This problem has been bothering me for a few days, please help me, thank you very much!

**Comment by gkatsev** [comment]
Not quite sure what is happening. You shouldn't need to do any flash code with videojs, you should be able to just get the url to the mp4 and give it directly to videojs and it should figure it out.
One thing I notice is that in your response, you set it to be an octet-stream content type, it should be a `video/mp4`, it's possible the browser is rejecting the request because of that. Also, it's possible that the mp4 is malformed or just not something that the browser can understand. On top of that, some browsers when dealing with mp4s will do byterange requests and if your server doesn't handle it, it can break.
Some things to try is to force the [flash tech](http://docs.videojs.com/docs/guides/tech.html), also, trying to host the mp4 locally on a static file server or via something like nginx for comparison. We constantly see issues on here where someone is trying to serve an mp4 with some custom php and it doesn't work. Could be a similar issue here.
Do you have this error in all browsers or just some? Does the mp4 play back in other media players?

Closing this issue because it's unlikely to require a change to videojs itself. However, we can still continue the discussion here and if it turns out to actually be an issue with videojs, we can re-open the issue.
