### ISSUE TITLE
How to setting auto play track?

### ISSUE THREAD

**Issue by dinhcode** [videojs/video.js#3214]
i have user videojs 5.8.6

html code
`  <video id="example_video_1" class="video-js vjs-default-skin" controls preload="none" width="640" height="264" poster="http://vjs.zencdn.net/v/oceans.png" data-setup="{}">
    <source src="http://vjs.zencdn.net/v/oceans.mp4" type="video/mp4">
    <source src="http://vjs.zencdn.net/v/oceans.webm" type="video/webm">
    <source src="http://vjs.zencdn.net/v/oceans.ogv" type="video/ogg">
    <track kind="captions" src="track.vtt" srclang="en" label="English" default>
 <track kind="captions" src="track-es.vtt" srclang="es" label="Spanish">
 <track kind="captions" src="track-fr.vtt" srclang="fr" label="French">
  </video>`

but play vieo allway show captions off (view image). I have to choose track dont auto play default English
How to setting auto play captions default?

![untitled](https://cloud.githubusercontent.com/assets/17776029/14079747/14841870-f52a-11e5-81e8-4ec639cb2280.png)

**Comment by gkatsev** [comment]
We have a bug around the `default` property for tracks (https://github.com/videojs/video.js/issues/1914). The spec only has a suggestion on how to handle the `default` attribute and we definitely need to figure out what videojs should do, since different browsers handle that attribute differently.

As a workaround, you can set the `mode` to `showing` programmatically.
