### ISSUE TITLE
ajax loading sources, but can't play

### ISSUE THREAD

**Issue by wdfsinap** [videojs/video.js#3216]
I want to use ajax to dynamic load videos to play, but after loading, the player just can't play,
here is my code:
```
<video id="my-video" class="video-js" controls preload="auto" width="100%" height="388"
  poster="MY_VIDEO_POSTER.jpg" data-setup="{}">
</video>
```

```
	$.ajax({
		url: 'http://104.236.182.195:8000?id='+'{{video_id}}',
		dataType: 'jsonp',
		success:function(resp) {
			var vi = '';
			$.each(resp.i,function(index,c) {
			 vi+='<source data-res="'+c.resolution+'" src="'+c.url+'" type="video/'+c.filetype+'" />';
			})
             $(".vjs-tech").html(vi);
		}
	})
```
please tell me how to play the videos after loading the source. thanks

**Comment by gkatsev** [comment]
You should be using the [videojs api](http://docs.videojs.com/docs/api/player.html#Methodssrc) to add the sources instead of adding the source elements to the DOM.
Your other option is to not have videojs autoinitialize the element (`data-setup="{}"`) and instead only initialize it after you've added the source elements to the page. That is, call `videojs('my-video');` after line `$(".vjs-tech").html(vi);`.
Hope that helps, thanks.
