### ISSUE TITLE
Can't change caption font-size in new versions of videojs?

### ISSUE THREAD

**Issue by rfs-** [videojs/video.js#3301]
Old ways to change font-size on captions don't work anymore with new versions of videojs. I saw that .vtt files are now using mostly native functions in browers instead of videojs controlling it but I still don't see how to change font-size now.

I believe cue's need to be unique otherwise it would be nice to just put ::cue (*){font-size:1.2em}

Tried changing .video-js .vjs-text-track font-size with no effect in the css file. Same with .video-js .vjs-captions.

Using Video.js 5.8.8

Is this even possible anymore?

**Comment by gkatsev** [comment]
The native tracks are just using the `::cue` pseudo class:
```css
::cue {
  font-size: 1.2em;
}
```
As for emulated tracks, I'm not sure there's an easy way to override the default but users are able to change the size themselves with the captions settings menu that's available.
Though, something like
```css
.vjs-text-track-display div {
  font-size: 1.2em;
}
```
should work for permanently setting a size.

Hope those help, let us know if that works or you're having more trouble. Closing because there's unlikely to be changes requires in videojs but discussion can continue.

**Comment by rfs-** [comment]
Thanks for the prompt response. Tried both, the cue solution didn't do anything for me. It looks like the 2nd option of:

`.vjs-text-track-display div {
  font-size: 1.1em !important;
}`

Makes firefox and IE change the font-size but chrome doesn't take any effect on sizing.

http://dev2.miramar.ca/dh/closedcaption/

**Comment by gkatsev** [comment]
You probably want both, on IE and firefox we use emulated tracks because the native implementations are broken or incomplete or impossible to work around but in chrome we use native tracks.
You can force emulated tracks everywhere if you want (https://github.com/videojs/video.js/blob/master/docs/guides/text-tracks.md#emulated-text-tracks) but make sure not to do it on iOS because otherwise, it won't work when you go fullscreen.

**Comment by rfs-** [comment]
Yes I had/have both on and chrome still wasn't taking effect. Tried setting nativeTextTrack to false in setup options from the link you gave without any luck as well.

`window.player = videojs('example_video_1', {
      fluid: true,
			html5: {
				nativeTextTrack: false
			}
    });`

**Comment by rfs-** [comment]
I figured it out.

In your example the option is spelled incorrectly. 

It is nativeTextTrack**s**: with an s instead of what is currently in the documentation without the s in tracks.

**Comment by gkatsev** [comment]
d'oh. Thanks @hartman for the PR.
