### ISSUE TITLE
multiple video files are not loading through video js

### ISSUE THREAD

**Issue by balajinunna** [videojs/video.js#3330]
In my webpage, Am trying to play the videos using videojs plugin. I was trying to show the videos in slide view (Next, previous navigation as like facebook). Here, For me the video which I clicked is loading properly without any issues. But, While navigating next video files are not loading.

When I Inspect and check in dom. For the first video(which played properly) have the src attribute in video tag. But, while navigation that src attribute is not there in the video tag.

Code for reference:

```
var vp='<video id="zdvideo_'+id+'" width=800 height=400 class="video-js vjs-default-skin zdvideoplayer" controls preload="none">';
vp+='<source src="'+previewURL+'" type="application/dash+xml">';
vp+='</video>';
$("[preview_docid="+id+"]").html(vp);
                                var elementId = 'zdvideo_'+id;
                                videojs(elementId,
                                {
                                        controlBar:
                                        {
                                                currentTimeDisplay:true,
                                                timeDivider:true,
                                                fullscreenToggle:false,
                                        }
                                });
```
And, how to destroy these multiple video instances at a time while click on esc key?

**Comment by nickygerritsen** [comment]
You should not create a new `videojs()` instance. Instead of this, create it once and save the returned variable. You can then use this to load a new video.

Example:

```js
var player = videojs(elementId, {/*opts*/});

// Then later:
player.src({src: 'http://...../x.mp4', type: 'video/mp4'});
```

**Comment by balajinunna** [comment]
Hi @nickygerritsen,

I changed the code as said like above. But, still no luck.

``
var vp='<video id="zdvideo_'+id+'" width=800 height=400 class="video-js vjs-default-skin zdvideoplayer" controls>'; //No I18N
                                
                                vp+='</video>';
                                $("[preview_docid="+id+"]").html(vp);
                                var elementId = 'zdvideo_'+id; //No I18N
                                var vplayer = videojs(elementId,
                                {
                                        controlBar:
                                        {
                                                currentTimeDisplay:true,
                                                timeDivider:true,
                                                fullscreenToggle:false
                                        }
                                });
                                vplayer.src({'src':previewURL,'type':'application/dash+xml'});

**Comment by nickygerritsen** [comment]
Are you doing this call every time a user switches video? As said you should not do that. You should only ever initialize ONE videojs instance for a video element and the use that.

So in your case you can change:

```js
var vplayer = videojs(elementId, {/**/});
```
to
```js
if (!window.vplayer) {
  window.vplayer = videojs(elementId, {/**/});
}
```

And the last line to also use `window.vplayer`.

**Comment by nickygerritsen** [comment]
Also don't recreate a `<video>` tag everytime I guess. It might work, but maybe it does not.

Is `id` unique every time?

**Comment by balajinunna** [comment]
@nickygerritsen Yes, id is unique everytime.

**Comment by nickygerritsen** [comment]
Could you set up a minimal example using our JSBin example: http://jsbin.com/axedog/edit?html,output

**Comment by balajinunna** [comment]
@nickygerritsen I have update in below jsbin
http://jsbin.com/luwagiheqo/edit?html,js,output

First, click on the VIDEO1. This will load properly. Now, click on keyboard righclick arrow to load another video. But, This video not.

**Comment by nickygerritsen** [comment]
Why not do it like this:

http://jsbin.com/beyecemiyi/1/edit?html,js,output

This creates one video element at pageload, but hides it. It then just changes the source (and shows it) depending on what you do.

In your example by the way tapping the right arrow will load the second video for me, but continues playing the first one in the background. Going right once more breaks it, but that's because the ID is reused then I think.

**Comment by balajinunna** [comment]
Thanks for your explanation @nickygerritsen But, If I did like above, Every time I have to send a request to my server to load the video which is costlier. My exact requirement is, If the video is already loaded and, If click next (I want to hide the video which is already loaded without replacing). Is there any possibilities to achieve this?

**Comment by nickygerritsen** [comment]
Then I guess you can keep track of some object on `window` for every player?

So
```js
window.players = {};

function startPlayer(id) {
  if (!window.players[id]) {
    window.players[id] = videojs(somethingwithid, {/**/});
  }

  // More code
}
```

**Comment by gkatsev** [comment]
I think the main issue with this example http://jsbin.com/luwagiheqo/edit?html,js,output is that when you hit the arrows, it will destroy the player element but with videojs already being initilized it won't re-initilize it and do nothing.
I updated the example with minimal fixes to make it work: https://jsbin.com/josezid/edit?js,output
However, I agree with @nickygerritsen that it would be better to to just have one player. Have you considered using something like [videojs-playlist](/brightcove/videojs-playlist)? You can tell the playlist what your videos are and then on the keypress event call `player.playlist.next()` or `player.playlist.previous()`.

Closing this issue because it's unlikely to require a change to videojs itself. However, we can (and should) still continue the discussion here and if it turns out to actually be an issue with videojs, we can re-open the issue.

**Comment by balajinunna** [comment]
Thanks a lot @gkatsev and @nickygerritsen for your suggestions and co-operation. Much appreciated.
