### ISSUE TITLE
adding a `silent:true` idea to `setCurrentTime`

### ISSUE THREAD

**Issue by erikyuzwa** [videojs/video.js#3334]
## Description
While it speaks to a conversation (perhaps?) of the event system in video.js in general, the beachhead in this effort might be the ability to use `setCurrentTime` without triggering internal event listeners.

We're making use of the `videojs-contrib-ads` (fantastic btw) and noticing that when `restorePlayerSnapshot` is called upon resuming playback from an ad, the `seeking` event is triggering as the content timeline is restored.

This is causing legitimate `seeking` (from the progress bar manipulation) events to fire which we have to add clunky workaround logic to handle. It would be nice to attack this at the source by just not having the event trigger in some cases.

(While this might sound like an issue belonging to the plugin, I think a general solution that might help everyone is worth considering)

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. add a listener to `player:seeking`
2. call `player.setCurrentTime()` to some arbitrary timepoint that exists
3. our listener established in 1. should trigger.

### Expected
Content resumes playback at desired point in timeline without triggering `seeking` event.

### Actual
Content resumes playback at desired point in timeline along with triggering of `seeking` event.

### Error output
No errors.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
latest
#### browsers
all
#### OSes
all
### plugins
 * videojs-contrib-ads

**Comment by gkatsev** [comment]
In videojs-contrib-ads, we try and capture and redispatch the native events and prepend them with an `ad` or `content` prefix so that a normal plugin doesn't need to be aware of ads for the normal lifecycle events.
This means that we try and prevent those seeking events from going through and instead we trigger them as `contentseeking`.
The main downside with this approach is that if you listen to these events *before* contrib-ads has had a chance to run and attach its event handlers, you will see the un-prefixed events.
I would be wary of adding this into videojs core without trying to see if there's something we can do with contrib-ads first to make everything work better.

**Comment by erikyuzwa** [comment]
:bow: really appreciate the feedback @gkatsev as well as the insight. I'll go back to the drawing board in our own event handling then and see if we can make use of `contentseeking` (or some other approach?). Much appreciated.
