### ISSUE TITLE
Is it possible to implement F11 fullscreen button (similar to current Fullscreen button)?

### ISSUE THREAD

**Issue by videojs-user** [videojs/video.js#3339]
Current Fullscreen function does not seem to allow background element? Whereas F11 fullscreen would seem to. allow a background <div> etc.

**Comment by gkatsev** [comment]
I'm not quite sure what you mean. Please follow the [issue template](https://github.com/videojs/video.js/blob/master/ISSUE_TEMPLATE.md) when opening an issue.

**Comment by videojs-user** [comment]
Request for additional button in Control Bar, please see here:

http://jsbin.com/vigatep/edit?html,output

Results:
No Background div is displayed in Fullscreen mode.

Expected:
Background div to be displayed.

Actual:
Only video is displayed.

Additional Information
The code uses [https://github.com/matthojo/videojs-Background">https://github.com/matthojo/videojs-Background](url) 

However, F11 fullscreen does display the  Background div. The request is that an F11 button is added to the Control Bar (to enable mouse-only control) - if possible.

versions:
v5

**Comment by mister-ben** [comment]
Do you mean you want a full screen control in the player that makes the page rather than the player full screen? If so, you'd want to add a button that triggers `document.body.requestFullscreen()` (or its vendor-prefixed variants).

Alternatively if you are just trying to overlay components over the player and expect them to still be displayed when the player is full screen, you could append them to the player element rather than just position them on top.

**Comment by videojs-user** [comment]
It was the second one and your comment put me on the right track, thanks.
