### ISSUE TITLE
Playing a video file located on harddrive still being downloaded

### ISSUE THREAD

**Issue by belaviyo** [videojs/video.js#3345]
So I have a huge video file I would like to use videojs to play it. Since the file is huge it takes sometime to be fully fetched. Using a desktop video player I can simply start watching the video file (MP4 format for instance) when just a small portion of it is fetched since the headers are all located in the first few segments. Unfortunately when I use videojs it only plays the parts that has been fetched upon video playing is requested. Although the file is fully fetch after a while, but videojs is not playing those parts where weren't ready when video playing was requested. If I reload the player it can play the file though.

Any idea if this could be addressed? Maybe somehow request videojs to scan the file one more time

**Comment by gkatsev** [comment]
Are you trying to play a video from a `file:///` url? Or is the page loaded on a `file:///` url? If so, then it's unlikely to work. 
What browser, os, and version of videojs are you using?

**Comment by belaviyo** [comment]
No the file is a temporay file created in the temp directory using fileEntry api. I got url to access this resource by "var url = URL.createObjectURL(file);". Now i am feeding this url to the latest version of videojs. Note that if i feed the url of a completed file object videojs can successfully play the whole track. By if i feed the url of a file object that is still being fetch, only portion of the file that has already been fetched id played. No matter if the rest of file is bwing fetch afterward

**Comment by belaviyo** [comment]
Btw this is on Chrome. Same thing on Firefox as well

**Comment by belaviyo** [comment]
An easier way to simulate this is download a video track with a download manager. Before video is completely being fetched, pause the downloader. Now feed this file to videojs using a local server (127.0.0.1). When url is set, videojs can play some initial part of the track as only portion of it is available. Without refreshing videojs, let the downloader finish downloading of the video file. You will see unless videojs is refreshed, it is unable to play the entire video file.

I tested this with many media players and they all can play new segments when they are available

**Comment by mmcc** [comment]
The behavior that you're seeing is the HTML5 `<video>` element, so unfortunately this is out of this project's hands.

> I tested this with many media players and they all can play new segments when they are available

I'd be interested to see a reduced case of this actually working with an HTML5 video element, because AFAIK, growing file support simply isn't supported with a "standard" video element. Streaming formats such as HLS and DASH are designed specifically for this use case; the player knows to continually ask for an updated manifest / segments until told otherwise, but the assumption with an mp4 is that once the download is complete, it's complete.

The good news is, you could totally get something like this working by using the [MediaSource API](https://developer.mozilla.org/en-US/docs/Web/API/MediaSource).
