### ISSUE TITLE
video.js playback in FireFox 47?

### ISSUE THREAD

**Issue by BenRad15** [videojs/video.js#3374]
## Description
I've set up a live streaming server using nginx and the nginx-rtmp module. I send the stream to video.js and it plays fine on Chrome and IE. Firefox gives the "Specified "type" attribute of "rtmp/mp4" is not supported. Load of media resource rtmp://server:1935/live/playtest failed."

I've read every single post here about this same issue, and none of the solutions have worked for me. Should video.js work in Firefox? I have flash installed and enabled, and still no luck. I've had several users try Firefox and they get the same error.

Using the latest version of video.js, on CentOS 7. 
Here's my code from the page:

`            <video id="live" class="video-js vjs-default-skin" controls autoplay preload="none" width="960" height="540"
               data-setup='{ "techOrder": ["flash","html5"] }'>
            <source src="http://server/hls/playtest.m3u8" type='application/vnd.apple.mpegurl'>
            <source src="rtmp://server:1935/live/playtest" type='rtmp/mp4'/>
            <source src="rtmp://server:1935/live/playtest/webm/playtest.webm" type='video/webm'/>
        </video>`

It's been suggested that I set up ffmpeg to transcode the live stream to webm in order to get it to work on Firefox (that's the last source line above), but that seems like a lot of trouble.

I'm a noob at all this so be gentle. What am I missing?

Thanks.

**Comment by mister-ben** [comment]
The error message suggests the Flash tech is not available, as it adds support for the rtmp/mp4 type. You're on Centos - I thought Adobe stopped making Flash for Linux years ago. Chrome has/had kept its own bundled version alive and updated longer, but that is only good for Chrome.

Since you're outputting HLS I'd strongly suggest using videojs-contrib-hls. You can then play HLS with Media Source Extensions rather than Flash. This also has much more active development than the Flash tech.
