### ISSUE TITLE
No Flash fallback for HLS streams

### ISSUE THREAD

**Issue by MTYannick** [videojs/video.js#3411]
## Description
It's not possible to play HLS streams on IE9, Safari etc. because the Flash fallback is not working.

## Steps to reproduce
1.Open http://videojs.github.io/videojs-contrib-hls/ in IE9 or Safari

### Expected
Video should play

### Actual
Player throws an error

### Error output
IE9: No compatible source was found for this media.
Safari: The media playback was aborted due to a corruption problem or because the media used features your browser did not support.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
5
#### browsers
IE9 and Safari
#### OSes
Windows 7 and Mac OS X Maverick
### plugins
The contrib HLS plugin

**Comment by gkatsev** [comment]
Contrib-hls doesn't support IE9 due to it lacking the necessary primitives for it to work plus it not running javascript fast enough for us to polyfill those primitives.
Not sure exactly why it isn't working in Safari, we'll investigate.
Also, it's generally best to open issues against the associated project, so, a contrib-hls issue should go on the contrib-hls project. Makes it easier for us to track and manage.
Thanks.
