### ISSUE TITLE
Load spinner do not start with .m4v and .flv video Format

### ISSUE THREAD

**Issue by onigetoc** [videojs/video.js#3413]
Load spinner do not start with .m4v and .flv video formats

In all my test, the spinner do not start with .m4v video, The user do not know if the video is loading.

**Comment by gkatsev** [comment]
That's very possible.
videojs uses the `waiting` event to add a `.vjs-waiting class which shows the loading spinner https://github.com/videojs/video.js/blob/master/src/css/components/_loading.scss#L21-L25

It's possible that m4v and flv videos end up not firing a waiting event from flash. A workaround would be to add the `.vjs-waiting` class yourself on something like the `play` event and then hide it either on `playing` or on `timeupdate`.

Given that this is Flash and flv related, it'll probably a low priority for us to fix, especially since it probably requires updates to the swf. But PRs are always welcome.
