### ISSUE TITLE
Play event not triggered on iOS, vjs.currentTime() always 0

### ISSUE THREAD

**Issue by achru** [videojs/video.js#3417]
## Description
Running videojs on mobile safari, 'play' event is not being triggered,
'timechange' is triggered but vjs.currentTime keeps being 0, even when video is playing
## Steps to reproduce
Run videojs 5.10.2 on mobile safari

## Results
no play event, currentTime not updated
### Expected
play event and currentTime moving on 

#### videojs
5.10.2
#### browsers
mobile safari 
#### OSes
iOS
### plugins
contrib-hls

**Comment by gkatsev** [comment]
I've definitely seen `play` and `timeupdate` and all the standard events working just fine. Also, contrib-hls is basically a no-op on iOS right now because we let the native HLS implementation take over.
If you provide a reduced test case we could take a look. Going to close this issue in the meanwhile.
