### ISSUE TITLE
Adding method to components' prototypes not working in version 5

### ISSUE THREAD

**Issue by cervengoc** [videojs/video.js#3425]
I'm tryping to migrate our custom VideoJS plugin from version 4 to version 5. However, an awful lot of things have changed, and there is quite little documentation on details.

I have some methods which extend or override for example `Player` type prototype methods, like this.

     var vjsPlayer = videojs.getComponent("Player");
     vjsPlayer.prototype.autoSetResolution = function(callback) { ... };

It was working properly in version 4, but in version 5 when our plugin tries to use this method on its current player instance, it somehow turns to `undefined`.

What is the way to extend/override `videojs` component methods in version 5?

**Comment by gkatsev** [comment]
We have quite a lot of documentation of the changes on the wiki: https://github.com/videojs/video.js/wiki/5.0-Change-Details
Also, things like that sounds like they fit well with the current definition of plugins. Though, the above code looks fine to add more methods to the player. However, I can't recommend it because it means that upgrades could cause problems. What if we decide to add an `autoSetResolution` method? As an example, we have no such plans.

**Comment by cervengoc** [comment]
Thank you for the review, actually it turned out that we messed up some coding conventions and had loaded the library twice. The second time it was after out plugin definition, so actually it reset the prototypes. 

It would be good to have a check for this and give an error message, or is there any valid use case when loading the library multiple times makes sense?

On the other hand, you are right about the potential danger of the upgrades when having prototype methods, but it's an old code, and also, basically every upgrade itself causes problems in most cases, unless you have a really simple plugin.

**Comment by gkatsev** [comment]
Yeah, generally not recommended to load videojs in twice. Having a check would be interesting, though, I guess only necessary for the script load. Since it'll probably be okay for webpack/browserify usage. I guess it could just log a warning in the console but still proceed with trying to load itself.
Would you be interesting in making a PR for such a check?

**Comment by cervengoc** [comment]
Yes, the warning would be completely enough and safe I think. Unfortunately I don't have time for making the PR now. It would take a bit of time because I'm not familiar with the current code.
