### ISSUE TITLE
How to scale video to fill the container

### ISSUE THREAD

**Issue by mkhazov** [videojs/video.js#3431]
video.js 5
http://codepen.io/mkhazov/pen/xOpwQp

How to stretch video so it fill the container like image with background-size: cover?
Currently there are black bars on top/bottom or left/right, depending on window size.

**Comment by mister-ben** [comment]
`.vjs-tech { object-fit: cover; }` works except on IE and Edge.

**Comment by mkhazov** [comment]
Thanks.
Here is the another solution: http://stackoverflow.com/a/27850657/1300562

**Comment by vaishnavravi33** [comment]
Set data-setup option to true and set the div width and height as per your need. 
It will show video in full size of container div.

```
<div class="full-vid">
    <video id="vid1" class="video-js vjs-default-skin vjs-big-play-centered"
        controls
        width="100%"
        height="100%"
        data-setup='{ 
            "techOrder": ["youtube"],
            "aspectRatio":"16:9", "fluid": true,
            "sources": [{ "type": "video/youtube", "src": "https://www.youtube.com/watch?v=PjGkVCAo8Fw"}]
        }'
      ></video>
</div>
```

**Comment by vaishnavravi33** [comment]
Set data-setup option to true and set the div width and height as per your need. 
It will show video in full size of container div.

```
<div class="full-vid">
    <video id="vid1" class="video-js vjs-default-skin vjs-big-play-centered"
        controls
        width="100%"
        height="100%"
        data-setup='{ 
            "techOrder": ["youtube"],
            "aspectRatio":"16:9", "fluid": true,
            "sources": [{ "type": "video/youtube", "src": "https://www.youtube.com/watch?v=PjGkVCAo8Fw"}]
        }'
      ></video>
</div>
```

**Comment by nefarioustim** [comment]
I have just been fighting with this exact issue, using fluid with an aspect ratio of 16:9. My 16:9 HLS stream video was displaying with an equal border around the video. I had set-up the player using an options object:

```
{
  playsinline: true,
  autoplay: false,
  controls: true,
  fluid: true,
  aspectRatio: '16:9',
  responsive: true,
  inactivityTimeout: 500,
  preload: 'auto',
  techOrder: ['html5'],
  plugins: {},
}
```
   
The result:

<img width="524" alt="Video with in-player padding" src="https://user-images.githubusercontent.com/33619/108022994-9f7cf200-705c-11eb-8d29-01be65ca5a56.png">

As soon as I add @mister-ben's suggestion—from 2016 no less—of the `object-fit` CSS property, everything is hunky dory again:

<img width="538" alt="Video stretched to container" src="https://user-images.githubusercontent.com/33619/108023074-caffdc80-705c-11eb-8b55-dd09f3960941.png">

This is less of a cross-browser worry in 2021, since Edge now supports `object-fit`, but it still feels a bit like a duct-tape fix for the VJS fluid behaviour. I'm confident the current intent is that VJS set-up with 16:9 aspect ratio should "just work" for this sort of video. Happy to provide any further detail if it helps.
