### ISSUE TITLE
controll bar not working properly 

### ISSUE THREAD

**Issue by vinothyada** [videojs/video.js#3555]
## Description
IOnic framework this issue happening 
Please describe what you expected to see.

### Actual
Please describe what actually happened.
![screenshot 1](https://cloud.githubusercontent.com/assets/12169748/17806965/471ddc5a-6625-11e6-9f5c-6eb20cf7ff46.png)
![screenshot](https://cloud.githubusercontent.com/assets/12169748/17806966/47273a0c-6625-11e6-86d1-55a127eff357.png)

 
                        videojs(elm, playerOptions, function () {
                            player = this;
                            var options = {
                                src: attrs.source,
                                type: 'application/x-mpegURL'
                            };
                            player.hotkeys({
                               enableFullscreen:true
                            });
        })

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with?
versions 5.11.4
#### browsers 
what browser are affected?
chrome and mozilla
#### OSes
what platforms (operating systems and devices) are affected?
ubuntu 14.4 
### plugins
are any videojs plugins being used on the page? If so, please list them below.

**Comment by misteroneill** [comment]
It looks like you're not on UTF-8. If you add `<meta charset="utf-8">` to your `<head>` does that fix it?

**Comment by gkatsev** [comment]
As @misteroneill mentioned, this is probably because the font icons aren't loading correctly. Adding the charset meta tag is definitely a good idea, though, there could potentially be other issues as well like it's not even able to  get the file correctly.
Having a live reduced test case would be helpful.
Going to close this in the meantime; discussion can continue and we can re-open if it turns out to be an issue with videojs.
