### ISSUE TITLE
Is there any method like player.currentTime but not trigger timeupdate event?

### ISSUE THREAD

**Issue by senwa** [videojs/video.js#3566]
If I  use  player.currentTime(5)  in timeupdate deal method, then a cycle appear,so ,Is there any method like player.currentTime(5) but not trigger timeupdate event?

**Comment by misteroneill** [comment]
Maybe try pausing before changing the current time? That might work. But it also might not because changing the current time is, in fact, a time update.

**Comment by gkatsev** [comment]
What are you trying to do? changing the `currentTime` *will* trigger a `timeupdate`.
Maybe what you want is to make a videojs source handler or tech.

**Comment by senwa** [comment]
I want the video playing can pause  at an given exact time. But when I am trying  **_timeupdate_** ，I find the **_player.currentTime_** in this method  is not have a fixed time interval. So I want that if the **_player.currentTime_** passed the given exact time I want the video to pause, I may use **_player.currentTime(exactTime)_** in  **_timeupdate_** method letting the video back to the  given exact time and pause, and then that runs in a cycle .

**Comment by misteroneill** [comment]
You're right that `timeupdate` does not fire with any kind of fixed interval. This has a lot to do with the fact that the video and JavaScript are on separate threads and JavaScript timers are inaccurate at best. 

Are you trying to pause at a resolution of milliseconds or something? Because `timeupdate`s usually fire pretty frequently (multiple times per second).

As to your use-case, you might be able to turn `timeupdate` listeners on and off. But that said, it seems strange that you'd need this kind of precision. I would think pausing at the first `timeupdate` after your target time would be sufficient.

Regardless, this doesn't sound like a bug in video.js.
