### ISSUE TITLE
registering an arbitrary handler for players setup

### ISSUE THREAD

**Issue by mrbar42** [videojs/video.js#3615]
after read the plugins/components guides and going through several "how to build a..." tutorials
i couldn't find a reliable way to capture setup of videojs instance - either through js declaration or html wise.
plugins must be declared, and components must be added, tech components seem unreliable for the task.

to put it simple:
is it possible to get this functionality somehow? (pseudo)
```js
function globalCallback(player, options) {
  // player === instance
}
videojs.on('setup', callback)

var instance = videojs('player', {/* options */})
```

**Comment by misteroneill** [comment]
The `videojs` function is not an event target, so it doesn't trigger events. That said, each player triggers a `"ready"` event that you can listen for in either of these two ways:

```js
player.ready(callback);
player.on('ready', callback);
```

This event occurs asynchronously.

What you seem to want is some kind of global listener for anytime a player is created and ready. That feature does not currently exist in video.js. You could do something like this:

```js
function createPlayer() {
  return videojs.apply(null, arguments).ready(function() {
    // Do some stuff.
  });
}

// Anytime you call createPlayer(), you'll bind a callback to that player's "ready" event.
createPlayer('foo', {});
createPlayer('bar', {});
createPlayer('baz', {});
```

That said, this isn't really relevant to writing plugins because plugins are called on a per-player basis. Of course, you could use something like the above to auto-setup plugins for any player you create.
