### ISSUE TITLE
Fullscreen does not work on iOS

### ISSUE THREAD

**Issue by paladox** [videojs/video.js#3643]
## Description
Briefly describe the issue.
Include a [reduced test case](https://css-tricks.com/reduced-test-cases/), we have a [starter template](http://jsbin.com/axedog/edit?html,output) on JSBin you can use.

fullscreen button on videojs does not work on ios.

The reason why is because videojs is using the full screen api which does not work on ios.

https://github.com/videojs/video.js/blob/4f6cb03adde9ddf800e2ecf6fa87b07d436b74e8/src/js/fullscreen-api.js

http://caniuse.com/#feat=fullscreen

Maybe we could use https://github.com/bdougherty/BigScreen/blob/master/bigscreen.js ?
## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. Use videojs play with a video that works on ios.

### Expected
I expect that I can do fullscreen.

### Actual
It wont go to fullscreen when I press the full screen button.

### Error output
If there are any errors at all, please include them here.
no errors

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
5.12.1
#### browsers
what browser are affected?
safari, chrome (ios)
#### OSes
ios
### plugins
are any videojs plugins being used on the page? If so, please list them below.

**Comment by gkatsev** [comment]
It definitely works. I was just playing with it the other day. We do a check in [`requestFullscreen`](https://github.com/videojs/video.js/blob/3a859f97d0647fc3d1ef6b2f4b755c71da8bef63/src/js/player.js#L1703-L1707) to see whether the fullscreen api is supported or not, otherwise, we end up calling on the tech to handle [fullscreen](https://github.com/videojs/video.js/blob/3a859f97d0647fc3d1ef6b2f4b755c71da8bef63/src/js/tech/html5.js#L598-L625).

**Comment by paladox** [comment]
Oh, I tried it on here https://en.random-wikisaur.tk/wiki/File:FEZ_trial_gameplay_HD.webm using the ipad pro 12inch ios 10.1 and it didn't work.

**Comment by gkatsev** [comment]
It looks like the sources on there are only webm and ogg which iOS doesn't support. Though, I can try that page on my end tomorrow.

**Comment by paladox** [comment]
Yep but we use https://github.com/hartman/videojs-ogvjs https://github.com/brion/ogv.js/ which allows .ogv videos to be played on unsupported browsers using js. There experimental support for webm too.

**Comment by gkatsev** [comment]
Oh, actually, I think I figured out what the issue was. iOS doesn't support the fullscreen API and it only lets the native video element be taken fullscreen with the native controls, which is what `enterFullscreen` on the tech does.
If the tech implements `supportsFullscreen`, videojs will try and enter "full window" mode where it just makes the player div take over the entire screen, kind of faking fullscreen. But otherwise, unless a native video element is being used, I don't think you'd be able to go fullscreen.

**Comment by paladox** [comment]
Oh, is there any way we can get full screen to work? Any workarounds like using a full screen package? Please

**Comment by gkatsev** [comment]
Unfortunately, unless `full window` is an acceptable solution, I don't think there's anything that can be done short of using a video format that iOS can play back natively.

**Comment by paladox** [comment]
Oh, but coulden we just do what kaultra plauyer does which is it extends the video but it doesn't hide the web bar above?

**Comment by gkatsev** [comment]
That's what `full window` mode does.

**Comment by paladox** [comment]
Oh, I guess  full window  would be better then nothing :), would we be able to add support for  full window please?

**Comment by gkatsev** [comment]
We already have it. videojs-ogvjs would need to implement `supportsFullscreen` and return `false` on iOS.
our `requestFullscreen` method checks to see whether the fs API is available in the browser, if it's available it uses it, otherwise, it asks the tech whether it can handle fullscreen (for example, using the iOS fullscreen API on the video element) and if it says yes, it will ask the tech to handle going fullscreen. If neither the fs API is available or the tech says it doesn't support full screen, it will then go into "full window" mode.

**Comment by paladox** [comment]
I filled for full screen api support for iOS here https://bugs.webkit.org/show_bug.cgi?id=162563

**Comment by gkatsev** [comment]
Thanks. I guess we should follow along on https://github.com/hartman/videojs-ogvjs/issues/23.
If there are issues with full window, please open another issue.
Going to close this in the meantime since it doesn't require any work on videojs's part.

**Comment by varemenos** [comment]
Shouldn't the FullscreenToggle be hidden when the supportsFullScreen function reports false? I mean shouldn't the video.js player handle this on it's own to prevent the users from finding themselves to be vulnerable.

**Comment by sunnybear** [comment]
Native player wth playsinline has fullscreen button, so it seems there should be a way to provide it via javascript (+bigscreen logic of course)
