### ISSUE TITLE
Please add or at least outline the build process for an audio-only build?

### ISSUE THREAD

**Issue by albell** [videojs/video.js#3650]
I would love to see this in the build docs. What can I comment out, etc? Or better yet add an optional "audio" task that builds an audio-only player.

Rationale: the default build is IMHO unjustifiably large for an audio-only player, and the <a href="https://github.com/jedfoster/audiojs">old audio fork</a> is four years old now, and hasn't been maintained.

**Comment by gkatsev** [comment]
Thanks for your patience, custom builds are definitely something we're going to be looking at in the near future. The main thing that a true audio-only player can do without is the text tracks, which do make a big chunk of the player, with the control bar and components being the largest chunk.
Going to close this for now (but feel free to ask questions about it for now) since we do have a plan forward. I hope to be writing up some plans for it (and further roadmap items) this week.
