### ISSUE TITLE
I18n not working?

### ISSUE THREAD

**Issue by Globulopolis** [videojs/video.js#3652]
## Description
See demo at https://jsfiddle.net/g98y28cz/

### Expected
Internationalized tooltips in player.

### Actual
Only `Play` button internationalized.

**Comment by gkatsev** [comment]
That example works for me. As soon as I started playing, I got an error in russian because the video urls are old and no longer valid.
I see the tooltips showing up properly for all buttons as well.
Seems to not be an issue, closing.

**Comment by Globulopolis** [comment]
@gkatsev yes, was my fault. But one small question. Big play button still not i18n. It's something missing or not?

**Comment by mister-ben** [comment]
It's because there isn't a translation yet for "Play Video". If you could add the missing Russian translations a pull request would be very welcome.

See the [English template](https://github.com/videojs/video.js/blob/master/lang/en.json) and the [translations needed doc](https://github.com/videojs/video.js/blob/master/docs/translations-needed.md) to see what's missing.
