### ISSUE TITLE
Mouseout event fire when mouse hover on slider bar

### ISSUE THREAD

**Issue by sawa74** [videojs/video.js#3668]
Hello,

I want to hide control bar only when the mouse move out of the player, i'm using this function :

player.on('mouseout', function(){ this.userActive(false) })

and

"inactivityTimeout": 0

It's working but when the mouse hover on slider, the control bar start to blink.

[https://jsfiddle.net/j6wdxp5j/1/](https://jsfiddle.net/j6wdxp5j/1/)

**Comment by gkatsev** [comment]
You probably want [`mouseleave`](https://developer.mozilla.org/en-US/docs/Web/Events/mouseleave) instead of [`mouseout`](https://developer.mozilla.org/en-US/docs/Web/Events/mouseout). They're very similar but `mouseleave` doesn't bubble, meaning that you don't get the event for children of the element getting the event where-as for `mouseout` you do.
Here's an example: https://jsfiddle.net/j6wdxp5j/2/
Hope that helps.

**Comment by sawa74** [comment]
Thank you !
It's working perfect now.
