### ISSUE TITLE
FLV Tag Data

### ISSUE THREAD

**Issue by manish001in** [videojs/video.js#3693]
## Description

So I am running an rtmp stream to show flv data on the video browser.
Can anyone guide me or point me towards the code from where I can get how to read each tag of the flv data?

Please ask if you need any more details regarding my use case!

TIA

**Comment by gkatsev** [comment]
Unfortunately, we don't provide that kind of information in javascript land and I'm not even sure it's available on the Flash side. You'd probably want to look around in the [swf](https://github.com/videojs/video-js-swf/blob/master/src/com/videojs/providers/RTMPVideoProvider.as).

Due to the status of Flash in the browser we're not going to be working on adding this functionality ourselves.
