### ISSUE TITLE
Remove method-chaining capabilities for player.currentTime

### ISSUE THREAD

**Issue by dmlap** [videojs/video.js#3704]
Method chaining can save some repetitious typing when using the player APIs:

``` js
player.currentTime(7).play();
```

Unfortunately, switching return types between different function invocations confuses Javascript optimizers and often means the method remains de-optimized. For methods that may be called very frequently during player interactions like currentTime, de-optimized functions that take 10s of milliseconds can lead to frame drops.

**Comment by dmlap** [comment]
Here's a sample timeline profile from Chrome. Note in the bottom pane that`currentTime` is de-optimized and took over 10ms of self-time:

![screen shot 2016-10-23 at 3 00 06 pm](https://cloud.githubusercontent.com/assets/56667/19628685/7552d42e-9931-11e6-962d-4a6e5388d159.png)

**Comment by misteroneill** [comment]
I think we all agree that we should either do nothing or remove _all_ method-chaining capabilities from video.js.

Presuming we remove method-chaining capabilities, one thing we need to discuss is what to do about returning a `Promise` from `play()` (which Chrome does) instead of `this`. There are a few options:

1. Return whatever the browser (and the tech) return.
1. Return a promise if the browser returns one. If the browser does not return a promise, but the browser _supports_ promises, return our own pre-resolved promise. Otherwise, return nothing/`undefined`.
1. Always return a promise. This would require users to use a promise-providing library like es6-shim or Bluebird for browsers that don't support promises.

**Comment by BrandonOCasey** [comment]
I really like solution 2, but maybe we could make it check if `Promise`s are available  instead of depending on a browser check. That way if the promise-providing library provides a `Promise`  or a native `Promise` exists we can use it, but it won't force anyone to use a promise library.

**Comment by misteroneill** [comment]
Yep, agreed.

**Comment by dmlap** [comment]
Solution 2 sounds right to me, too.

**Comment by misteroneill** [comment]
Sounds pretty uncontroversial, then.
