### ISSUE TITLE
Specify own function for fetching media segments in video.js

### ISSUE THREAD

**Issue by silverbucket** [videojs/video.js#3713]
I'm trying to create my own media fetching function for `video.js`, I've read through the API docs and guides and didn't find anything that explained how to do this.

With other players like `hls.js` or `dash.js`, there are ways - during initialization - to register your own function which is called whenever the player needs a new segment of media (assuming we're reading from a playlist). Is there a way to do this for `video.js`?

I originally asked this on stackoverflow.com but received no responses, so if you'd prefer to answer it there for posterity that would be fine as well. http://stackoverflow.com/questions/40171080/specify-own-function-for-fetching-media-segments-in-video-js

**Comment by mmcc** [comment]
The core Video.js player has no notion of fetching segments or media at all, since it assumes you're going to give it an HTML5 media element that knows how to do all of that. To do what you'd want, you'd need to write your own [source handler](1560) that knows how to do such things.

**Comment by silverbucket** [comment]
Thanks for your reply @mmcc - I think I'm a little confused about the difference between something like hls.js, dash.js and shaka player (all which handle playlists, and fetch media segments as needed - allowing 3rd parties to hook in and carry out the fetching their own way, while the player tells the function what is needed and when, based on the state of the playback buffer), and `video.js`. so if I understand correctly, DASH and HLS implement functionality such as handling playlists and fetching segments, while `video.js` just provides a JS API for controlling native MediaSource video players? (single media files). 

So, in order to have playlist, segmenting, support in `video.js` I would need to write my own code to handle the parsing of the playlists, fetching the media, then feeding it to `video.js`

**Comment by misteroneill** [comment]
Assuming you're dealing with HLS or Dash playlists, you can use either [videojs-contrib-hls](https://github.com/videojs/videojs-contrib-hls) or [videojs-contrib-dash](https://github.com/videojs/videojs-contrib-dash).

**Comment by gkatsev** [comment]
Video.js provides consistent accessible UI and API across browsers as well as support for captions, Flash fallback, and plugin functionality. The plugin functionality is particularly huge because it means you can share in the work that people have done instead of having to implement everything yourself. There's a huge ecosystme of videojs plugins. As @misteroneill mentioned, you can use videojs-contrib-hls and videojs-contrib-dash to get HLS and DASH playback in the video.js player. You can also play back youtube videos through videojs-youtube. This means that if you need to support HLS, DASH, and youtube playback, you don't have to swap players and deal with two different sets of APIs, you can just do everything via video.js.
Video.js itself can't have a media segment fetching API because it rarely deals with it directly, instead, delegating to it's techs and source handler plugins (like those already mentioned).
1 Comment
