### ISSUE TITLE
video.js fullscreen button set callback event?

### ISSUE THREAD

**Issue by kevin4z** [videojs/video.js#3730]
## How to set fullsceen callback event?
Video.js can't play video fullscreen with landscape mode in Android `WebView`, so I want to write fullscreen button callback event to change phone direction.

**Comment by kevin4z** [comment]
Videojs API [handleClick()](http://docs.videojs.com/docs/api/fullscreen-toggle.html), how to use this?

**Comment by misteroneill** [comment]
Are you sure there is a problem with Video.js? There seem to be a lot of questions [on the web about fullscreen in Android `WebView`](https://www.google.com/search?q=android+webview+video+fullscreen+orientation).

You might be able to use the `'fullscreenchange'` event on the player:

```js
player.on('fullscreenchange', function() {
  // do stuff...
});
```

Otherwise, this isn't really a support forum - it's a bug tracker. If you have a question about your implementation, you might have better luck checking out Stack Overflow or something like that.

**Comment by mister-ben** [comment]
There is a note buried away in the Android dev docs outlining what you have to implement to get fullscreen support. 

https://developer.android.com/reference/android/webkit/WebView.html
