### ISSUE TITLE
Adding Headers into beforeRequest Hls Videojs function

### ISSUE THREAD

**Issue by apatinoyu** [videojs/video.js#3752]
Hello everyone and thanks for you offering help. I tried to send Headers into the videojs.Hls.xhr.beforeRequest function, so I implement:

```
videojs.Hls.xhr.beforeRequest = function(opt){
opt.headers.access-control-allow-origin= nameDomain
opt.headers['X-User-Id'] = userId;
}
```
Debugging the library videojs, it seems like it gets my headers and it adds the headers into xhr but when it is sent suddenly it disappears. So in the request headers result is:
`Access-Control-Request-Headers:access-control-allow-origin,x-user-id` and no values. I am using videojs version 5.12.2 and videojs-contrib-hls as well. Regards.

**Comment by hartman** [comment]
Please use the issue template...

`access-control-allow-origin` is a server [response header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#The_HTTP_response_headers), not a [request header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Access-Control-Request-Headers)". Likely the browser won't even allow you to set it, so that might be why it is missing. Are you 100% sure that X-user-id is not being sent by the browser ? How have you checked ?

**Comment by apatinoyu** [comment]
Thanks for your fast reply. Yes, you are right. I am sending the Headers but the issue was with Cors in server side.
Regards.
Closed Issue.
