### ISSUE TITLE
BeforeRequest function is not called on Safari

### ISSUE THREAD

**Issue by apatinoyu** [videojs/video.js#3769]
Hello, thanks for the player.
I found an issue or maybe I am doing something wrong. Please help me to understand this.

Description

I want to set custom HTTP headers on every request made by the player. To do so I would like to use `beforeRequest` callback. So, I am setting these headers in my videojs variable. Then I initialize the player. It is working fine on Chrome & Firefox but fails on Safari.

Steps to reproduce

On Safari, while debugging it never goes into/through the `beforeRequest` function so the headers are not being set at all.

Results

Expected

I expect to see the same queue or list of functions that are being called for this process in different kind of browsers.

Actual

Does not go through the `beforeRequest` function on Safari.

Additional Information

versions

videojs

videojs#^5.12.6
videojs-contrib-hls version 3.6.9

browsers

Safari 9.1

**Comment by gkatsev** [comment]
Hi, please only open one issue on one repo. This makes it so that we don't spend time looking for an answer when it's already been answered on the other issue (https://github.com/videojs/videojs-contrib-hls/issues/904). Given that this is a contrib-hls issue, it should only be opened there. If it turns out to be a general videojs issue, we can always open another issue at that point.

Thanks.
