### ISSUE TITLE
How can I display caption in iOS when video's in fullscreen mode?

### ISSUE THREAD

**Issue by linherest** [videojs/video.js#3793]
## Description
I'm not sure this is a bug or another type of issues.
But I just want to show the caption in fullscreen mode.
How can I do that?
How can I switch caption from videojs track to native track by code?

## Steps to reproduce
Reduced test case: http://codepen.io/linherest/pen/xRRMmQ

1. In the index page, set the html5 | nativeTextTracks to true.
2. Play the video.
3. Toogle fullscreen.

## Results
In fullscreen mode, the caption was hidden.

### Expected
In fullscreen mode, the caption was show.

#### videojs
5.11.9
#### browsers
Mobile Safari
#### OSes
iOS 9.3.5

**Comment by gkatsev** [comment]
I think the issue is that in your codepen, you have `nativeTextTracks` set to `false`. Unfortunately, we don't currently have a way to switch between native and emulated captions.
I would recommend making sure that `nativeTextTracks` is not set to false on iOS (and potentially desktop Safari as well).

Sorry for the late response, hope that helps.

**Comment by linherest** [comment]
Thank @gkatsev very much.
