### ISSUE TITLE
how can i check the video is load finish

### ISSUE THREAD

**Issue by y284663247** [videojs/video.js#3806]
how can i check the video is load finish,i want to check the video is finish and do something after this ,but now i can do this,

play.currentTime(200) when ths video is not finish ,this will show the error

**Comment by mister-ben** [comment]
Typically if you can't seek until the file has downloaded the issue is an MP4 with its moov atom at the end of the file instead of the start. You should also verify your server supports and honours range requests.

FWIW `player.buffered()` returns one or more time ranges which describe which part(s) of the video are downloaded, and the `progress` event fires periodically as that updates, but fixing the file/delivery is a better solution.

**Comment by gkatsev** [comment]
I think fixing delivery is the only actual solution to this. Video.js mostly relies on the browser to play back the video, so, if that's broken, you're in trouble.
