### ISSUE TITLE
VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) 

### ISSUE THREAD

**Issue by YexuanGuo** [videojs/video.js#3817]
videojs.min.js:23 VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The video could not be loaded, either because the server or network failed or because the format is not supported.

**Comment by mister-ben** [comment]
This error means your source is not supported.

We may be able to give you a better answer but you'll have to provide better information.

Fill in the [issue template](https://github.com/videojs/video.js/blob/master/.github/ISSUE_TEMPLATE.md) and provide a reduced test case that replicates the issue.

**Comment by haibo32012** [comment]
video.js:22963 VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported.

Hello, I have a page for display a couple of most watched videos, and click it jump to play page, so  in this page and use .vjs-fluid for style, how I eliminate the error message, stop it display.thank you!

**Comment by mister-ben** [comment]
Rather than posting on an old issue, please follow these steps

- Check the [troubleshooting guide](http://docs.videojs.com/tutorial-troubleshooting.html)
- If you are still having a problem, create a new issue and **complete the information asked for in the template**.
- Do not forget to include a **reduced test case** - a simple, isolated example that demonstrates the problem.

Thanks

**Comment by ckw-cyb** [comment]
<video id="myVideo" class="video-js">
              <source :src="item.videourl" type="video/mp4">
 </video>
 
Use the above command to report an error  我裂开

VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported. MediaError

**Comment by ckw-cyb** [comment]
<video id="myVideo" class="video-js">
              <source :src="item.videourl" type="video/mp4">
 </video>

Use the above command to report an error

VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported. MediaError

**Comment by ckw-cyb** [comment]
video.es.js?f0e2:142 VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported. 


我裂开

**Comment by ckw-cyb** [comment]
我裂开

**Comment by ckw-cyb** [comment]
我裂开了
