### ISSUE TITLE
Playback rate API not working for IE11

### ISSUE THREAD

**Issue by nishthaGupta** [videojs/video.js#3858]
The playback rate API does not work at all on IE11. When called, it gives the following error:
VIDEOJS: ERROR: (CODE:0 MEDIA_ERR_CUSTOM) FLASH: propertynotfound [object Object]

**Comment by gkatsev** [comment]
Playback rate isn't supported with flash and probably not supported on IE11 either. The fact that it throws is interesting, though. I'm not sure it should throw.

**Comment by crobinson42** [comment]
<img width="644" alt="screenshot 2017-04-05 14 08 36" src="https://cloud.githubusercontent.com/assets/5973579/24727061/78954e60-1a09-11e7-8b95-ee9d60684ab3.png">
I'm seeing this in IE11 - my code works fine in all other browsers.

**Comment by crobinson42** [comment]
Interesting, it shows that playbackRate is supported in IE11? http://caniuse.com/#search=playbackrate

**Comment by mister-ben** [comment]
This is reproducible anywhere with the Flash tech rather than on IE11 specifically. `playbackRate` has never been supported with the Flash tech but I didn't recall that it threw an error, but that's probably because the playbackRateControl tests whether playbackRate is supported before using it, with `player.tech_.featuresPlaybackRate`.

**Comment by gkatsev** [comment]
Given that Adobe Flash is [being end-of-lifed this month](https://www.adobe.com/products/flashplayer/end-of-life.html) we will no longer be working on flash related features.
