### ISSUE TITLE
Hide video, show only controls for audio streaming?

### ISSUE THREAD

**Issue by neowinston** [videojs/video.js#3880]
I need to hide de video, to show only the controls for an audio only player. How do I do that via CSS? Thank you!

**Comment by arpit1997** [comment]
Seems to be a duplicate issue of #3811 by @BrandonOCasey 
I was having the same issue and i did not know how to work with video.js iand audio files. May be @neowinston  you should try other options like [Plyr](https://github.com/selz/plyr). They have got a very good customisable light weight player you can see a demo [here](http://github.com/arpit1997/PQusic)
:smile_cat: :smile_cat:

**Comment by gkatsev** [comment]
The tl;dr is use an audio element instead of a video element. While video.js is called video.js it does work with audio just fine. In fact, the only difference between audio and video elements is whether they have a drawing area or not, so, there's no need to switch to another player :)
But I agree with @arpit1997 that #3811 would satisfy this issue, so, going to close this as a duplicate.
