### ISSUE TITLE
Broken SASS dependency

### ISSUE THREAD

**Issue by vit-koumar** [videojs/video.js#3998]
## Description

When trying to build a video.js project it fails on task `sass:build` complaining about not found file import.

## Steps to reproduce

1. Clone the repo
2. Run `npm i`
3. Run `grunt dist`

### Expected

Script finishes with successfully with `Done, without errors.`

### Actual

Script finishes with an error `Aborted due to warnings.`

### Error output

```
Running "sass:build" (sass) task
>> Error: File to import not found or unreadable: node_modules/videojs-font/scss/icons.
>>        Parent style sheet: /home/vit/Workspace/video.js/src/css/video-js.scss
>>         on line 5 of src/css/video-js.scss
>> >> @import "node_modules/videojs-font/scss/icons";
>>    ^
Warning:  Use --force to continue.
```

## Additional Information
The broken import is the line 5 in `src/css/video-js.scss` which is `@import "node_modules/videojs-font/scss/icons";`. When I change it to `@import "../../node_modules/videojs-font/scss/icons";` it works fine. I must be missing something.
#### videojs
5.x and also 6.x
#### browsers
N/A
#### OSes
Tried on Linux Debian Stretch
### plugins
N/A

**Comment by gkatsev** [comment]
I wonder if it's a change in node-sass/libsass since what we had used to work.

Looks like that is exactly the issue. In the [latest release](https://github.com/sass/node-sass/releases/tag/v4.5.0), they changed how it works: https://github.com/sass/node-sass/issues/1876

Can you open a PR to update node-sass to the latest (as a minimum) and change the `@import`? Would be greatly appreciated.

**Comment by gkatsev** [comment]
Actually, need to do work that depends on this, so, I'll go ahead and fix it. Thanks for reporting it to get me to investigate, @vit-koumar.
