### ISSUE TITLE
Should we expose the ability to deregister a Component/Tech?

### ISSUE THREAD

**Issue by BrandonOCasey** [videojs/video.js#4013]
## Proposal
We have a method to deregister a `Plugin` called `deregisterPlugin`, is there any reason not to have something similar for `Component`'s and `Tech`'s. I think that these methods would be:

* `Component.deregisterComponent`
* `Tech.deregisterTech`

### Pro's
* Some unit tests will be easier
* More standard API
* There doesn't seem to be any good reason that `Component`'s/`Tech`'s should not be deregistered

### Con's 
* More code to support
* May not be used by anyone outside of the Video.js organization

**Comment by misteroneill** [comment]
Remind me, will `registerTech` and `registerComponent` throw errors when trying to register something that already exists? If so, I think a `deregister*` method makes sense - that's why I added it for plugins in 6.0.

**Comment by gkatsev** [comment]
Nope, it'll just override what's currently registered.

**Comment by BrandonOCasey** [comment]
In `Tech`'s case it will also re-add that same component to `defaultTechOrder_` twice. Not sure if that will cause issues or not, it is an edge case bug though.

**Comment by gkatsev** [comment]
I think we shouldn't add this until we actually get a specific usecase for this. Multiple techs in the tech order shouldn't cause any issue, since it just loops through it, so, worst case it'll reject it multiple times. Both techs and components can be disabled by changing the techOrder for a player or setting component options for a player.
