### ISSUE TITLE
How support multiple *.flv?

### ISSUE THREAD

**Issue by caobug** [videojs/video.js#4104]
I have a full video be split to many flv files, I hope it can play like m3u8.

A plugin ckplayer can load an XML file, It contains video clip information, I hope videojs can support:

```
<?xml version="1.0" encoding="utf-8"?>
<ckplayer> 
  <video>
    <file><![CDATA[a.flv]]></file>
    <size>32594386</size>
    <seconds>204</seconds>
  </video>
  <video>
    <file><![CDATA[b.flv]]></file>
    <size>31835748</size>
    <seconds>189</seconds>
  </video>
  <video>
    <file><![CDATA[c.flv]]></file>
    <size>48219871</size>
    <seconds>189</seconds>
  </video>
  <video>
    <file><![CDATA[d.flv]]></file>
    <size>49745973</size>
    <seconds>206</seconds>
  </video>
</ckplayer>
```
![64a37032-f36a-11e6-9174-eefb02a72bd4](https://cloud.githubusercontent.com/assets/7737673/23117760/2a420ef0-f78c-11e6-8bec-e389182137af.jpg)

**Comment by gkatsev** [comment]
Closing in favor of https://github.com/videojs/videojs-contrib-hls/issues/1009. There's nothing that already exists like it. Best would be if you can transcode from flv to something else. Otherwise, a custom plugin can be made, as suggested in https://github.com/videojs/videojs-contrib-hls/issues/1009.
