### ISSUE TITLE
a page hava  multiple video  just one can work!

### ISSUE THREAD

**Issue by waitkwy** [videojs/video.js#4113]
## Description
when the page hava two  videojs ,like this:
```
<video id="video" class="video-js vjs-default-skin vjs-big-play-centered vjs-16-9"
       controls preload="auto" width="300px" height="300px">
    <source src=" http://ojk72s2sn.bkt.clouddn.com/test" type='video/mp4'/>
    <p class="vjs-no-js">need html5</p>
</video>
<video id="video2" class="video-js vjs-default-skin vjs-big-play-centered vjs-16-9"
       controls preload="auto" width="300px" height="300px">
    <source src=" http://ojk72s2sn.bkt.clouddn.com/test" type='video/mp4'/>
    <p class="vjs-no-js">need html5</p>
</video>
```

just the first video hava scene,the  second video just hava voice  no scene;

**Comment by gkatsev** [comment]
The easiest would be to switch the second `video` element to be an `audio` element.

**Comment by waitkwy** [comment]
i need a most video in a page;

**Comment by kavin-90** [comment]
I tested. I've 2 videojs it works correctly no problem. I've 4 videos in a page all of them worked and show videojs player.

**Comment by gkatsev** [comment]
@waitkwy an `audio` element works the same as a video element except it just doesn't have a display area, or scene as you called it. So, doing something link:
```html
<video class="video-js" controls>
  <source src="video.mp4">
</video>
<audio class="video-js">
  <source src="video-audio.mp4">
</audio>
```
should produce the desired results.

I'm going to close this issue now because I don't think that it requires any changes to videojs. However, discussion can still continue. Also, asking on a platform like Stack Overflow, you're more likely to get a more specific answer, here we try to keep to generic questions and answers at most, and to try to focus on actual issues.
