### ISSUE TITLE
prevent download ts files with download manager applications

### ISSUE THREAD

**Issue by elhampour** [videojs/video.js#4136]
I have created a video sharing website, and i convert my mp4 videos to ts files. when i open my website through chrome  idm catch ts files , and wants to download them, how can i prevent this ?

**Comment by sylvio-ruiz** [comment]
I believe your mime type for ts files is not correct.
Check the server configuration and be sure the mime file for ts files is : video/mp2t

**Comment by sylvio-ruiz** [comment]
There is no way, like your mp4 file.

**Comment by Globulopolis** [comment]
@elhampour see https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats

**Comment by elhampour** [comment]
@Globulopolis please tell me what i am looking for ?

**Comment by Globulopolis** [comment]
@elhampour try to read.

**Comment by gkatsev** [comment]
@Globulopolis please be nice.

@elhampour chrome doesn't support ts segments by default. So, when encountered with a file like that, it seems that idm wants to download it rather than trying to play it. If you're trying to play HLS content, you'll want something like [contrib-hls](https://github.com/videojs/videojs-contrib-hls) to be able to play it back.

**Comment by sylvio-ruiz** [comment]
A browser only will force to download a file, if it doesn't know how to handle it, so the first step is make sure that you are serving the correct mime type for the file. You must to check your server configuration and the mime type for ts files = video/mp2t
