### ISSUE TITLE
[compatibility] Should not add tracks in disabled mode for Safari

### ISSUE THREAD

**Issue by KingMario** [videojs/video.js#4220]
## Description
In Chrome or Firefox, when a track is in disabled mode, it will not be added to the player, but in Safari, it will be added to the player. Wish it will not add tracks in disabled mode.

Thanks.

**Comment by gkatsev** [comment]
Not exactly sure what you mean. However, we rely completely on Safari's native track behavior. Safari remembers any previously selection a user has made and will choose that selection for you. We think that while this behavior is different than other browsers, Safari's native track support is worth it and there's not much you can do with the native tracks beyond just disabling them manually when they're added.

However, you can also try [forcing our emulated tracks](https://github.com/videojs/video.js/blob/master/docs/guides/text-tracks.md#emulated-text-tracks).

**Comment by KingMario** [comment]
Thanks.

I was playing a video that is for sure have no captions, but in Safari, there's a CC button on the control bar, with items: captions off, unknown. Debug with breakpoint, I see that there's one caption in mode _disabled_. 

![image](https://cloud.githubusercontent.com/assets/3956876/24226308/b4d0cc4c-0fa0-11e7-871b-9d9f8dc26cba.png)

Debug in Chrome, there's no such a caption. So I think different browsers treat the tracks differently - Chrome abandons the _disabled track_, and Safari adds it.

We are playing videos that are shot by our customers on our own camera. https://portal.waylens.com/video.html?aWQ9NTgxMQ==

Video.js is fabulous and thanks a lot for your great work.

In this case, I just set `captionsButton: false` in controlBar option. The same thing happens to autio tracks. So I set `audioTrackButton: false` too.

**Comment by gkatsev** [comment]
Does it show up in the menu as "unknown CC"? That's an apple thing (https://developer.apple.com/library/content/qa/qa1801/_index.html). Basically, unless they know for sure that your HLS doesn't have captions, it displays that option. If you update your HLS to have CLOSED-CAPTIONS=NONE, it'll go away. Though, I guess hiding the captions button works too, if you don't care about those ever, either.
As for the audio track, that's fixed in videojs 5.19.0.

Hope that helps.
