### ISSUE TITLE
Semi transparent Captions background Default ?

### ISSUE THREAD

**Issue by surikat1978** [videojs/video.js#4231]
Good Day!  
Can make the default in the  next releases  Semi transparent background of Captions?
Or how to change the old releases?
It is clear that for this there are settings of captions. But do not explain to users for settings  :-)
Background  Opaque very badly looks by default on any site, IMHO! 
Thanks  advance!
 Regards!

**Comment by gkatsev** [comment]
Thanks for asking, however, we do not have plans to change the defaults away from what they currently are. This is because the defaults are in vtt.js for our emulated caption usage but we also use native text tracks on iOS and Safari.
While it would be possible to change the default in vtt.js in a custom videojs release, I would discourage you from doing so. While a white on black isn't the best looking, it's by far the best accessible default you can provide. And given that videojs provides a way for users to set captions on desktop devices (iOS and Safari users can modify the look of captions using the default OS/browser mechanism), users can choose a different look if, for them, a white on black isn't the best choice.

If there is a lot of concern about changing the default style, we would consider adding an option to allow it but have no plans for such a feature yet.

**Comment by surikat1978** [comment]
Users iOs 5-10%. And yet, the semi-transparent is better than opaque.
Thanks for answer!
