### ISSUE TITLE
RTMP on IE11 Windows 7

### ISSUE THREAD

**Issue by haietza** [videojs/video.js#4235]
## Description
RTMP with VideoJS on IE11/Windows 7 loads black boxes instead of full players: www.appstate.edu/~meltonml/videojs.html

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Open IE11 on Windows 7
2. Browse to www.appstate.edu/~meltonml/videojs.html
3. See black boxes, no players

### Expected
Expected to see VideoJS Flash players, as on IE11/Windows 8

### Actual
Saw black boxes with no players, no error messages.

### Error output
No error output.

#### videojs
5.11
#### browsers
IE11
#### OSes
Windows 7
### plugins
no plugins

**Comment by gkatsev** [comment]
It seems like your HTML is malformed. Video.js [uses an &](https://github.com/videojs/video.js/blob/master/docs/guides/faq.md#q-how-can-i-play-rtmp-video-in-videojs) as the stream and connection separator but in your page, the url ends up looking like `rtmp://streams-dev.appstate.edu/private/&amp;amp;mp4:meltonml/throttle.mp4` instead of `rtmp://streams-dev.appstate.edu/private/&mp4:meltonml/throttle.mp4`. If I make the change locally and update the player src, it seems to work just fine.

Hope that helps.

**Comment by haietza** [comment]
@gkatsev Thank you for your quick response! I changed my HTML formatting, and now I am seeing the error "The media could not be loaded, either because the server or network failed or because the format is not supported. I moved my test to a single video for simplicity: http://www.appstate.edu/~meltonml/videojs-ie.html. If you have this working, would you mind sharing your code, so I can compare it with mine to see what I might be missing please? Thank you for your help!
