### ISSUE TITLE
RTMP mp3 with captions on iOS

### ISSUE THREAD

**Issue by haietza** [videojs/video.js#4241]
## Description
An mp3 file streamed from RTMP via the .m3u8 link with captions does not play on iOS or native Safari: http://www.appstate.edu/~meltonml/videojs-ios.html

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Embed mp3 from RTMP stream in audio tag as m3u8 with captions
2. Browse to page on native Safari or iOS
3. Get "The media playback was aborted due to a corruption problem or because the media used features your browser did not support" error

### Expected
Expected to see audio player with CC option on.

### Actual
Got "The media playback was aborted due to a corruption problem or because the media used features your browser did not support" error

### Error output
"The media playback was aborted due to a corruption problem or because the media used features your browser did not support"

#### browsers
native Safari
#### OSes
iOS, OSX Sierra - Safari
### plugins
none

**Comment by gkatsev** [comment]
Seems like it's something with your master playlist. Maybe the specified codec isn't correct.
If I load in the media playlist directly (http://streams-dev.appstate.edu/private/_definst_/mp3:meltonml/demo.mp3/chunklist_w953914400.m3u8), it seems to work fine.

I think the codec in the master playlist needs to be either `mp4a.69` or `mp4a.6b` since you're playing back mp3s. https://cconcolato.github.io/media-mime-support/#audio/mp4;%20codecs="mp4a.69"

Hope that helps.
