### ISSUE TITLE
play() function does not work on Mobile

### ISSUE THREAD

**Issue by Umaroth** [videojs/video.js#4262]
## Description

play() function works fine on all the desktop browsers I've tried but does not work on the latest version of Chrome on my android device.

## Steps to reproduce
```
<video id="player" class="video-js">
    <p class="vjs-no-js">
          To view this video please enable JavaScript, and consider upgrading to a web browser that <a href="http://videojs.com/html5-video-support/" target="_blank">supports HTML5 video.</a>
    </p>
</video>

<script>
    var player
    player = videojs('player', {
        aspectRatio: '16:9',
        poster:'url',
        controls: true
    });
    player.src("url");

    player.ready(function(){ alert("Player Ready"); player.play(); )
</script>

```

### Expected
Alertbox containing "Player Ready" appears and then the video starts playing across both desktop and mobile

### Actual
On mobile devices, the alertbox pops up, indicating that player.ready(); is working properly, but the video does not play, indicating that player.play(); is not working.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
5.19.1
#### browsers
At least the mobile version of Chrome
#### OSes
At least android

**Comment by gkatsev** [comment]
Mobile devices restrict usage of the play method to only run as part of a user-action. It cannot be called otherwise.
Recently, Apple with iOS 10 (and Chrome for Android in a recent version) has starting allowing autoplay on mobile if the video is muted. I haven't tested it, but it probably means that the `play` method works in this case as well.

Hope that helps.
