### ISSUE TITLE
Is it possible to use .ts directly?

### ISSUE THREAD

**Issue by slayer1ss** [videojs/video.js#4297]
Hi, i have been using videojs to play rtmp streams at my website for years and i almost never had any problems however i cant seem to accomplish what i am trying to do right now so if you guys can tell me if it is possible or not and show me a way i would be really glad...

I have a m3u8 file which contains .ts links to hundreds of channels and i am using this file on vlc player to watch iptv, i want to use some of these .ts links(about 50 or so channels) to broadcast on my website too, is this possible? What is the proper way of doing this?

**Comment by gkatsev** [comment]
Unfortunately, I don't think that any browser supports playing back ts segments natively. However, some browsers (mostly mobile) can play m3u8 natively and it can also be played in desktop browsers in video.js via our [contrib-hls](/videojs/videojs-contrib-hls) plugin.

It's probably possible to play ts files directly, though, it won't be without effort. You'd need to use [MSE](https://en.wikipedia.org/wiki/Media_Source_Extensions) and then transmux the raw video data inside the container into a format that the browser can play directly. We have projects to [help](https://github.com/videojs/mux.js) with [that](https://github.com/videojs/videojs-contrib-media-sources) but they're not really set up to do it directly but rather for contrib-hls.

Hope that helps, I'm going to close the issue but we can continue the discussion. Otherwise, you can pop over to our [slack](http://slack.videojs.com).
