### ISSUE TITLE
Chrome 56.0 and loading the page for the first time

### ISSUE THREAD

**Issue by Equipement** [videojs/video.js#4388]
With Chrome 56.0, on the site videojs.com, if i load the page for the first time (or if i use CTRL + F5), i can see during 50 millisecond the controls of the Chrome native player.
I have take a screen capture :
[https://contrib.spip.net/IMG/jpg/videojs_chrome_56_ctrl_f5.jpg](https://contrib.spip.net/IMG/jpg/videojs_chrome_56_ctrl_f5.jpg)

With Firefox 45.3 and IE 11, this problem doesn't exist.

**Comment by Equipement** [comment]
With Chrome 58, there is the same problem.
With Android + Chrome, there is the same problem (with more than 50 millisecond).

**Comment by hartman** [comment]
That's because the element in the HTML specifies 'controls' combined with the fact that the JS will kick in slightly later then the video element being initialised. To avoid this, don't specify 'controls' on the html, and only add controls when you do the video.js initialisation. It is not possible to avoid this JS manipulation of the controls attribute if you don't want the native controls to shortly be visible.

It is a side effect of the current specification for video/audio elements. Unfortunately web developers have very little styling control over the native controls, including wether or not the native controls should even be visible, a critical issue when you are doing late loading asynchronous initialisation of JS enhancements. There is a discussion going on in https://github.com/whatwg/html/issues/2293 where some of these problems are being discussed.

**Comment by Equipement** [comment]
Thank you for this solution.
However, if javascript is disabled, i will not be able to control the video.

**Comment by hartman** [comment]
@Equipement when JS is fully disabled (when noscript would kick in too), browsers are required to present native controls, even if you have not specified a controls attribute.

**Comment by Equipement** [comment]
Good news.
Thank you.

**Comment by misteroneill** [comment]
Sounds like this question is resolved. Thanks @hartman!
