### ISSUE TITLE
dispose() removes source video element, making reuse difficult

### ISSUE THREAD

**Issue by SaintFlipper** [videojs/video.js#4397]
I have a webapp page which displays an RTMP live stream only if the user enables the option via a checkbox. If the checkbox is disabled then I want to hide the video player.

Here's the video element:

`<video id="rloPreviewVideo" class="live-video-area video-js" controls muted="true" data-setup="{}"></video>
`
When the checkbox is enabled:

```
player = videojs ("rloPreviewVideo");
player.src ({"type": "rtmp/mp4", "src": "rtmp://my-rtmp-host&mp4:rtmp-stream"});
```
and when the checkbox is disabled, to hide the player (as per http://docs.videojs.com/tutorial-player-workflows.html#showing-and-hiding-a-player):

`player.dispose();`

However dispose() has removed the 'rloPreviewVideo' element from the DOM, so the next time the user enables the checkbox the videojs ("rloPreviewVideo") call throws the error:

**TypeError: The element or ID supplied is not valid. (videojs)**

Is this by design or a defect? If by design then what is the intended way to hide the video.js player such that it can later be shown again?

I appreciate that it's possible to programatically recreate the video element but that seems like a workaround. It seems like it would be good to have some sort of reset method that releases player resources, removes any attached Flash player etc., allowing hide() and show() to work as expected.

**Comment by gkatsev** [comment]
We do have a `reset()` method which is probably what you want. Though, might still be an issue if you change the `techOrder` because it switches to the first tech in the tech order, so, if you set it to `flash` you'll run into the same issue.
Dispose removing the element directly is probably partly a historical because we actually associated the player on the DOM element itself. We no longer do it but we couldn't change how `dispose` works because it'll be a breaking change. I would probably just create the element dynamically right before calling videojs() and pass that element in.
An argument could be made that we need some kind of `unload` feature which is like `dispose` but resets as close to the original DOM structure as we can.

**Comment by SaintFlipper** [comment]
OK, thank you. I hadn't looked `reset()`, since the docs recommended using `dispose()` when hiding the player. In practice as you point out `reset()` may not be the answer here since the previews are all RTMP, so yes using the flash tech.

Currently I'm working around the issue by programatically creating the video element in a named parent:
`<div class="form-group" id="rlo_preview_parent">`

then
```
$("#rlo_preview_parent").append ( $("<video id='rloPreviewVideo' class='live-video-area video-js' controls muted='true' data-setup='{}'></video>") );
var player = videojs ("rloPreviewVideo");

```
seems a bit kludgy, but it works.

**Comment by gkatsev** [comment]
Yeah, unfortunately, we can't change the API for `dispose`. For better or worse, having a wrapper element isn't a bad idea. And if you're using video.js 6.5.0, we just added a new way of specificying Video.js `<video-js>` which means the markup is a bit less of divs all the way down.
