### ISSUE TITLE
How to prevent video from downloading played in Videojs using HLS and WOWZA STREAMING ENGINE

### ISSUE THREAD

**Issue by saas-ivthyear** [videojs/video.js#4433]
I have used videojs HLS and wowza streaming engine for video storing and transcoding. Everything working fine but not able to prevent user from downloading the video using softwares like IDM etc. 

Anyone help if know any way to prevent video from downloading in video.

**Comment by gkatsev** [comment]
Short of implementing DRM, there isn't really much you can do to prevent persistent users who know what they're doing and really want to download the video.
Just switching to HLS makes it harder for regular users to download the video because of the whole segments and manifest formats.

If preventing downloads is a huge issue I would suggest looking at DRM and https://github.com/videojs/videojs-contrib-eme.

Hope that helps.

**Comment by gkatsev** [comment]
Apparently we have an FAQ item for this as well: https://github.com/videojs/video.js/blob/master/docs/guides/faq.md#q-how-can-i-hide-the-links-to-my-videosubtitlesaudiotracks

**Comment by kobaltz** [comment]
Sorry for digging up an old thread, but this came up as a google search so this information may be useful for others. You can use a JS Encryption library to decrypt HLS files on the client side and send them encrypted over the net. This adds a layer of obfuscation and would mitigate software programs like you mentioned from scrapping together the files. Savvy folk could reverse engineer the javascript and write a scrapper to gather and decrypt all of the files, but that would be a med-large effort.
