### ISSUE TITLE
Cannot play m3u audio file

### ISSUE THREAD

**Issue by beautylix** [videojs/video.js#4513]
## Description
The player cannot play m3u file, there is no voice when it shows live.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. input the m3u url
2. play, there is NO voice when it shows LIVE
3.change the type to mp3, mpeg, mpegURL, and x-mpegURL, there is still no voice

### Error output
Just no voice, others look nornal

## Additional Information

the code is as follows

```
<audio autoplay  class="video-js vjs-default-skin vjs-big-play-centered"
  controls preload="auto" width="640" height="360"
  data-setup='{"fluid":true}'>
<source src="http://stream.abacast.net/playlist/foxnewsradio-foxnewsaac-ibc2.m3u" type="audio/x-mpegURL" />
</audio>
```

**Comment by gkatsev** [comment]
Unfortunately, most browsers do not support m3u files. It looks like Safari can play it natively but other browsers cannot.
It may be possible to make a plugin like videojs-contrib-hls that enables the playback of m3u files. If you're interested in making such a plugin we'd be able to provide some support on [slack](http://slack.videojs.com) but otherwise, we have no plans to support it.
