### ISSUE TITLE
npm package too big for jsDelivr

### ISSUE THREAD

**Issue by bharod** [videojs/video.js#4609]
I'm trying to load this package from [jsDelivr CDN](https://www.jsdelivr.com/package/npm/video.js) but it fails because the package is over 50 MB. Are there any files that could be removed to reduce the package size?

**Comment by MartinKolarik** [comment]
50 MB out of the total 57 MB is the documentation under `docs/`  which should probably excluded from npm anyway.

**Comment by thijstriemstra** [comment]
+1 for cutting docs out of npm package.

**Comment by gkatsev** [comment]
I think it's good to have the documentation with the release and I think it's weird that jsdelivr makes such an exception when other CDNs have no issues (cdnjs, unpkg.com). But I get where you're coming from.
Currently, we rely on the docs folder in the release to deploy our docs site but we'll consider removing it when we change how the docs site is deployed.

**Comment by MartinKolarik** [comment]
@gkatsev the limit is there because when serving a file from a package for the first time, we need to download and unzip the full package. The bigger it is, the higher the chance it will take too long and user's request will fail, which is why we used this limit (in most cases, even a 150 MB package would download fast enough, but "most cases" is not good enough).

I understand why you would want the documentation in a release that people download manually, e.g. from GitHub, but npm is mostly used for automated installation and IMHO should only have the necessary code.

**Comment by gkatsev** [comment]
Btw, this should be fixed by #4774.

**Comment by MartinKolarik** [comment]
@gkatsev 👍 I forgot to mention it here but I added an exception for this package so it already works, but removing the docs is still a good idea.

**Comment by gkatsev** [comment]
Well, in that case, NEVERMIND! ;)
yeah, it'll also be good for the docs to auto-update, since we're now 3 semver-minor versions behind :)
