### ISSUE TITLE
Automatically Switch to Landscape on Fullscreen in Mobile Device

### ISSUE THREAD

**Issue by khalisafkari** [videojs/video.js#4628]
Please help, tutorial auto switch to landscape on full screen mobile

**Comment by anoosi** [comment]
+1

**Comment by pawankumar01** [comment]
+1

**Comment by gkatsev** [comment]
Unfortunately, we aren't able to help with general help questions like this on the issue tracker. I would suggest asking on a forum like Stack Overflow.

**Comment by prateekrastogi** [comment]
Just wrote a plugin https://github.com/prateekrastogi/videojs-landscape-fullscreen for solving the issue. Since the thread is one of top results in google search, mentioning it here for saving time and efforts of people like me.

**Comment by briquetech** [comment]
Does this plugin work in Angular 8+/IONIC 4+?

**Comment by prateekrastogi** [comment]
It works as expected in all javascript proto domains.

-------- Original Message --------
On 1 Aug 2021, 13:33, BRIQUE Technology Solutions and Consulting < ***@***.***> wrote:
Does this plugin work in Angular 8+/IONIC 4+?
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.￼
[ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "[https://github.com](<a href=)/videojs/video.js/issues/4628#issuecomment-890471182">https://github.com/videojs/video.js/issues/4628#issuecomment-890471182", "url": "[https://github.com](<a href=)/videojs/video.js/issues/4628#issuecomment-890471182">https://github.com/videojs/video.js/issues/4628#issuecomment-890471182", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

**Comment by briquetech** [comment]
> It works as expected in all javascript proto domains.
> […](#)
> -------- Original Message -------- On 1 Aug 2021, 13:33, BRIQUE Technology Solutions and Consulting < ***@***.***> wrote: Does this plugin work in Angular 8+/IONIC 4+? — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.￼ [ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "[[https://github.com](<a](https://github.com%5D(<a) href=)/videojs/video.js/issues/4628#issuecomment-890471182">[#4628 (comment)](https://github.com/videojs/video.js/issues/4628#issuecomment-890471182)", "url": "[[https://github.com](<a](https://github.com%5D(<a) href=)/videojs/video.js/issues/4628#issuecomment-890471182">[#4628 (comment)](https://github.com/videojs/video.js/issues/4628#issuecomment-890471182)", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

My Code:

`this.player = videojs(this.target.nativeElement, this.options, function onPlayerReady() {
     console.log("Player Ready");
});
this.player.landscapeFullscreen({
	fullscreen: {
		enterOnRotate: true,
		alwaysInLandscapeMode: true,
		iOS: true
	}
})`

My Error:
`ERROR TypeError: this.player.landscapeFullscreen is not a function`

**Comment by prateekrastogi** [comment]
Instantiation of player instance in angular, with video url scope, is also required.

-------- Original Message --------
