### ISSUE TITLE
videojs module causes player initialization issue

### ISSUE THREAD

**Issue by vincentf06** [videojs/video.js#4632]
## Description
I'm using videojs 6.2.8(brightcove) on my Cordova app. Player is created by dynamically adding the script tag. When I tried to use videojs('playerId') to get player's instance, the player initialization failed sometimes. Please see the screenshots below.

It seems if a player is being initialized by the inserted script and in the meantime, if videojs() is being called, this issue will occur.

## Steps to reproduce
1. Set up html
```
<video id="player"
  data-video-id="{{ videoId }}"
  data-account="xxxxxx"
  data-player="xxxxx"
  data-embed="default"
  class="video-js"
  controls>
</video>
```
2. dynamically adding script tag to initialize the player
```
var s = document.createElement('script');
s.src = "http://players.brightcove.net/xxxxxxx/xxxx_default/index.min.js";
document.body.appendChild(s);
s.onload = callback();
```
3. try to get player in the callback
```
videojs('player').ready(function(){
     console.log(this)
})
```
4. 
![image](https://user-images.githubusercontent.com/16532850/30892645-16dab9f0-a37d-11e7-8aed-b87bc8513ad2.png)

![image](https://user-images.githubusercontent.com/16532850/30892616-f2c23002-a37c-11e7-9843-0fa29bb26dc7.png)

### Expected
Player is created and the instance of player can be returned from videojs module

### Actual
Get the player's instance instance
But player is not initialized correctly

### Error output
"VIDEOJS: Ignoring already initialized player"

#### videojs
6.2.8
#### browsers
Cordova
#### OSes
Android
### plugins
No plugins

**Comment by gkatsev** [comment]
I think the issue here is that the Brightcove player script is trying to initialize the player but your usage of `videojs()` to get the player will also potentially initialize the player. This could potentially cause issues where the player gets initialized by your call to `videojs()` instead of by the Brightcove script. The recommended approach to getting players is referencing them by id in the `videojs.players` object.
In addition, since loading the script is dynamic, you probably want to use the hooks `setup` event to know when the player is initialized: http://docs.videojs.com/tutorial-hooks.html#setup.

Hope that helps.
