### ISSUE TITLE
document how to add version nr to plugin

### ISSUE THREAD

**Issue by thijstriemstra** [videojs/video.js#4636]
https://github.com/videojs/video.js/blob/master/docs/guides/plugins.md does not mention how to set this up.

In browser console `getPluginVersion` returns an empty string, but I'd like to know how to change this for my own plugins.

```
> videojs.getPluginVersion('record')
""
```

**Comment by thijstriemstra** [comment]
After some fiddling this was only way I got it to work, e.g.:

```javascript
// version nr gets replaced during build
Record.VERSION = 'dev';

// register plugin
videojs.Record = Record;
videojs.registerPlugin('record', Record);
```

**Comment by thijstriemstra** [comment]
Is this the correct way? I can add it to the plugins doc with a PR if someone can give some feedback here.

**Comment by chadisdad83** [comment]
Do you just want video to play?

**Comment by chadisdad83** [comment]
Just download vlplayer iptv from play store that's what I use

**Comment by thijstriemstra** [comment]
> Just download vlplayer iptv from play store that's what I use
what

**Comment by chadisdad83** [comment]
The all I recommended made it to where you get video and sound while it
will also install or create a plugin to work for whatever video format

On Oct 2, 2017 5:38 PM, "Thijs Triemstra" <notifications@github.com> wrote:

Just download vlplayer iptv from play store that's what I use
what

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/videojs/video.js/issues/4636#issuecomment-333672811>,
or mute the thread

**Comment by mister-ben** [comment]
That' is the correct way to add the version. The plugin generator implements this by Ring the version from package.json:

https://github.com/videojs/generator-videojs-plugin/blob/master/generators/app/templates/src/_plugin.js

**Comment by misteroneill** [comment]
Yeah, we should clarify this in the plugin doc here.

**Comment by thijstriemstra** [comment]
done, see #4642
