### ISSUE TITLE
What is required to make the video player responsive with a max-height?

### ISSUE THREAD

**Issue by jsonhuntrods** [videojs/video.js#4644]
## Description
I am trying to play a video on a website that is not a 4:3 or 16:9 video, more like a 9:16, kind of the video size you get when "selfie-recording" on your phone, posting on snapchat, etc. I've set up a fluid video-js instance, and the video does fine adjusting when screen width is changed. But screen height is another story. I have tried setting max height on my container and max height on the video instance. But when I load a page with a high quality video that has a height of say 1920 pixels and a width of only 1000 pixels, it takes up the entire screen, especially on mobile devices. I can't seem to make video-js respect the aspect ratio and a max height. Am I missing something? Here's a basic jsbin with a fluid video-js instance (http://jsbin.com/yucoyifodo/edit?html,output). How can I make that video responsive, but with a max height? As you can see setting a max-width works as expected, but max-height does not.
## Steps to reproduce
Go to the jsbin and try to make the video responsive with a max-height

### Expected
Video obeys the max-height of the container

### Actual
Video does not obey the max-height of the container

### Error output
None

#### videojs
5.18.4
#### browsers
All
#### OSes
All
### plugins
None

**Comment by ClemAdelanteWeb** [comment]
Good question !

**Comment by gkatsev** [comment]
I think it's because `fluid` mode uses `padding-top` to control the size, so, it doesn't really have a height.
If you want an a 9:16 aspect ratio, you can give it as an option and we'll do that instead. Example: https://jsbin.com/reredur/2/edit?html,output

Hope that helps and thanks for you patience.

**Comment by jmichaelbrown** [comment]
I see this issue is marked "closed" but it's not.  The issue is, even in 16:9 when the height of the player container is greater than the video, bars are created on top and bottom and the player controls are below the "bars".  When the window is full screen, this forces the controls off the screen.  So far, I've not been able to overcome this and it's wasting time.  I've tried the css hack of specifying max width and height but that has no effect.  Anyone else overcome this?

**Comment by jmichaelbrown** [comment]
I found a work around but it's not ideal.   This will force the player controls to stay on the bottom, no matter the size of the video

.vjs-control-bar {
    position: fixed !important;
}

**Comment by jsonhuntrods** [comment]
Forgot I had raised this a while ago, if it still helps @im-xavi I just resized all my videos to be the same size. I couldn't find a way to easily modify the CSS/JS and make it work.

@jmichaelbrown I'm guessing that's probably the best option for handling your issue.

**Comment by thenewguy** [comment]
This is what popped up for me searching the question so I am leaving a note to `vjs-fill` for anyone who stumbles upon this: https://docs.videojs.com/tutorial-layout.html

At first glance, it seems to be the solution to this problem
