### ISSUE TITLE
Unable to reference to player from tech

### ISSUE THREAD

**Issue by kocoten1992** [videojs/video.js#4733]
I'm using [shaka player](https://github.com/google/shaka-player) as tech for videojs

This tech have many ability on it own, one of that is ability to auto jump from 360p to 720p if network can afford it (etc..)

When that happen, there should be a way to connect back to videojs player, to show ```240p``` or ```360p``` on the player (like youtube)

But I can't seem to do it, there is no way to reference back to videojs once in the tech, might be because of this https://github.com/videojs/video.js/blob/master/src/js/tech/tech.js#L98 ?

Right now, I'm attach player to ```window.player```, and reference it from the tech, but it doesn't feel right, think maybe we should have a way to connect between tech and videojs ?

**Comment by gkatsev** [comment]
We specifically unlinked the player from the tech because you generally shouldn't be touching the player from the tech. But we are missing a way for the tech to provide capabilities to the player. For example, in the youtube tech, after the tech loads it will then know what captions and playback rates are available. The player should then update with those. The resolution thing also fits in here.

**Comment by mysuf** [comment]
The root of this issue is here: https://github.com/videojs/video.js/blob/bc2da7c67bfe1be6deb811269ed3b4a438f8c1a6/src/js/component.js#L55 

So actually `player_` is present in Tech, but contains only refernce to own instance cos Tech has `play()` method. 

Usecase: I want to trigger custom tech events on player and this is not possible now. Now I have to use `player.tech_.ready(...)`.

Events are safe to use. For example tech's play, pause etc are retriggered on player anyway so why not to get access to player instance also for custom ones.. The fix should be easy.

Thanks.
