### ISSUE TITLE
Captions menu doesn't show up in IE when having longer caption labels

### ISSUE THREAD

**Issue by mrdtron** [videojs/video.js#4758]
## Description
When using longer caption labels, the captions/subtitles menu doesn't render correctly in IE/Edge so a user can't select them. 

Sample test case: https://codepen.io/ttom/pen/rYJBrM

## Steps to reproduce
1. Load the player in IE/Edge
2. Start playback and click on captions/subtitle button in the control bar

### Expected
Captions/subtitles is displayed menu with a list of captions 

### Actual
An empty menu with scrollbars appear http://take.ms/MGe1W

#### videojs
6.x/7.x
#### browsers
IE11/Edge
#### OSes
Windows 7/8.1/10

**Comment by OwenEdwards** [comment]
@mrdtron if you look in the Console window when you use the CodePen sample test case (especially on Firefox or Chrome), you'll see that loading of the text tracks is being [blocked because of cross-origin permission issues](http://docs.videojs.com/tutorial-text-tracks.html#text-tracks-from-another-domain). I don't know if this is the exact cause of what you're seeing, but it'll be hard to debug any further without fixing that issue.

**Comment by mrdtron** [comment]
@OwenEdwards CORS error you observed would prevent loading VTTs. However, the issue here has nothing to do with loading text tracks. The problem here is that captions menu gets out of wack in IE when adding more than 4 tracks.  NB Firefox or Chrome don't exhibit this, only IE is affected.

## Chrome or Firefox (4+ caption tracks)
http://take.ms/qwjWM

## IE (4+ caption tracks)
http://take.ms/ginDJ

## IE (4 or less caption tracks)
http://take.ms/9tq96

Applying the following fixes the issue:
```
 .vjs-subs-caps-button .vjs-menu-content{
  overflow: hidden
}
```
https://codepen.io/anon/pen/RjQqgv

**Comment by OwenEdwards** [comment]
Ahh, well that's great, you found the solution! I was thinking that the differences in the CORS error handling might be causing problems with IE knowing the names of the tracks which couldn't be loaded, but apparently, it's just a CSS issue. Can you submit a PR?

**Comment by gkatsev** [comment]
The problem with `hidden` is that it prevents scrolling, so, if you end up having a lot of items, you won't be able to see them all. Example: https://jsfiddle.net/c4ho5whm/.
The menu currently uses `overflow: auto` which creates the scroll bar if the content is too big to fit. Example: https://jsfiddle.net/c4ho5whm/1/.
Probably the issue is that the width of the menu, particularly, the SubsCaps Button isn't tweaked correctly to account for IE and the cc icons in it. So, because the items end up being too wide, the scroll bars show up and mess everything up.

This pen, a fork of yours, enables the regular captions menu, does it have the same issue? https://codepen.io/anon/pen/VrQONQ. As a workaround, you could try using it, or adding your CSS snippet, assuming you only have 4 tracks.

The real fix will probably require more finagling with sizing.

**Comment by gkatsev** [comment]
@OwenEdwards ah, yeah, the sizing issue in #4599 and this are probably related.

**Comment by mrdtron** [comment]
@gkatsev that's a fair point. A better approach perhaps would be to leave vertical scrollbar
```
.vjs-subs-caps-button .vjs-menu-content{
  overflow-x: hidden
}
```
