### ISSUE TITLE
"dist" folder is missing on v6.x

### ISSUE THREAD

**Issue by oxodesign** [videojs/video.js#4764]
"dist" folder is missing on new releases, any plans on including it?

**Comment by gkatsev** [comment]
Is this about `dist/` not being available in the git tags for bower? Unfortunately, we dropped bower support in v6 because maintaining the `dist` folder in the repo or only in the git tags caused too much of maintenance burden. We publish Video.js to npm and also github releases, so, you can grab the files from [github releases](https://github.com/videojs/video.js/releases), from a place like [unpkg](https://unpkg.com/video.js@6.4.0/dist/), or even use the [npm bower resolver](https://www.npmjs.com/package/bower-npm-resolver).
