### ISSUE TITLE
Vast & Vpaid support

### ISSUE THREAD

**Issue by SolmazKh** [videojs/video.js#4766]
Hello
Our player was Videojs v5 and we are planning to upgrade it to v6.
However there is one major problem:
The plugin we used for supporting vast and vpaid
[https://github.com/MailOnline/videojs-vast-vpaid](https://github.com/MailOnline/videojs-vast-vpaid)
does not suppport Videojs v6 and actually it seems to be dead!!
What should we do to implement vast and vpaid for our Videojs v6?

**Comment by mister-ben** [comment]
You could try Google's IMA plugin https://github.com/googleads/videojs-ima

**Comment by gkatsev** [comment]
Yeah, unfortunately, we don't provide a vast vpaid support ourselves. Maybe one of the forks of mailonline/videojs-vast-vpaid has updated with v6 support?
Also, trying out videojs-ima is a great idea, since the plugin should theoretically support any VAST/VPAID.

**Comment by EhsanCh** [comment]
There is no good vast/vpaid/**vmap** plugin for videojs 6 and 7 and it is the biggest cons of videojs. 
videojs-ima is not an option. because it loads very JS resources from google domains (like youtube.com) and it depend to google. so it is not good for youtube competitors.

Please develop this required plugin.

**Comment by kgabalesvideomaker** [comment]
We need VAST for videojs 7.

**Comment by geco** [comment]
> We need VAST for videojs 7.

No one yet implemented it or found a solution?
