### ISSUE TITLE
can not drag on progress bar and volume control in IE9

### ISSUE THREAD

**Issue by dante1977** [videojs/video.js#4773]
## Description
can not drag on progress bar and volume control in IE9

#### videojs
v6.5.0
#### browsers
IE9

**Comment by gkatsev** [comment]
Probably due to this fix: https://github.com/videojs/video.js/pull/4613
@kocoten1992 would you be able to take a look at this?

**Comment by kocoten1992** [comment]
@gkatsev yes, I'll try land a fix tomorrow

**Comment by gkatsev** [comment]
Awesome, thanks @kocoten1992. Worst case, just special case old IEs and let it do whatever :)

**Comment by kocoten1992** [comment]
@dante1977 , I need your help (your video)

I use Heff video here, http://www.steveheffernan.com/test/11811992/test.html, test on 6.3 and 6.4, volume-bar work fine, but I can't back drag (drag on seekbar closer to 0:00), I think it because of my video (not sure), do your player behave the same ?

If not, could you attach your video somewhere and give me the link?

**Comment by dante1977** [comment]
@kocoten1992 big help~~
