### ISSUE TITLE
Ts only loads the first one

### ISSUE THREAD

**Issue by kobe0116** [videojs/video.js#4794]
## Description
Briefly describe the issue.
Include a [reduced test case](https://css-tricks.com/reduced-test-cases/), we have a [starter template](http://jsbin.com/axedog/edit?html,output) on JSBin you can use.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1.Try loading video and find that only the first ts is loaded. This phenomenon is not obvious

## Expected
I want to load the ts in the list normally
## Additional Information
Please include any additional information necessary here. Including the following:
#### browsers
Chrome Firefox
#### OSes
what platforms (operating systems and devices) are affected?
windows 
### plugins
are any videojs plugins being used on the page? If so, please list them below.
videojs-contrib-hls.js

**Comment by kobe0116** [comment]
This phenomenon doesn't happen every time, only three times, and it's on different devices.
You need a complete m3u8 file or a playable address

**Comment by dakora1310** [comment]
Hello, I have the same problem. Video loading only first ts, after I have Error 
videojs video.js:489 videojs: warn: problem encountered with the current hls playlist. trying again since it is the final playlist.

videojs-contrib-hls  @version 5.12.2
Video.js 6.4.0

I  put my link here http://videojs.github.io/videojs-contrib-hls/ and I had the same error.

In Chrome Network I see
http://filename.m3u8?md5=4a2MfuhY5biGAzGG6r7B8g&expires=1513355321&shift=10721
Response
#EXTM3U
#EXT-X-VERSION: 3
#EXT-X-MEDIA-SEQUENCE: 1161227
#EXT-X-ALLOWCACHE:0
#EXT-X-TARGETDURATION: 11
#EXTINF:10.932000
ip0.ts?segment=1161227
#EXTINF:10.900000
ip0.ts?segment=1161228
#EXTINF:11.096000
ip0.ts?segment=1161229

http://ip0.ts?segment=1161227
http://ip0.ts?segment=1161228
http://ip0.ts?segment=1161229

http://filename.m3u8?md5=4a2MfuhY5biGAzGG6r7B8g&expires=1513355321&shift=10721
Response
#EXTM3U
#EXT-X-VERSION: 3
#EXT-X-MEDIA-SEQUENCE: 1161228
#EXT-X-ALLOWCACHE:0
#EXT-X-TARGETDURATION: 11
#EXTINF:10.900000
ip0.ts?segment=1161228
#EXTINF:11.096000
ip0.ts?segment=1161229
#EXTINF:10.947000
ip0.ts?segment=1161230

And not any ts 

Pls, help me.

**Comment by gkatsev** [comment]
Asked the playback team and they seem to recall potentially similar scenarios but they all ended up being issues with the content.
Unfortunately, without a reduced test case we cannot help further. closing for now but let us know if you have a reduced test case.
