### ISSUE TITLE
Issue in Video.js 6.4.0 below

### ISSUE THREAD

**Issue by sanjaykpatel** [videojs/video.js#4795]
## Description
Warn come in this version and also playbackRates not display in control bar
VIDEOJS: WARN: Player "video-player" is already initialised. Options will not be applied.

## Steps to reproduce
1. playbackRates not display in control bar
2. VIDEOJS: WARN: Player "video-player" is already initialised. Options will not be applied.

**Comment by mister-ben** [comment]
This is because you are trying to set up the player twice. This is most often because you have used the `data-setup` attribute which automatically initialises the player, and then try to initialise the player with options, e.g. `videojs('myPlayer', {myOption: true})`. In this case the options are applied, as the warning describes.

You probably just need to remove `data-setup` from your video element.
