### ISSUE TITLE
Bad UX with fluid player and vertical video resolution

### ISSUE THREAD

**Issue by hardcodet** [videojs/video.js#4808]
## Description

This may be an edge case, but I ran into this today when just trying out to get the player working with a sample file that has an unusual layout.

## Steps to reproduce

1. Copy the markup below into an HTML file
2. Open in Chrome.
3. You'll already see that the UI doesn't adjust too nicely - it uses the whole width and thus is way too high for the screen. Entering full-screen mode would fix that.
4. Enable dev tools and go to mobile device mode (see screenshot below).
5. Since the device in portrait mode matches the dimensions, the video fits the screen nicely.
6. Switch to landscape (see also in the screenshot)
7. The video again doesn't fit. Furthermore, screen controls don't show up when I tap the UI, so I couldn't even go to full-screen mode.

## Markup

    <head>
        <link href="http://vjs.zencdn.net/6.4.0/video-js.css" rel="stylesheet">
    
        <style>
            body {
                background-color: black;
                margin: 0;
            }
        </style>
    </head>
    
    <body>
    
        <div>
            <video id="my-player" class="video-js vjs-big-play-centered" controls preload="auto" poster="//vjs.zencdn.net/v/oceans.png" data-setup='{"fluid": true}'>
    
                <source src="https://ridrstorage.blob.core.windows.net/temp/vertical.mp4" type="video/mp4"></source>
            </video>
        </div>
    
        <script src="http://vjs.zencdn.net/6.4.0/video.js"></script>
    </body>

![image](https://user-images.githubusercontent.com/873009/33881207-5d72ce46-df34-11e7-9fc8-1b80c086c4c0.png)

**Comment by gkatsev** [comment]
I do think this is a bit of an edge case. The default sizing of the player is taken from the inherent video size, so, it ends up being 1080x1920 which is pretty big. On top of that, fluid mode is enabled which keeps the video to that aspect ratio provided or the one calculated from the video's size, so, in this case it's 9:16. However, because the video element is just in a div that isn't size, the width of the entire viewport is used to size the player. Adding a css like `body { width: 50vw; }` makes this example more reasonable, also, I've been able to scroll the page in landscape mode to get to the controls. The main difficulty with fluid mode, given that we use padding-top to keep the aspect ratio is that it's hard to constrain the height of the element. Another option to consider is using the `vjs-fill` class instead of fluid mode which makes video.js take up the entire area of the containing element (at some point we'll make fill mode like we have with fluid mode).
Hope that helps.

**Comment by hardcodet** [comment]
Great explanation! I'll play with the options you laid out next week - closing this thread for now.
Thanks for taking the time, I greatly appreciate it 👍

**Comment by gkatsev** [comment]
You're welcome. Feel free to ping back here if you have more questions relating to it or drop by our [slack](http://slack.videojs.com).

**Comment by hoodsy** [comment]
@gkatsev `vjs-fill` was a lifesaver for me, thank you!

You're all over the place in the issues – thanks for all your hard work on the project. :D

**Comment by gkatsev** [comment]
@hoodsy haha, thanks. And you're welcome :)
