### ISSUE TITLE
I can not use vedio.js to play my rtmp stream, plz help

### ISSUE THREAD

**Issue by Faterjames** [videojs/video.js#4829]
I use ffmpeg to push my rtmp stream, i used vlc to prove it worked.

i wrote html file like this 
 
```
**<!DOCTYPE html>
<html>
<head>
<title>RTMP Embed</title>
<link href="http://vjs.zencdn.net/4.11/video-js.css" rel="stylesheet">
<script src="http://vjs.zencdn.net/4.11/video.js"></script>
</head>
<body>
<h1>RTMP Embed</h1>
<video id="streamContainer" class="video-js vjs-default-skin" controls preload=$
<source src="rtmp://192.168.31.240/rtmp/live" type='rtmp/flv'>
</video>
</body>
</html>**
```

just copy another issue, but it not worked , the error is 
video.js:23 VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this video. t.D {code: 4, message: "No compatible source was found for this video."}

thank you a lot ahead of time !

**Comment by gkatsev** [comment]
Video.js 4.11 is incredibly old and not something we support anymore. However, basically, the issue is that browsers no longer provide a way to detect whether flash is available or not. This is fixed for Video.js 6 in videojs/videojs-flash#39. You could try applying the fix manually to a self-hosted version of Video.js.

Hope that helps.
