### ISSUE TITLE
Flash of unstyled HTML player

### ISSUE THREAD

**Issue by iamdubx** [videojs/video.js#4838]
I am using Video.JS with Vue and having flesh of unstyled default HTML5 player if I refresh the page.

Any tips how to fix this?

**Comment by gkatsev** [comment]
In [6.5](http://blog.videojs.com/video-js-6-5-0-release/) we just released what I call I Can't Believe It's not Custom Elements: https://github.com/videojs/video.js/pull/4640
Basically, it allows you to use a `<video-js>` element instead of a regular video element and it'll create the video element inside. It should help with the flash of the html5 player.

Hope that helps.
