### ISSUE TITLE
Could we keep the video tag id?

### ISSUE THREAD

**Issue by intijk** [videojs/video.js#4878]
Dear videojs team:

After tried videojs for some time, I think this is a great library for video control . But there is one thing which make me feel a little bit hard , I want to know that could we not change the id here?

https://github.com/videojs/video.js/blob/e0ed0b5cd762f83dc54a7b56e8774718485e924d/src/js/player.js#L596

I have a set of video tags for multiple videos and we use a unique id generator to control the video element, this id change action could break the original logic. 

Even now we are trying to patch the id with this suffix, but it seems not a good solution and could prone to future change also. Please consider my request, thank you.

**Comment by mister-ben** [comment]
The player element will always take the id of the placeholder video element, so a video element retained as the playback tech could not keep it. After a source is loaded a player may have no video element at all, most often if the flash tech were used.

You should always be using the Video.js API rather than interacting with a video element within an initialised player in any case.

`videojs.getPlayers()` returns an object of players that have been created. The keys of that object will be the players' ids.

**Comment by gkatsev** [comment]
Unfortunately, we're unable to do this because it will be a breaking change for us. Also, because of the way that Video.js works, the video element is basically taken over by Video.js and becomes Video.js internals. In a lot of cases, like @mister-ben mentioned, it can even go away or a new one will get created.
Besides using the Video.js API to interact with the player, you can also consider using the `<video-js>` element or a `<div data-vjs-player>` element wrapper so your references don't change once Video.js is initialized. More info on our [embeds guide](http://docs.videojs.com/tutorial-embeds.html).

**Comment by intijk** [comment]
I am creating a hover canvas on top it, so I need the dom element to accurately calculate the position and size of the video element, or the feature won't be possible.

**Comment by rynam0** [comment]
FWIW: I am trying VideoJS in an Elixir Phoenix LiveView app which tracks diffs/changes to elements in the DOM.  Because the ID has been changed, the entire element is replaced by LiveView vs simply showing an element when I update a boolean to display a peer element to the video tag.   Indeed if I change the ID of the video tag back to my original ID after initializing a player, LiveView issues updates vs full on replacements of my view (which is what I want here) but of course this breaks the videojs API (finding the initialized player, disposing, etc).  :(

**Comment by intijk** [comment]
some small comment from future, my later solution is use a piece of code save id first, dispose, then restore my stored id.
