### ISSUE TITLE
Facebook Android Browser Issue

### ISSUE THREAD

**Issue by samueleastdev** [videojs/video.js#4882]
## Description
When accessing a video link from a Facebook feed, the video will open up in the Facebook browser on Android the video does not display.

Hard to explain please see the video at the bottom for a live example it's from an emulator but the same is happening on Android devices.

You can test these links
http://videojs.com/advanced/ 
http://output.jsbin.com/vokipos 

Post on a Facebook timeline and then access the link through the feed in the Facebook app.

### Error output
I am working on finding the errors because it's in the simulator and not an app I cannot produce any and the Android phone I have is old and uses the old functionality by opening links in an external browser, going to try and get them.

### videojs version
video.js 5.20.2 also tested the latest

### Browsers
Android Facebook Browser 

### Other Plugins
Same issue with the hls plugin

Video of the issue: https://goo.gl/Xdqssf

**Comment by mister-ben** [comment]
Those URLs and others work in Facebook's web view on a real device. I tried some URLs in Android Studio's emulator, which I think is what you're using in that video, but no HTML5 video works there. That includes URLs such as https://www.w3.org/2010/05/video/mediaevents.html which are a plain video element, not Video.js

This looks like a web view and Android emulator issue rather than anything Video.js can influence, probably to do with hardware acceleration.

**Comment by samueleastdev** [comment]
Hi @mister-ben 

Yes, thanks for the update been debugging for a few hours I will list my findings see if it helps anyone else.

Your correct the black screen issue is simply down to the Android SDK simulator.

I managed to get hold of a real newer Android device to run some tests and I could see that the advanced video js example worked and it has a hls video which also worked so that narrowed it down to my setup.

This left me in a bug testing nightmare which if someone can explain a better way to do this it would be greatly appreciated normally I connect the phone via usb to the laptop and in chrome under dev tool, real devices select the phone and inspect element on the browser tab get a full console log output can see any errors happy days.

Trying to do this with the Android Facebook in app browser doesn't work it is not even listed as a browser in the dev tools, so I started commenting out code rebuilding my project submit to a live test environment clearing Chromes cache closing the facebook browser and then reopen check and then repeat (painful) then I found this helpful snippet.

~~~
window.onerror = function(message, url, linenumber) {
    alert("JavaScript error: " + message + " on line " +
        linenumber + " for " + url);
};
~~~

Again probably the dumbest way to debug and if someone can tell me another way to get the debug output from an Android FB browser I would love to hear it.

This time I finally got some errors and it turned out to be an issue with the Chromecast plugin i am using.
~~~
chrome is not defined on line 1
~~~

Did a little research on the Facebook in-app browser bit more info here: http://www.stateofdigital.com/facebook-browser-biggest-browser-ignore/

I fixed that and the player would now load and I cleared my CloudFront cache and everything started working.

Thanks

**Comment by mister-ben** [comment]
The situation is better than it used to be but views can still be pretty horrible and inconsistent to work with for the sort of reasons outlined there, and Facebook's is likely one of the better ones. Android has had [Chrome custom tabs](https://developer.chrome.com/multidevice/android/customtabs) for some time now which is a much better experience all round for this use case. I can't think of a non-cynical reason for Facebook not to use that instead of their web view "browser".

I've used [weinre](https://people.apache.org/~pmuellr/weinre/docs/latest/) in the past debugging remote devices without proper dev tools, that may work for you.

**Comment by gkatsev** [comment]
weinre could work, also, debugging in the Android browser usually involves copious console.log statements and then [`logcat`](https://developer.android.com/studio/command-line/logcat.html) with grep.
Android emulators are often terrible with video so testing video on them is shakey at best. It is also very possible that it is not possible to get chromecast to work inside of an android webview without lots of work on the android app side, if it's even possible. Unless Facebook switched to the chrome custom tabs, you won't be able to chromecast from within it, unfortunately.
