### ISSUE TITLE
problem when loading videojs files to server and using them in a javascript file

### ISSUE THREAD

**Issue by softimpactdev** [videojs/video.js#4898]
Hello,
im having an issue when i upload my video js to server and using them, but when i call them using localhost url i dont have the same issue.

in the attached file there is my javascript file of how im using it.

I would appreciate any help
[EmbedPageFunctionsTesting.zip](https://github.com/videojs/video.js/files/1656336/EmbedPageFunctionsTesting.zip)

**Reproduce:**

- downloaded Videojs files and uploaded to a server
-comment code between //LocalHost and //online
- used them in a javascript file

**Error output**
- plugin levels does not exist
-  player.hotkeys is not a function
- player.contextmenuUI is not a function

**Expected**
- if i remove the code between //online and function LoadFunctions it works perfectly

**Comment by gkatsev** [comment]
Hi, unfortunately, your example is really complicated. However, it seems like this is a timing issue. Loading in scripts, programmatically, will evaluate the script whenever each script finishes. Different files are different sizes and take a different amount of time to load over the network, locally, they all take about the same time. That means that some files will end up loading before Video.js loads.
You'll want to change your logic to make sure that things are loaded in order, specifically, Video.js is loaded before. This is why adding the files directly in the HTML is beneficial, because they are guaranteed to be evaluated in order unless you tell them not to.

Hope that helps.
