### ISSUE TITLE
Load part of files during waiting event

### ISSUE THREAD

**Issue by xMADOXX** [videojs/video.js#4907]
Hi,

I'm using videojs and I'm stuck to load multiple files. When my player has fired event "waiting" I would like to make sure that every external audio files has enough data before the player continues playing. 

Exemple : Video is playing and I've got 3 more external audio files at the same time. How can I make sure that video + 3 audios files have enough data ?

Is there an event that's fired or something like this ? It would be perfect but I didn't find it for the moment. 

I'm using Video.js 5.20.4

Thx in advance for your help !

**Comment by gkatsev** [comment]
Can you elaborate on what you mean by "load multiple files"? Are you trying to use separate audio and video files and sync them? Or are you doing something like HLS or DASH?
If it's mp4s and the such, we're at the mercy of browsers (or flash in a few cases) for being able to load the file. As for HLS, that is also a bit tricky and would be implementation specific. Are you using any particular plugin for it, like contrib-hls?
If you can provide a reduced test case, that would be great too.

**Comment by xMADOXX** [comment]
Yes I'm trying to use separate audio and video files (1 mp4 file+ 3 mp3 files). So what should I do ? Addeventlistener on each audio file like waiting and playing ?

**Comment by gkatsev** [comment]
Yeah, you'd basically need a player or video/audio element per mp4 and mp3 file and then listen for stuff like `canplay` or `canplaythrough`.
You also could potentially do your own thing using MSE and download the files manually but would require a lot more work but it would also give you a lot more control.

Are these mp3s alternate audio basically? Might be better to just switch to HLS or DASH which already has handling for making sure that the audio is loaded along with the video.

I'm going to close this issue because it won't require any changes in video.js but we can definitely continue the discussion if you want to continue talking through things.
