### ISSUE TITLE
play() doesn't work on Android

### ISSUE THREAD

**Issue by AntonioMIN** [videojs/video.js#4915]
## Description
HTML code
```
<video id="video_1" class="video-js vjs-default-skin" preload="auto" width="100%" height="100%" loop data-setup="{}">
        <source src="/static/vid/dottintro_1.mp4" type='video/mp4'>
        <p class="vjs-no-js">Need HTML5 sentense</p>
</video>
```
JS code..
```
var vid1 = videojs('video_1',null,function(){
            this.addClass('fullsize'); // CSS :  width: 100% !important;    height: 100% !important;
        });
        $("#main-dot").hover(function() {
            $('.main-element').hide();
            vid1.play();
        },function() {
            vid1.pause();
        });
```
this code work on Windows or PC something. But on mobile, they doesn't work.

## Steps to reproduce
On Android Chrome
1. click #main-dot element.
2. Video div will cover the screen
3. video doesn't play

#### videojs
6.6.3
#### browsers
Chrome 64.0.3282.123
#### OSes
Android 7.0.0 SM-G610S Build/NRD90M (Galaxy On7 2016)

**Comment by gkatsev** [comment]
Unfortunately, calling `play()` on the player on mobile is no longer allowed unless it is part of a user action. Hovering doesn't count. Desktop browsers are actually getting similar restrictions where autoplaying unmuted audio won't be allowed. Desktop safari already has that restriction and Chrome is getting in version 66.
If you want to autoplay and you don't mind having the video muted at first, adding the `muted` attribute to the video element will make it work, otherwise, you need to wait for the user to request playback.
