### ISSUE TITLE
Need to display the progress bar in separate row

### ISSUE THREAD

**Issue by sarathmunusamy** [videojs/video.js#4924]
Hi Team,

I am using the videojs 6.2.4 now. I am getting the video player display as given in the below image. 

![image](https://user-images.githubusercontent.com/22632082/35719678-82c29b68-0810-11e8-9ccd-690f253476d3.png)

But I need to display the progress bar in the separate row as like in the below image. I tried with css to change its position, but I can’t able to do this. Is there any possibility to bring the progress bar in separate row.

![image](https://user-images.githubusercontent.com/22632082/35719685-8bf2968e-0810-11e8-8ac9-e24787d0a1af.png)

When I use videojs 4.1.0 , I  can able to achieve this but we like to stick with the latest version. It would be more helpful if anybody help on this. Thank you.

**Comment by dandelionred** [comment]
Check this out https://github.com/VD39/videojs-iplayer-skin-1
Both players in the demo have progressbar in a separate row.

**Comment by gkatsev** [comment]
Thanks for the example @dandelionred.
http://blog.htbx.net/videojs-skin-twitchy/ is another example.

This is definitely something that is possible to do with just CSS. It's possible to even just move the progress bar up but leave everything else the same. Unfortunately, this isn't really something that we have the time to support ourselves but if you have specific questions trying to write the CSS we may be able to help. I'm going to close this issue because it won't require a change in Video.js (most likely) but if you have questions, feel free to continue the discussion in here.
