### ISSUE TITLE
Does videojs support play http-flv streaming by use flash?

### ISSUE THREAD

**Issue by coolicer** [videojs/video.js#4930]
I'm using rtmp well,but http-flv is better.so I want to try.

**Comment by gkatsev** [comment]
I'm not sure what http-flv is. Is it an RTMP alternative? However, we're not really focusing on flash or RTMP currently because of browser support for flash is greatly diminishing. If http-flv requires flash, you should look at the [videojs swf](/videojs/video-js-swf) repo. You should be able to update the swf to include http-flv. If you make a PR we'll consider adding it in but we're not going to work on it ourselves and, frankly, it's super low priority.
However, if you did want to update the swf, we'll definitely try and help you find your way if you drop by our [slack](http://slack.videojs.com) for questions.
Hope that helps and sorry I don't have a better answer :)

**Comment by coolicer** [comment]
http-flv means turned video into flv format, and then transmitted to the client use http protocol.

**Comment by gkatsev** [comment]
Ah, I see. I thought it was something specific. We do have a Media Source-like interface for our swf that allows you to put in flvs: https://github.com/videojs/videojs-contrib-media-sources
We use this in some versions of contrib-hls to download a ts segment and transform it into an flv that we hand to flash to play.
