### ISSUE TITLE
I don't want to use the video player that comes with my cell phone. How to disable it?

### ISSUE THREAD

**Issue by toKnowMore** [videojs/video.js#4934]
## Description
Briefly describe the issue.
Include a [reduced test case](https://css-tricks.com/reduced-test-cases/), we have a [starter template](http://jsbin.com/axedog/edit?html,output) on JSBin you can use.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1.
2.
3.

### Expected
Please describe what you expected to see.

### Actual
Please describe what actually happened.

### Error output
If there are any errors at all, please include them here.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with?
#### browsers
what browser are affected?
#### OSes
what platforms (operating systems and devices) are affected?
### plugins
are any videojs plugins being used on the page? If so, please list them below.

**Comment by gkatsev** [comment]
I'm not quite sure what you mean. This is for playing back local files on your phone? If so, you'll need to install a separate app.
If videos on the web are being played using a native video player that you're not a fan off, unfortunately, I don't think there's much you can do about it. It's possible that a different browser won't have that issue, though.
I'm going to close this issue because I don't think it's related to Video.js but if it is, feel free to elaborate and we can re-open if necessary.
