### ISSUE TITLE
Grunt too slow for a compilation tool.

### ISSUE THREAD

**Issue by gkf442573575** [videojs/video.js#4973]
Use grunt, too slow；
Will consider for a translation tool?

**Comment by thijstriemstra** [comment]
@gkf442573575 how slow is it? what's faster? do you have any stats?

**Comment by gkatsev** [comment]
Grunt is definitely not the fastest tool but it's working just fine and is serving our needs. I see no particular need to migrate away from it just because other tools are faster. Especially, since migration may introduce weird issues or we'll miss functionality in the migration. That said, new tools and things shouldn't be directly tied to grunt that way as we work on our build tools we can move more and more stuff out of grunt as we can.
