### ISSUE TITLE
Slow when skipping back and forth in a video

### ISSUE THREAD

**Issue by eliOcs** [videojs/video.js#4975]
## Description
We are using Amazon CloudFront to serve a video to a video.js player. You can reproduce it in the following jsbin: http://jsbin.com/toyequ/1
Seems like skipping to an already buffered starts the downloading of data again instead of using the buffer so it takes some time to load.

## Steps to reproduce

1. Open: http://jsbin.com/toyequ/1
2. Open the network tab of the developer console
2. Play de video
3. Skip to near the end of the video (around 1:05)
4. Let it play
5. Skip to near the beginning of the video (around 0:05)
6. Let it play

Repeat steps 3 to 6 and you will experience that sometimes the video is load instantly and sometimes it takes 2/3 seconds to load. You can also set the developer console to use a slower connection so the effects even more noticeable.

### Expected
Instant skipping between buffered parts.

### Actual
Sometimes there is some unexpected loading time and redownloading parts of video that have been buffered.

**Comment by gkatsev** [comment]
Unfortunately, this is just how browsers work and it isn't really anything that Video.js can change. When I disable caching with dev-tools, I can definitely see a lot fewer requests happening when seeking behind currentTime by about 5 to 10 seconds and forward within about 30 seconds. Beyond making a complicated thing using MSE and service-workers that cache data, I'm not really sure there's anything that can be done beyond asking the browsers to cache video for longer. Though, it's surprisingly tricky because if you have a high quality video, caching the entire thing would be a lot of data.

**Comment by eliOcs** [comment]
@gkatsev thanks for your insight, using a lower quality would then give better performance because more of the video could be buffered.

**Comment by gkatsev** [comment]
Probably, I think the amount of buffer cached is by bytes.
