### ISSUE TITLE
Unable to display native track elements for subtitles 

### ISSUE THREAD

**Issue by billy-coursera** [videojs/video.js#4978]
## Description
I am working on upgrading video.js from 5.8 to v6.6. Native video subtitles (via the <track> element) seem to work in Chrome in v5.8. These don't seem to be available in any browser but Safari in v6.6. These elements are needed for accessibility purposes.

I noticed https://github.com/videojs/video.js/blob/67634cf216fdde45cf52286c8ee1919319c7a25a/src/js/tech/tech.js#L135 and I couldn't determine how `nativeTextTracks` could be set to true given the `techOptions` here: https://github.com/videojs/video.js/blob/67634cf216fdde45cf52286c8ee1919319c7a25a/src/js/player.js#L852 I was using the HTML5 tech in this case.

## Steps to reproduce
Subtitles always revert to emulated mode on non Safari browsers.

### Expected
Please describe what you expected to see.
an option to include native text tracks - which would enable the track elements to appear in Chrome.

### Actual
Track elements do not appear in chrome.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with?
6.6
#### browsers
all (except Safari)

Additionally, I am confused about the reasoning from this commit message: https://github.com/videojs/video.js/commit/881cfcb346b588013768f538faf3d5f20ce42109. I'm not sure why only Safari should enable this feature by default if only Chrome does not support programmatic access.

**Comment by gkatsev** [comment]
Safari and iOS currently have the best implementations of the VTT spec and also provide FCC compliant and easily accessible ways for the viewer to customize the look of the captions. We turned on emulated captions for everything except Safari because most browsers just have a lot of weird edge cases that it wasn't worth supporting by default.
The `nativeTextTracks` option is set on the tech by name, so, if you're using the html5 option, it should be under an html5 property in the player.
```json
{
  "html5": {
    "nativeTextTracks": false
  }
}
```
Which should enable the native captions functionality.
