### ISSUE TITLE
How to show a video in a popup box after scrolling past it?

### ISSUE THREAD

**Issue by mawenmaywin** [videojs/video.js#4982]
## Description
Is there any way to make existing VideoJs videos appear in a popup box after I scroll past them?  I need the popup video to continue playing where the original video left off once I scroll past the original and if I scroll back to the original video then the popup should disappear. Can you guys point me in the right direction to achieve something like this?

**Comment by gkatsev** [comment]
A question like this is more suited for a forum like Stack Overflow because it is relatively generic. However, [this tutorial](https://webdesign.tutsplus.com/tutorials/how-to-create-a-sticky-floating-video-on-page-scroll--cms-28342) should help. It uses a youtube player, but can easily be modified for a Video.js player. In addition, they use scroll top but you might want to use an [IntersectionObserver](https://developers.google.com/web/updates/2016/04/intersectionobserver) instead because it's more performant.

Hope that points you in the right direction.
