### ISSUE TITLE
When changing sources video flashes black

### ISSUE THREAD

**Issue by redochrelabs** [videojs/video.js#4984]
## Description
When I change sources in videojs, my screen flashes black.

http://jsbin.com/cuwuzijeso/edit?html,output

Hard to see but it flashes black when I change sources. This is a bad example but for my use case it is obvious when it flashes. 

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Visit link
2. Play video
3. Change source.

### Expected
Please describe what you expected to see.

No black screen when I change sources. 

### Actual
Please describe what actually happened.
Black screen between switches. I would expect it to go to the first frame of the video or the poster.

### Error output
If there are any errors at all, please include them here.

## Additional Information
Please include any additional information necessary here. Including the following:
If you guys have any way around this it would be super helpful. Thanks!
#### videojs
what version of videojs does this occur with?
Current
#### browsers
what browser are affected? All
#### OSes
what platforms (operating systems and devices) are affected?
Mac/Win
### plugins
are any videojs plugins being used on the page? If so, please list them below.

**Comment by gesinger** [comment]
Hey @redochrelabs , I'm seeing the poster come up for the second video in the sample you provided (running Chrome on Mac)

**Comment by redochrelabs** [comment]
@gesinger  I have updated the jsbin and it is located here: http://jsbin.com/qoloxajovu/edit?html,output

You can now notice the black screen flash which occurs when we change sources.

**Comment by redochrelabs** [comment]
Hopefully that JSbin clears it up. If not, you could reproduce the thing I am seeing by watching the first video (.m3u8 supplied) and then changing the source of the video to the second .m3u8. You should see a quite obvious black screen between changes. What I am trying to do is avoid the black screen and just play the second video right away.

**Comment by gesinger** [comment]
I just took a brief look, but I think what's happening is that when you change the src, the old src clears, therefore the screen goes black. There's actually not a poster set, so the black will only go away once the first segment is loaded (and the first frame is shown). You can see the speed at which it goes away depends on your network connection and whether you enable caching (since it depends on the speed at which the first segment is downloaded and appended to the buffer).

If you set the "poster" attribute, then you can avoid the black screen and the poster will show instead of waiting for and showing the first frame.

**Comment by redochrelabs** [comment]
@gesinger Thank you for the fast response! Is there a way to wait for the video to be loaded before changing sources (and thus avoiding the black screen). if not no worries, I might be able to take a snapshot of the current video and set that as the poster

**Comment by gkatsev** [comment]
There isn't really a way to pre-load the next video using the same player. At best, you can try downloading the first segment yourself so that it'll be in cache before switching or using two players and swapping between the two. Using a poster might be the simplest solution, though.

Seems like this is more or less answered, so, I'm going to close this but we can continue the discussion if necessary.
