### ISSUE TITLE
(Android) HLS Support in Firefox 59

### ISSUE THREAD

**Issue by reinhart1010** [videojs/video.js#5000]
Starting from version 59, Firefox for Android will finally support the HTTP Live Streaming (HLS) technology, which is used in some Video.js players.

In this case, **Vidio.com**, one of the websites that uses the Video.js player, is still throwing an "Unsupported Browser" error in Firefox version 59 and above. If this is caused by the HLS detection that is available in Video.js, please fix this issue before Firefox 59 released later this month.

![Screenshot](https://webcompat.com/uploads/2017/12/5a1bfaa6-9e4a-4f54-a853-a1c8e236cac9-thumb.jpg)

References and Related Bugs:
webcompat/web-bugs#14318
webcompat/web-bugs#14523
https://bugzilla.mozilla.org/show_bug.cgi?id=941351

**Comment by gkatsev** [comment]
I don't think we do anything specifically to disable HLS on Firefox. If the native `canPlayType` reports support correctly, it should work. We do patch canPlayType on some browsers but Firefox isn't one of them :https://github.com/videojs/video.js/blob/f03ac5e9b57aa052dbeafb45388d398efcb5512d/src/js/tech/html5.js#L1051-L1072

However, I'll take a look and see if it's anything that Video.js can do something about.

**Comment by mister-ben** [comment]
We used to have the opposite bug - that `canPlayType` was causing us to erroneously detect native HLS support on Android Firefox. That was fixed ~18 months ago.

Video.js is not blocking native HLS playback on Firefox beta - see this example: http://output.jsbin.com/fanujudobo

HLS playback _should_ work on Android Firefox on that site even on versions <59 without native HLS since they are using videojs-contrib-hls which would be able to play HLS with MSE.  However no player is initialised and there is no request for the m3u8 playlist. There is a js error showing in the console in Android Firefox that doesn't apepar on other browsers. Most likely that error is utimately stopping the player intialisation and causing them to show the message that the browser is unsupported.

**Comment by reinhart1010** [comment]
Oh, good to know. I have reported the site owner about this issue, and with some analysis from @webcompat reports.

**Comment by gkatsev** [comment]
Thanks for the investigation @mister-ben.
@mister-ben could you tell if the error comes from videojs? or is this issue good to close?

**Comment by mister-ben** [comment]
I don't see anything actionable here, it's not a Video.js error.
