### ISSUE TITLE
Exited fullscreen because fullscreen element was removed from document.

### ISSUE THREAD

**Issue by nandishsadrani** [videojs/video.js#5036]
I'm having a trouble with full-screen toggle. 

I've got two videos on a page (https://yiddishevinkel.com/archives/9555) where the main video looks ok. But the video in sidebar, I'm not able to switch to full screen mode. When i hit the full-screen toggle, It switches to full screen and immediately gets exited from the full screen mode with "**Exited fullscreen because fullscreen element was removed from document.**" warning in Firefox console.

Note that, Issue persist with single instance of video on page and chrome as well.

**Comment by gkatsev** [comment]
Looks like this is a weird interaction between jquery.fullscreen plugin and Video.js. Video.js handles its own fullscreen but at the same time the jquery plugin seems to be registered with the sidebar video but then jquery.fullscreen detects that the page has gone fullscreen but breaks because it wasn't the one to take the element fullscreen and it doesn't have a reference to the element.

**Comment by nandishsadrani** [comment]
Yeah and the thing is that same thing seems to be working fine for the main video!

**Comment by nandishsadrani** [comment]
it's ok. but hope you check that a same player's working fine on other places of the site. 
Thanks!
