### ISSUE TITLE
Make video-js clickable 

### ISSUE THREAD

**Issue by brenogithub** [videojs/video.js#5043]
On desktop I can make video-js clickable by just adding a href to the container div. On mobile browser does not work. I tried to disable pointer-events on vjs-poster, but still can`t get onclick to work on mobile.

**Comment by gkatsev** [comment]
This probably doesn't work because on mobile devices we make the controls toggleable via tapping on the player and we call `preventDefault` on the touchend event which will prevent click events from happening which would cause the player to toggle playback state, which is the default behavior on desktops.
You probably want to make the anchor tag be positioned in front of the player and the same size and position of the player rather than wrapping the player. You can also do the same with a regular div element and listen to the click event.

**Comment by brenogithub** [comment]
Thank you so much. I believe is the way to go. By any change do you know any example code of successful player overlap?

**Comment by brenogithub** [comment]
Hi, it worked. Using z-index to overlap the div. Thank you.

**Comment by gkatsev** [comment]
Glad you got it working!
