### ISSUE TITLE
No Loading Spinner While Waiting for the Video to Play After Selecting a quality.

### ISSUE THREAD

**Issue by maryam-abdullah** [videojs/video.js#5044]
Hey there,

I'm using the videojs-contrib-quality-levels plugin, and whenever I select a quality and the video starts loading, the loading spinner doesn't appear in Chrome (desktop).

Thank you in advance.

**Comment by forbesjo** [comment]
Assuming you mean the videojs-contrib-quality-levels plugin along with videojs-contrib-hls the behavior you are describing is by design. Playback will continue on the the previous rendition until the playhead hits the new selected rendition in the buffer. The intent is to not disrupt playback for the viewer. 

We can implement a fast switch that clears the buffer in the hls plugin if users want that feature.

**Comment by maryam-abdullah** [comment]
Yes, I see.

Thanks for the clarification.

That happens as well in live broadcasting, right?
It requests chunks of the selected quality, so the chunk with previously selected quality will continue playing.
