### ISSUE TITLE
Japanese subtitle is broken in IE 11

### ISSUE THREAD

**Issue by zironycho** [videojs/video.js#5070]
## Description
Japanese subtitle is broken in IE 11
[used demo url](https://videojs.github.io/videojs-contrib-hls/)
![captured](https://github.com/zironycho/blog/raw/master/etc/videojs-jp-broken.png)

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. open [url](https://videojs.github.io/videojs-contrib-hls/) on IE 11.
2. change cc to Japanese

### Expected
display Japanese subtitle 

### Actual
broken subtitle text

### Error output
![captured](https://github.com/zironycho/blog/raw/master/etc/videojs-jp-broken.png)

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
It is just official demo page from `videojs-contrib-hls`
#### browsers
IE 11.
#### OSes
Windows 10 Home
### plugins
videojs-contrib-hls

**Comment by gkatsev** [comment]
That's really interesting. The first thing I noticed is that the VTT file wasn't being served with the correct mimetype. I tried changing the mimetype using the Charles proxy but it was still not doing the right thing. We should probably still change the mimetype.
Also, adding the file as a `<track>` element seems to work just fine.
This is probably related to us defaulting a "string decoder" when a utf8 TextDecoder isn't available: https://github.com/videojs/videojs-contrib-hls/blob/a3ecfd0b346c7a55f198e772dc07ffd4b212a7e2/src/vtt-segment-loader.js#L314-L323
It should work fine if a TextDecoder polyfill is included on the page, we don't ship one by default because it often isn't needed and it's a pretty large piece of code otherwise.

**Comment by zironycho** [comment]
@gkatsev :heart: Thank you for response and answer.
I will try that you suggested !!

**Comment by gkatsev** [comment]
After investigating it some more, we think this may be because we're downloading the text as arraybuffers in VHS/hls. @forbesjo is going to look into if we can just download it as just text, which may improve this behavior.

**Comment by gkatsev** [comment]
This is being worked on in VHS: https://github.com/videojs/http-streaming/pull/105

**Comment by forbesjo** [comment]
The fix has been deployed in VHS, it should be picked up by video.js 7 some time soon

**Comment by gkatsev** [comment]
This is fixed in @vidoejs/http-streaming 1.2.1 and it's in Video.js as of commit 7b6aa5c03d0e973cbe4e665ce5e58397a09e9ba3, it'll be in the next release.
