### ISSUE TITLE
Unable to override font-path

### ISSUE THREAD

**Issue by nitin-jotwani** [videojs/video.js#5087]
I'm using bootstrap sass and overriding variable `$icon-font-path` in that.

Now, videojs also uses the same variable name. How should I resolve this then?

**Comment by gkatsev** [comment]
How are you including the css file? Also, the way we define the path is via [sass's variable defaults feature](https://sass-lang.com/documentation/file.SASS_REFERENCE.html#variable_defaults_default), meaning if you define the variable before importing the video.js sass files, the path variable will be the original one you set rather than the one that Video.js sets.

**Comment by colingreene28** [comment]
I was facing the same issue. @gkatsev just to give you a bit more context, I fixed it by doing something like this:

```
$icon-font-path: "~bootstrap-sass/assets/fonts/bootstrap/";
@import "~bootstrap-sass/assets/stylesheets/bootstrap";
...
$icon-font-path: "~videojs-font/fonts/";            
@import "~video.js/src/css/vjs";
```

I do feel like this could have unintended consequences and might be better if the variable was named something like `$videojs-icon-font-path` ?

**Comment by gkatsev** [comment]
Oh, I see. Thanks for giving more info @colingreene28. In Video.js 7 we removed the $icon-font-path as all the font stuff is now fully embedded as we dropped support for IE8.

**Comment by colingreene28** [comment]
Ah! Well that should give me more of a push to upgrade from 5.x. Appreciate the swift response.
