### ISSUE TITLE
Two controls bar appear

### ISSUE THREAD

**Issue by huzhenjie** [videojs/video.js#5117]
## Description
Can U show me how to disable the sys controls, there are two controls bar appear. And I can't find any options about this.

## Steps to reproduce

Here is My Code
```
<!DOCTYPE html>
<html class="U_html_bg U_color_a">
<head>
    <meta charset="utf-8" />
    <title>video test</title>
    <meta name="robots" content="all" />
    <meta name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no,minimal-ui">
    <meta name="format-detection" content="telephone=no" />
</head>
<body>
<link href="//vjs.zencdn.net/6.7/video-js.min.css" rel="stylesheet">
<script src="//vjs.zencdn.net/6.7/video.min.js"></script>
<style type="text/css">
  .video-js .vjs-tech {
    position: inherit;
  }
</style>

<div style="height: 180px; text-align: center;">
  <video
      id="my-player"
      class="video-js"
      controls
      preload="auto"
      style="background-color:#000;width: auto;height:100%; max-width: 100%" 
      poster="//vjs.zencdn.net/v/oceans.png"
      data-setup='{}'>
    <source src="http://any.host.com/my_video.mp4"></source>
  </video>
</div>
<script type="text/javascript">
</script>
</body>
</html>
```

### Expected

Here is in the `webview` of `wechat`:

![http://biuugames.huya.com/screenshot-1524475361681.jpg](http://biuugames.huya.com/screenshot-1524475361681.jpg)

Here is in the browser of `MIUI`

![http://biuugames.huya.com/screenshot-1524475331755.jpg](http://biuugames.huya.com/screenshot-1524475331755.jpg)

### Actual

Two controls bar appear

### Error output
*nothing here*

#### videojs
`6.7`
#### browsers
Browser in `MIUI`

#### OSes
`MIUI 8.6.9.8 dev` `Android 5.0.2`

### plugins
*nothing here*

**Comment by mister-ben** [comment]
It sounds like those browsers don't support removing the native controls programmatically. The video element starts out with controls because of the `controls` attribute. We disable the native controls when we add Video.js's controls. 

A couple of things you might try:

Remove the `controls` attribute from the player, and turn on Video.js's controls separately with `data-setup='{"controls": true}'`. Perhaps that browser will allow a video element to be created with no native controls, even if it won't allow them to be disabled once there. I'm doubtful that this will work - in your screenshot the native element is overlaid on top of the Video.js controls rather than behind it, so it looks like the media playback is separate from the browser. 

If that doesn't work, you may have to disable Video.js's controls, and stick with the native controls with `data-setup='{"nativeControlsForTouch": true}'`.

**Comment by huzhenjie** [comment]
@mister-ben 

After I removed the `controls` attribute from the player, and turnend on Video.js's controls separately with `data-setup='{"controls": true}'`. Not work...

And disable Video.js's controls, stick with the native controls with `data-setup='{"nativeControlsForTouch": true}`. 

In `Wechat`.

![http://biuugames.huya.com/28164dc672ea9ef2b2b320b810604ccd.png](http://biuugames.huya.com/28164dc672ea9ef2b2b320b810604ccd.png)

In browser of `MIUI`.

![http://biuugames.huya.com/a93d296ccecb3496331c3e99ab9fd8f5.png](http://biuugames.huya.com/a93d296ccecb3496331c3e99ab9fd8f5.png)

It seems works in `Wechat`, but not for browser of `MIUI`. Here is my code.

```
  <video
      id="my-player"
      class="video-js"
      preload="auto"
      style="background-color:#000; width: auto;height:100%; max-width: 100%;" 
      poster="//vjs.zencdn.net/v/oceans.png"
      data-setup='{"nativeControlsForTouch": true}'>
    <source src="https://ugcbsy.qq.com/x0353k31dr6.m701.mp4?sdtfrom=v1103&guid=41d99c4d8152d90c8e658f2a0d02dbf5&vkey=CBAA7BB2139A66FDAE80F485724EAD709DB2FB575F2649B043445838302650924A82712259C61FA734013382DDCEC4AAE8590F8AD7ABD5CD7A543510D549EEFDDDE58381E91DAB314180573079C4ECBFBD837ACBC958D6E1CB5A6FB7A596B47C20EC964B5203340C582FBF0A2E13488EE4B6FE3B881F04C8&platform=2"></source>
  </video>
```
