### ISSUE TITLE
Error when file is unavailable (even temporarily)

### ISSUE THREAD

**Issue by Akxe** [videojs/video.js#5178]
## Description
During video streaming of video the error event won't give information, if the video file is unavailable (responding with any of 4xx - 5xx errors).

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Go to any videojs example. Ex. [advanced](https://videojs.com/advanced/)
2. Start a video
3. Turn off internet (ex. switch to offline)
4. Error should be coming in, but none are.

### Expected
I would see some errors.

### Actual
Error should be coming in, but none are. Only once it will show the error message, it will send the error, but it is bit too late.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
6.6.3

**Comment by gkatsev** [comment]
This is a slightly tricky issue because I believe the native video element doesn't handle it with files like mp4s. And just throwing out an error when the network connection drops isn't a good user experience because it's possible that the connection will be back before you finish playing through your buffer.
In [videojs-errors](https://github.com/brightcove/videojs-errors/), we've added a TIMEOUT error, which is when the player just sits there and doesn't do anything for a while. I'm not sure there's really a better way of handling this issue more gracefully.
