### ISSUE TITLE
Failed to execute 'appendBuffer' on 'SourceBuffer'

### ISSUE THREAD

**Issue by genelamarellis** [videojs/video.js#5184]
## Description
We are using VideoJS to create and HTML5 Web App to be used on SmartTVs. We are noticing that some of the TVs are reporting the following error:
Failed to execute 'appendBuffer' on 'SourceBuffer': The SourceBuffer is full and cannot free space to append additional buffers. This does not happen in a computer web browser. Just on certain models of SmartTVs. Any suggestions? Thank you

## Additional Information
Please include any additional information necessary here. Including the following:
VideoJS = 6.9.0
Video HLS Plugin
Google IMA Plugin

**Comment by genelamarellis** [comment]
Nope!

**Comment by gkatsev** [comment]
Awesome, thanks for getting back to us. Hopefully, we'll be able to ship that fix soon too.

**Comment by Sivitas** [comment]
We're seeing the same issues on Vizio's SmartCast TV platforms. Is this code anticipated to be released anytime soon? I see there hasn't been any updates on that ticket in the last month

We're also using VideoJS v7.2.3 now and since it has support for hls impliciltly, we aren't directly using videojs-contrib-hls anymore, though I assume the lib is just internally referencing it

**Comment by locpd** [comment]
I still got this issue on Samsung UN43RU7100FXZA. On other Smart TVs, mobile and PC browsers there's no problem.
