### ISSUE TITLE
Uglify throwing an error with 7.0.0

### ISSUE THREAD

**Issue by jcbreel** [videojs/video.js#5186]
## Description
I'm using Uglify with Webpack and if I use v7.0.0 I get the following error when trying to uglify my code:

`ERROR in 0.js from UglifyJs
Unexpected token: punc (,) [0.js:45921,41]`

Anyone experiencing this?

**Comment by nypinstripes** [comment]
Yes @jcbreel I started experiencing this last night also when getting ready to deploy & needed to downgrade back to 6.10.0. Everything looked ok locally in my dev build, but when i ran it through my prod webpack-html minifying & uglifyjs-webpack-plugin pipeline (with relatively minimal but tested config on webpack 3.11.0),  i couldn't get past this issue and one other one which i believe was related to use of object assignments in default values for function args in ES6 like: 

```
const playerFunction = ({ attributes: stuff }) =>
```

Neglected to save the output before downgrading, can try reproducing later.

I'd suppose this is due to uglifyjs-webpack-plugin not capable of parsing es2015/es6 features, but even after transforming the core playerjs with babel it doesnt seem to be succeeding. I'm a little out-of-my-depth going much further into it, perhaps i'm required to do the webpack 4 upgrade i've been avoiding lol, not sure though. Maybe @gkatsev or @mjneil can help shed light.

**Comment by gkatsev** [comment]
We do use ES6 syntax in source code but we use babel to compile it all down to es5 code. We do have a pkg.module file pointing at an es modules code that webpack potentially is using, but webpack should know how to handle es modules. Maybe something unexpected snuck through?

**Comment by nypinstripes** [comment]
@gkatsev thanks for the quick response, here's the generic error uglify spits out for me, after setting mangle to false & compress: beautify to true.
```
    ERROR in player.js from UglifyJs
    Invalid assignment [player.js:11289,77]
```

this is my uglify config:
```
UglifyJSPlugin({
          cache: false,
          parallel: true,
          sourceMap: true,
          uglifyOptions: {
            compress: {
              join_vars: true,
              passes: 3,
              reduce_vars: true
            },
            mangle: false,
            output: {
              beautify: true,
              indent_level: 2
            },
            warnings: false
          }
```

the line in the output looks like:
![screen shot 2018-05-17 at 4 04 54 pm](https://user-images.githubusercontent.com/1851296/40201092-16c22c3e-59ec-11e8-9377-2bc2ae186abb.png)

**Comment by nypinstripes** [comment]
which seems fine but perhaps the illegal assignment is on the line above,
```
var __WEBPACK_IMPORTED_MODULE_0_url_toolkit__ = __webpack_require__(7), __WEBPACK_IMPORTED_MODULE_0_url_toolkit___default = __webpack_require__.n(__WEBPACK_IMPORTED_MODULE_0_url_toolkit__), __WEBPACK_IMPORTED_MODULE_1_global_window__ = __webpack_require__(3), __WEBPACK_IMPORTED_MODULE_1_global_window___default = __webpack_require__.n(__WEBPACK_IMPORTED_MODULE_1_global_window__);```

**Comment by nypinstripes** [comment]
@gkatsev strange but it seems like everything up to that line is transpiled to ES5 but everything afterwards is ES6. I've also just upgraded to 7.0.1.

**Comment by gkatsev** [comment]
Oh, looks like our mpd-parser in VHS isn't using babel for the es build and that's probably what's being used. I'll look into it, nice catch @nypinstripes

**Comment by nypinstripes** [comment]
np, @gkatsev after doing the webpack 4.8.3 upgrade, everything's building smoothly in UglifyJS webpack plugin with 7.0.1.

**Comment by gkatsev** [comment]
webpack 4 uses uglify-es, so, it can handle minifying es6 code. Going to work on fixing it on our end also.

**Comment by gkatsev** [comment]
Both have been released, going to update vjs to latest VHS which should fix this.

**Comment by jcbreel** [comment]
So should I just update to latest? What version exactly? Thanks for looking at this guys.
