### ISSUE TITLE
remove video url

### ISSUE THREAD

**Issue by damianoporta** [videojs/video.js#5195]
Hello,
can i remove the link for the download from the menu?

**Comment by magikstm** [comment]
Which link exactly?

What is your use case?

**Comment by damianoporta** [comment]
hi @magikstm 
i know i cannot prevent user to download my videos, if anyone looks at the code will see the url, but i am referring to the "copy" on the menu (right click on mouse).

**Comment by gkatsev** [comment]
There is no way to remove that as that comes directly from the browser. The best you can do without looking at other technology is disable the right click menu.
If you want to go further, you can look at stuff like HLS or DASH, which I believe won't have a download link because of the way the format works, and that we play it back using MSE.
And you can even go further and investigate using DRM. Though, hopefully, just using HLS or disabling the right click menu would be enough for you.
