### ISSUE TITLE
[Problem] video playback changes height of the player

### ISSUE THREAD

**Issue by PPastene** [videojs/video.js#5215]
## Description
I'm using a streaming service to host and play videos  via HLS to my website using VideoJS. Since the website uses Bootstrap for responsive design in videojs i'm using the vjs-fluid class to make responsive the player too, but there are some videos on the streaming server that has different resolution. From width the video fits very well but if the video excess the height the player aligns to match with the videos height breaking the page layout. If im not using the vjs-fluid class the player remains ok but it doesn't adapt to mobile or another screen resolution

Here are 2 images comparing when the player plays the video on the correct dimensions and then when put another video with the resolution mismatch
https://imgur.com/a/U5gV4nu

**Comment by gkatsev** [comment]
The player does resize when the video loads based on the video width and video height but in fluid mode i'd expect it to only update the intrinsic ratios for the fluid mode. Do you know what the two resolutions of the videos are?
Also, something to look into is the `vjs-fill` class instead of `vjs-fluid`. `vjs-fill` tells Video.js to fill out it's container, then, you just need to make sure that your container is sized properly for your layout.

**Comment by PPastene** [comment]
Well, i've found the cause of this. The problem is not the video or the player resolution, it's the aspect rtio of the video. Most of the videos played on the website are 16:9, and when changes to a video for example 4:3 that happends.

Never hear abour vjs-fill, when i needed to find a solution for a responsive player the first thing that i came up was vjs-fluid. It would be a nice feature if you can "force" the aspect ratio of the player so the videos must adapt to the player

**Comment by gkatsev** [comment]
Yup, vjs-fill isn't very well documented.
Have you been able to fix your issue? You can also set the aspect ratio for the player with the `aspectRatio` option or force it to be 16-9 with `vjs-16-9` or `vjs-4-3` classes.
