### ISSUE TITLE
How to use videojs to play HLS/FLV files offline (local hard disk)

### ISSUE THREAD

**Issue by doer2017** [videojs/video.js#5217]
I tried to use videojs to play HLS/FLV files on my local disk, but it doesn't work. 
I don't want to start a local HTTP server to play, that doesn't meet my needs. 
If videojs can't support this feature, how can I modify the code to support it? or which part of the code can be modified to support ? or is there any other good way to do it ?
Please give me some advice, Thank you very much.

**Comment by gkatsev** [comment]
Unfortunately, the answer is that you cant. To play back HLS we make requests to download the segments and these requests are not allowed to be made to files if the page has been opened directly (i.e., via `file:` rather than via `http:`). The same goes for flash, if your browser even runs flash at all anymore, it definitely isn't allowed to run properly via `file:`.

**Comment by ParfectShot** [comment]
Hey, I am building a screen recordder app on electronjs. I record it in HLS format. The chunks are stored locally and are uploaded simultaneously. In my app I am building a video preview from the chunks stored locally. I have the path for `playlist.m3u8` file. I load the videopreview using the path of that file as `src` in videojs options.

I've specified the correct type ( `application/x-mpegURL` ) also. Still getting the error - `VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this media`.

Videojs version - 7.11.4
Chrome version - 87.0.4280.141 (Official Build) (64-bit)

**Comment by gkatsev** [comment]
Unfortunately, it isn't possible, you must have a local file server and interface the HLS through that.
