### ISSUE TITLE
How to player video and audio at same time?

### ISSUE THREAD

**Issue by maple3142** [videojs/video.js#5259]
## Description
I have a muted video and an corresponding audio.
They have same length, so how can I play them like one video?
I use html5 audio api to `play`,`pause`,`timeupdate`... when videojs events fired.
But sometimes they cannot correctly sync.
Is there any methods to do that in videojs? Or I have to manually sync it with audio api?

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Open fiddle: https://jsfiddle.net/3fc6mwt1/37/
2. Click `Run`

### Expected
When I jump to specific time, audio can correctly sync with video.

### Actual
But The audio keep playing when video takes some time to load. 

### Error output
No

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with? 7.0.3
#### browsers
what browser are affected? Chromium 66.0.3359.181
#### OSes
what platforms (operating systems and devices) are affected? Win10
### plugins
are any videojs plugins being used on the page? If so, please list them below.

**Comment by gkatsev** [comment]
I'm not sure that it's really recommended to have an audio element and a video element mostly due to sync problems but also, I think some platforms limit the amount of audio and video elements that can play at the same time.

Is there a particular reason you have the audio separate from the video?

What you probably want is to look at Media Source Extensions and load in the video and audio data into a single video element and have the browser internals keep the two in sync.

Also, try using requestAnimationFrame (rAF) rather than `timeupdate` events to keep the two in sync. `timeupdate` can happen quite slowly to do a reliable job of syncing where rAF happens quite often.

**Comment by OwenEdwards** [comment]
Synchronizing an audio track with a video in a browser is a surprisingly tricky thing to do. @brothercake did some interesting work on it to implement audio description (see https://www.sitepoint.com/accessible-audio-descriptions-for-html5-video/), but the `mediacontroller` concept in JavaScript was never actually implemented.

The easiest way to implement what you're trying to do is actually to use an HLS mux with both the video and audio track in it; you'll find lots of information online about how to do that.

**Comment by maple3142** [comment]
It seems like it is not easy to do this.
Besides, it there any way to know is video loaded?
For example, video may have not been loaded when I jump to `1:30`, so I have to pause the audio.

**Comment by gkatsev** [comment]
You can use seek and seeked events to know when there are jumps or just use a rAF to check the time of the main video. In Video.js, middleware provide a good way to know exact seeking times before they happen, you could potentially use middleware to make a mediacontroller thing better.

**Comment by gkatsev** [comment]
I'm going to close this issue because it isn't something that would require changes in Video.js itself. However, we can definitely continue the conversation in here, you can also drop by our slack (http://slack.videojs.com) for a more real-time chat.

**Comment by brothercake** [comment]
Yeah you have to track timeupdate and seeking etc as I talked about in that article, but you also have to consider loading states of the video (so the audio doesn't keep playing if the video is buffering). You also have to not re-synchronise too often, because changing the time-point causes Safari to mute briefly and sometimes causes audio artefacts in Firefox, so the syncing needs to allow a certain amount of leeway before it kicks in to prevent that happening to often.

It seems a bit perverse that two digital media sources should go out of time, cos they're not physical tape machines with mechanical variances! But they do have variable latency because of how CPUs schedule threads, hence the playback can go out of sync.

**Comment by gkatsev** [comment]
Thanks for chiming in @brothercake!

**Comment by YaBoiBreezy** [comment]
I had the same issue, I think I made a really good fix
function syncTime(){
	var a=audPlayer.currentTime();
	var v=vidPlayer.currentTime();
	//if(Math.abs(a-v)>0.1){console.log(a+' '+v)}
	if((a-v)>0.1){audPlayer.playbackRate(vidPlayer.playbackRate()-0.1)}
	else if((a-v)<-0.1){audPlayer.playbackRate(vidPlayer.playbackRate()+0.1)}
	else{audPlayer.playbackRate(vidPlayer.playbackRate())}
}
window.setInterval(syncTime, 25);

my general code applies all position/speed/pause updates to both the video and audio objects, and resyncs them when pausing/updating position, but that's no guarantee of stuff and to apply it you have to actually interact with the video.
this little bit handles drift and desyncs automatically by saying "if audio is more than 0.1 seconds off from the video, speed it up (or slow it down) by 0.1x until they are within margins again".
It works really well for me, uncomment the console.log to see it detect desyncs and then fix them.
