### ISSUE TITLE
lastet version support rtmp

### ISSUE THREAD

**Issue by liuyuqingenglish** [videojs/video.js#5272]
Video.js latest realease version does not support the playback of rtmp video streaming, hope the author reply

**Comment by magikstm** [comment]
This section of the FAQ may be useful:
https://github.com/videojs/video.js/blob/master/docs/guides/faq.md#q-how-can-i-play-rtmp-video-in-videojs

**Comment by gkatsev** [comment]
Thanks @magikstm. We also have that on our site here http://docs.videojs.com/tutorial-faq.html#q-how-can-i-play-rtmp-video-in-videojs

In v6, we moved flash out of core due to flash being less important on the web. However, we kept it around in the [videojs-flash](/videojs/videojs-flash) package. Including that package is required to be able to play back flv and RTMP in Video.js.

Hope that helps.
