### ISSUE TITLE
Fullscreen button should be removed or greyed out when fullscreen is unavailable

### ISSUE THREAD

**Issue by DoomTay** [videojs/video.js#5290]
## Description
See title.

Example use case: an iframe that doesn't have the allowfullscreen attribute. The [given starter template](http://jsbin.com/axedog/edit?html,output) is such an example

### Expected
Fullscreen button should be removed or greyed out

### Actual
Fullscreen button appears functional, but clicking on it does nothing. It takes looking at the console to see that it's because the containing iframe doesn't have the allowfullscreen attribute

### Error output
If there are any errors at all, please include them here.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
7.0.5
#### browsers
Firefox 60.0.2
#### OSes
Windows 10
### plugins
None

**Comment by gkatsev** [comment]
Looks like we can check `document.fullscreenEnabled` and the vendor prefixed versions of that to know whether fullscreen is enabled or not.
Looks like we already get the correct prefix in our [fullscreen-api](https://github.com/videojs/video.js/blob/master/src/js/fullscreen-api.js) file ([sample usage](https://github.com/videojs/video.js/blob/master/src/js/player.js#L2381), so, we can just use that either in the [fullscreen-toggle file](https://github.com/videojs/video.js/blob/master/src/js/control-bar/fullscreen-toggle.js) to disable it and grey it out (making sure to apply correct aria labels) or just removing it from the default components. I'm leaning towards disabling it rather than removing the button.

Would you be interested in making the change?

**Comment by DoomTay** [comment]
Sure, sounds pretty simple
