### ISSUE TITLE
Cannot enable first text track on DASH content that has multiple text tracks

### ISSUE THREAD

**Issue by sevagsim** [videojs/video.js#5304]
Cannot enable first caption track on DASH content with multiple text tracks

## Steps to reproduce
1.  Visit http://videojs.github.io/videojs-contrib-dash/
2.  Load https://d2xk91j6i9s5cq.cloudfront.net/test/multi_subtitle_dash/02/presentation-static.mpd
3.  Select the first `en` text track

### Expected
Expect captions to show at 8 or 9 second mark.

### Actual
No captions display

### Error output
If there are any errors at all, please include them here.

## Additional Information
Please include any additional information necessary here. Including the following:
Tested using Chrome browser.

Note: No issues found using dash.js reference player here http://reference.dashif.org/dash.js/v2.8.0/samples/dash-if-reference-player/index.html

**Comment by ldayananda** [comment]
I looked into this and it looks like there's a few things happening:

- we should be passing the track.kind in to dash.js (I'll make a quick PR to fix this)
- Looks like that first English track is actually inband captions. I ran a few of the segments through ccextractor(https://github.com/CCExtractor/ccextractor) and it looks like the captions in that track are not in fact what the dash.js player is showing. So I think you'll want to open an issue against the https://github.com/Dash-Industry-Forum/dash.js/ repo since it seems dash.js isn't handling the captions in that source correctly.

**Comment by ldayananda** [comment]
Created https://github.com/videojs/videojs-contrib-dash/pull/263 to handle the first issue.

**Comment by ldayananda** [comment]
After more discussion and investigation, it appears that dash.js does not add captions to tracks that are not enabled:

https://github.com/Dash-Industry-Forum/dash.js/blob/a9e4ba9bfeeea95385c6e4a4a4b6b47dfed51511/src/streaming/text/TextSourceBuffer.js#L413

This does not seem right to me since the subtitles/captions could be requested at any point and you would want to add the captions to a text track whether it is shown or not

**Comment by sevagsim** [comment]
Created https://github.com/Dash-Industry-Forum/dash.js/issues/2696

**Comment by gkatsev** [comment]
Given that this is a dash.js bug and there's already an issue there to track this, I'm going to close this.
If, after the dash.js is fully fixed and there are still issues here, feel free to open a new issue.

Thanks.
