### ISSUE TITLE
hello, iwant need help

### ISSUE THREAD

**Issue by ZhangDewei** [videojs/video.js#5310]
hello, i use videojs with videojs-contrib-hls and flv.js to play live stream. but my boss think videojs to heavy. So he call me to decompose videojs, remove css style. but i don't know how to do …… so please help me, thanks ( i'm chinese, english to fail, so sorry)

**Comment by magikstm** [comment]
What web server are you using? (Apache, NGINX, IIS?)

I suggest using: HTTP/2, GZIP compression as well as the minified version if you're not already

You wouldn't save a lot of KBs by decomposing or removing css styles.

**Comment by gkatsev** [comment]
The Video.js CSS is a really small piece of the player itself, about 40K compared to around 300K of javascript. These numbers don't include gzipping.

Some of the biggest features of Video.js are the control bar, caption and subtitles support, and VHS. As part of the [Video.js roadmap](https://github.com/videojs/video.js/pull/5274) we're going to be breaking things up so that unneeded features can easily be excluded by users. However, that may take a while.

As a workaround, you could try building a custom version of Video.js yourself that you don't need.

Also, compared to other players that are available and the features available, Video.js actually comes in at a good size.

Other things to look into is brotli compression if your users support it as it'll make things smaller compared to gzip.

**Comment by gkatsev** [comment]
Closing.

If there are more specific questions, we can help out in the comments of the closed issue or on [slack](http://slack.videojs.com)
