### ISSUE TITLE
Multiple sound overlays

### ISSUE THREAD

**Issue by hao15239129517** [videojs/video.js#5318]
There are multiple sound overlay issues on some people's computers. The browser is a 360 secure browser.

**Comment by hao15239129517** [comment]
@ldayananda We uploaded MP4 video files through the background management system。Sounds are normal in both chrome and edge browsers, but the chrome kernel using 360 Secure Browser will have multiple sound overlays in the same video. When paused, the sound is still playing.The videojs version is 6.7.4.

**Comment by ldayananda** [comment]
Are you able to provide a reduced test case to help us debug or at least a video source? Our [issue template](https://github.com/videojs/video.js/blob/master/.github/ISSUE_TEMPLATE.md) has a JSbin you can start from.

**Comment by ldayananda** [comment]
Are you able to reproduce this issue on Chrome, IE, Edge, Firefox or Safari?

**Comment by hao15239129517** [comment]
@ldayananda Sorry.On Chrome, IE, Edge, Firefox or Safari is normal.On some people's computers is not normal using 360 Secure Browser.The 360 Secure Browser download url is:https://browser.360.cn/se/

**Comment by ldayananda** [comment]
Thanks for trying this out on those browsers! Unfortunately, we don't officially support 360 Secure browser and since you don't observe any issues on major browsers it is unlikely that Video.js is the cause of the issue. If you are able to debug the issue and find that you can reproduce a bug with the Video.js player on one of those 5 browsers, feel free to open a new issue with an example source that shows the bug.
