### ISSUE TITLE
How can i disable play and pause event when seeked event is fire?

### ISSUE THREAD

**Issue by Bluebang** [videojs/video.js#5338]
How can i disable play and pause event when seeked event is fire?

**Comment by gkatsev** [comment]
Unfortunately, until we're able to refactor how seeking behavior functions in Video.js, there is no way of doing that. You can check if the player is seeking by looking at `player.seeking()`.

What's your usecase, maybe we can help out some more?

**Comment by Bluebang** [comment]
I did some business that save the user's playback record or other information the start and pause events，when the `seeked()` also triggers other events, And their triggers are unordered ，It will bring me a lot of trouble.

**Comment by spodlecki** [comment]
@Bluebang The answer here is to write a plugin and trigger your own events that you'd be tracking. Here is a short example of how you'd accomplish (just the logic / proof of concept).

https://codepen.io/spodlecki/pen/ZjZjJK

I do something similar, because we do event tracking, and I don't want to count plays 100 times as our users seek through the videos. I have similar logic that does the same for buffering events. I can't say its 100% fool-proof, but it works, and has been working for a while for me.

Let me know if this helps.
