### ISSUE TITLE
Caption Button not appearing on Android devices

### ISSUE THREAD

**Issue by mcrayshill** [videojs/video.js#5382]
## Description
Tested CEA-608 caption playback across Windows/Mac/iOS/Android and everything works well except Android devices.  I tried different versions of Chrome and FireFox within browerstack on different devices and I cannot get the caption button to appear with videojs 7.1.0. 

[See this test page for playback](http://pages.suddenlink.net/wowzamac/videojs.html)

I have a file on loop as a live source with CEA-608 captions being presented to the player. 

## Steps to reproduce
Simply playback the test page above on different devices/browsers.  Android has failed consistently. 

### Expected
There should be the CC Button showing in the player. 

### Actual
The CC button is not appearing when captions are present in the stream.

### Error output
No errors present

**Comment by alex-barstow** [comment]
Your player is setup to use native HLS on Android and iOS. While Safari supports 608 captions with native HLS, Chrome on Android apparently does not, which is why you don't see the caption button. If you want your 608 captions to work on Android, you'll have to override native HLS:

```js
var player = videojs('vid1', {
  html5: {
    hls: {
      overrideNative: true
    }
  }
});
```

Initializing the player this way should solve your problem.

**Comment by gesinger** [comment]
Please let us know if @alex-barstow 's suggestion doesn't work for you, and thanks!
