### ISSUE TITLE
How to remove (hide or replace) the control text 'Close Modal Dialog'?

### ISSUE THREAD

**Issue by coddok** [videojs/video.js#5433]
Video.js 7.1.0

How to remove (hide or replace) the control text 'Close Modal Dialog'?
E.g. for nothing to be displayed when mouse is over the close button in modal window.

**Comment by misteroneill** [comment]
The title text exists as an accessibility measure, especially for non-sighted users. We strongly advise against removing it and will not be making any such changes to Video.js.

If you insist on making your video player harder to use for the disabled, you can achieve the effect you're looking for via DOM method(s) like `removeAttribute` and by hooking into the various modal dialog events that Video.js fires.

**Comment by VasiliyRusin** [comment]
@misteroneill, I really do not want to be rude, but I suppose that "non-sighted users" is not the most part of people who use video players. I strongly believe that a11y is really important but it would be greate if it will move to additional module or plugin.

**Comment by OwenEdwards** [comment]
@VasiliyRusin certainly "non-sighted users" are not the largest group of users of video players; nor are deaf/hard-of-hearing, but most people understand the need for Captions, and wouldn't disable that feature to achieve a small tweak in how the UI of the player looks for other users. We will continue to build accessibility (including for blind and low-vision users) into the **core of video.js**, not into an additional module or plugin, so that accessibility is enabled by default. If you chose to disable it, you can do so.

Having said that, @coddok can remove the `title` attribute on the `CloseButton` component of the `ModalDialog`. It's probably easiest to piggyback off the `@event ModalDialog#modalopen` (https://github.com/videojs/video.js/blob/master/src/js/modal-dialog.js#L206-L213). This is not the same as removing the "control text" (https://github.com/videojs/video.js/blob/master/src/js/clickable-component.js#L110-L135), so fortunately, in this case, it will not break the accessibility of the player.

**Comment by OwenEdwards** [comment]
A timely announcement from DRA Legal: [Hulu Becomes Latest Streaming Service to Commit to Accessibility for Blind Users (October 17, 2018)](https://dralegal.org/press/hulu-becomes-latest-streaming-service-to-commit-to-accessibility-for-blind-users/)
