### ISSUE TITLE
Play Promise never resolves in FireFox and Microsoft Edge

### ISSUE THREAD

**Issue by ishish** [videojs/video.js#5441]
We have a product that lets you click thumbnails to switch videos on the video player. We've upgraded to video.js 6.12.1 and are finding that Firefox/Microsoft Edge sometimes stalls on videos after we switch.

It seems that the video play() promise doesn't always resolve or reject. Here is a code snippet to show how we handle autoplay situations per the article published on the video js blog.

```
var self = this;

this.player.ready(function() {
	var promise = self.player.play();
	if (promise !== undefined) {
	    promise.then(function () {
		// Autoplay started!
	    }).catch(function (error) {
		// Autoplay was prevented 
			//... Code that shows big play button
	    });
	}
	else {
        	//... Code that shows big play button   		
	}
    }
);
```

In Chrome and Safari this works great because the promise always gets resolved or rejected. However in Firefox (Quantum v62.0)/Microsoft Edge(17) at times the promise just never resolves after being in a pending state. 

The only solution I've found is to put a javascript timeout and if the promise doesn't resolve then just show the play button. This isn't ideal, and is actually worse behavior than what I'm experiencing in video.js 5.

By the way our videos are HLS streams so we are using the videojs-contrib-hls v5.14.1.

**Comment by ishish** [comment]
For now I timeout if the promise doesn't returns. If the timeout happens I call player.play() and the video plays. Not the best solution in the world but it works. Would love to know if there is another solution out there or a timeout mechanism will be built into video.js.

**Comment by Yalhu** [comment]
Promise of player-videojs and video-html  vary on different browsers or situation. I customized code from different browser.

**Comment by JoshuaCWebDeveloper** [comment]
I do _not_ experience this issue on Edge `96.0.1054.62`; however, I _do_ experience this issue on Firefox `95.0`. When this issue happens, I can call `play()` on the `HTMLVideoElement` directly and the promise will ~immediately reject, so it is only video.js that returns a non-resolving promise. I've observed this using `video.js@7.14.3`.

Either this issue should be re-opened or a new issue should be created (happy to do that) since it still seems to be happening.

As a workaround, I'm currently implementing a timeout in the case that the promise never resolves:
```js
await Promise.race([
    player.play(),
    new Promise((_, reject) => {
        setTimeout(() => reject('E_TIMEOUT'), 1000)
    }),
])
```
