### ISSUE TITLE
Safari on iOS (iPads/iPhones) do not skip & play .currentTime() correctly. 

### ISSUE THREAD

**Issue by zoblue** [videojs/video.js#5467]
Apologies if this was found before, I couldn't find this issue nor a fix via search. 

## Description
Links were added to let users skip to certain points in the video. In Safari on iOS devices (iPad/iPhone) the first link will only play the video but it will not skip ahead to the correct time code. It's only when a user clicks again will the video skip ahead as intended. 

## Steps to reproduce
1: Run code pen example in Safari on iPad or iPhone running current iOS version https://codepen.io/zoblue/full/QZbzKW/
2: Tap either of the links under the video to skip to a certain time code and play the video from there
3: Tap either the same or the other link to skip to a second time code

## Results
The first link tapped on will play the video but not skip ahead to the correct time code. If the same link is tapped again or another one is tapped, the video will skip & play correctly.

### Expected
Any link tapped on will play the video from the time specified in the code. 

### Error output
No errors seen because the video plays. 

#### videojs
Video.js 7.0.5

#### browsers
Safari 

#### OSes
iOS 11 & 12

### plugins
None

**Comment by gkatsev** [comment]
Yeah, this is something we've been aware off for a while (https://github.com/videojs/video.js/issues/4696 is just one issue). Safari really doesn't let you seek before `loadedmetadata` has triggered on a new source.
We've been thinking that `currentTime` should cover this case but because it's kind of tricky to get right and other priorities got in the way so we never got around to this.

Listening to `loadedmetadata` and then seeking there should significantly increase the likelihood that it'll seek, but once the video has loaded you shouldn't have any problems.
