### ISSUE TITLE
Streams no longer works with createObjectURL() in Chrome

### ISSUE THREAD

**Issue by ixdi** [videojs/video.js#5469]
Hi,

Is there a way to set srcObject from a MediaStream? 
I have not found it in Video.js API but this is the new way to load a local video file.

Streams no longer works with createObjectURL() in Chrome.

Thanks

**Comment by gkatsev** [comment]
Do you have a code example of what you're doing currently that stopped working?

**Comment by ixdi** [comment]
I have created a codepen example. 
It's strange, when you first try to load local file it fails, but if you first try to load a server video then local file can be reproduced.
Maybe there's a mistake in my code.

https://codepen.io/ixdi/pen/jerYgo

Thanks

**Comment by ixdi** [comment]
Ok, I think we found the problem.

The param autoplay="muted" is need!

**Comment by gkatsev** [comment]
Looks like this is because from removed this capability? https://developers.google.com/web/updates/2018/10/chrome-71-deps-rems https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/tWzutytXsqc/discussion

They want you to transition to assigning the mediasource directly to the `.srcObject` property of the video element.

**Comment by thijstriemstra** [comment]
yes, use `srcObject` instead.
