### ISSUE TITLE
Installing via npm is not work

### ISSUE THREAD

**Issue by RavinduSachintha** [videojs/video.js#5530]
## Description
When try to install the video.js via npm according to the official website provided method, it wasn't install perfectly.

## Steps to reproduce
1. Execute the following command in the terminal. 
```
npm install video.js
```

### Expected
Successful video.js installation with complete **file structure** that you have mentioned in website.

### Actual
It's installed package-lock.json file and some sort of node_modules. But there isn't even package.json file.

### Error output
incomplete file structure.

#### OSes
Ubuntu

**Comment by gkatsev** [comment]
I just tried it and I'm not seeing that behavior. I do see a package.json. Also, our npm package isn't meant to match what's in source code as we do a lot of builds at publish time and mostly just publish what's built.
Did npm finish the install successfully? What version of npm were you using? Can you post the output of `ls` in `node_modules/video.js`?

**Comment by OwenEdwards** [comment]
I think the [Getting Started page](https://videojs.com/getting-started/) is a little confusing.

Running `npm install video.js` in an empty directory does throw some errors about `ENOENT: no such file or directory, open 'package.json'`, and the Distributions directory structure shown is placed under `node_modules/video.js/dist/`, not under `Video.js`.

(Also, the .zip file is no longer part of the NPM distribution, so that's not in the Distribution directory.)

@RavinduSachintha, if you look in `node_modules/video.js/dist/`, do you see the files you're looking for?

**Comment by gkatsev** [comment]
Ah, yeah, we should do a better job at targeting those that aren't familiar with node projects.
If `npm install` was run in a blank directory, it's possible that the `node_modules` folder is actually a folder up, so, `../node_modules/video.js/dist/`

**Comment by RavinduSachintha** [comment]
Thank you guys for helping. I just misunderstood the file location.

**Comment by Vaxxx** [comment]
I have the same issue in laravel. After installing video-js via npm, it doesn't work but if I use the CDN, it works... Any help will be appreciated
