### ISSUE TITLE
HLS not show video but we can listen audio

### ISSUE THREAD

**Issue by lucianogrippa** [videojs/video.js#5583]
## Description
The following playlist
**https://mediaservicerainet02-euno.streaming.media.azure.net/25f3217d-9e2f-4bc0-b331-347a0142d3a4/test_10min.ism/manifest(format=m3u8-aapl-v4)**

audio it's plays but video not,
If we test it in another player the playlist work fine but in videojs not work.
 

## Steps to reproduce
```
https://codepen.io/lucianogrippa/pen/yQMvYm
```

### Expected
We expected to see and listen video and audio with subtitles

### Actual
Just play audio but not video

**Comment by squarebracket** [comment]
This is likely caused by having only an audio-only playlist and a high-bandwidth audio+video playlist. The short version of the problem is that the initial bandwidth calculation thinks it isn't sufficient for selecting the audio+video playlist, so it picks the only-audio one, which unfortunately locks it to being audio-only forever, preventing a switch to the audio+video playlist when it gets a better estimation of bandwidth.

We have [an open issue](https://github.com/videojs/http-streaming/issues/175) for only allowing audio+video playlists when there are both audio-only and audio+video playlists in the manifest, but unfortunately, we haven't been able to implement that behavior yet. In the mean time, doing either of these will let you get around this:
- set the [`enableLowInitialPlaylist` option](https://github.com/videojs/http-streaming#enablelowinitialplaylist) -- this is the best option, since it should always select the lowest-bandwidth audio+video playlist for its first playlist
- set the [`bandwidth` option](https://github.com/videojs/http-streaming#bandwidth) to a value high enough to select the audio+video playlist -- for this media, the effect should be the same as using `enableLowInitialPlaylist` since there's only one audio+video playlist, but it's something you may want to keep in mind if you add more rates

It's also worth mentioning that Apple no longer recommends having an audio-only rate; instead, they recommend a very-low-bitrate audio+video rate. Removing the audio-only rate would of course eliminate this problem since there would be only audio+video playlists to choose from.

**Comment by gkatsev** [comment]
Looks like some wires got crossed. While @squarebracket's recommendation about the audio-only rate applies, the options for for contrib-hls and videojs-http-streaming, not for videojs-hlsjs-plugin which uses hls.js internally.
We don't maintain that plugin, I would look at the hls.js documentation and videojs-hlsjs-plugin docs for options that do similar things.
