### ISSUE TITLE
unable to select another source if the first one fails to load because the ui disappears

### ISSUE THREAD

**Issue by elypter** [videojs/video.js#5597]
## Description
on [invidio.us](https://github.com/omarroth/invidious), a youtube mirror software, some videos do not work. i dont know the exact cause but this is not the problem i am reporting. the issue i have is that i get the "The media could not be loaded, either because the server or network failed or because the format is not supported." error message and the video control elements disappear which makes it impossible to select another source which might work.

## Steps to reproduce
open any video that doesnt work: eg live streams: https://invidio.us/watch?v=PhTbzc-BqKs
the video controls are gone because the error message triggers a removal.

#### videojs
it is not my project, so i dont know
#### browsers
i tested it on firefox but its probably a general behavior
#### OSes
linux mint mate 18.3 32bit
### plugins
it is not my project, so i dont know

**Comment by gkatsev** [comment]
By default errors aren't dismissible in Video.js because they tend to be unrecoverable issues. The error dialog should close if a new source is set in the player. Developers also have the option of listening to the error event and hiding the error before it shows up for users.

This seems like you should ask invidio.us to have better error handling.

**Comment by elypter** [comment]
thanks
