### ISSUE TITLE
Cannot move the play pointer on progress bar back and forth

### ISSUE THREAD

**Issue by Trony** [videojs/video.js#5668]
## Description
When clicking on the play time progress bar the play pointer goes always to the beginning of the video instead of going to the min:sec that we've clicked.

## Steps to reproduce
1. Play a video
2. Click on the time progress bar
3. the play starts from the beginning.

#Version
Version 6.13
#### browsers
Chrome 
#### OSes
Windows 10
### plugins
No plugins

**Comment by mister-ben** [comment]
This sounds like your server is not responding to range headers correctly, sending the start of the file instead of the bytes requested. This usually is where you have a server side script proxying the file which is ignoring the headers.

**Comment by user8159** [comment]
I have the same problem, I get video via API.
You say that the problem is in the headers, maybe agree, but why then FireFox and IE browsers work correctly, the error only in Chrome.

**Comment by weiving** [comment]
I have the same problem,you solve this problem

**Comment by gkatsev** [comment]
Chrome always uses byte range request and if the backend doesn't support it, it would end up playing back from the beginning. Other browsers, like firefox, don't necessarily rely on byte range requests, which is why they work even when the backend doesn't support byte range requests.

Unfortunately, there isn't anything we can do in Video.js to make this work as it is a browser and back-end problem. The best and only realistic solution  is to switch or update the hosting of the media to support byte range requests.
