### ISSUE TITLE
Video stop loading when using Dash on Safari and HLS or Dash on IE11 

### ISSUE THREAD

**Issue by luisbritescarvalho** [videojs/video.js#5669]
## Description
When playing:
- Dash on Safari 
- HLS or Dash on IE11 win 8.  

the video pauses after a few seconds. 

It works fine on Chrome and Firefox with the same source.

## Steps to reproduce
1. Create a basic player to play https://d32rxv2sehu2w7.cloudfront.net/23/manifest.mpd
2. Open on safari 

Here's a ready sample: https://x9qw594w74.codesandbox.io/

### Expected
To work on Safari and IE11 the same way that it works on Chrome and Firefox.

**Comment by gkatsev** [comment]
This is likely because VHS is disabled on Safari because we assume that native HLS will be played back. We probably shouldn't make that assumption and only disable our HLS implementation on Safari by default. You can probably force that via the `overrideNative` option.
As for IE11 on Win8, it's possible that this version of IE11 doesn't have MSE.

Anything to add @videojs/playback?

**Comment by Dardaxe** [comment]
Hey,
In order to have more information about this issue [videojs/http-streaming#209](https://github.com/videojs/http-streaming/issues/209) could you say which service or tool you're using to transcode your video ? @luisbritescarvalho

**Comment by gkatsev** [comment]
@forbesjo ah, cool, didn't realize.

**Comment by luisbritescarvalho** [comment]
@Dardaxe we're using bitmovin
