### ISSUE TITLE
Why some videos give me this problem?

### ISSUE THREAD

**Issue by giggioman00** [videojs/video.js#5716]
Hello. I don't understand why some .mp4 files play correctly, while others I have to wait for the full video to be buffered in order to play them. 

I though maybe this was an encoding problem, but it's not. That's because, If I upload the same file on google drive, I can play it correctly. I though maybe google drive re-encode the mp4 on their server, so I tried to use their generated .mp4 on videojs, but still I'm facing the same exact problem for that file. So I guess the problem is in your player not able to play it?

**Comment by mister-ben** [comment]
Usually because your MP4 has the moov atom (metadata) at the end of the file. Most modern encoders would place it at the start by default, others call the something like "fast start".

Google Drive does play back a transcoded version of an uploaded video, but when you get a link it will be the original file
