### ISSUE TITLE
Video can't supported in Safari 12.0.3

### ISSUE THREAD

**Issue by Yijx** [videojs/video.js#5799]
## Description
When I use Safari(12.0.3) play  [100282](https://works.gaiamount.com/works/player/100282) or every videos in [video list](https://works.gaiamount.com/works/list).
Video can not play,and show me 'CODE: 4 MEDIA_ERR_SRC_NOT_SUPPORTED'

### Expected
If I use 12.0.2,everything is Ok

### Error output
CODE: 4 MEDIA_ERR_SRC_NOT_SUPPORTED - The media could not be loaded, either because the server on network failed or because the format is not supported.
Unhandled Promise Rejection:NotSupportedError:The operation is not supported

#### videojs
video.core.min 7.3.0
videojs-contrib-hls 5.14.1
videojs-contrib-media
videojs-contrib-dash 2.10.0

#### browsers
Safari 12.0.3

#### OSes
MAC

### other
I set overrideNative=true When I play avc video,set overrideNative=false When play hevc

**Comment by g-faucheux** [comment]
Have you fixed the issue yet?
I'm getting the same problem with Safari and iOS in general. 
VideoJS throw this error because of the small requests (64kb) Safari/ios perform for 206 Partial content. Although the videos play just after the dozens of requests. 
I don't really know how to fix it :/ perhaps add some quick hack so that VideoJS don't throw the errors (-2 or 4). Firefox/Chrome and all others works super fast with no issues. 

Please if you find any solution regarding this let me know

**Comment by gkatsev** [comment]
I am unable to play the stream that is chosen on Safari in Chrome either. The page linked above ends up playing an MPEG-DASH stream on another browser. Creating a reduced test case is very helpful to be able to track down issues.
As far as I can tell, the issue is that the stream is HLSe but the backend isn't serving the key properly. When trying in Chrome it's getting a CORS error. Safari isn't able to play it directly either.

**Comment by Yijx** [comment]
> Have you fixed the issue yet?
> I'm getting the same problem with Safari and iOS in general.
> VideoJS throw this error because of the small requests (64kb) Safari/ios perform for 206 Partial content. Although the videos play just after the dozens of requests.
> I don't really know how to fix it :/ perhaps add some quick hack so that VideoJS don't throw the errors (-2 or 4). Firefox/Chrome and all others works super fast with no issues.
> 
> Please if you find any solution regarding this let me know

ok but I still have no idea :(

**Comment by gkatsev** [comment]
I spent a bit more looking into this. As far as I can tell the HLS playlists are malformed and need to be re-encoded or the server serving the key files is misconfigured.
Ultimately, there's nothing that Video.js can do here, unfortunately.

**Comment by ankithtv** [comment]
@Yijx , @g-faucheux , @gkatsev  have you fixed the issue. i am having the same issue for the last 4 days. In my Angular project videos are playing on chrome and firefox. Not works with safari

observed : After removing cache of safari, video are playing but after 2 , 3 video it's shows CODE: 4 MEDIA_ERR_SRC_NOT_SUPPORTED. Again i need to remove cache to play videos

**Comment by g-faucheux** [comment]
> @Yijx , @g-faucheux , @gkatsev have you fixed the issue. i am having the same issue for the last 4 days. In my Angular project videos are playing on chrome and firefox. Not works with safari
> 
> observed : After removing cache of safari, video are playing but after 2 , 3 video it's shows CODE: 4 MEDIA_ERR_SRC_NOT_SUPPORTED. Again i need to remove cache to play videos

It's from Safari, I just don't know why Safari requests only 64kb ranges which in the end timeout, but if we switch to HLS, all work good, in the end we just gave up

**Comment by maneeshrao66** [comment]
Did you solved the issue?

**Comment by Yijx** [comment]
> Did you solved the issue?

no. i have been working without videojs for a long time. you can contact other people who reply above
