### ISSUE TITLE
XSS Vulnerability in VideoJS

### ISSUE THREAD

**Issue by kaizen1** [videojs/video.js#5847]
The CSS for video.js uses url(data:application/font-woff...) -- for the play/pause control bar icons.
This is a XSS hole. Any plan to use plain old font files or image files? This would allow for proper Content Security Policy at the domain level. 
Using data: in a Content Security Policity is a bad idea. 
Thanks in advance.

**Comment by thijstriemstra** [comment]
This ticket probably belongs in the https://github.com/videojs/font project.

**Comment by gkatsev** [comment]
I do have to say that the way things currently are, it doesn't cause an XSS because there are no user data is used. I do agree that it makes CSP harder as there isn't a way to whitelist a particular stylesheet, I think, which may lowers security.
Adding a stylesheet that links out to the font icons makes sense, though, I don't think I want to change the default away from what it currently is.

**Comment by kaizen1** [comment]
Using **data:** to load fonts is insecure and forces CSP policy to use the 'unsafe-inline' property because the player won't load if 'self' CSP policy is used i.e. if a secure policy is used.
From  MDN:
_data: Allows data: URIs to be used as a content source. This is insecure; an attacker can also inject arbitrary data: URIs. Use this sparingly and definitely not for scripts._

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src
