### ISSUE TITLE
Cross Origin for WebVTT failing with use-credentials

### ISSUE THREAD

**Issue by fkunkel** [videojs/video.js#5864]
I am currently working on a project that contains the video and track files on a separate domain than the main site.  In order to access to the video/track files requires specific cookies to be present.  I've set options for video files (HLS) to use withCredentials  and crossorigin="use-credentials" on the video tag as described in the documentation.  The video files are behaving as expected but the vtt files are not passing along the required cookie.  

Locally, I modified  https://github.com/videojs/video.js/blob/master/src/js/tracks/text-track.js 
Line 79 -81 from this 
```
 if (crossOrigin) {
    opts.cors = crossOrigin;
  } 
```
 to 
``` 
if (crossOrigin) {
    opts.cors = crossOrigin;
    opts.withCredentials = crossOrigin;
  }
 ``` 
and this has corrected the issue but it is unclear if this is the correct fix.  

Sample of code: 
```
<video-js id="vid1" class="vjs-default-skin" controls preload="auto" crossorigin="use-credentials" >
        <source src="https://whatever.com/video/package.m3u8" type="application/x-mpegURL">
        <track kind="captions" src="https://whatever.com/video/textTrack1.vtt" srclang="en" label="English" default>
        <track kind="captions" src="https://whatever.com/video/textTrack2.vtt" srclang="fr"  label="French" ></video-js>
<script>
        var player = videojs('vid1',{html5: { hls: { withCredentials: true } }});
</script>
```
Version 7.4.1

**Comment by gkatsev** [comment]
Unfortunately, just add `withCredentials` when CORS is needed isn't the best approach, because if the back end isn't set up to accept and give credentials, then all requests will fail.
Video.js currently isn't really set up to work with credentials and crossorigin="use-credentials". However, we should add support for setting the attribute. Then, when it is set, tracks should see if it is set to "use-credentials" and do the right thing. HLS should probably be updated to honor this option as well.

**Comment by gkatsev** [comment]
We have https://github.com/videojs/video.js/issues/5438, which I'm going to use as the main issue to track progress with. Going to add the above to it so that we don't forget.

**Comment by fkunkel** [comment]
Thank you!  I'll keep an eye on that issue.
