### ISSUE TITLE
VideoJS's event system does not mimic the dom as stated in the documentation.

### ISSUE THREAD

**Issue by KevinBrogan** [videojs/video.js#5884]
From: https://docs.videojs.com/tutorial-event-target.html
> Events in Video.js are setup so that they mimic the DOM API that is used on Object

This statement is not accurate.
- The same (event,callback) pair can be added multiple times using videojs.on(). This is not true with the DOM API. The DOM will ignore any request to add a callback that has already been added to a specific event type.
- Adding a callback pair using videojs.one() will remove all prior instances of the callback once that callback fires.
`function callback(){};`
`vjs.on('test',callback);`
`vjs.one('test'callback);`
`vjs.trigger('test') // there are now no handlers for the 'test' event`

The behavior should be in line with the documentation. Either by modifying the documentation or by modifying the code behavior.

**Comment by gkatsev** [comment]
The event system is still based on the DOM event system. The second item is a known issue because of how the event system is implemented. I think we've actually tested and the native event system had similar issues at one point.

For the first issue, we've probably just never noticed and likely due to how it's implemented. Unfortunately, I don't think this is something we could lock down without potentially breaking people.
