### ISSUE TITLE
Playing a MKV container

### ISSUE THREAD

**Issue by Anan5a** [videojs/video.js#5910]
## Description
I've videos in .mkv files which are encoded with FFMpeg libx264 codec. I want to play it using videojs on a browser. But it seems so impossible! 

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Take any video file 
2. run this to encode ``` ffmpeg -i myinput.mp4 -c:v libx264 -s 700:300 output.mkv ```
3. try playing ``` output.mkv ``` using videojs

### Expected
Play the video 

### Actual
This video cannot be played 

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with?
#### browsers
tried on chrome
#### OSes
Android
### plugins
NO PLUGIN

**Comment by mister-ben** [comment]
The short answer is that browsers don't support MKV for HTML5 video.

The slightly longer answer is you can sometimes get some MKVs to play in browsers that support webm, because webm is a subset of MKV. You'd probably have to give the type as video/webm for that to work at all. But even then no browser supports the AC3 audio codec commonly used in MKV, so you might get no audio.

See also https://docs.videojs.com/tutorial-troubleshooting.html#choosing-a-video-format

**Comment by gkatsev** [comment]
Yeah, unfortunately, it's basically not supported. mp4 with h264 video and aac audio is probably your best bet.

**Comment by Anan5a** [comment]
Just a response ...
Was able to play the video by setting the type to ``` video/mp4 or video/webm ``` on my Default browser. But Google Chrome didn't bother playing it. (just the duration was loaded)
