### ISSUE TITLE
pre-roll playing audio w/ no video - isolated to 3gpp encoding

### ISSUE THREAD

**Issue by webmmg** [videojs/video.js#5919]
We are looking to find some answers. 

we were having issues with our video.js player (at least we thought it was) where all of a sudden our pre-roll videos were playing audio with no video. 

We are using Google Ads Manager (formerly DFP). 

Our pre-roll videos that were hosted on Ads Manager we found that if we turned off the 3gpp encoding the pre-roll would play normally. 

However, we have a client that has 3rd party VAST tags that Ads Manager automatically adds the 3gpp encoding as a backup source, but that pre-roll now only plays audio and no video. 

Is there a way to turn off the 3gpp encoding within Ads Manager? or perhaps a way to prevent that encoding from being used through our video player?

We are only experiencing this with auto-encoding and need to find out if we can turn it off or if there is an alternative video player or adjustments to video.js files to prevent from showing.

**Comment by gkatsev** [comment]
Unfortunately, we don't really know much about Google Ads Manager. I wonder if your 3rd part VAST tag adds the 3gpp video as the first video rather than the alternative. Ultimately, yes, 3gpp videos do not play back in browsers. I would recommend reaching out to Ads Manager support to turn off encoding of 3gpp videos.

If you have a test case, we can see if there's something that can be configured in Video.js, however, as it stands, Video.js isn't going to try playing 3gpp videos unless the browser tells us it can, and no browser should be doing that.
