### ISSUE TITLE
I want to change  language option

### ISSUE THREAD

**Issue by liuyuanke** [videojs/video.js#5922]
## Description
I want to change  language option ,but it not work,please help me,thank you !

source below:
```
import videojs$1 from 'video.js';
 this.player = videojs$1(this.videoNode,this.props, function onPlayerReady() {});

<video ref={ node => this.videoNode = node } className="video-js vjs-big-play-centered" controls preload="auto" width="640" height="480"  data-setup='{"language":"zh-CN"}'>
            <p className="vjs-no-js">
              No support HTML5，please upgrade!
            </p>
            <track kind="captions" />
          </video >
```
videojs.addLanguage  is  not define ?

**Comment by BH-NOTHING** [comment]
yeah ,  I have encountered the same problem that doesn't work

**Comment by BH-NOTHING** [comment]
@liuyuanke I solved it in the following way
`const zhCN = require('video.js/dist/lang/zh-CN.json')`
 ` videojs.addLanguage('zh-CN',zhCN)`

**Comment by gkatsev** [comment]
We also compile the json files into js files you can require which automatically call addLanguage. For example https://unpkg.com/video.js@7.5.4/dist/lang/zh-CN.js.
```js
const videojs = require('video.js')
require('video.js/dist/lang/zh-CN.js');
```

We do no include the translations by default because otherwise the file size of Video.js will be unreasonably large.

If importing the language file (in one of the two methods specified above) doesn't work, let us know and we can re-open this issue.
