### ISSUE TITLE
Remove title attributes on the controlbar buttons

### ISSUE THREAD

**Issue by aydinkn** [videojs/video.js#5930]
Hello guys,

I'm trying to develop tooltips for controlbar buttons. Is there any way to remove title attribute on the buttons? Because i don't want to show browser tooltip.

Note: I don't want to listen mouseover or click events and set the titles to empty string.

I saw this in the ClickableComponent:

```
if (!this.nonIconControl) {
      // Set title attribute if only an icon is shown
      el.setAttribute('title', localizedText);
    }
```

but nonIconControl is never used.

**Comment by OwenEdwards** [comment]
@aydinkn `nonIconControl` is used for things like menu items, which have a text label rather than an icon label, and therefore don't need a title attribute to label the purpose of the control. See https://github.com/videojs/video.js/blob/master/src/js/menu/menu-item.js#L64, for example.

Custom tooltips, which show on keyboard focus as well as mouse over, instead of just the title attribute, would definitely be an improvement, if you want to submit a PR.

**Comment by aydinkn** [comment]
Thanks @OwenEdwards 
I'll create custom tooltips and if it is ok then I'll submit a PR about that.
