### ISSUE TITLE
How to capture segment errors

### ISSUE THREAD

**Issue by vksbansal** [videojs/video.js#5940]
Hi Team,

I need to refresh the src URL on segment 403 error.

Is it possible to capture segment errors?

Please help, your thankfull
Vikas Bansal

**Comment by gkatsev** [comment]
Unfortunately, there isn't a specific way to see 403 errors with segments. However, you can listen to the `retryplaylist` event on the tech which will fire once we reload the playlist since it is the final one. You can see an example here: https://github.com/videojs/video.js/issues/5435#issuecomment-471998039

**Comment by gkatsev** [comment]
Yeah, we're aware of the current limitation and are thinking about what would be useful and how to expose it.

**Comment by vksbansal** [comment]
@gkatsev just a suggestion, just like `beforeRequest`there can be an `after response` interceptor.

**Comment by gkatsev** [comment]
That is definitely an option. Going to close this while we consider our options.
