### ISSUE TITLE
why is 7.5 marked as pre-release for so long?

### ISSUE THREAD

**Issue by thijstriemstra** [videojs/video.js#5943]
when will 7.5  be released?

**Comment by gkatsev** [comment]
Mostly because I forgot that it's still in pre-release. I'll promote it to latest today.

**Comment by gkatsev** [comment]
Updated 7.5.4 to latest. Thanks for the reminder!

**Comment by thijstriemstra** [comment]
@gkatsev when looking at the releases list, there are many marked as pre-release, maybe those should also be 'un-pre-released' and marked as such?

**Comment by gkatsev** [comment]
I've marked the latest 7.4.x as not a pre-release. I'm not sure it's worth updating older dot releases as not-pre-release.

**Comment by EhsanCh** [comment]
Hi @gkatsev , Does this happens to 7.7.x also or all releases after v7.6.6 is really pre-release ?

**Comment by gkatsev** [comment]
It's both because I forgot but also we've had a few bugs that we've been ironing out as part of the 7.7 release line.

**Comment by EhsanCh** [comment]
So the bugs are new in 7.7 or it is suggested for production use ?

**Comment by gkatsev** [comment]
The big issue that we had was fixed in 7.7.4 (https://github.com/videojs/video.js/pull/6373) and we just merged another small fix (https://github.com/videojs/video.js/pull/6445) which should be released soon. Once that's released, hopefully, by tomorrow, we'll let it hang out in pre-release for a couple of days and probably promote it latest early next week.
7.7.4 is probably ok to go to production with (but not earlier 7.7) assuming you are ok with #6445 being missing.
