### ISSUE TITLE
Help! Videojs HLS m3u8 files are not playing in iOS devices (Chrome or safari)

### ISSUE THREAD

**Issue by AmirKaftari** [videojs/video.js#5996]
## Description
hi guys.
I am able to play the m3u8 files in the PC and android devices, but i am not able to play those files in the iOS mobile devices , I disabled the overrideNative to 'true' for the android devices, so its working in the android. but we should not disable the native for iOS and safari, because iOS Safari uses a native player, so I have set the overridnative false for the iOS. but its not working.

Regard.

## Steps to reproduce
1. Tried to use videojs v7.2.4 
2. i use this code for  disabled the overrideNative to 'true' : 
`let sitePlayer = videojs('player', {
                    playbackRates: [0.5, 1, 1.5, 2],
                    html5: {
                        hls: {
                            overrideNative: true
                        },
                        nativeVideoTracks: false,
                        nativeAudioTracks: false,
                        nativeTextTracks: false
                    }});`
### Expected
Play video in IOS device

### Actual
Play video in all OS browsers except IOS.

#### videojs
7.2.4

**Comment by gkatsev** [comment]
iOS doesn't support the MSE APIs required for VHS to work. Unfortunately, if you're stream doesn't work in iOS, you need to fix your stream to get it working, there's nothing we can do about it in the player.

**Comment by AmirKaftari** [comment]
> iOS doesn't support the MSE APIs required for VHS to work. Unfortunately, if you're stream doesn't work in iOS, you need to fix your stream to get it working, there's nothing we can do about it in the player.

thanks for reply , how fix my stream? Can you guide me?
i use ffmpeg for m3u8 file.

**Comment by TomGudman** [comment]
Out of curiosity, does it work if you go "Desktop mode" in Safari or Firefox on your IOS device?

**Comment by AmirKaftari** [comment]
hi tom.
That's my problem too , i cant play video in iOS device browsers(safari , chrome , firefox).
do you have any solution ?

**Comment by AmirKaftari** [comment]
> Out of curiosity, does it work if you go "Desktop mode" in Safari or Firefox on your IOS device?

hi tom.
That's my problem too , i cant play video in iOS device browsers(safari , chrome , firefox).
do you have any solution ?

**Comment by mysterfitz** [comment]
Have you tried setting `playsinline` to true?
`player.playsinline(true);`

This was the answer to all of my (similar) problems.

**Comment by AmirKaftari** [comment]
> playsinline

**Comment by AmirKaftari** [comment]
> Have you tried setting `playsinline` to true?
> `player.playsinline(true);`
> 
> This was the answer to all of my (similar) problems.

thanks for reply. but this not work for me

**Comment by rickcha** [comment]
How about webkit-playinline?

**Comment by dryize** [comment]
This hasn't solved yet?

**Comment by dotesfera** [comment]
Hi, i'm having the same issue, video does not play on IOS on Video.js 7.8.3

**Comment by gkatsev** [comment]
We test playback on iOS on a regular basis and when there is an issue we fix it when we can (for example, the caption related issue recently).
In addition, on iOS, we handle the video to the browser and don't handle the playback itself. So, if playback doesn't work it is likely due to bad media.

If you have an issue, please open a *new* issue and fill out the issue form with as much information as you can, preferably with a link to the stream you're trying to play even better if you can provide a minimal, complete, verifiable example.

**Comment by noahschumacher** [comment]
Hi @AmirKaftari  did you ever solve this?

We have the same issue. We are delivering live streaming content via nginx-rtmp and outputting hls to be ingested (.m3u8, .ts files) Our video-js player works on all browsers except for iOS.

We have been looking over the [iOS HLS Authoring Spec](https://developer.apple.com/documentation/http_live_streaming/hls_authoring_specification_for_apple_devices) and have found a few requirements that are missing but don't believe this to be the issue. We think it has something to do with the player because we can view the stream in the VLC player application on iOS devices. This makes me think it is somehow player-specific.

**Comment by vladuma** [comment]
I am experiencing exactly the same issue. FFmpeg + nging-rtmp to serve the stream and video.js 7.17.0 to view it.
Works everywhere except for iOS Safari (desktop & mobile).
Any ideas on how to set up the player or stream itself to work on Safari?
