### ISSUE TITLE
HLS video has black screen at the start of video in Chrome

### ISSUE THREAD

**Issue by gitamj** [videojs/video.js#6031]
## Brief description
When a HLS video is played by the user, it has black display for first five seconds but audio keeps playing. This is happening randomly in Chrome. Firefox works okay. It happens when a video is played manually by the user. If video is played via javascript `player.play();` on page load then it works fine.

## Steps to reproduce
Below is the url to jsFiddle in order to reproduce it. 
This is happening randomly in Chrome. Sometimes video display is okay and sometime it is missing for few seconds. Firefox runs the video as expected.
https://jsfiddle.net/hgozy4re/

Please run the jsFiddle multiple times and click on big play button. Sometime video is played normally and sometime there is black screen.
Please run the same tests in Firefox and everything is fine there all the time.

## Results
When I click the big play button, video starts playing but there is black screen for first 5 seconds.

If I move the seekbar to the start of the video then video displays okay every time.

### Expected
Video should play normally and there is should be video display.

### Actual
Video display missing for first 5 seconds.

#### browsers
Google Chrome Version 74.
Vivaldi 2.5.1
#### OSes
Windows 10

**Comment by melzoSMIS** [comment]
Facing the same issue. 
I am working on aframe and video.js in react to show a 360 video (hls video) in browser.
It is working fine in desktop browser but in mobile browser it shows black screen and plays only audio.
Search almost everything.
Project url : https://melzo.com/dekho/5d0b7e1ab263bf000fa383a7
open this in mobile browser and and click on tutorial2

Browser error : (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported. MediaError {code: 4, message: "The media could not be loaded, either because the …rk failed or because the format is not supported."}

**Comment by gkatsev** [comment]
I can reproduce the original issue in the jsfiddle. Not sure what's going on, though.

**Comment by gkatsev** [comment]
Not seeing anything in media-internals either.

**Comment by hanleym** [comment]
I'm having this issue as well. It seems to just get stuck on the first frame of the video as mine is white instead of black but has the exact same behavior.

**Comment by jjustpsu** [comment]
We also seem to be having this issue. Any update?

**Comment by umneeq** [comment]
Having this issue as well. So what is the point?

**Comment by msyagli** [comment]
Same issue, anyone pinpoint the problem?

**Comment by jokezer** [comment]
In my case, it happened because videojs function wasn't actually called on the video component. And it has a blank black screen because of the videojs css styles.

**Comment by rsvidevince** [comment]
> In my case, it happened because videojs function wasn't actually called on the video component. And it has a blank black screen because of the videojs css styles.

Could you elaborate on which css style exactly is it? So we could... override it? I would be happy if instead of a black screen, I got a white one.
