### ISSUE TITLE
HLS Error : lastMatchedSample is undefined 

### ISSUE THREAD

**Issue by koreus** [videojs/video.js#6038]
## Description

VideoJS doesn't play all segment and stop loading with javascript error.
On Firefox : TypeError: lastMatchedSample is undefined
On Chrome: Uncaught TypeError: Cannot read property 'pts' of undefined

## Steps to reproduce
Go to https://www.koreus.com/test/videojs.html and play the video at 360p quality

### Expected

Playing all segments without stopping 

### Actual

VideoJS will stop playing at 0:12 , when loading 3rd segment (6 seconds segment duration)

### Error output
On Firefox : TypeError: lastMatchedSample is undefined
On Chrome: Uncaught TypeError: Cannot read property 'pts' of undefined

## Additional Information

I have used ffmpeg to make the stream (fMP4 single file) with 6 seconds segment duration
 -hls_time 6   -hls_segment_type fmp4   -hls_flags single_file

#### videojs

7.5.4

#### browsers

Chrome 74
Firefox 67

#### OSes
Windows, Linux and macOS

### plugins
videojs-contrib-quality-levels
videojs-hls-quality-selector

**Comment by carloscarnero** [comment]
I had a *very* similar issue as you have reported. In my case, it went away when I packaged my media with [Shaka Packager](https://github.com/google/shaka-packager) instead of `ffmpeg`, but that was just a fluke. There's an [open issue](https://github.com/videojs/mux.js/issues/223) in [mux.js](https://github.com/videojs/mux.js) that maybe is affecting you as well.
