### ISSUE TITLE
 error after lock/unlock iPhone

### ISSUE THREAD

**Issue by konstantinGN** [videojs/video.js#6066]
## Description
I try to play hls-video with help video.js,
after first load on IPhone it works fine but after lock/unlock I have error on screen and in console

## Steps to reproduce
1. open link https://jsfiddle.net/konstantinG/c5fhqym4/ on IPhone
2. Lock device
3. Wait ~5min
4.  Unlock device
## Results
You can see  error message on screen and  error in console

### Expected
It will  use native HLS as in first load
### Actual
after unlock IPhone, video.js try to use Hls.js for IPhone but Hls.js not supported mobile safari

### Error output
![hls error](https://user-images.githubusercontent.com/50979187/59923754-d4c2de00-943c-11e9-8a0d-466d9ab32b45.jpg)

#### videojs
7.5.5
#### browsers
safari
#### OSes
IOS IPhone

**Comment by gkatsev** [comment]
Yeah, this happens due to how Safari handles putting the browser into the background. Unfortunately, it seems like we probably need to detect the browser going inactive and becoming active again and then reload the video in that case but that's a non-trivial amount of work which we don't have time scheduled to fix in the near term.
