### ISSUE TITLE
Query to server is been done for every target duration in case of event playlist

### ISSUE THREAD

**Issue by SetV** [videojs/video.js#6116]
## Description
1. Live stream spec [section 6.3.4](https://tools.ietf.org/html/draft-pantos-http-live-streaming-23#section-6.3.4) states playlist shouldn't be queried when not being played, whereas the query for event playlist is happening even in the paused state.

> In order to reduce server load, the client SHOULD NOT reload the Playlist files of Variant Streams or alternate Renditions that are not currently being played.

2. The query to server is happening for every target duration, whereas the spec defines this is the least duration.
 
> the client MUST wait for at least the target duration before attempting to reload the Playlist file again

Event playlist is looking for _EXT-X-ENDLIST_ tag to stop the playlist query. There is no other option available to delay the playlist query.

I see the first issue as spec violation, where as the second should be supported to serve multiple clients. Consider a case where 1000s of clients querying the server for every 6 seconds, there should be a way to avoid frequent query to the server.

## Steps to reproduce
1. Create a m3u8 event playlist.
2. Make sure _EXT-X-ENDLIST_ is not served in the playlist.
3. Play the m3u8 playlist through VideoJS
4. Observe frequent query to the server.

### Expected
Query to server should be configurable to avoid server load.

### Actual
Query to server is much frequent done for every target duration, say 6 seconds.

#### videojs
7.6.0
#### browsers
Chrome 75.0.3770.142
#### OSes
Windows 10, Mac Sierra
### plugins
NA

**Comment by gkatsev** [comment]
So, we've talked about this some more internally. We do believe that our behavior is correct. The specifically talks about not reloading the playlists that aren't currently being played. Plus, while you're at the live edge, we still need to make the request every target duration or the playback will stall, so, ultimately, your backend should be able to handle the load (perhaps with good cache-control headers).
We probably want to implement something like https://github.com/videojs/videojs-contrib-hls/pull/785 so that users like you can tweak things manually. It'll also help with issues like https://github.com/videojs/video.js/issues/6081.
Unfortunately, we're pretty swapped and are unlikely to be able to implement this in the short term.

**Comment by musarano** [comment]
Thank You for address this thread: #6081. 
Lets hope you guys can have sometime to spend with this, Cant wait to begin using VideoJs as soon is implemented ! We do have a whole enhanced and waiting to be upload and substitute the Flowplayer 7.latest for VideoJs Player.

Thank You and best wishes !

-M

**Comment by SetV** [comment]
We are looking forward to get it implemented! Thanks for the feedback!

**Comment by SetV** [comment]
"Unfortunately, we're pretty swapped and are unlikely to be able to implement this in the short term."

Fix is planned for any upcoming release? I am holding the VideoJS deployment because of this option. Any alternate way this can be achieved, I will try to explore in the meantime.

**Comment by musarano** [comment]
Hi.
I went back to FP7 until this could get resolved . Couldnt keep waiting..

Thank you
