### ISSUE TITLE
second video not playing

### ISSUE THREAD

**Issue by ssudhak** [videojs/video.js#6121]
## Description
We have 2 videos in home page of our site. Requirement is like second video has to play when first one ends. We have written the following code. But seems like this is not working. Any idea how to resolve this?

```
videojs('myExperience-1_html5_api').ready(function () {
          var myPlayer = this;
          myPlayer.muted(true);
          $('.mute-button').addClass('muted');
          myPlayer.play();

          myPlayer.on('ended', function () {
            console.log('end');
            if ($('.banner-video-loop').length) {
              videojs('myExperience-2_html5_api').ready(function () {
                var myPlayer2 = this;
                myPlayer2.play();
              });
            }
          });
        });
```

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs - v0.4.2
what version of videojs does this occur with?
#### browsers - Chrome and firefox
what browser are affected?
#### OSes - mac OS
what platforms (operating systems and devices) are affected?
### plugins 
are any videojs plugins being used on the page? If so, please list them below.

**Comment by mister-ben** [comment]
You mute the first player but not the second. If you are muting to avoid autoplay restrictions you may need to mute both.

As an aside, use the player's id rather than the tech's, i.e. `myExperience-1` not `myExperience-1_html5_api`. While calling `videojs()` on an inititated player's tech wil return the player object, you shouldn't rely on a video element with that exact id existing.

**Comment by ssudhak** [comment]
@mister-ben muting the second video solved the issue for me.

Thanks a lot for the help.
