### ISSUE TITLE
Large bundle size (900KB)

### ISSUE THREAD

**Issue by ddrjm** [videojs/video.js#6166]
Hello, I'm using videojs via NPM and webpack which is incorporating the CSS files needed for the player and a few kb (3kb) of custom CSS that tweaks color here and there.

When building for production, I notice that the bundle has about 900kb. How can I reduce this size?
Is there a way to only import the bare minimum from videojs to have it working? (both modules and css)

Sorry if this isn't the right place to ask about this subject

**Comment by sampathkumar7** [comment]
const CompressionPlugin = require('compression-webpack-plugin');

plugins:[
	new CompressionPlugin(),	
  ],

Use above setup it will create gzip file something like bundle.js.gz i used it to reduce 600KB file to 60KB
Also use can use google brotli compression plugin which is much better than Gzip

**Comment by ddrjm** [comment]
> const CompressionPlugin = require('compression-webpack-plugin');
> 
> plugins:[
> new CompressionPlugin(),
> ],
> 
> Use above setup it will create gzip file something like bundle.js.gz i used it to reduce 600KB file to 60KB
> Also use can use google brotli compression plugin which is much better than Gzip

Sorry for the dumb question, but if I serve the .js.gz files, won't they be downloaded by the browser instead of being served? 

A 10x reduction sounds interesting but I'm confused about the .js.gz script files

**Comment by sampathkumar7** [comment]
You need to enable in server to use gzip files.

**Comment by brandonocasey** [comment]
You can also use `dist/alt/videojs.novtt.js` if you don't need vtt support baked in, `dist/alt/video.core.js` if you don't need `HLS/dash` support, or `dist/alt/videojs.core.novtt.js` if you don't need either of those.

**Comment by ddrjm** [comment]
@brandonocasey in this case how would I include it via npm? 
At the moment I'm just doing `import videojs from video.js`. Should I change it to `import videojs.core.novtt.js` ?

**Comment by brandonocasey** [comment]
### Solution for now is:
It should be `import videojs from 'video.js/dist/alt/videojs.core.novtt.js;` or if you don't do minification to your own bundle and you want the smallest video.js: `import videojs from 'video.js/dist/alt/video.core.novtt.js';` 

### Alternative solution (not working now due to a build issue on our end #6176) 
Typically you should be able to get webpack to exclude modules from the build and just use `import videojs from 'video.js';` but it seems that we messed that up on our end. You will only be able to exclude `videojs-vtt.js`, and not `@videojs/http-streaming` I have a pull request out to fix that #6176 

Once this is fixed you should be able to use webpack to load an empty module in place of `@videojs/http-streaming` or `videojs-vtt.js`. I haven't used it or webpack much but that might be possible with https://github.com/webpack-contrib/null-loader

**Comment by pat-eason** [comment]
How prevalent is lodash? ES6 largely makes it irrelevant minus a few utilities which would be recreated without too much trouble.
