### ISSUE TITLE
Bundle Size

### ISSUE THREAD

**Issue by iqradada** [videojs/video.js#6190]
I am curious about the bundle/library size of video.js.

**Comment by iqradada** [comment]
Also, does video.js support mirroring over the air like airplay or chromecast?

**Comment by gkatsev** [comment]
There are plugins that support airplay and chromecast but it isn't available out of the box.
The bundle size is not small because of all the features that Video.js provides from captions to HLS and DASH playback to accessible custom controls. Unfortunately, this means that there's a lot of javascript in there. However, size-wise we're on par with other players when considering feature support.
