### ISSUE TITLE
how to switch videojs src 

### ISSUE THREAD

**Issue by lt978613** [videojs/video.js#6236]
I switch  videojs  src by clicking a button when the src is liked 
`http://www.ablesky-a.comcom:8080/course.do?action=videoUrl&courseId=1073122`
there is no request to send when player play, but the src like 
`http://www.ablesky-a.comcom:8080/video.mp4`
the request is sended  directly.
player init code 
```
var myPlayer = videojs('player', {
	    muted: true,
	    controls: true	,
	    loop: false,
	    fluid:true,
	    language:'zh-CN',
    	playbackRates: [0.5, 1, 1.5, 2],
    	sources: [{
			src: 'video.mp4',
			type: 'video/mp4'
		  },{
			src: 'video.webm',
		 	type: 'video/webm'
		},{
			src:'video.m3u8',
			type:'application/x-mpegURL'
		}]
	},function(){
	});
```
click button code
```
myPlayer.src(src);
myPlayer.load(src);
myPlayer();
```
when the src is not a file link there is no request sending why?

my  videojs version : 7.6.4

**Comment by diephv** [comment]
var oldPlayer = document.getElementById("player");
            videojs(oldPlayer).reset();
Try it!

**Comment by gkatsev** [comment]
`reset` isn't what you want. Ideally, you would provide a source object rather than just a string. With a string like `video.mp4` we can infer the type of the video from the extension but we can't do that from your example `http://www.ablesky-a.comcom:8080/course.do?action=videoUrl&courseId=1073122`. This is because we need the type to know which tech to load and whether we need to load our HLS or DASH playback engine.

Instead, you can provide the type to the src method:
```js
player.src({
  src: 'http://www.ablesky-a.comcom:8080/course.do?action=videoUrl&courseId=1073122',
  type: 'video/mp4'
});
```
