### ISSUE TITLE
Seeking doesn't work correct

### ISSUE THREAD

**Issue by Fogord** [videojs/video.js#6250]
Hi everybody

## Description
Seeking trouble of "m3u8" file.
The m3u8 file has the "#EXT-X-ENDLIST" mark and the video of 24 hours, 20 GB  size is.

# Steps to reproduce
Settings 
```
{
autoplay: false,
controls: true,
playbackRates: [0.7, 1.0, 1.5, 2.0, 4.0, 8.0],
bigPlayButton: false,
live: false,
controlBar: {
liveDisplay: false,
seekToLive: false,
pictureInPictureToggle: false
},
sources: [{
src: "http://195.201.183.198:80/record/cam1/2019-10-01/archive.m3u8",
type: "application/x-mpegURL",
allowSeeksWithinUnsafeLiveWindow: true
}]
}
```
1. click play
2. seeked to ~20:00:00
3. seek to ~01:00:00
3.1 seeked event was emitted
3.2 repeat 4-5 time the 2 and 3 steps
4. videojs is try to load content of the last seeking 
5. and finally event seeked not emitted

### Expected
Expected that can seeking video anytime, not only some few times

### Error output
no errors

#### videojs
7.6.0
#### browsers
Chrome 
#### OSes
MacOS
### plugins
no plugins

**Comment by gkatsev** [comment]
Looks like there are two things that could be causing issues here. First, the target duration of the manifest is 6 seconds but each segment alternates between being 6 and being 4 seconds long. This means that the further into the 24-hour stream we're at, the less accurate our seeking guess is, and we could be widely off from where the seek was supposed to be, which can cause some issues. Also, the way we handle timestamps in mux.js right now, it doesn't handle seeking past 13 hours.

**Comment by Fogord** [comment]
Thanks @gkatsev 

For the first case, the hls doesn't forbid has files less than set tag #EXT-X-TARGETDURATION and this m3u8 file generated by ffmpeg. I try to open my m3u8 file by another players and all is fine. 

In the second case I am not understood what do you mean. Describe it more fully please.

However I found new information of issue:
Firefox - seeking is completely no work
Chrom - it is describe in current issue
Safari - working correct

**Comment by gkatsev** [comment]
It isn't disallowed but it does make it a lot harder to know where to seek because we are making guesses based on the target duration and if you are trying to seek very far large mismatches between segment durations and target durations will make us guess incorrectly because the differences will create a large error gap.
Unfortunately, I can't describe in more details the mux.js issue but it's likely the main problem here. Something about PTS values and rollover and streams longer than 13 hours will have multiple rollovers and so if you seek longer than 13 hours it likely will get confused about the timing.

The reason why Safari works is that our playback engine doesn't run and uses native playback on Safari.

**Comment by Fogord** [comment]
Yes, you are clearly right. Mux.js has  `var RO_THRESH = 4294967296;`
> // Note: A seek forwards or back that is greater than the RO_THRESH (2^32, ~13 hours) will
> // cause an incorrect adjustment.

I trid to seek video by little steps of ~3-4 hours and it work correct.  

Maybe you have any idea to fix it?
