### ISSUE TITLE
Video player resuming issue with m3u8 format video in mobile devices

### ISSUE THREAD

**Issue by vamsimudadla** [videojs/video.js#6360]
## Description
I made a player using videojs. First I played the video in chrome browser of computer. When I refresh the url, the video played from the last stopped time. Next I played the video in chrome browser of my android mobile. Now if I refresh the url , the video is not playing from the last stopped time. It is playing from the start

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1.clone the repo https://github.com/vamsimudadla/video-player
2.do yarn start
3.check in the mobile device

### Expected
In mobile, I am expecting that the video starts playing from 60 sec

### Actual
It is playing from 0 sec

### Error output
If there are any errors at all, please include them here.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
7.6.6
#### browsers
I have checked in chrome browser and safari
#### OSes
linux, android, ios

**Comment by gkatsev** [comment]
Sounds like whatever you are doing to resume at last watched time isn't working nicely with mobile devices. If you have a reduced test case, we can take a look and point you in the right direction.

**Comment by vamsimudadla** [comment]
Hey @gkatsev , thanks for your reply
Actually the problem is occuring while playing with m3u8 formats.
Here is the sample react-video-player repo to reproduce the issue.
https://github.com/vamsimudadla/video-player

**Comment by gkatsev** [comment]
That's not a very reduced example but if the issue is that you're starting at 60s per https://github.com/vamsimudadla/video-player/blob/master/src/Components/Video/index.tsx#L32 but it isn't happening on mobile this is likely because mobile takes longer to load and you probably should listen to `loadedmetadata` event before setting currentTime. See https://github.com/videojs/video.js/issues/6111#issuecomment-513872631 for more info. We do plan to make this better by basically handling this for you but that won't be out for a while.

**Comment by vamsimudadla** [comment]
I tried  *loadedmetadata* event but it is not working for me and I also tried *canplay* event, but its behaviour is changing in different cases. If changed the time in canplay event function, it is working but if i changes the time in outside the canplay event, it is not working. Please check the repo once.
Thank You
