### ISSUE TITLE
Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by yanyunlong** [videojs/video.js#6384]
{
        key: "probeSegmentInfo",
        value: function(e) {
            var t = e.segment
              , i = e.playlist
              , n = void 0;
            return (n = **t.map** ? this.probeMp4Segment_(e) : this.probeTsSegment_(e)) && this.calculateSegmentTimeMapping_(e, n) && (this.saveDiscontinuitySyncInfo_(e),
            i.syncInfo || (i.syncInfo = {
                mediaSequence: i.mediaSequence + e.mediaIndex,
                time: t.start
            })),
            n
        }

An abnormality was detected on the network. I have tried versions 7.66 and 7.73. Is there a new version to solve this problem?

**Comment by mister-ben** [comment]
Reproducible example where this happens?

**Comment by unknn** [comment]
I have the same error. This error only happens when i'm streaming a HLS. 

The problem happens when the hls video have the current durarion of the m3u8 is < 2min. Look at this example:

I started streaming a video with 20min length, the user started whaching it from start (00:00), it will play normaly. Let's say that now the user is at time 01:15, and my server already have added many segments to the m3u8 which will be equal to 3min. The videojs uses the function named "XhrFunction" to keep traking the m3u8 file, when it detects that the m3u8 file already have many segments it will update the player duration to 2min ~ 2:30min,  and then it shows the error described by yanyunlong, and the player stop working, i'm not sure but looks like it only happens when the m3u8 is a playlist.

Until my m3u8 file reach a multi of 2, (2min, 4min, 6min, 8min) the player only add +1s to the video duration. And for some reason the error only appear at 2min, if reload the page or start watching the LIVE at +2min, the error don't happen.

Maybe it's not videojs fault? I use ffmpeg 4.2.1 and Video.js 7.6.6, the error happens in Mozilla and Chrome. The error don't happen when the m3u8 have the tag "#EXT-X-ENDLIST"

If someone wants to reproduce the error, it's easy, i don't know if ffmpeg is needed but this is what i do:

1 - Convert a mkv video to hls using ffmpeg
2 - Watch the hls file in the browser (the m3u8 needs to have  < 2min at the moment)
3 - When the ffmpeg transcode reach +2min, the videojs will update the m3u8 at the player and the error will appear in the console

This thing about multi of 2 is really strange, when the error appear the m3u8 does not update anymore looks like there's some "cache" , although the "XhrFunction" keep doing requests.

**Comment by MilosRasic** [comment]
Happening over here as well with live HLS streams. Happened only 8 times in production during the last week with thousands of daily users so definitely not easy to reproduce. No correlation between playback time and errors.

**Comment by JFrankfurt** [comment]
Seeing this a fair bit in prod JS logs

- 350 occurrences in the last week
- this UA accounted 57% of the errors `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36`
- Live HLS. No matter how long the manifest is. Seems to happen more often when there are discontinuities in the manifest.

**Comment by DaveStein** [comment]
@mister-ben are you able to re-open this? Would seeing an HLS manifest help you here?

**Comment by JFrankfurt** [comment]
@mister-ben @gkatsev 
Here's an HLS manifest associated w/ a stream that triggered this error.
```
#EXTM3U
#EXT-X-VERSION:4
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio",NAME="audio_und",LANGUAGE="und",DEFAULT=YES,AUTOSELECT=YES,URI="QualityLevels(128000)/Manifest(audio_und,format=m3u8-aapl)"
#EXT-X-STREAM-INF:BANDWIDTH=351536,RESOLUTION=320x180,CODECS="avc1.64000d,mp4a.40.5",AUDIO="audio" QualityLevels(200000)/Manifest(video,format=m3u8-aapl)
#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=351536,RESOLUTION=320x180,CODECS="avc1.64000d",URI="QualityLevels(200000)/Manifest(video,format=m3u8-aapl,type=keyframes)"
#EXT-X-STREAM-INF:BANDWIDTH=555936,RESOLUTION=480x270,CODECS="avc1.640015,mp4a.40.5",AUDIO="audio" QualityLevels(400000)/Manifest(video,format=m3u8-aapl)
#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=555936,RESOLUTION=480x270,CODECS="avc1.640015",URI="QualityLevels(400000)/Manifest(video,format=m3u8-aapl,type=keyframes)"
#EXT-X-STREAM-INF:BANDWIDTH=964736,RESOLUTION=640x360,CODECS="avc1.64001e,mp4a.40.5",AUDIO="audio" QualityLevels(800000)/Manifest(video,format=m3u8-aapl)
#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=964736,RESOLUTION=640x360,CODECS="avc1.64001e",URI="QualityLevels(800000)/Manifest(video,format=m3u8-aapl,type=keyframes)"
#EXT-X-STREAM-INF:BANDWIDTH=1782336,RESOLUTION=960x540,CODECS="avc1.64001f,mp4a.40.5",AUDIO="audio" QualityLevels(1600000)/Manifest(video,format=m3u8-aapl)
#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=1782336,RESOLUTION=960x540,CODECS="avc1.64001f",URI="QualityLevels(1600000)/Manifest(video,format=m3u8-aapl,type=keyframes)"
#EXT-X-STREAM-INF:BANDWIDTH=3213136,RESOLUTION=1280x720,CODECS="avc1.64001f,mp4a.40.5",AUDIO="audio" QualityLevels(3000000)/Manifest(video,format=m3u8-aapl)
#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=3213136,RESOLUTION=1280x720,CODECS="avc1.64001f",URI="QualityLevels(3000000)/Manifest(video,format=m3u8-aapl,type=keyframes)"
#EXT-X-STREAM-INF:BANDWIDTH=5768136,RESOLUTION=1920x1080,CODECS="avc1.640028,mp4a.40.5",AUDIO="audio" QualityLevels(5500000)/Manifest(video,format=m3u8-aapl)
#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=5768136,RESOLUTION=1920x1080,CODECS="avc1.640028",URI="QualityLevels(5500000)/Manifest(video,format=m3u8-aapl,type=keyframes)"
```
I also have what appears to be a Microsoft IIS Smooth Streaming Media config that I can share if that is helpful.

**Comment by gkatsev** [comment]
Any chance you can provide a version of the stream that don't restrict CORS?
But we can try and take a look.

**Comment by DaveStein** [comment]
@gkatsev The HLS manifest that is linked is what the player successfully uses on a non-azure domain. I am confused about the CORS bit. I see this manifest work fine here, which is on a different host.

https://ampdemo.azureedge.net/?url=https%3A%2F%2Fstreamprod-eastus-streamprodeastus-usea.streaming.media.azure.net%2Fb6343b1b-b5e4-45ec-8938-e100429f6737%2F33333b4b-8e8e-4dff-97e9-8c329be26a64.ism%2Fmanifest(format%3Dm3u8-aapl%2Caudio-only%3Dfalse)

**Comment by gkatsev** [comment]
For whatever reason I see a cors error on here https://videojs-http-streaming.netlify.app/?debug=false&autoplay=false&muted=false&minified=false&liveui=false&partial=false&url=https%3A%2F%2Fstreamprod-eastus-streamprodeastus-usea.streaming.media.azure.net%2Fb6343b1b-b5e4-45ec-8938-e100429f6737%2F33333b4b-8e8e-4dff-97e9-8c329be26a64.ism%2Fmanifest(format%3Dm3u8-aapl%2Caudio-only%3Dfalse)&type=application%2Fx-mpegURL&keysystems=

> Access to XMLHttpRequest at 'https://streamprod-eastus-streamprodeastus-usea.streaming.media.azure.net/b6343b1b-b5e4-45ec-8938-e100429f6737/33333b4b-8e8e-4dff-97e9-8c329be26a64.ism/manifest(format=m3u8-aapl,audio-only=false)' from origin 'https://videojs-http-streaming.netlify.app' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header has a value 'https://livestream-cdn.adobe.io' that is not equal to the supplied origin.

**Comment by DaveStein** [comment]
@gkatsev let me find out what's going on here.

**Comment by DaveStein** [comment]
@gkatsev just wanted to give an update here. There is some issue with our CDN where it's mirroring the original request for a cache miss (we saw the origin header be netlify at some point). We are investigating with the CDN, so we can actually debug this thing. I'll go silent until it's resolved.

/cc @JFrankfurt

**Comment by DaveStein** [comment]
Just so this doesn't get stale... working on getting some weird CORS headers taken off. We should be set by next week 🤞 Then you'll have access to an entire HLS manifest where this happened! Huzzah.

**Comment by DaveStein** [comment]
@gkatsev @JFrankfurt CORS issue fixed! You should be able to debug now. Keep in mind this manifest will be slightly different from when it was live so it can be used as a replay rather than truly live content.

**Comment by JFrankfurt** [comment]
Just checking in to say we're still seeing this one in our js logs pretty frequently.

**Comment by gkatsev** [comment]
@DaveStein seems to be working well for me via https://videojs-http-streaming.netlify.app/?debug=false&autoplay=false&muted=false&minified=false&liveui=false&partial=false&url=https%3A%2F%2Fstreamprod-eastus-streamprodeastus-usea.streaming.media.azure.net%2Fb6343b1b-b5e4-45ec-8938-e100429f6737%2F33333b4b-8e8e-4dff-97e9-8c329be26a64.ism%2Fmanifest(format%3Dm3u8-aapl%2Caudio-only%3Dfalse)&type=application%2Fx-mpegURL&keysystems= now.
