### ISSUE TITLE
Conflict with Greensock/GSAP 3

### ISSUE THREAD

**Issue by gem0303** [videojs/video.js#6386]
## Description
Loading GSAP 3 and then VideoJS (in that order) breaks VideoJS. In my Codepen, the video is still playable, but VideoJS doesn't initialize and there's a few console errors. If I reverse the load order, everything works fine.

Codepen: https://codepen.io/gem0303/pen/WNbXzQR

Reported the issue on GSAP's forum here: https://greensock.com/forums/topic/22404-conflict-between-gsap-3-and-videojs/

The dev said there is an issue in how VideoJS declares window$1. He is adding something to GSAP to work around it but I thought I should report it here still.

## Steps to reproduce
1. Load GSAP
2. Load VideoJS
3. Initialize a player 
4. Observe console log errors

### Error output
"window$1.setTimeout is not a function"
"Uncaught ReferenceError: videojs is not defined"

**Comment by gkatsev** [comment]
We don't declare `window$1` manually but rather have rollup generate that. Since we `import` it, rollup basically does `window$1.default || window$1`. It seems like gsap is setting the property `default` on window.
There isn't really an easy way for us to work around this. The name `default` is super generic and using it for a library isn't the best thing.
However, we'll take a look at what we can do.

**Comment by DJ-PD** [comment]
I am on my way to start build a new website with use of VideoJS and GSAP 3 so I just would like to thank for the information and tips!

**Comment by jackdoyle** [comment]
GSAP was recently updated to 3.1 which has a workaround in place for this. Enjoy!

**Comment by gkatsev** [comment]
Thanks @jackdoyle!
I think our solution is to also have a non-umd build for just `<script>` usage.
