### ISSUE TITLE
Issues with playing mkv files

### ISSUE THREAD

**Issue by universegalaxy1112** [videojs/video.js#6442]
## Description
I have encoded .mkv files with 2 audio tracks and subtitle tracks inside itself.
The audio and subtitle tracks were switching between them in exoplayer, but not working in video.js.

## Steps to reproduce

1. mkv files can be played successfully with the default audio track , but not showing multiple audio tracks and even not showing any subtitle track.
 

## Results 
Not showing multiful audio tracks and not showing subtitle 
### Expected
I wanted to switch the two audio tracks and subtitle tracks between them.
 

#### videojs
Latest version
#### browsers
Chrome
#### OSes
Webos
### plugins
no plugin

**Comment by Dniel97** [comment]
As mentioned in [https://docs.videojs.com/tutorial-audio-tracks.html](https://docs.videojs.com/tutorial-audio-tracks.html) :
> Switching audio tracks for playback is not handled by Video.js and must be handled elsewhere

If you want to be able to switch languages you need to reencode your video according to HLS or DASH Guidelines ([https://support.brightcove.com/multiple-audio-tracks](https://support.brightcove.com/multiple-audio-tracks)). You need to create a master playlist which includes the two audio tracks in AAC and your video file in H264.

**Comment by gkatsev** [comment]
Most browsers do not support mkv files, and we don't support it either. Some browsers may be able to load the mkv file but likely not everything will work. For example, because webm is basically just mkv, you can load the mkv file in Chrome and the video may play if it's a codec that chrome supports but I've found that the audio rarely works.
In addition, for files like mp4s and what not, we generally hand it off to the browser to handle. I believe that Safari supports multiple audio tracks in mp4s and we will display those if the brwoser exposes them.
Generating HLS or DASH is definitely the most supported and our recommendation.
