### ISSUE TITLE
can't loop?

### ISSUE THREAD

**Issue by bsabiston** [videojs/video.js#646]
The 'loop' tag does not seem to work in Android, is that right?  

So I am trying to make it loop by using the 'ended' listener to got to time 0 and then play again.

Only when my 'ended' listener is called, the current time is already 0.  Setting the current time to 0 and playing again does not do anything.  

Is this broken?  The video clips are only a couple of seconds long, sometimes only even a second long.  Can it not handle that?

**Comment by cirovladimir** [comment]
Hi, sorry to bring this up again but I'm trying to loop a video on a mobile device (android phone, chrome browser) and it doesn't work. Though the same page works fine on Chrome Desktop (Mac).
I understand the [limitiation](http://android.stackexchange.com/questions/59134/enable-autoplay-html5-video-in-chrome) with 'autoplay' on mobile devices but I expected at least to be able to play the video just once and keep it looping afterwards. I know it can be done, since jwplayer works this way, you can see a demo [here](http://www.jwplayer.com/html5/autoloop/).
@mmcc the stack overflow question you mentioned is not linked, would you mind to repost it again to see if it helps... thanks!

**Comment by mmcc** [comment]
@cirovladimir looks like the link was malformed so it wasn't showing up. I've updated, but we should look into the root cause of this.

**Comment by cirovladimir** [comment]
Tried the suggestion on stackoverflow post but it didn't work.

[This reference](https://developers.google.com/web/fundamentals/media/video/quick-reference#video-element-attributes) from google developers says it should work on all browsers (mobile included).

I've been playing with this and it seems that the video needs to be fully streamed, for it to loop. I've tested on my android device the video on [this page](http://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_video_loop) and it did work. I've replaced the lengthy video on my page with the short one from the previous example and it did loop just fine (I've tested it with and without videojs). At the moment, I can't confirm this because of the duration of my original video, I'll try to keep it playing later this afternoon and will keep you updated.

thanks

**Comment by cirovladimir** [comment]
I've tested my original video on **safari and chrome for iOS** (iPad) and you can forward to near the end of the video or let it play completely and **it will loop.**

On **chrome for android** there are **some videos that do loop and some others that don't**. This is my [original video](https://www.youtube.com/watch?v=imtsDjndR4w), [this works](https://www.youtube.com/watch?v=dKi5XoeTN0k), and [this doesn't](https://www.youtube.com/watch?v=fqULJBBEVQE). I guess there is some issue with chrome for android :(

**Comment by mmcc** [comment]
Hrm...that's really strange :( 

Having the sources on YouTube makes it hard to take a look on our end since they process the videos after upload. Mind uploading the original sources you were trying to loop somewhere?

**Comment by cirovladimir** [comment]
I've used the videos from youtube (after processing) for my testing. I've downloaded them with [ClipGrab](http://clipgrab.org/) at 720p.
