### ISSUE TITLE
Feed raw data to player src with headers

### ISSUE THREAD

**Issue by minedun6** [videojs/video.js#6503]
First and foremost,
I think that my issues is not related to the "video.js" player so I'd like to apologize beforehand.

# what I'm doing

I'm using an external api to get a file and display it in a generic HTML 5 video player.
The thing is that the api call needs to have a SESSION_ID header set beforehand.

When I test the api in POSTMAN, this is a glimpse of the result 
```
 ftypisomisomiso2avc1mp41free鑹mdat�����E���H��,� �#��x264 - core 157 r2969 d4099dd - H.264/MPEG-4 AVC codec - Copyleft 2003-2019 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x1:0x111 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=0 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=22 lookahead_threads=3 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00�E]e��/���[�,�5�����/����*P4e�<���04���`@�-�f[ j�Z�t� ��E�q1�O�;�#��Z�J(Kh��o�/+�kt��?�R��(��H�|�^�޸]����-�ӵ �j�x�g�z�7β׈Tb̲4*N4s3��_&�Y�In�����z��L��u��N|Cq�]\WGѣ �r>o�J�,j�2gu���$���ZP��kw���4J�}Wc���i�sQ��Z��w�`$�6�<_�Xv�ku���n���H����U�1��j
�+�,�:�T�}3�q�Fj���
�ySK���(���\P���Ո���xH�cX�I�����c�Q6r560N��u���M+��k����.BV���W#��iYkd����
3�]��6z=d}_Ԑ>d܀�"H�!$$W@��ۂa��7G�m����b&�em�w*￘Q������~5��ĳ,o�
�%l	#F�I��Vg�9K���+޻��I���-�BR������wBֽ�*)��;A�z(g�ܟg�ј
SZ�y��[�C���q3,>z/���s���!�Y㑥����7Q�F�ZT64��No�^c.ᡠ��:����(�l��\E����Q)`W�k��0�b��RH�@`�Z	�\҂�`2���yy{#���M�X�&ޕ�	I��_��z�@��د�r�ˇf-�y6����D�����y��T��7e	�9:�$�Em�z'�U�Z�A�$�I��N��Z�T'����7�GŒ+�#���rW(�Q�`@�(�9K
ǃ:�5�FEl.��C���|��"a,�N�"p�����Xs�13��șf�Q?���Uj�c ��EѰ���w��'�	��ϔ���^�
�Q�?�wz����1�c#� L�^�i5E���k�t`�5k�j��z+�~���B~�kLvH�c�8`�!��y���]�z^l�j|�|q�R��-fO/���iiyG�Lp�@���������1�?$Tǥ6B�Q�y$q�%�����R^L�l���}��g|���M�>ݞ!�2 	�2l�I~��C��X'���zSH>�g�Cܥ�c�5�W~/�+�
7�^�!�5a��5߭��y_��r�T�us���+
```

I'm assuming that this is the file's raw data.
Problem is that sometimes, the files are ranging from 10MB to 500MB (even more).

Can I task the "video.js" player to do the request instead of the backend and stream the file back to the player (progressively loading the video) ?

**Comment by gkatsev** [comment]
Video.js doesn't support anything like that naively. We have VHS which does some of what you need but it is specifically set up to handle HLS or DASH streams and my recommendation would be to convert your stream to HLS or DASH and just use native functionality of Video.js.

Alternatively, you'll need to package the data up into fmp4s to be able to put it into [MSE](https://www.w3.org/TR/media-source/). We have https://github.com/videojs/mux.js but it isn't set up to take raw h264 data (assuming that's what you're getting), though there's a [PR](https://github.com/videojs/mux.js/pull/200) to add it, but we're unlikely to merge it in due to limited bandwidth. Once you have it repackaged you can then input the data into the MSE source buffer.

Hope this sets you on the right path.
