### ISSUE TITLE
DASH MPEG + Clearkey

### ISSUE THREAD

**Issue by georgio-sd** [videojs/video.js#6512]
I am currently using Shaka Player but I want to switch to Video.js in order to use watermarks.

I use dash mpeg with clearkey encryption. I have a php script installed like https://domain/dash-key.php, which returns keys in a format like this

`[{"key":"nGW01Bdr/Y+/mENcWKyyrQ==","key_id":"ASNFZ4mrze8BI0VniavN7w==","pssh":[{"uuid":"1077efec-c0b2-4d02-ace3-3c1e52e2fb4b","data":"AAAAAQEjRWeJq83vASNFZ4mrze8AAAAA"}]}] `

Also I have a link on a video like this https://domain/dash/video.mp4/manifest.mpd

Could you give me an HTML example how I can use the clearkey URL and the video URL to show the video in a web browser? Video.js has a few plugins, which I am supposed to use but it's not clear how to form an HTML file with all the parameters.

**Comment by gkatsev** [comment]
You'll want to grab videojs-contrib-eme and set it up with the source and your clearkey options. There are examples in the contirb-eme readme: https://github.com/videojs/videojs-contrib-eme#setting-options-per-source
You can also probably use `licenseUri` and `certificateUri` directly instead of using the get methods if the data returns from the backend is the appropriate one to be used directly.
