### ISSUE TITLE
vhs json source issue

### ISSUE THREAD

**Issue by sampathkumar7** [videojs/video.js#6529]
## Description
Use plugin concat along with http-streaming
`player.concat({
  manifests: [{
    url: 'https://s3.amazonaws.com/_bc_dml/example-content/bipbop-advanced/bipbop_16x9_variant.m3u8',
    mimeType: 'application/x-mpegURL'
  }, {
    url: 'https://s3.amazonaws.com/_bc_dml/example-content/bipbop-advanced/bipbop_16x9_variant.m3u8',
    mimeType: 'application/x-mpegURL'
  }],
  targetVerticalResolution: 720,
  callback: (err, result) => {
    if (err) {
      console.error(err);
      return;
    }
    console.log(result);
    player.src({
      src: `data:application/vnd.videojs.vhs+json,${JSON.stringify(result.manifestObject)}`,
      type: 'application/vnd.videojs.vhs+json'
    });
  }
});`
one url is vod and another is live when player stared playing its not seeking to live
what is actual branch or version i should use to work with vhs-json-source not with url.

I want to use parsed manifest.

**Comment by gesinger** [comment]
Hey @sampathkumar7 , the concat function only works for VOD manifests right now. For playing a VOD then live stream after, you may be better off looking at a playlist plugin.

**Comment by sampathkumar7** [comment]
Thank you.
One more doubt is there any option with playlist to seek past to 1hour or 2 hours from seekbar.

**Comment by gkatsev** [comment]
Can you elaborate on what you mean?
If you want to be able to seek from the VOD manifest to the live manifest with the playlist plugin, then you can't because they are treated as separate videos.
If you want to be able to seek within your live video, you can enable the `liveui` option in Video.js. You also need to make sure that the there are 1-2 hours of segments in the window displayed inside the live manifest.
