### ISSUE TITLE
HLS AES encryption key not secured

### ISSUE THREAD

**Issue by abdelazizk** [videojs/video.js#6629]
what is the best way to secure the HLS encryption key?

**Comment by gkatsev** [comment]
I think that is a bit beyond the scope of this project. HLSe is mostly used to protect the media at rest on the CDN.
You can try and using cookies or tokens that then gets passed with the request, for example with [`beforeRequest`](https://github.com/videojs/http-streaming#hlsxhr), though, that won't help with Safari/iOS because we use native playback there.
For truly secure playback you should take a look at DRM.
