### ISSUE TITLE
Player "ID" is already initialised.

### ISSUE THREAD

**Issue by d4lv** [videojs/video.js#6641]
what is wrong?? i cant find how to fix this error "video.min.js:19 VIDEOJS: WARN: Player "uniqueID" is already initialised. Options will not be applied."

this is my code: https://pastebin.com/b3mmJ174

**Comment by mister-ben** [comment]
`data-setup` here causes the player to be initialised when the Video.js script runs.

```
<video id="uniqueID" class="video-js vjs-fluid vjs-16-9" controls ... data-setup='{}'>
```

Then you try to set up the player with options here:

```
videojs('uniqueID', {
 
    controls: true,
    plugins: {
 
    }
  }, function(){
    var player = this;
    ...
```

As the warning message says, the options have no effect since the player was already initialised. In this case it's irrelavant as the options are redundant, but if you do want to set up the player by passing options, remove the `data-setup` attribute.

**Comment by d4lv** [comment]
> `data-setup` here causes the player to be initialised when the Video.js script runs.
> 
> ```
> <video id="uniqueID" class="video-js vjs-fluid vjs-16-9" controls ... data-setup='{}'>
> ```
> 
> Then you try to set up the player with options here:
> 
> ```
> videojs('uniqueID', {
>  
>     controls: true,
>     plugins: {
>  
>     }
>   }, function(){
>     var player = this;
>     ...
> ```
> 
> As the warning message says, the options have no effect since the player was already initialised. In this case it's irrelavant as the options are redundant, but if you do want to set up the player by passing options, remove the `data-setup` attribute.

nothing changes same error
the problem is the play action won't work i press the icon but nothing.
