### ISSUE TITLE
Seek bar does not show after a long enough seekable interval is available

### ISSUE THREAD

**Issue by hernanrz** [videojs/video.js#6646]
## Description

If the player starts in liveui mode with the seek bar hidden (for example, when a livestream just started), and the seekable range expands over time, the seek bar should appear after a long enough seekable interval is available, without reloading the player.

## Steps to reproduce

1. Start a video.js player with liveui enabled
2. Seek bar is hidden (there's not enough seekable range available yet)
3. Wait for enough seek range to be available

### Expected
Seek bar should be displayed

### Actual
Seek bar does not show

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
7.8.1
#### browsers
Chrome 84 and probably others

#### OSes
Windows 10

---

We've tried adding the following settings to the videojs options

```js
videojs(container, {
   ...options,
   liveTracker: {
        trackingThreshold: 0,
    }
});
```

but that just forces the seek bar to be available even when there's nothing to seek yet

**Comment by hrn4n** [comment]
it seems that this event handler in `live-tracker.js` controls the display of the progress control bar

```js
  /**
   * handle a durationchange event on the player
   * and start/stop tracking accordingly.
   */
  handleDurationchange() {
    if (this.player_.duration() === Infinity && this.liveWindow() >= this.options_.trackingThreshold) {
      if (this.player_.options_.liveui) {
        this.player_.addClass('vjs-liveui');
      }
      this.startTracking();
    } else {
      this.player_.removeClass('vjs-liveui');
      this.stopTracking();
    }
  }
```
While testing I found that the durationchange event is only triggered on player startup.

My question is, is the durationchange event only supposed to be triggered once?

**Comment by DispatchCommit** [comment]
I was having this issue as well and found the `trackingThreshold` property as well. On average I have 10 seconds of delay for HLS. I told my server to only send a "live" command to clients after 15 seconds so that a client only attempts to load after about 5 seconds of the stream are available. Doing that has worked well for me so far:

![image](https://user-images.githubusercontent.com/45262335/87115264-93f45d80-c227-11ea-9de4-786c0ac8f130.png)

Additional testing and info:
https://github.com/videojs/http-streaming/issues/378#issuecomment-656450980
