### ISSUE TITLE
Release version of 7.8.1 ?

### ISSUE THREAD

**Issue by jinyeng** [videojs/video.js#6670]
Any dates on when 7.8.1 will be available as release version ? Its stuck on pre-release for a while and we would really like a release version for our upgrade.

**Comment by gkatsev** [comment]
It's mostly been stuck because I've forgotten to update it because I've been busy and distracted with other things.
We're going to be backporting https://github.com/videojs/video.js/pull/6644 to the 7.8 release branch and I'll update 7.8.2 to latest with that then. Should be soon.
In the meantime, I would definitely say you can start using 7.8.1 directly.

**Comment by jinyeng** [comment]
Awesome! Thanks appreciate your quick response.

**Comment by gkatsev** [comment]
[7.8.2](https://github.com/videojs/video.js/releases/tag/v7.8.2) is now out as latest.
