### ISSUE TITLE
How to disable active plugins with option object before calling video()

### ISSUE THREAD

**Issue by strix25** [videojs/video.js#6686]
I have 2 plugins enabled: ima and ads. And after all the ads are done playing, I would like to play normal .mp4 content. To do that I assume I have to disable both plugins.

Is it possible to disable active plugins before calling video() function, by passing playerOptions object? 

Something like: 
```typescript

this.playerOptions.plugins = {
  ads : false,
  ima : false
}
this.player = videojs(this.playerDom.id, this.playerOptions, () => {})
```

So when I console.log(this.player); both plugins in activePlugins_ object would be set to false
![image](https://user-images.githubusercontent.com/16744352/83659992-8ca4b900-a5c4-11ea-9516-13c99bce3a32.png)

**Comment by mister-ben** [comment]
There's no standard way to deactivate a plugin unless the individual plugin has implemented some sort of dispose lifecycle. In any case, you don't deactivate contrib-ads and videojs-ima in order to play the content video, the plugins handle intercepting the content playback to play ads and then playing the content video.
There are samples of using videojs-ima in that repository: https://github.com/googleads/videojs-ima

**Comment by strix25** [comment]
But the problem I have it if I pass in location to video .mp4 file, I get:
 AdLoader error: 1010: the ad response was not understood and cannot be parsed.
like this: `options.adTagUrl = "localhost:3000/video.mp4`
Should I pass url  to the video in some different way when I want to play content instead of ads ? 
I can not find any example like this on the docs page you sent

**Comment by strix25** [comment]
@mister-ben that worked, thank you!
