### ISSUE TITLE
Failed to execute 'replaceChild' on 'Node': The node to be replaced is not a child of this node. 

### ISSUE THREAD

**Issue by travisbader** [videojs/video.js#6699]
## Description
Briefly describe the issue.
Include a [reduced test case](https://css-tricks.com/reduced-test-cases/), we have a [starter template](https://codepen.io/gkatsev/pen/GwZegv?editors=1000#0) on JSBin you can use.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. I am not sure the exact steps to repro, but I theorize this crash is surrounding disposing of the video player and the updating of the remaining time

### Expected
Don't throw errors

### Actual
The error is thrown

### Error output
![Screen Shot 2020-06-09 at 1 58 57 PM](https://user-images.githubusercontent.com/7252621/84199068-6a45ec00-aa59-11ea-917d-a3972bbc5b5c.png)
## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
7.7.6
#### browsers
Chrome for sure, haven't seen in other browsers yet
#### OSes
unknown
### plugins
    "@silvermine/videojs-airplay": "^1.0.0",
    "@silvermine/videojs-chromecast": "^1.2.1",
    "videojs-contrib-quality-levels": "^2.0.9",
    "videojs-hotkeys": "^0.2.25",
    "videojs-vtt.js": "^0.12.6"

**Comment by travisbader** [comment]
PR submitted

**Comment by gkatsev** [comment]
Like https://github.com/videojs/video.js/issues/5706, it would be good to figure out the root cause. Often times these issues and fixes with null checks just hide a worse problem that would be better if it were fixed.

**Comment by dansgithub** [comment]
Hey everyone, is there any update on this issue? Currently we have many error logs coming from this one and there seems to be no fix!

**Comment by JustinMGaiam** [comment]
This is also our highest error rate in our NewRelic Browser monitoring (we use VideoJS through the Brightcove player) so anything that moves towards fixing this error would be very helpful.

**Comment by travisbader** [comment]
Now three users all reporting high quantity of errors.  Im ok if you don't merge my naive fix for reasons of wanting to find the root cause, but can you please find the root cause! We still have an enormous number of errors emitting out of this and would appreciate any attention you can give it

**Comment by gkatsev** [comment]
Are all of you using newrlic for error tracking?

Also, can you give me some more info about your environments? I've tried to reproduce it a bit but I've been unable to.

**Comment by travisbader** [comment]
We are using raygun as our error reporting tool.  We use video.js in a react app similar to a netflix like product.  I suspect that this issue comes up when the video.js player is disposed when swapping to a new video

**Comment by gkatsev** [comment]
Wonder if it's a react? Have a sample of how the player is disposed and a new source used?

**Comment by Darkein** [comment]
Hi there, we have exactly the same problem.

Our app use Angular 8, not react. We can't reproduce it, but some of our users have it (about 1%) whatever the browser or the OS.
We contacted a user who has exactly the same computer than me (macbook pro 13"2017). He has the problem everytime, with the latest version of Chrome.

Could we just suppress the error while we try to find why it crash? Because we can't catch the error ourselves, it crash the entire application. And like @JustinMGaiam we have homemade log/error tracking, filled by this error.

**Comment by sebastien-f** [comment]
We also have the issue on an angular 8+ application. We upgraded to the latest version of videojs and pushed to production on November 9. We got so many errors that we exceeded our Sentry quota due to it. You can see the grap of errors from the month here : https://imgur.com/a/V6H5E2l

Here it is compared to other issues : https://imgur.com/a/xSIgfCy so you can have an idea of what volume difference we are talking.

We are investigating the issue on our side (as we saw that our implementation was different than the one in the documentation) to see if can come from that.

**Comment by kontrollanten** [comment]
We're facing this as well, using PeerTube 2.4.0 (Angular 11). Our sentry quota was eaten up as well. PeerTube doesn't provide source maps so I can't dig deeper into where the actual source is (I just assume it is video.js since other people are facing the same issue here).

@sebastien-f @travisbader @JustinMGaiam @Darkein Do you have any stack traces from NewRelic/Sentry that you can provide?

**Comment by sebastien-f** [comment]
@kontrollanten Sorry, can't provide any it's a project under a very strict NDA.
Also for what it's worth, we redid the integration to follow more closely one of the documentation and don't have any error or warning now. We will be reenabling Sentry at the start of next year after updating it again to be sure to include @gkatsev fix (thank you for that btw !)

**Comment by nayaaltahan** [comment]
Using Google translate to translate a page that load videos causes this error, on my case.

**Comment by chaitanyabd** [comment]
Confirmed that adding translate="no" on the DIV that encapsulates videojs prevents this issue entirely. 

Ref: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/translate
