### ISSUE TITLE
Immediately restart the player if an error occurs

### ISSUE THREAD

**Issue by Raino** [videojs/video.js#6744]
Hello!
I found a similar problem (https://github.com/videojs/videojs-contrib-hls/pull/902, https://github.com/videojs/video.js/issues/1805, https://github.com/videojs/video.js/issues/3725, https://github.com/videojs/videojs-contrib-hls/issues/1030) and did not fully understand the final way to solve it.
I tried it:
```
var options = {
  plugins: {
    reloadSourceOnError: {}
  }
};
var player = videojs('myVideo', options);
```
but the player still returned an error and did not restart. 
Please help us figure out how to solve this problem. 
Thanks!

**Comment by gkatsev** [comment]
I tried it locally with initializing the plugin in the player options. Then, I ran `player.error({code: 4})` and I could see the player reload the current source.
Can you create a live minimal, complete, verifiable example you can share?

**Comment by Raino** [comment]
@gkatsev It will be difficult, but I can try. But first I want to clarify, during your initialization, the player did not show any error messages at all? Perhaps you can send me Your code and I will try to compare it with my own? Where you connect libraries, which ones, how you call them, and so on.

**Comment by gkatsev** [comment]
So, I was going to make an example and noticed that it was working with HLS or DASH videos but not with mp4s. This is because the plugin was specifically written with our playback engine in mind and was never tested with other sources.
The example page: https://codepen.io/gkatsev/pen/GRoxYwX?editors=1010
You can comment out the mp4 or the m3u8 to try one or the other and then click on the "create a fake error" button to trigger a fake error that will cause the source to reload for the m3u8 but not for the mp4.

**Comment by gkatsev** [comment]
Made a PR with a fix https://github.com/videojs/http-streaming/pull/893.

**Comment by Raino** [comment]
@gkatsev I tried creating the error twice. The first time everything worked, and the second time the video was not interrupted, but an error message appeared on top of the player and it did not go away

**Comment by gkatsev** [comment]
The plugin is set up to not retry if there are multiple errors in quick succession. If you need that, you'll want to write your own plugin (or make edits based on the existing piece of code).

**Comment by Raino** [comment]
@gkatsev In https://github.com/videojs/video.js/issues/3725 in the message from **brodjustice** was an example of the code. I take it it's just for restarting the player? Can you tell me if it's relevant? Since I see working with objects of the `.rtmp-video-js` classes there. Or perhaps there are other ways to make the player initialization cyclic?

**Comment by Raino** [comment]
@gkatsev Maybe You can advise me some methods or plug-ins, so that when the HLS stream is bad, the player does not give an error, but always tries to connect?

**Comment by nikhil0897** [comment]
@gkatsev @Raino 
I am encountering a problem while trying to fallback from hls to mp4. I want to have my primary source as m3u8 and secondary as mp4. So if the player doesn't find m3u8 I want it to fallback to the next src and start playing the mp4 one. But my player doesn't stop trying to fetch the m3u8 file even when it's not there.
I get this in my console `VIDEOJS: WARN: Problem encountered with the current HLS playlist. Trying again since it is the only playlist.`

I am trying this in React with video.js v7.8.4 and this is my code:

```
  const options = {
  fill: true,
  fluid: true,
  responsive: true,
  preload: "auto",
  controls: true,
  width: 720,
  height: 300,
  html5: {
    vhs: {
      enableLowInitialPlaylist: false,
      smoothQualityChange: true,
      overrideNative: true
    }
  },
  playbackRates: [0.25, 0.5],
  sourceOrder: true
};

export default function VideoViewer(props) {
  const { src } = props;
  const classes = useStyles();
  const videoRef = useRef(null);
  const [player, setPlayer] = useState(null);

  useEffect(() => {
    const videoPlayer = videojs(videoRef.current, options);
    setPlayer(videoPlayer);

    return () => videoPlayer.dispose();
  }, []);

  useEffect(() => {
    if (player !== null) {
      player.src([
        {
          src: src.replace(".mp4", "/master.m3u8"),
          type: "application/x-mpegURL"
        },
        {
          src,
          type: "video/mp4"
        }
      ]);
    }
  }, [src, player]);

  return (
    <div data-vjs-player>
      <video ref={videoRef} className="video-js vjs-big-play-centered" />
    </div>
  );
}

VideoViewer.propTypes = {
  src: PropTypes.string.isRequired
};
```

Am I missing anything here or did anything wrong? Please let me know as I am stuck on this playback thing for 2 days now!
Any kind of help is appreciated, thanks!

**Comment by Feofilakt** [comment]
@gkatsev, Unfortunatly, your example doesn't work. Steps:
1. Play
2. Enable the dev tools "network blocking" feature for address "https://d2zihajmogu5jn.cloudfront.net"
3. Wait until player stops
4. Disable "network blocking"

![image](https://user-images.githubusercontent.com/5498396/135203872-f3105673-c9d5-4f74-8f04-0b5f478b24a7.png)

**Comment by Feofilakt** [comment]
@gkatsev, Unfortunatly, your example doesn't work. Steps:
1. Play
2. Enable the dev tools "network blocking" feature for address "https://d2zihajmogu5jn.cloudfront.net"
3. Wait until player stops
4. Disable "network blocking"

![image](https://user-images.githubusercontent.com/5498396/135203872-f3105673-c9d5-4f74-8f04-0b5f478b24a7.png)
