### ISSUE TITLE
VideoJS 7 with Cast and Airplay

### ISSUE THREAD

**Issue by Brandonza** [videojs/video.js#6802]
Hi

I have been looking around for a VideoJS plugin that supports VideoJS 7, I have tested a few of them:
- https://github.com/silvermine/videojs-chromecast 
- https://github.com/silvermine/videojs-airplay
- https://videojs.electroteque.org/chromecast
- http://www.lib4dev.in/info/kim-company/videojs-chromecast/24055163). 

None of them seem to support VideoJS 7. 

Does anyone have a solution to being able to add a cast button?

**Comment by gkatsev** [comment]
A version written for Video.js 6 will work for Video.js because the main change in Video.js 7 is removal of IE8-10 support. Though, if the version ranges in package.json don't match, that may be a bit tricky.

silvermine's chromecast plugin has the peerDeps version range for Video.jas a >=6 <8, so, it should work. And the airplay silvermine plugin is also >=6. So, both of these should work.
The electroteque demo seems to be using Video.js.
Though, the kim-company one seems to be archives and no longer maintained.

Unfortunately, we don't maintain any of these plugins, but they seem to be supporting Video.js 7. If you can confirm that things don't work, I would open an issue against the respective plugins.

**Comment by DJ-PD** [comment]
Similar issues here with Video.js v7.
https://github.com/PatocheLJ/videojs-google-chromecast/issues/5

NOTE. I can get Silvermines Chromecast to work with Video.js v7 even if it's far away from plug and play especially when you like a more proper Ui in audio mode.
https://github.com/silvermine/videojs-chromecast/issues/108
