### ISSUE TITLE
HLS streaming issues on v7.9.3 

### ISSUE THREAD

**Issue by boris-savic** [videojs/video.js#6813]
## Description
There are certain playback issues with new version with HLS live streams when the stream starts. The stream will start and playlist manifest will contain for example:

```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-TARGETDURATION:6
#EXT-X-DISCONTINUITY
#EXTINF:5.000,
0.ts
#EXTINF:5.133,
1.ts
```

Video will play normally while the playlist is still _warming_ and filling in the chunks. Our stream server keeps maximum of 5 video chunks in the playlist. 

As soon as the playlist reaches 5 chunks and changes to as pasted below, the player displays a loader and never recovers. Chunks are being downloaded normally in the background (Network tab shows normal activity)

```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:1
#EXT-X-TARGETDURATION:6
#EXTINF:5.133,
1.ts
#EXTINF:5.133,
2.ts
#EXTINF:5.634,
3.ts
#EXTINF:5.900,
4.ts
#EXTINF:5.533,
5.ts
#EXTINF:5.733,
6.ts
```

This issue did not exist in version v7.8.2 and there is no error/warning messages in the console logs. If user refreshes the player works as expected, the issue starts only when the playlist reaches max chunks, removes `#EXT-X-DISCONTINUITY` and starts incrementing the `#EXT-X-MEDIA-SEQUENCE:1` instead. 

Hope this provides enough information. 

### Expected
Player should continue playing the stream normally

### Actual
Player displays loading animation and never recovers. 

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
v7.9.3
#### browsers
Chrome and Firefox both tested 
#### OSes
Windows, Linux, MacOS
### plugins
No plugins used

**Comment by gkatsev** [comment]
I'm not sure why it's broken now but that isn't a valid HLS stream. If you have a discontinuity and remove it you must have a discontinuity sequence number too.

From https://tools.ietf.org/html/draft-pantos-hls-rfc8216bis-07.html
>    If the server wishes to remove segments from a Media Playlist
   containing an EXT-X-DISCONTINUITY tag, the Media Playlist MUST
   contain an EXT-X-DISCONTINUITY-SEQUENCE tag.  Without the EXT-X-
   DISCONTINUITY-SEQUENCE tag, it can be impossible for a client to
   locate corresponding segments between Renditions.
>
>  If the server removes an EXT-X-DISCONTINUITY tag from the Media
   Playlist, it MUST increment the value of the EXT-X-DISCONTINUITY-SEQUENCE
   tag so that the Discontinuity Sequence Numbers of the
   segments still in the Media Playlist remain unchanged.  The value of
   the EXT-X-DISCONTINUITY-SEQUENCE tag MUST NOT decrease or wrap.
   Clients can malfunction if each Media Segment does not have a
   consistent Discontinuity Sequence Number.

Can you test your stream on https://videojs-http-streaming.netlify.app/?

**Comment by boris-savic** [comment]
Hi,

the player on the link https://videojs-http-streaming.netlify.app/ works. 

We're using Nginx RTMP like many others - i realise it was not updated in very long time, but I'm guessing that it should still work with new videojs release given that v7.8.2 does not have this problem

I'd be happy to provide more information/logs to help find the core reason for this if needed.

**Comment by gkatsev** [comment]
If it works on https://videojs-http-streaming.netlify.app/ then it'll be fixed in an upcoming Video.js minor release as that'll be the next version of the playback engine in Video.js.
