### ISSUE TITLE
VideoJs Thumbnails preview VTT file integration

### ISSUE THREAD

**Issue by sunilstg** [videojs/video.js#6833]
Hi, 

Can you please help in doing setup of VideoJS VTT thumbnails preview images? I have followed the instructions given in - https://github.com/dirkjanm/videojs-vtt-thumbnails but still VTT is not working.  Can you please review below sample file file? 

https://smedia2.intoday.in/demo_poc/vjs_support/example.html

Also if there is any other setup for VTT thumbnails on seekbar preview please share example file setup. 

Many thanks for your valuable time for help. 

Best regards,
Sunil Kumar

**Comment by gkatsev** [comment]
Looks like a timing issue. Since you are initializing the thumbnails plugin on player init, it doesn't have the text track loaded at the time.
If you initialize it on, say, `loadedmetadata` with `video.thumbnails({width:120,height:90,basePath:"//indiatoday-pdelivery.akamaized.net" })` it works (though, the image end point isn't working for me)
