### ISSUE TITLE
"You aborted the media playback" issue in Firefox

### ISSUE THREAD

**Issue by usman64** [videojs/video.js#6961]
## Description
I have a video player to play videos in the browser and a download button to download the video. When I click the download button while using Firefox the video playback throws an error "You aborted the media playback" however the video keeps running in the background. It works fine in other browsers.

## Results
Error while using Firefox.

### Expected
Should work fine with all browsers.

### Actual
Throws error with Firefox.

### Error output
VIDEOJS: ERROR: (CODE:1 MEDIA_ERR_ABORTED) You aborted the media playback

## Additional Information
Please include any additional information necessary here. Including the following:

#### videojs
what version of videojs does this occur with? 
7.0.0

#### browsers
what browser are affected? 
Firefox

**Comment by LITTMER** [comment]
请问问题解决了吗？

**Comment by gkatsev** [comment]
Unfortunately, there isn't enough information to help out here. Firefox playback should be working, though.
I'm not sure what the download button does.
Video.js 7.0.0 at this point is super old, I would recommend updating to the latest version, 7.12 or 7.13.

Since this issue is quite old, I'm going to close it. If an example can be provided and it's still an issue with Video.js 7.12 or 7.13, I'd be happy to re-open and investigate.
