### ISSUE TITLE
Eventhandler for TextTrack modechange does not fire in Safari

### ISSUE THREAD

**Issue by PabloGS** [videojs/video.js#6996]
## Description
Eventhandler for TextTrack modechange does not fire in Safari.

## Steps to reproduce
Add one or more VTT Tracks to your player.

Once your player is ready add an eventHandler to your tracks and a callback function.

Example:
player.ready(
  function () {
    video = this.tech_.el_;  
    var textTrackElements = player.textTracks();
    for(var i=0; i<textTrackElements.length; i++){
      console.log("modechange event connect")
      player.on(player.textTracks()[i], "modechange", textTrackChanged);
    }
 }         
);
function textTrackChanged() {
  console.log("modechange triggered")
}

### Expected
Call of eventHandler function textTrackChanged() when selecting different subtitles.

### Actual
This works for Chrome Edge and Firefox but not Safari.

### Error output
Safari throws:     
  'Invalid target; must be a DOM node or evented object.'
in video.js:2571

#### videojs
JS 7.10.2
#### browsers
Safari 14 (MacOS, doesn't work on mobile either, but didn't check if the same error is thrown)
#### OSes
MacOS 10.15, iOS 14, iPadOS 14

**Comment by isabelleingato** [comment]
Looked into this a bit and am also able to reproduce in Safari 14 using https://github.com/videojs/video.js/blob/main/sandbox/combined-tracks.html.example as the sample (looked good in Chrome).

Agree that the issue seems to be with `TextTrack` not being validated as evented (https://github.com/videojs/video.js/blob/main/src/js/mixins/evented.js#L42). Seems like it's because `object instanceof EventTarget` is not working as expected in Safari here and is returning false. At first glance, seemed like it could be related to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/instanceof#instanceof_and_multiple_context_e.g._frames_or_windows or otherwise maybe WebKit differing from the spec (https://bugs.webkit.org/show_bug.cgi?id=216816).

As a workaround, I am thinking one could sub in checking for the expected properties of `EventTarget` on that line.

**Comment by gkatsev** [comment]
`modechange` is basically an internal event to Video.js that is done when our [emulated tracks](https://docs.videojs.com/tutorial-text-tracks.html#emulated-text-tracks) are being used. On Safari, by default, native tracks are used. What you're looking for instead is to listen to the `change` event on the text track list object, i.e., the object returned from `player.textTracks()`.
I would *strongly* recommend against listening to `modechange` on individual tracks and listening to `change` on the track list object instead.

```js
var trackList = player.textTracks();
trackList.addEventListener('change', function(e) {
 // look through the trackList to find the tracks that had their mode changed
});
```
