### ISSUE TITLE
vjs-fluid is broken in Chrome

### ISSUE THREAD

**Issue by DaveZMB** [videojs/video.js#7018]
## Description
When using the class vjs-fluid in Chrome, if the video is close to making the vertical scrollbar appear, they will flash on and off constantly.

- https://codepen.io/DaveZ123/pen/xxEpPmb?editors=1100
- Here's a screen recording of it happening https://recordit.co/ym63ScNX3X

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Open Chrome
2. Go to https://codepen.io/DaveZ123/pen/xxEpPmb?editors=1100
3. Adjust your browser height & width so the video is just almost tall enough to cause vertical scroll bar

### Expected
I expect the vertical scroll bar to show when needed and not show when they are not needed.

### Actual
The vertical scroll bar flashes on and off making the video height & width change.

### Error output
N/A

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
7.11.1

#### browsers
1. Mac / Chrome v87.0.4280.88
2. PC / Edge v87.0.664.66

#### OSes
1. Mac 10.15.7
2. PC Windows 10 v2004 OS Build 19041.685

### plugins
None (the same thing happens in private mode)

**Comment by gkatsev** [comment]
This issue totally got lost in the churn. I think this is less an issue with vjs-fluid itself and more of a thing that can happen with CSS. If I swap from padding-top to using `aspect-ratio` to have the same behavior, I get the same jiggly behavior.
At a first glance, I'm not sure that there's really anything that we can do to fix it from within Video.js itself. Basically, what happens is that due to the size, the scrollbar should be shown, but then the element resizes to account for the smaller display area. But because the element is now smaller, there's no longer a need for scrollbars. So, the scrollbars hide and the element grows a bit. Rinse and repeat.
One fix in the linked example is to set `overflow: hidden` or `overflow: scroll` on the body element.

**Comment by DaveZMB** [comment]
Hi @gkatsev thanks for the reply!

We used permanent scrollbars to solve this issue but our UX team was not happy with that trade-off so I had to ask about it.

After doing more research it seems to affect plain / native HTML5 video players as well, but we were hoping the video.js player would have some sort of work around. We've also filed a bug report with Chrome but haven't heard back.

**Comment by gkatsev** [comment]
Thanks for confirming!
Do you have a link handy for the chrome bug? Would be useful in case someone comes looking in the future.
