### ISSUE TITLE
Unable to set playback rate when using custom audio context

### ISSUE THREAD

**Issue by qhyun2** [videojs/video.js#7150]
## Description
The only way I am aware of  boosting audio past 100% with vjs is to setup a slightly janky custom audio context with a gain node.
**This makes changing the playback rate not work.** I understand that `player.tech()` is not really intended to be used but it seems like this is the only way to boost audio volume.

Is there something I am doing wrong here? If so what is the best way be able to both boost volume past 100 as well as control playback rate?

## Steps to reproduce
https://codepen.io/qhyun2/pen/gOgPKqP

**Comment by gkatsev** [comment]
We used to hide the tech a lot, but you can use it for the times when the regular API isn't sufficient. Now we just log a warning (which can be turned off by passing any argument into the tech method, I often use `true`) because most times people shouldn't be mucking around in the Tech.
As for your example, it seems to be working for me, aside from not getting any audio I can change the playback rates using the menu and can see the video play back quicker or normal again.

**Comment by qhyun2** [comment]
Thanks for the quick reply @gkatsev , I'm wondering what browser you are using?

After looking around a bit more I've come to the conclusion that the AudioContext API and HTML playbackRate don't mix well.
Even using volume boosting Firefox addons, which probably use the same API, seem to mess with the video playback rate.

If anyone knows a good way of boosting volume past 100% while simultaneously changing the playback speed, please re-open this issue and let me know.

My solution for now would just be to boost the volume with `ffmpeg` before serving. Feel free to close the issue now.

**Comment by qhyun2** [comment]
## Solved!
This is a bug in Firefox 😒 
https://bugzilla.mozilla.org/show_bug.cgi?id=1517199

Demo without VJS: https://codepen.io/qhyun2/pen/abpZmMB
