### ISSUE TITLE
onError not getting triggered

### ISSUE THREAD

**Issue by KVPasupuleti** [videojs/video.js#7151]
## Description

In our React-based web application, we are using plugins like 

1. @videojs/http-streaming - v1.12.0
2. videojs-contrib-dash - v2.11.0
3. videojs-contrib-quality-quality-levels - v2.0.9
4. videojs-http-source-selector - v1.1.6

for getting quality change option and dash and hls support for the player. In case of any overload on the server, we are using some fallback URLs so that we could change the src dynamically. We are doing this by using `error` event on the player. 

When rendering the sources, we are giving src, type(.mpd, .m3u8, .mp4) and key to the `source` tag. 

```
this.videoPlayer = videoJS(id, options, () => {
         this.registerEvents()
})
```

```
                  <source
                     src={source.src}
                     type={source.type}
                     key={source.src}
                  />
```

```
this.videoPlayer.on('error', this.onError)
```

The problem is 

**Case - 1:**

If type is given, `error` event is not getting triggered, hence we are not able to change the src

**Case - 2:**

If type is not given, `error` event is getting triggered, but the quality levels are empty and hence there are no options to change the quality.

Here are other observations, 

| Case |HTTP Streaming | Contrib-dash| Type given | On Error Triggered | Quality Levels Availability
|--- | ---| --- | --- | --- | --- |
| 1 | Enabled | Enabled| Yes | No | Yes |
| 2 | Enabled | Enabled| No | Yes | No |
| 3 | Enabled | Disabled| No | No | Yes |
| 4 | Enabled | Disabled| Yes | No | Yes |
| 5 | Disabled | Enabled| Yes | Yes | No |
| 6 | Disabled | Enabled| No | Yes | No |
| 7 | Disabled | Disabled| No | No | Yes |
| 8 | Disabled | Disabled| Yes | No | Yes |

## Steps to reproduce

1. Import the specified packages through **require**
2. Give type to the source tag => onError won't get triggered, but quality levels are available
3. Remove type from the source tag => onError gets triggered, but quality levels are not available

### Expected
Quality levels should be available and onError should be triggered when a chunk fails to get downloaded
### Actual
Either of them is not working based on giving or not giving the type of src

#### videojs
7.6.6
#### browsers
Chrome89
#### OSes
Linux
### plugins
1. @videojs/http-streaming - v1.12.0
2. videojs-contrib-dash - v2.11.0
3. videojs-contrib-quality-quality-levels - v2.0.9
4. videojs-http-source-selector - v1.1.6

Could you please let us know what might have gone wrong?

**Comment by Kaywee27** [comment]
Hey @gkatsev, Could you please respond to this issue?

**Comment by gkatsev** [comment]
videojs-contrib-dash doesn't current support contrib-quality-levels.
The error event is only meant for things defined as MediaErrors https://developer.mozilla.org/en-US/docs/Web/API/MediaError/code. Since HLS and DASH are supposed to be recoverable, by generally switching renditions, that's what happens and why no error event occurs if one of the stream fails.
Also, you should generally provide a type for the source. We try to detect the url type but it often doesn't work. So, your best bet for getting the best plyback is to provide the type.

What exactly are you trying to detect for switching sources? What about putting the fallback URLs into the manifests themselves and letting the players handle switching? You could also use the quality-levels (or whatever api DASH.js provides) to switch renditions.

**Comment by Kaywee27** [comment]
@gkatsev 

We are trying to detect if there is any MediaError while playing the video. As the video player tries to retry the failed chunks, we are replacing the current DASH or HLS src with an MP4 type when we detect a certain number of MediaError failure events consecutively, so that the video won't be frozen in a waiting / buffering state.

I feel this explained what we are trying to do with a bit of detail.

And, I didn't understand `putting the fallback URLs into the manifests`. Could you please elaborate a little?

**Comment by gkatsev** [comment]
Using HLS as an example, you can have multiple renditions with the same settings but only a different url:
```
   #EXTM3U
   #EXT-X-STREAM-INF:BANDWIDTH=1280000,AVERAGE-BANDWIDTH=1000000
   http://example.com/low.m3u8
   #EXT-X-STREAM-INF:BANDWIDTH=1280000,AVERAGE-BANDWIDTH=1000000
   http://example.net/low.m3u8
   #EXT-X-STREAM-INF:BANDWIDTH=2560000,AVERAGE-BANDWIDTH=2000000
   http://example.com/mid.m3u8
   #EXT-X-STREAM-INF:BANDWIDTH=2560000,AVERAGE-BANDWIDTH=2000000
   http://example.net/mid.m3u8
   #EXT-X-STREAM-INF:BANDWIDTH=7680000,AVERAGE-BANDWIDTH=6000000
   http://example.com/hi.m3u8
   #EXT-X-STREAM-INF:BANDWIDTH=7680000,AVERAGE-BANDWIDTH=6000000
   http://example.net/hi.m3u8
```
And clients will switch from the `example.com` stream to `example.net` stream if the `.com` one has issues.

As for retries, we have had requests to limit the number of retries (and we have a couple of PRs for that). Unfortunately, right now we retry indefinitely. It is something you can listen to in the internals of our playback engine (see https://github.com/videojs/video.js/issues/5435#issuecomment-471998039) but won't help you on browsers where native playback is used for HLS, like Safari and iOS. Though, they may error out eventually.
