### ISSUE TITLE
HTTP2_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by bhargavavarma** [videojs/video.js#7160]
## Description
Video Chunks that are failed are getting retried sometimes and sometimes not. Is there any specific reason for not getting retried?

This is especially happening with the chunks that are failed with HTTP2_PROTOCOL_ERROR having 200 as the response code. 

## Steps to reproduce
1.Play the video in a network with fluctuating speeds.
2.Seek the video randomly while observing the network tab for the chunks getting downloaded
3.Observe the chunk which is failed with HTTP2_PROTOCOL_ERROR

### Expected
Chunk should get retried if it gets failed.

### Actual
Chunk is getting retried sometimes and sometimes not.

### Error output
HTTP2_PROTOCOL_ERROR

#### videojs
what version of videojs does this occur with? - videojs 7.6.6
#### browsers
CHROME Version 89.0.4389.82 (Official Build) (64-bit)
#### OSes
LINUX
### plugins
1. @videojs/http-streaming - v1.12.0
2. videojs-contrib-dash - v2.11.0

**Comment by gkatsev** [comment]
This sounds like the culprit:
> This is especially happening with the chunks that are failed with HTTP2_PROTOCOL_ERROR having 200 as the response code.

If it's returning a 200 response we likely think that it succeeded and then the failure happens in a different spot in the chain and we don't know that we need to retry to download that segment. This may or may not be why contrib-dash is failing, since that uses DASH.js which we're not that familiar with.
