### ISSUE TITLE
How do we set headers on a non-streaming video request?

### ISSUE THREAD

**Issue by obuw** [videojs/video.js#7207]
## Description
Every example I could find for setting headers on a video request involves intercepting the request using xhook or xhr, on hls videos. These methods apparently don't work when you are simply trying to play an standard mp4 file.

I find it hard to believe that a major plugin like videojs does not provide a way to set headers, a feature so basic and frequently used.

I can't find a way intercept, or otherwise add headers to the requests made by videojs. Is there a method that I am missing?

Oh, and this isn't just about the video files, I also can't intercept or add headers to subtitle track requests.

## Additional Information
Any suggestions would be welcome.

**Comment by gkatsev** [comment]
Unfortunately, there is no way to add headers for media like mp4 files. We hand that off directly to the browser, and it handles all loading of things while not providing this extra set of functionality.
For subtitles, Video.js can either load things itself or have the browser load it natively. In both cases, there is no way to add headers. When native subtitles are used, the browser doesn't provide any hooks as it handles everything itself. For our emulated tracks, while we do use XHR, we do not currently expose a way to add headers for these requests. This has come up before, and we have some thoughts on how to provide hooks for the various XHRs that Video.js and submodules make, but it isn't available right now and won't be available in the near term, unfortunately.

For HLS/DASH, when using our playback engine (videojs/http-streaming), since we handle all the requests ourselves we provide a `beforeRequest` method for adding custom headers. This does mean that when you're playing back HLS on Safari, this method won't be available because native playback is used for Safari with HLS.

**Comment by obuw** [comment]
Thanks for the response. Unfortunately I was able to already gather all this valuable information you shared before I made this ticket. I was hoping I was missing something.

>"This does mean that when you're playing back HLS on Safari, this method won't be available because native playback is used for Safari with HLS."

Does that mean that we need to use DASH to add custom headers on Safari? Or is that going to be the same as HLS?

**Comment by gkatsev** [comment]
You can use HLS and force our playback engine, however, that's only possible on desktop safari. For iOS, particularly iPhones, you're, unfortunately, stuck with native playback and you cannot play DASH there.

**Comment by obuw** [comment]
Okay, so there is no way to provide authorization headers at all on iPhones, regardless of what method we use?

**Comment by gkatsev** [comment]
Unfortunately, that's pretty much the case. Your best bet is writing a proxy, using query paramters on the source url, or switching to use DRM.
