### ISSUE TITLE
Can't resolve imports in video.es.js with yarn v2 / berry

### ISSUE THREAD

**Issue by rtritto** [videojs/video.js#7209]
## Description
I'm using [yarn v2](https://yarnpkg.com) with `videojs`.
During compiling, I get different import errors on `video.js/dist/video.es.js` file.

## How to fix
Add `@videojs/vhs-utils`, `m3u8-parser`, `mpd-parser` and `mux.js` in `video.js` package.json dependencies or change/update code of `video.js/dist/video.es.js` file.

## Workaround
Add in `.yarnrc.yml` file:
```
packageExtensions:
  'video.js@*':
    dependencies:
      '@videojs/vhs-utils': '*'
      'm3u8-parser': '*'
      'mpd-parser': '*'
      'mux.js': '*'
```

## Steps to reproduce
1. `video.js` in package.json
2. Run `yarn install`
3. Compile

### Expected
Compile success.

### Actual
On compiling, I get these errors:
```
...
error - .yarn/cache/video.js-npm-7.12.1-53ac059ebb-e371896a4d.zip/node_modules/video.js/dist/video.es.js:26:0
Module not found: Can't resolve '@videojs/vhs-utils/es/resolve-url.js'
...
error - .yarn/cache/video.js-npm-7.12.1-53ac059ebb-e371896a4d.zip/node_modules/video.js/dist/video.es.js:27:0
Module not found: Can't resolve 'm3u8-parser'
...
error - .yarn/cache/video.js-npm-7.12.1-53ac059ebb-e371896a4d.zip/node_modules/video.js/dist/video.es.js:28:0
Module not found: Can't resolve '@videojs/vhs-utils/es/codecs.js'
...
error - .yarn/cache/video.js-npm-7.12.1-53ac059ebb-e371896a4d.zip/node_modules/video.js/dist/video.es.js:29:0
Module not found: Can't resolve '@videojs/vhs-utils/es/media-types.js'
...
error - .yarn/cache/video.js-npm-7.12.1-53ac059ebb-e371896a4d.zip/node_modules/video.js/dist/video.es.js:30:0
Module not found: Can't resolve 'mpd-parser'
...
error - .yarn/cache/video.js-npm-7.12.1-53ac059ebb-e371896a4d.zip/node_modules/video.js/dist/video.es.js:31:0
Module not found: Can't resolve 'mux.js/lib/tools/parse-sidx'
...
error - .yarn/cache/video.js-npm-7.12.1-53ac059ebb-e371896a4d.zip/node_modules/video.js/dist/video.es.js:32:0
Module not found: Can't resolve '@videojs/vhs-utils/es/id3-helpers'
...
error - .yarn/cache/video.js-npm-7.12.1-53ac059ebb-e371896a4d.zip/node_modules/video.js/dist/video.es.js:33:0
Module not found: Can't resolve '@videojs/vhs-utils/es/containers'
...
error - .yarn/cache/video.js-npm-7.12.1-53ac059ebb-e371896a4d.zip/node_modules/video.js/dist/video.es.js:34:0
Module not found: Can't resolve '@videojs/vhs-utils/es/byte-helpers'
...
```

#### OS
Windows

**Comment by gkatsev** [comment]
I'm not sure whether I just haven't ran it properly or because I still had a package-lock that yarn used or something, but I've had a sample project I used where yarn+berry was able to resolve things properly.
However, given the other issues we've seen with yarn, I do think that we likely need to declare the dependencies from `@videojs/http-streaming` (VHS) as dependencies of `video.js` because we inline VHS into Video.js for the dist files, except for some of the dependencie.
An alternative is to inline the dependencies as well, but, there is a likelyhood that someone could be using one of those modules themselves, so, deduplication of modules would be beneficial there.
