### ISSUE TITLE
Videojs full screen gives black bars on top, bottom, left and right

### ISSUE THREAD

**Issue by Anil-matcha** [videojs/video.js#7227]
## Description
Briefly describe the issue.
Videojs on full screens adds black bars everywhere around the video

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1.Please go to url https://api.vadoo.tv/test_hls and try full screen of video

### Expected
Black bars only in one direction i.e either left, right or top, bottom

### Actual
Black bars in all directions

## Additional Information
Please include any additional information necessary here. Including the following:
Videos 7.12.1 version, Windows 10, Chrome browser

Observing black bars in all directions while playing video in full screen. The expected is black bars only on one direction, having on all directions makes it look like video is smaller and not occupying all the space

I don't want to do object-fit:cover since it crops the video and I lose information. I don't want to do object-fit:fill as well since it changes aspect ratio and makes the video look bad

Can anyone kindly suggest what can be done ?

**Comment by gkatsev** [comment]
Your video has black bars in top and bottom in it making the aspect ratio of the video 1.5, or 3:2. Most screens are 16:9 (~1.7) aspect ratio, though, some laptops are coming in 3:2 aspect ratio now. This means that when you fullscreen you see black bars to the right and left too because the entire video doesn't fit on screen.
