### ISSUE TITLE
What is the algorithm for video.js to download the next segment in advance when playback DASH ? Is it possible for me to change the time for this early download?

### ISSUE THREAD

**Issue by jinqinghua** [videojs/video.js#7255]
## Description
What is the algorithm for video.js to download the next segment in advance when playback DASH? 
Is it possible for me to change the time for this early download?

## Steps to reproduce
when playback 4k video, video.js will download segment 0 and segment 1 at first, 

1. it will playback when the segment 1 download finished.
2. at some time (what is the algorithm?) when playing segment 1 then download segment 2
3. it will be hung when segment 1 playback finished but segment 2 not download fully.
4. Is it possible for me to change the time for this early download?

### Expected
N/A

### Actual
N/A

### Error output
N/A

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
video.js 7.9.7
dashjs 2.9.3
videojs-contrib-dash 2.11.0

#### browsers
any
#### OSes
any
### plugins
N/A

**Comment by gkatsev** [comment]
All the work happens in https://github.com/videojs/http-streaming. We don't provide hooks for the timing of segment downloads. When playing 4K content, it's very likely that you'll end up buffering between segments. At some point, we plan on being able to download and append chunks of content rather than entire segments but we're not ready for that yet and unfortunately, it isn't something that we'll be able to work on in the short term.

**Comment by jinqinghua** [comment]
Got, Thanks a lot.
