### ISSUE TITLE
AES encryptionusing videojs

### ISSUE THREAD

**Issue by Sushmahp95** [videojs/video.js#7268]
## Description
I am using videojs player to play the content. requirement is to play AES encrypted hls and dash  urls. from api i am getting one token, We need to use that token for decryption of video and play that video. How to acheive using videojs. I am new  to videojs. Please help me out on this

videojs version: 7.12.3
videojs/http-streaming: "^1.11.2"
"videojs-contrib-dash: "^2.11.0",

platform:
Chrome: 90.0.4430.212 - (64-bit)

> steps to reproduce:

below are encrypted hls and dash urls

hls: https://temedia-inct.streaming.media.azure.net/ebce35f4-b67e-4dcc-86a1-19b1f9579cef/Avengers.ism/manifest(format=m3u8-aapl,encryption=cbc)

Dash: https://temedia-inct.streaming.media.azure.net/ebce35f4-b67e-4dcc-86a1-19b1f9579cef/Avengers.ism/manifest(format=mpd-time-csf,encryption=cbc)

AES decryption key: eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJURUxAMTIzNDUiLCJuYmYiOjE2MjM0MDkwODAsImlzcyI6Ik5DUEFfQ0xJRU5UIiwiZXhwIjoxNjIzNDA5NjgwfQ.6HDnU26eeHYN78lxrVtMnqgPTsXdgWTcskwx9XvXhlw

how to pass descryption key to play hls and dash urls in videojs?

**Comment by gkatsev** [comment]
The tl;dr is that you won't be able to get this working on iPhones because everything is handled natively. It is a platform limitation and can't be worked around.
For desktop browsers, you can use `beforeRequest` to attach the token to the key request, see https://github.com/videojs/http-streaming#vhsxhr.
