### ISSUE TITLE
how run in xhtml

### ISSUE THREAD

**Issue by arthurj58** [videojs/video.js#730]
html is word but html rename xhtml is not work

**Comment by davidtorroija** [comment]
It's hard to have an online fiddle because there is not fiddles for xhtml, I have a problem with XHTML, there are several errors of xhtml invalid because the librarys uses &nbsp; instead of &#160; and uses <li selected></li> instead of  <li selected="selected"></li> can you fix this in the library I tried to do this myself but it is not enough when I fix this the player is not reproducing the video, you can see the video but the play not work, my code:

`<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops">
  <head>
    <meta charset="utf-8" />
    <title>videojs-overlay Demo</title>
    <link href="https://vjs.zencdn.net/5-unsafe/video-js.css" rel="stylesheet" />
  </head>
  <body>
    <h3>Dynamic video</h3>
    <p>Dynamically add or remove markers on the fly.</p>
    <div class="row">
       <div class="medium-6 columns small-12 video-container">
          <video id="dynamic-demo" controls="controls" preload="auto" muted="muted" class="video-js vjs-default-skin">
             <source src="http://vjs.zencdn.net/v/oceans.mp4" type="video/mp4" />
              <track kind="captions"  src="/Poe/VTT_files/M20697_1BM01L01T09S01.vtt" srclang="en" label="English caption" default="default"></track>
          </video>
          <br />
       </div>
      

        

        <script type="text/javascript" src="../../shared/js/external-libs.js"></script>
        
        <script src="/Poe/videojs-overlay/video-js.5.8.js"></script>
      
      
        


    </body>
</html>`

**Comment by mmcc** [comment]
I updated the styling of your post for you to make the code samples. Sorry, but no, we won't be making changes to Video.js to pass XHTML validations.

**Comment by davidtorroija** [comment]
ok :( thanks for the fast reply

**Comment by davidtorroija** [comment]
I decided to upload the compiled version of videojs with my modifications to work in xhtml documents and is working so far for my projects. https://www.npmjs.com/package/videojs-xhtml
