### ISSUE TITLE
Caption CC button not shown for live HLS streams

### ISSUE THREAD

**Issue by killerbishop** [videojs/video.js#7316]
## Description
Closed caption option does not display on Chrome 91 on Android 10 devices - actual device is a Samsung Note 9. This appears to be the case even for older versions of VideoJS (7.8.4). Suspicion is that something about the live HLS stream's embedded captions causes VideoJS to decide to not show the caption button.

Note: that the HLS stream is not always "on" because it is a live feed from a news station.

## Steps to reproduce
1. Vanilla video JS configuration with a HLS live stream is not offering captions
2. Example can be found at https://app1.cms.us-corp-dev-3.vip.tndev.net/vid/

### Expected
Caption CC button should be shown

### Actual
No CC button is ever offered on Android - works on Chrome on Windows desktops though

### Error output
None

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
7.8.4, 7.11.4, 7.13.3
#### browsers
what browser are affected?
#### OSes
Android 10 with Chrome  91.0.4472.120
### plugins
None - Vanilla videoJS

**Comment by gkatsev** [comment]
Looks like what's happening is that the native playback is getting used. It seems like your stream contains 608 and 708 captions, which native android playback probably doesn't handle. The easiest way to get around that is probably changing the video element to a `video-js` element, it should work equivalently. Otherwise, you probably want to remove the source elements and add the source programmatically.
This happens because if Video.js sees that the browser has already started loading the video, it will let it continue rather than force our playback engine.

**Comment by killerbishop** [comment]
I can confirm that switching from `<video>` to `<video-js>` tags fixes the issue.
