### ISSUE TITLE
ID="XXX_html5_api" injected into <video> markup

### ISSUE THREAD

**Issue by steveadamsfixedit** [videojs/video.js#7358]
## Description
I'm attempting to create an interface to capture user engagement and analytics of video.js player events with a set of custom event listeners. In order to correlate the analytics in a meaningful fashion, I'm needing to integrate a unique ID attribute for each video in my markup. When using the video.js version 7.8.1 my ID's are appended with "_html5_api". 

Where is this coming from and why? Is there any precedent on overriding it? Do different versions of video.js handle this ID attribute in different ways?

## Steps to reproduce
take a peek at https://dev.ceavco.live/mux-analytics/ and inspect the source code and javascript console upon play actions for the embedded video

**Comment by gkatsev** [comment]
Yes, this is the expected behavior. It's been like this basically always and unfortunately, we aren't able to change this behavior.
That tech element will get a different suffix depending on the tech being used. `<video>` elements that use the html5 tech, will get `_html5_api` and when Flash was a thing, the `<object>` elements would've had a `_flash_api` suffix instead with the Flash tech.

Ideally, you wouldn't be interacting with the video element directly, but rather via the Player object that's created when you initialize Video.js.
