### ISSUE TITLE
Integrate with Prebid Video Module

### ISSUE THREAD

**Issue by karimMourra** [videojs/video.js#7381]
### Request
This ask is to implement a Submodule for video.js in Prebid's Video Module.

### Context
Development of a Video Module in Prebid is currently under way. The Video Module will serve as a standardized Video interface that Prebid can use to listen to video events, obtain oRTB video and content information, and load ad tags. 
The Video Module delegates the above requests to a video submodule which acts as a bridge to the video player.

## Benefit
members of the Prebid community can easily integrate with Video.js

## Additional information
[PR adding a submodule for JW Player](https://github.com/jwplayer/Prebid.js/pull/5)
[WIP PR implementing the Video Module in Prebid](https://github.com/jwplayer/Prebid.js/pull/5)
[Video Module proposal](https://docs.google.com/document/d/1sueL8EXnD-DViTIEBNayAzNNrYocdHtmEl7433g0f5I/edit#heading=h.mu3wwhanpo5)

**Comment by gkatsev** [comment]
Hi, unfortunately, this isn't something that we're able to tackle.
If you're interesting, I'd recommend [publishing a plugin](https://docs.videojs.com/tutorial-plugins.html) that adds this functionality. Most of these types of features are built out as plugins that can be used in Video.js.
Also, since this is related to ads, I would recommend taking a look at [contrib-ads](https://github.com/videojs/videojs-contrib-ads) as well.
