### ISSUE TITLE
textTrack returns different type of object on Safari, has no on() method, event listeners never fire

### ISSUE THREAD

**Issue by sneakyimp** [videojs/video.js#7417]
## Description
I've got a video embedded from MUX, which has metadata containing Program Data Time (PDT). Most browsers behave, but videojs appears to return a different type of object in safari so I am unable to attach an event listener to capture the cuechange event and extract its PDT date string.

On most browsers I test (Firefox, Chrome, Edge, etc.), this code will properly show the latest PDT in DIV#sneakyimp_pdt, but in Safari, the object returned by the videojs player.textTracks() function is a different type. Rather than being some class **e**, as it is in most browsers, Safari yields a metadataTrack object that is a **TextTrack** object. Even so, I cannot seem to attach any event listeners to the TextTrack.cuechange event.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Embed MUX livestream (or similar) which contains PDT information in text track.
2. Create videojs (with nativeOverride option) for the video.
3. Try and attach cuechange event to the text track with label **segment-metadata**

Here's some sample code:
```html
<html>
<head>
	<meta charset="utf-8">
	<link href="https://vjs.zencdn.net/7.14.3/video-js.css" rel="stylesheet" />
</head>
<body>
<div id="sneakyimp">
	<video id="vjs_video_3_html5_api" class='mux-player video-js'  width=1920 height=1080 poster='https://dev.ceavco.live/wp-content/uploads/2021/09/3106--thumb.jpg' controls preload='metadata'>
		<source src='https://stream.mux.com/QahebrniJwoz8BUCfI8MCVAckwgq7JQG02tz00T4yl9Jc.m3u8' type='application/x-mpegURL' />
	</video>
</div>
<div id="sneakyimp_pdt">PDT WILL LOAD HERE</div>
<div id="sneakyimp_ct">currentTime WILL LOAD HERE</div>
<script>
// the videojs player object
let player = null;
function myPlayerInit() {
    // try to grab this...it works on most browsers, but after Safari hard reload, does not work
    let metadataTrack = Array.prototype.find.call(player.textTracks(), track => track.label === 'segment-metadata');
    console.log(metadataTrack);
    if (!metadataTrack) {
      // on Safari, after hard page reload, metadataTrack is undefined
      console.log('metadataTrack NOT FOUND');
      // this does produce a PDT value but also produces a warning
      console.log('player.tech().el().getStartDate()=' + player.tech().el().getStartDate());
    } else {
      console.log('adding metadataTrack.on listener');
      metadataTrack.on('cuechange', () => {
        // metadataTrack.activeCues[0] is occasionally undefined
        let pdt = metadataTrack.activeCues[0].value.dateTimeString;
        document.getElementById('sneakyimp_pdt').innerHTML = pdt;
      });
    }
    // THIS WORKS ON ALL BROWSERS I'VE TESTED
    player.on('timeupdate', (evt) => {
      document.getElementById('sneakyimp_ct').innerHTML = player.currentTime();
    });
}
// we wait for DOM to do most of this stuff
window.addEventListener('DOMContentLoaded', (event) => {
    let video = document.querySelector("#sneakyimp video");
    if (!video) {
        throw "no video found";
    }
    player = videojs(video, {
      html5: {
        nativeTextTracks: false,
        vhs: {
          overrideNative: true
        }
      }
    });

    console.log('attaching loadeddata event to player');
    player.on('loadeddata', () => {
      console.log("== player loadeddata, firing myPlayerInit ==");
      myPlayerInit();
    });
});
</script>
<script src="https://vjs.zencdn.net/7.14.3/video.js"></script>
</body>
</html>

```

### Expected
Expect cuechange event to fire as segment-metadata text tracks arrive.

### Actual
vidoeojs player.textTracks() in MacOS Safari 14.1 is returning different data type on Safari than other browsers. This may also be a problem on android. On my iPhone (also running Safari 14.1), the browser fails to locate a texttrack for `metadataTrack` at all. My sample code says metadataTrack NOT FOUND.

### Error output
The TextTrack object returned by textTracks on Safari has no `on()` method, which was causing errors, when i started checking data types, the `TextTrack` object i get in `metadataTrack` doesn't complain when I call `metadataTrack.addEventListener` or set `metadataTrack.oncuechange` but those events never fire.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
7.8.1
#### browsers
Safari 14.1.2. 
#### OSes
MacOS, iOs.
### plugins
I don't think so.

**Comment by gkatsev** [comment]
This is basically expected. You should use `addEventListener` rather than `.on`. When we handle captions ourselves rather than relying on the native captions like in Safari, we return an object that looks pretty much the same. However, because it uses Video.js internal helpers, you also get the methods such as `.on`.
As for `segment-metadata`, that is only available when VHS is being used. VHS isn't used by default on Safari and cannot be used on iPhones.

Hope this helps.

**Comment by sneakyimp** [comment]
@gkatsev I appreciate your post, but I must be missing something. If you look at my code, I specifically check for the existence of an **on()** method before attempting to use **addEventListener()** and it doesn't work. Also, I'm confused why we get a different textTrack object in Safari than *every other browser.* How could this possibly be "expected" behavior? I must be missing something.

**Comment by gkatsev** [comment]
Ok, so, after fiddling with your example a bit locally, I got it working (a live minimal example would've made it easier). I can see the PDT being updated in the page in both Chrome and Safari. For iPhones, it won't work because `segment-metadata` is only available when VHS is used and due to platform limitations (MSE isn't available on iPhones) it isn't possible to use VHS on iPhones.

`player.textTracks()` will always return a TextTrackList. By default, on Safari, this will be the native TextTrackList where-as on Chrome and other browsers, it will be our internal TextTrackList. The API for these objects is equivalent. So, while they're "different" objects, they aren't really "different" objects. If you only use `addEventListener` on it, it will always work, regardless of what browser you're running.

**Comment by sneakyimp** [comment]
I have tried to reduce this to a minimal live example -- if there's code you think is extraneous, let me know and I'll try and reduce it more. I'm testing right now with my code and get **metadataTrack NOT FOUND** from the code above. I can provide a url where you can see yourself. I'd prefer not to post the url publicly, but would truly appreciate any advice you may have. If you tweaked the code, perhaps you might suggest where I've gone wrong? I still don't really understand why this works on every other browser but not Safari?

Once again, I'm seeing `metadataTrack NOT FOUND` which suggests that the player is returning an empty value.

**Comment by gkatsev** [comment]
Specifically, a live example. I had to do a couple of tweaks before anything worked. At first I thought I had to do a lot more changes, but since I was using a local Video.js build, I realized I had something broken there. Switching to a hosted version, I was able to make the changes just be adding the Video.js css and js files and also switching from `video.id` to just `video` where `videojs()` gets called. I get an error otherwise.
In either case, in both Safari and Chrome, it does find a metadataTrack for me and does get `cuechange` events using the code you have written above.

**Comment by sneakyimp** [comment]
That is extremely helpful information. I have put up a page [here](https://www.oldgreyhorror.com/bar.html) which demonstrates the problem `metadataTrack NOT FOUND` error.  This contains the JS and CSS (I thought these would be assumed so I removed them from my example to further minimize. I also changed the parameter supplied to the videojs constructor from `video.id` to just `video`.

It looks like this line, suggested by MUX dot com tech support, is returning `undefined`:
```
const metadataTrack = Array.prototype.find.call(player.textTracks(), track => track.label === 'segment-metadata');
```
You indicated above that this value may not be supplied for Safari, If you can suggest an alternative approach or solution for extracting PDT on Safari (both MacOS and iOS), I'd be truly grateful.

**Comment by gkatsev** [comment]
I think `player.tech().el().getStartDate()` may get you the PDT on Safari.

**Comment by sneakyimp** [comment]
OK it would seem that the behavior on this page is experiencing race conditions somehow. Sometimes it finds `metadataTrack` but other times it does not. I can apparently trigger the `metadataTrack NOT FOUND` error pretty consistently by holding down the shift key and hitting refresh (i.e., a force-refresh).

player.tech().el().getStartDate() does indeed seem to retrieve the PDT originally embedded in the video when I first recorded the livestream, however it throws a warning.  I edited the check for metadataTrack like so:
```js
    if (!metadataTrack) {
      console.log('metadataTrack NOT FOUND');
      console.log('player.tech().el().getStartDate()=' + player.tech().el().getStartDate());
    } else {
      // in Safari, construct.name is TextTrack, on other browsers, it's just e
      console.log('metadataTrack located, constructor name is ' + (metadataTrack.constructor.name));
      console.log(metadataTrack);
    }
```
And a shift-refresh causes it to fail to locate metadataTrack but output the tech start date with this warning:
```
VIDEOJS: - WARN: - "Using the tech directly can be dangerous. I hope you know what you're doing. See https://github.com/videojs/video.js/issues/2617 for more info.
```
Might there be some better command to locate the appropriate metadataTrack that works in safari also? Or perhaps there is some other event rather than **loadeddata** or **loadedmetadata** to listen for before I call `myPlayerInit`?

**Comment by sneakyimp** [comment]
Let me add that when Safari *does* find the metadataTrack, everything seems to work pretty great for a couple of seconds but then a few seconds after starting video playback, there's an error that happens sometimes but not all the time:
```
VIDEOJS: - "ERROR" - TypeError: undefined is not an object (evaluating metadataTrack.activeCues[0].value) - bar.html:55
video.min.js:12:1825
```
Even after that error happens, in a few seconds we continue to get PDT time updates firing with the cuechange event. Sometimes this error doesn't ever happen.

**Comment by sneakyimp** [comment]
@gktsev I have further pinpointed the issue.

In Safari, It would appear that player.textTracks() is empty when you visit a page for the first time or after you do a hard reload (i.e., hold shift and click reload) in safari. I'd also point out that the player.on(loadeddata) function doesn't run after a hard reload until you press play on the video, whereas a soft reload triggers this event as soon as the page loads.

Also, the code works without issue on Safari after a soft page reload. I have updated and further reduced the minimal live example code in the original post. I have put that code on a webserver [here](https://www.oldgreyhorror.com/foo3.html).

**Comment by thujone** [comment]
@gkatsev I have encountered this problem as well

**Comment by mister-ben** [comment]
While `overrideNative: true` does trigger VHS/MSE playback on desktop Safari, the catch is that if the video element has already loaded the source, Video.js will not re-load the source with VHS. On the hard load, the video element has already started loading the HLS source before playback starts and continues to play natively. On soft reloads with cached js the player init happens sooner and the source is loaded with MSE.

There are a couple of ways to avoid this. Either use a `<video-js>` placeholder element instead of `<video>`, or load the source into the player with `src()` instead of the `<source>` element.

Still, you'd need to account for times when only native playback is possible (e.g. iOS, as mentioned above) and use `player.tech(true).el().getStartDate()`.

**Comment by sneakyimp** [comment]
@mister-ben thanks for your response. Your post is over my head -- I'm not familiar with the particulars of VHS or MSE or HLS, but it defintely seems like a bug in the player to me that player.textTracks() returns an empty list and yet we can get PDT from `player.tech(true).el.getStartDate()`. Videojs triggers a blunt warning about using `tech` and the pdt it returns *presumably* comes from the TextTrack?

**Comment by gkatsev** [comment]
the PDT doesn't come from the text tracks in the case when VHS is used. The playback engine in Safari and other browsers is different. The object return by `player.textTracks()` has the same interface always.
The `segment-metadata` track is only available when VHS is used, i.e., not on Safari. For Safari you have to get the time via it's `getStartDate()` method.
We trigger a warning when `player.tech()` is called because _most_ people shouldn't need to access stuff there. Though, we have an escape hatch to silence that warning `player.tech(true)`. We've also been considering making `getStartDate()` available on the player itself and having that return the expected value whether we're in Safari or using VHS in other browsers. However, this hasn't made any progress yet.
Unfortunately, right now, there isn't a way to target *all* browsers with the same piece of code. When VHS is used, you can definitely use the segment-metadata track, but on Safari, specifically iphones, you'll have to use `getStartDate()`
