### ISSUE TITLE
Disable pause when clicking on the progress bar and the progress control while video is playing

### ISSUE THREAD

**Issue by VioletFlare** [videojs/video.js#7429]
## Description
I am attempting to remove the pause behavior by overriding the handleTechPause_ but the solution is glitchy, slows the player, and it does not work the first time.
https://codepen.io/S4nt1n1/pen/mdwXKoa

I'd like the pause icon not to change only when clicking on the progress bar or the progress control.

## Steps to reproduce
1. Play the video
2. Click on the progress bar or progress control
3. The video pauses for an instance when selecting the time

### Expected
The video should not pause.

### Actual
The video pauses.

### Error output
None

#### videojs
'7.15.4'
#### browsers
Chrome; I haven't tested IE or Safari.
#### OSes
Windows
### plugins
None

**Comment by VioletFlare** [comment]
I have fixed my workaround using the mousedown event.

https://codepen.io/S4nt1n1/pen/xxrWmpN

Still, I wonder if there is a better way to do this.

**Comment by gkatsev** [comment]
you should be able to do it with css
```css
.video-js .vjs-tech {
  pointer-events: none;
}
```

**Comment by VioletFlare** [comment]
Hello, @gkatsev that would disable pointer events on the video element. This solution is not only not doing what I intended but also the opposite of what I wanted.

Please, note that I don't want to disable the pause behavior, I want to disable the pause behavior only when the user interacts with the progress bar.

Also, please do not take my codepens into consideration as they more or less solve the issue I had.

On deeper analysis i found out this is not an issue with videojs but with the underlying HTML5 video player.

**Comment by gkatsev** [comment]
Oh, I misunderstood what you meant, sorry.

This has to do with how we handle seeking in Video.js. When a seek starts, we pause the video and then unpause it when the seek ends. This is particularly an issue you scrub, i.e., click and drag. Because if we don't pause, when if you click and drag and keep holding down the mouse button but stop moving, the  video will continue playing from that location.
We are considering changing this to be a playback rate change rather than a pause/play in a major update of Video.js. It may also come with better hiding of these "behind the scenes" events.
