### ISSUE TITLE
Appear Modal in a Specific Time

### ISSUE THREAD

**Issue by monsky32** [videojs/video.js#7492]
how to automatically appear modal in a specific time in the video

**Comment by FredZeng** [comment]
```js
player.on('timeupdate', () => {
    // currentTime: the current playback time in seconds.
    if (Math.floor(player.currentTime()) == targetTime) {
        // TODO: show your modal
    }
});
```

**Comment by OwenEdwards** [comment]
Personally I wouldn't use `Math.floor` and `==`. I would save the `currentTime` each time this handler is called, and then check for `((player.currentTime() >= targetTime) && (previousCurrentTime < targetTime))`. You'd need to add some logic to handle things like skipping/scrubbing, etc.

**Comment by monsky32** [comment]
I have test the code and it works well but after i press the close button the modal keeps on appearing i suspected that the it must pass on the set current time so that the modal must close permanently

**Comment by FredZeng** [comment]
In my experience, `timeupdate` triggers 4 times in a second. You may need a bool `flag` to save the state of the modal to ensure the modal will not be displayed after it is turned off.

**Comment by OwenEdwards** [comment]
@FredZeng is correct - `timeupdate` usually triggers 4 times a second, but it can be more often.

Where I mentioned saving the previous time above (as `previousCurrentTime`), I'd also add logic so that it doesn't show up again once dismissed until the `currentTime` is different from the `previousCurrentTime`. But you might want it to be that the modal doesn't show again until you finish the video, or something like that. There are lots of other events that video playback fires that you could/should listen for, so that your modal appears when it should and doesn't when it shouldn't!
