### ISSUE TITLE
AudioTrack selector not working in Safari

### ISSUE THREAD

**Issue by 0caspy** [videojs/video.js#7494]
## Description
AudioTrack selector not working in Safari
https://codepen.io/0caspy/pen/GRvMaKq
seems like problem appeared after commit 4707ce82c0524e3b1f93b560c6b32e38a4f5e24d

## Steps to reproduce
1. create player with m3u8 video with audio renditions (bipbop in example)
2. change audio track
3. look at menu list with audio tracks or try to change again

### Expected
audio track changes without problems

### Actual
both menu item stay selected. 
unable to change track anymore.

### Error output
no errors

#### videojs
latest
#### browsers
Safari
#### OSes
MacOS
### plugins
none

**Comment by gkatsev** [comment]
I'm unable to reproduce this in Safari 14, but I do see it happen with Safari Technology Preview and iOS 15.1.
It's possible that something changed in Safari 15+ that causes this.

**Comment by 0caspy** [comment]
i have Catalina 10.15.7 with Safari 15.1

**Comment by lribelle** [comment]
I'm having the same problem on Safari 15, one item stays selected and you can't select it anymore after switching.
![Screen Shot 2021-11-08 at 14 41 38](https://user-images.githubusercontent.com/28066069/140791429-ec873f43-3d2d-4252-b421-1e4d3524686a.png)

Downgraded to 7.11.8 without the commit 0caspy linked and it works correctly.

**Comment by gkatsev** [comment]
Ah, I know what the issue here is. It seems like in Safari 15, they allow multiple audio tracks to be enabled at the same time. This new change is in-line with the HTML spec, which says that multiple audio tracks could be enabled at the same time. Though, we generally don't let multiple items be selectable from the controls.

Previously, Safari would automatically turn off the other audio tracks, so we didn't need the code that #7163 removed, especially since we had code in our AudioTrackList that turned off the other tracks.

Probably, what we want to do is bring back the code from #7163 but only when native audio tracks are used.

**Comment by gkatsev** [comment]
I have a proposed solution in #7519
