### ISSUE TITLE
Cannot read properties of undefined (reading 'tracks')

### ISSUE THREAD

**Issue by CodeAssemblingChicken** [videojs/video.js#7512]
## Description
I have separate video and audio tracks. They will be fetched from googlevideo.com later (for testing purposes, I used a local mp4 without audio and a m4a file).
Perhaps there is a nicer way of mixing both tracks with video.js (if so, please let me know), but I could only think of using a m3u8 playlist. I created a m3u8 file that does what I want and does correctly play in VLC and mpv, but with video.js I get the error message 
`Uncaught TypeError: Cannot read properties of undefined (reading 'tracks')`.
If I use ffmpeg to properly convert my tracks to a m3u8 playlist, it does work in video.js as well. So I guess the problem has to do with codecs or bitrates not matching the specifications.
I'd be grateful for some thoughts on this. I guess it's my fault as I am not using HLS as intended, but I didn't know where else to ask.

For reference, here are my [m3u8-files](https://github.com/videojs/video.js/files/7526440/m3u8-files.zip).

### Expected
Video plays as it does in VLC

### Actual
Video refuses to play

### Error output
If this is of any use:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'tracks')
    at handleSegmentBytes (video.es.js?f0e2:41606)
    at segmentFinish (video.es.js?f0e2:41930)
    at eval (video.es.js?f0e2:41972)
    at eval (video.es.js?f0e2:41447)
    at callbackWrapper (video.es.js?f0e2:30597)
    at Object.eval [as callback] (video.es.js?f0e2:30622)
    at cbOnce (index.js?3603:104)
    at XMLHttpRequest.loadFunc (index.js?3603:178)
```

#### videojs
v. 7.15.4
#### browsers
The above is for electron. In Firefox, I get `Uncaught TypeError: segment.map is undefined`
#### OSes
Tested on Linux Mint

**Comment by gkatsev** [comment]
Yeah, unfortunately that's unlikely to work properly. HLS is meant to be segmented so that each segment is short and can be downloaded quickly. In browsers, Video.js uses Media Source Extensions to be able to load in media data, but that has a limit to how much we can actually include.
In your example, we'd end up trying to download the entirety of the "segment" and then try to insert all of it into the source buffer.
In addition, it's very possible that your files are mp4 files rather than fragments mp4, and it works in desktop apps because they are a lot more resilient and can handle things more loosely.
Unfortunately, this isn't a supported configuration. You'll want to either generate a single mp4 file that has both audio and video or generate proper HLS.

**Comment by CodeAssemblingChicken** [comment]
Thanks for the elaborate explanation. Good to know how it is meant to work.
I will look into other possibilities then. I discovered DASH recently, and maybe it does what I want.
Have a nice day
