### ISSUE TITLE
Media Tailor DASH ads skip and crash player

### ISSUE THREAD

**Issue by s3bubble** [videojs/video.js#7535]
## Description
We have stitched ads into this DASH stream using media tailor.

https://578dac017a234b1b8a4cca1ed506804d.mediatailor.us-east-1.amazonaws.com/v1/dash/d02fedbbc5a68596164208dd24e9b48aa60dadc7/MEr2s67s-1637260410/master.mpd

This playback fine on.
https://bitmovin.com/demos/drm
https://developer-tools.jwplayer.com/stream-tester

But with videojs it jumps between ads and playlist and then crashes see this demo.

https://output.jsbin.com/qocabuz/2/

Error in console
```
VIDEOJS: ERROR: (CODE:3 MEDIA_ERR_DECODE) The media playback was aborted due to a corruption problem or because the media used features your browser did not support. 
```

**Comment by gkatsev** [comment]
Our DASH support is still definitely lacking, and we're always working to improve it. I do see it play in Shaka/DASH.js for example and fail in our player. One thing I noticed is that when I ran the stream through the [DASH IF conformance checker](https://conformance.dashif.org/), it showed a few issues. It's probably worth fixing those, though, I'm not sure if it'll make it play in our player.

<details>
<summary>Relevant log snippet</summary>
```
location="/*:MPD[namespace-uri()='urn:mpeg:dash:schema:mpd:2011'][1]/*:Period[namespace-uri()='urn:mpeg:dash:schema:mpd:2011'][1]/*:AdaptationSet[namespace-uri()='urn:mpeg:dash:schema:mpd:2011'][1]/*:SegmentTemplate[namespace-uri()='urn:mpeg:dash:schema:mpd:2011'][1]">
--
If more than one Media Segment is present the duration attribute or SegmentTimeline element shall be present.
  
  
location="/*:MPD[namespace-uri()='urn:mpeg:dash:schema:mpd:2011'][1]/*:Period[namespace-uri()='urn:mpeg:dash:schema:mpd:2011'][2]/*:AdaptationSet[namespace-uri()='urn:mpeg:dash:schema:mpd:2011'][1]/*:SegmentTemplate[namespace-uri()='urn:mpeg:dash:schema:mpd:2011'][1]">
If more than one Media Segment is present the duration attribute or SegmentTimeline element shall be present.
  
  
 location="/*:MPD[namespace-uri()='urn:mpeg:dash:schema:mpd:2011'][1]/*:Period[namespace-uri()='urn:mpeg:dash:schema:mpd:2011'][3]/*:AdaptationSet[namespace-uri()='urn:mpeg:dash:schema:mpd:2011'][1]/*:SegmentTemplate[namespace-uri()='urn:mpeg:dash:schema:mpd:2011'][1]">
 If more than one Media Segment is present the duration attribute or SegmentTimeline element shall be present.
  
Schematron validation not successful - DASH is not valid!
```
</details>

In the meanwhile, if you want to use Video.js you can include videojs-contrib-dash and use the DASH.js playback engine instead of our default playback engine for your DASH streams.

**Comment by s3bubble** [comment]
Thanks @gkatsev we will give that a go.

Also we will pass those logs onto MediaConvert as this was used to create the stream 👍🏻
