### ISSUE TITLE
Android play 5.1 surround sound video can only hear 2 channels

### ISSUE THREAD

**Issue by ayconanw** [videojs/video.js#7570]
## Description
https://codepen.io/ayconanw/pen/zYEwGBa

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1.play on android phone

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
7.17.3
#### browsers
chrome
#### OSes
android
### plugins
no plugin

**Comment by ayconanw** [comment]
set nativeAudioTracks true or false will not help

**Comment by mister-ben** [comment]
The browser is handling the decoding and playback. I'm not sure there's a way to feature detect 5.1 channel support.

**Comment by Migacz85** [comment]
Any update on this issue ?

**Comment by mister-ben** [comment]
There's no update, still the same situation. The browser handles playback of an MP4 natively. It's disappointing that Andorid can't handle this better, even on Pixel devices that supposedly suport "spacial audio", but that's out of Video.js's control. It's common that an MP4 with a 5.1 track would also have a stereo track so that could be played.
