### ISSUE TITLE
Vimeo served HLS Videos continually buffer and never start playing

### ISSUE THREAD

**Issue by GaryWorthingtonUK** [videojs/video.js#7610]
## Description
Whilst using HLS URL available via Vimeo's video API, Android devices using Chrome are unable to play videos using Video JS player v 17.7.  This issue does not appear on desktop Chrome on IUbuntu, Windows, iOS and MacOS.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Using Android Chrome Visit https://20220114t183713-dot-yourpilatesphysio.ew.r.appspot.com/video/introduction-to-pilates (example)
2. Click Play
3. Video buffers but does not play

### Expected
I expected that after a short period of buffering, the video would start playing

### Actual
The video continued to buffer forever

### Error output
If there are any errors at all, please include them here.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
7.17.0
#### browsers
Chrome
#### OSes
Android
### plugins
Chromecast - @silvermine/videojs-chromecast

**Comment by mister-ben** [comment]
It's using Android's native HLS playback in this case, which is buggy. Modern versions of Video.js will use our playback engine in preference to native on Android, but not if you init the player from a video element that _already_ has the source loaded.

Either chage is to use a `<video-js>` element instead of `<video>`, or set the source with `player.src()` instead of the `<source>` element.

**Comment by GaryWorthingtonUK** [comment]
This has sorted it!  You are a legend, thanks for the rapid response.
