### ISSUE TITLE
Recommended way to add custom properties/methods?

### ISSUE THREAD

**Issue by KianBadie** [videojs/video.js#7680]
I am currently created a simple plugin to switch between qualities (using different mp4 files, not hls). I would like a way to retrieve the current quality of a player. I was thinking of adding a property like `quality_` to the player and maybe a method like `quality()`. However, I am not sure if there is a more "videojs" way of adding properties or methods to a player?

**Comment by mister-ben** [comment]
Video.js generally uses a "private" property like that with the underscore, and a getter/setter method which is the supported API.

It may be better to add to the instance of the plugin on the player though, just to reduce the risk of name conflicts e.g. `player.mySwitcherPlugin.quality()`.

**Comment by KianBadie** [comment]
@mister-ben I see. How would one go about doing that? So far I only added my plugin by using something like `videoPlayer.controlBar.addChild("QualityChanger", { });`. How would I get my hands on an instance of the plugin?

**Comment by mister-ben** [comment]
A basic [plugin](https://videojs.com/guides/plugins/) is something like this

```js
videojs.registerPlugin('myPlugin', function() {
  // `this` is the player that has executed the plugin
  var player = this;

  player.ready(function() {
     // do something.... 

      // add something to the plugin instance so it's accessible from `player.myPlugin.someFunction()`
      this.myPlugin.someFunction = function() {
        ...
      };
  });
});
```

What you're describing is a component rather than a plugin. Usually (but you don't strictly need to) you'd have a plugin that's keeoing everything toogether, including and adding the custom components.

Any methods you define in your custom component would be acccessible in any case.

A common pattern is to add the component as a property of the parent component you're adding it to, like `videoPlayer.controlBar.qualityChanger = videoPlayer.controlBar.addChild("QualityChanger", { });`. Then you could call any of the component's methods with `videoPlayer.controlBar.qualityChanger.doSomething()`.

The standard player controls are added like this, so you can call e.g. `videoPlayer.controlBar.playToggle.hide()` for theplay button's `hide()` method.

**Comment by misteroneill** [comment]
To build on what Ben said, in cases where you want to give you plugin methods, state, logging, and the ability to fire events, we strongly suggest using a so-called "Advanced Plugin" - which is documented in the link Ben shared.

The short version is that an Advanced Plugin uses a class where a Basic Plugin uses a function.

**Comment by KianBadie** [comment]
@mister-ben @misteroneill Thank you very much for the detailed answers and resources! If someone wanted to add a custom component to the control bar, at what point do you think that component should be written as a plugin?

**Comment by misteroneill** [comment]
Closing this as "answered" but feel free to reopen if needed.
