### ISSUE TITLE
is this library maintained? examples on docs doesn't work

### ISSUE THREAD

**Issue by Nisthar** [videojs/video.js#7759]
I followed the example from the docs here https://videojs.com/guides/components/#what-is-a-component

https://codepen.io/Nisthar/pen/NWyRVKB

the button doesn't seems to be visible. The clicking doesn't seems to work.

**Comment by mister-ben** [comment]
Your codepen uses a very old version of Video.js, 5.11. You need at least 7.7.0 for the `clickHandler` option, and 7.19.0 for `controlText` and `className`.

The class in the example in the doc is wrong, I'll fix that. It's `vjs-visible-text` rather than `vjs-text-visible`.

The first button in your codepen is not visible as it is not added to the DOM, or added to a component which would add it to the DOM.

The second is there, but the button styles all assume the button is a child of the control bar; you'd need to add some styles for a player directly added to the player, as here: https://codepen.io/mister-ben/pen/oNGmOVv
