### ISSUE TITLE
audio append of 214921b failed for segment #0 in playlist 0-m3u8File.m3u8

### ISSUE THREAD

**Issue by Impre-visible** [videojs/video.js#7841]
### Description

I want to play some movies on my website, so I do my things, and with some movies, I have this error, I encode in live my files with this command : ``ffmpeg -hide_banner -loglevel error -ss 0:00:00 -to 0:00:05 -i G:\Films-Series-Emissions\Films/Despicable me 3.mkv -output_ts_offset 0:00:00 -c:v h264 -c:a aac -preset veryfast -f mpegts pipe:1``

### Steps to reproduce

1. DO some HLS streaming on ur back (mine is Flask)
2. Import your m3u8
3. Be disappointend 'cause some files don't play

### Errors

Audio append of ...

### What version of Video.js are you using?

v7.19.2

### What browser(s) including version(s) does this occur with?

Chrome 103

### What OS(es) and version(s) does this occur with?

Windows 10

**Comment by Impre-visible** [comment]
I'm back, and there's always the problem

**Comment by TrevorYS** [comment]
I have a same question in video.js version 7.20.3, The browser version is 69.0.3497.100. 

Error msg: The media could not be loaded, either because the …rk failed or because the format is not supported

**Comment by Impre-visible** [comment]
> I have a same question in video.js version 7.20.3, The browser version is 69.0.3497.100. 
> 
> Error msg: The media could not be loaded, either because the …rk failed or because the format is not supported

I found a way to repair that, with a map 0:0 as I remember, I go check

**Comment by Impre-visible** [comment]
here's my python command, : ```py
command = [
        "ffmpeg", "-hide_banner", "-loglevel", logLevelValue,"-i", video_path, "-c:v", "libx264", "-vf", f"scale={newHeight}:{newWidth}", "-c:a", "aac", "-b:a", "128k", "-ac", "2", "-preset", "ultrafast", "-f", "mpegts", "pipe:1",
    ]``` 
    as you can see, I change the codec, the scale, and the audio bitrate, but the more important, is the -ac 2 in my souvenir it's that a way to patch the problem.

**Comment by venomone** [comment]
Still existing with 7.20.3 ...
Really I don't understand this, we now have this bug about opened 3 times:

https://github.com/videojs/video.js/issues/7008
https://github.com/videojs/video.js/issues/7587  
https://github.com/videojs/video.js/issues/7841 -> This thread

And I could also open a 4th issue onto that. To me, it seems that we often see new features, but old bugs keep persisting.
I can't use VideoJS for HLS streaming in production, simply because each time I switch the quality, no matter on what device, I frequently drop into video append error until I restart the browser, clean the cache, then it's magically working again, and damn it sucks, can we please have this append issue on priority 1 super ultra critical as it's basically totally interrupting the playback experience ...

**Comment by venomone** [comment]
@Impre-visible are you using fragmented mp4 or ts segmented. Your cmd shows mpegts, From my understanding this issue only appears with fragmented mp4.

**Comment by Impre-visible** [comment]
You can't do fragpented mp4 in a m3u8 normally. Or am i wrong ?

**Comment by Impre-visible** [comment]
I check on knternet, you can, with m4s files

**Comment by Impre-visible** [comment]
@venomone you referenced to a video append, that's not the same problem

**Comment by venomone** [comment]
@Impre-visible I can confirm that fmp4 is compatible beside, it's even absolutely needed if you do HEVC streaming for example, there is no way around it. I also saw this issue with audio append errors, not only video. I already had this issue in various colors and forms, and it's really not about how I process a stream, its about how fmp4 get processes in my opnion. either this or VideoJS has a concrete bug nobody was able to find till now... Maybe you know [Nuevo](https://www.nuevodevel.com/nuevo/), the premium VIdeoJS player, even this piece of software has the same bucks with fmp4 but not with mpegts

**Comment by Impre-visible** [comment]
> @Impre-visible I can confirm that fmp4 is compatible. It's even absolutely needed if you do HEVC streaming for example, there is no way around it. I also saw this issue with audio append errors, not only video. I already had this issue in various colors and forms, and it's really not about how I process a stream, its about how fmp4 get processes in my opinion. Either this or VideoJS has a concrete BUG nobody was able to find till now... Maybe you know [Nuevo](https://www.nuevodevel.com/nuevo/), the premium VIdeoJS player, even this piece of software has the same bucks with fmp4 but not with mpegts. It really sucks

Did you tried ac -2 ? It patched the problem for me

**Comment by venomone** [comment]
@Impre-visible Currently not sure what "ac" parameter was, but I guess it's the audio channel mapping, or the amount of channels for the specific audio track, then yes I also tried it with Stereo instead of 7.1 or 5.1 sound with no difference according to this issue. I created a bug today, maybe you also find some answers here, not sure if it collides with your issue https://github.com/videojs/video.js/issues/7981 ;)

**Comment by Impre-visible** [comment]
The audio append error append when there's to many audio tracks (for me) -ac 2 will reduce the stereo to only two tracks. It patched the problem for me. Let's give it a tru

**Comment by venomone** [comment]
This is a very interesting information, I will try to validate onto that ... also using fmp4

**Comment by venomone** [comment]
@Impre-visible I just created a stream with 2 channel audio, the issue still appears (The media playback was aborted due to a corruption problem or because the media used features your browser did not support.). So I'm currently not sure what's the problem here. But I also have to say that I only checked with fmp4, not mpegts.

**Comment by Impre-visible** [comment]
> @Impre-visible I just created a stream with 2 channel audio, the issue still appears (The media playback was aborted due to a corruption problem or because the media used features your browser did not support.). So I'm currently not sure what's the problem here. But I also have to say that I only checked with fmp4, not mpegts.

Ok, try with mpegts, but I don't know for fmp4

**Comment by venomone** [comment]
@Impre-visible I've now built a simple stream only using h.264 and AAC @ 128 Kbps 2 channels stereo in four different languages. Interestingly, switching the quality now does NOT lead to an error. I can seamlessly switch between 480p, 720p and 1080p without any append error after 100x times switching and also after a VideoJS dispose call, so it seems to do exactly what it should do! Yeah :D

Then I created another stream, also using only h.264 but this time E-AC3 and AAC @ 384Kbps and 5.1 Channels. And the issue also does NOT appear with these settings. So Audio Channels do not make a difference for me.

All streams have been packed as mpegts segments (.ts files) this time!


I then repeated the whole test, but this time using fmp4 instead of mpegts, and there you have it, the quality switching breaks after switching a couple of times and even after a player dispose this issue persists for the next video you are watching. It keeps persisting until you restart the browser and clean the cache ...

**Comment by venomone** [comment]
@Impre-visible Also created some testing content to show the issue, please have a look here:

https://github.com/videojs/video.js/issues/7981

**Comment by Impre-visible** [comment]
> @Impre-visible I've now built a simple stream only using h.264 and AAC @ 128 Kbps 2 channels stereo in four different languages. Interestingly, switching the quality now does NOT lead to an error. I can seamlessly switch between 480p, 720p and 1080p without any append error after 100x times switching and also after a VideoJS dispose call, so it seems to do exactly what it should do! Yeah :D
> 
> Then I created another stream, also using only h.264 but this time E-AC3 and AAC @ 384Kbps and 5.1 Channels. And the issue also does NOT appear with these settings. So Audio Channels do not make a difference for me.
> 
> All streams have been packed as mpegts segments (.ts files) this time!
> 
> 
> I then repeated the whole test, but this time using fmp4 instead of mpegts, and there you have it, the quality switching breaks after switching a couple of times and even after a player dispose this issue persists for the next video you are watching. It keeps persisting until you restart the browser and clean the cache ...

So the problem is with fmp4, and I don't use that. Sorry 😄

**Comment by venomone** [comment]
I know, so I cannot really reproduce your issue then :(.
Can you maybe share your Video code Setup for VideoJS? Possibly we find something there, but I cannot imagine that this is about the audio channels. I also sometimes get an append error for Audio files, but mostly I get it for video ... so this more looks like an issue with the segments processing.

**Comment by misteroneill** [comment]
This issue has been open for a while, but we didn't get around to investigating it. If this is still an issue in a current version of Video.js, please open a new ticket with sufficient details including a reduced test case.
