### ISSUE TITLE
can not play on ios 

### ISSUE THREAD

**Issue by scientificCommunity** [videojs/video.js#7923]
### Discussed in https://github.com/videojs/video.js/discussions/7920

<div type='discussions-op-text'>

<sup>Originally posted by **scientificCommunity** September  9, 2022</sup>
can not play the video with type `application/x-mpegURL` in ios(safari or chrome), but can play on desktop.
here is the code:

```
<head>
    <title>Video.js | HTML5 Video Player</title>
    <link href="http://vjs.zencdn.net/7.0/video-js.min.css" rel="stylesheet">
    <script src="http://vjs.zencdn.net/7.0/video.min.js"></script>

</head>
 <video id="video_1" class="video-js vjs-default-skin" controls preload="auto" width="640" height="268"
         data-setup='{}'>
      <source src="https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8" type='application/x-mpegURL'>
  </video>
```

And, if I set Safari to request desktop sites or change the code in `video.min.js` like follows, it will be fine.
 ```
tt = /iPad/i.test(Je),
it = /iPhone/i.test(Je) && !tt,
```
to
```
tt = false,
it = false,
```
Can anyone help me？ thanks a lot!</div>

**Comment by mister-ben** [comment]
That stream plays fine in a simple player, e.g. https://codepen.io/mister-ben/pen/XWqjQBY?editors=1000. There must be some other factor in your implementation. A minimal test case would be needed to know any more.

**Comment by Paul-Hadfield** [comment]
That code pen works for me on my IPad too,  I found this issue because we're seeing something similar to this issue and [/  this one ](https://github.com/videojs/video.js/issues/7886).  For us, videos without DRM work fine, but our videos with DRM fail to play. For us, changing to desktop site doesn't help.   We don't have a replicable use-case at the moment, need to see if we can create one because it is licensed content behind authentication that is causing us issues.   The (since rolled back) chrome issue caused us to do a big jump from 7.8.2 (and 3.7.0 for videojs-contrib-eme) to the latest versions.  That broke playback in iOS devices.   We've since been able to roll back (since Chrome rolled back their breaking change) and the issue in iOS has gone away (I know it's a massive gap between versions which isn't that helpful)

**Comment by riksagar** [comment]
We're in the process of upgrading from 7.11.7 and we're seeing it too.  Issue is happening for us on 7.21.0.  It's intermittent, but 7.21.0 is better than 7.20.1 (which we assume is due to the fix for `requestVideoFrameCallback` ).

Don't have a simple test app to repro steps at this time.  I'll see what I can do.

**Comment by vicglarson** [comment]
https://drova.io/translations
examples of videos that do not play on ios but work fine in firefox and chrome. Is there a setting for hls to not use the native player or vice versa.

**Comment by ricardorodarte** [comment]
Hi, did you find any solution? I used videojs with React in a nextjs environment, everythings works fine but NOT on iphone, on android and web the player is working fine. I tried everything and still I don't know why on iOS devices is not working.
