### ISSUE TITLE
Chrome 105 on MacOS 12.2 (21D49) not displaying encrypted video over Screen Mirroring (AirPlay) using Video.JS 7.20.2, and the EME plugin 5.0.1

### ISSUE THREAD

**Issue by nick-myers-dt** [videojs/video.js#7932]
### Description

Video.JS with contrib-eme plugin does not display video when using Chrome Version 105.0.5195.125 on MacOS Monterey 12.2 and using Screen Mirroring (AirPlay) to Apple TV.  Audio can be heard.

Safari, Edge, Firefox all work.

### Reduced test case

https://codepen.io/nick-myers-dt/pen/OJZbogL

### Steps to reproduce

1. Using latest version of Chrome on MacOS Monterey
2. Open https://codepen.io/nick-myers-dt/pen/OJZbogL
3. Mirror Screen to Apple TV 
4. Observe video is now black/blank (audio can be heard)

### Errors

No errors in player or console, and no video is displayed.

![Screenshot 2022-09-15 at 16 32 49](https://user-images.githubusercontent.com/57220787/190448348-364efa7e-499e-43ca-9348-50ae2a68f131.png)

### What version of Video.js are you using?

7.20.2

### Video.js plugins used.

videojs-contrib-eme@5.0.1

### What browser(s) including version(s) does this occur with?

Chrome 105.0.5195.125

### What OS(es) and version(s) does this occur with?

MacOS Monterey 12.2 (21D49)

**Comment by nick-myers-dt** [comment]
Also raised in other projects (because I have no idea where the issue lies):

Chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=1364125
Apple Support Community (the long shot): https://discussions.apple.com/thread/254197199
VideoJS-contrib-eme: https://github.com/videojs/videojs-contrib-eme/issues/174

**Comment by evanluu** [comment]
I have the same issue with

- video.js@7.20.3
- videojs-contrib-eme@5.0.1

I can AirPlay with any kind of video format. But with the decrypted video (DRM Fairplay) I can play, but can't use Airplay (the black screen and loading endlessly). Please advise!!!

**Comment by mister-ben** [comment]
It's not in the control of Video.js or contrib-eme. It's the content decryption module that blanks the video if the playback pathway is considered not secure enough to prevent recording. If you disable hardware acceleration in Chrome, you'll either find you can airplay, because the software decryption can't blank the video, or that the doesn't play at all depending on whether the DRM licence doesn't allow less secure decryption. I'm more surprised Fairplay/Safari isn't blanking the video. Apple would say stream the video to Airplay instead of screen mirroring - https://github.com/silvermine/videojs-airplay/ is a plugin you might try.

**Comment by nick-myers-dt** [comment]
Thanks @mister-ben.  Will take a look at the plugin you mentioned.

I was surprised as prior to Chrome 105, this was working fine.
