### ISSUE TITLE
Quality levels an empty array in Safari 16.4

### ISSUE THREAD

**Issue by osanzharevskyy** [videojs/video.js#8245]
Chrome [https://ibb.co/wdzLDsF](url)
Safari [https://ibb.co/tsVm8jf](url)

video.js: 7.21.1,
videojs-contrib-quality-levels: 3.0.0

Safari 16.4
macOS Ventura 13.3.1

**Comment by gkatsev** [comment]
By default, Video.js will play back HLS using native playback. In Safari, native playback doesn't provide a way to get quality levels. This is expected behavior.
It's possible to use [overrideNative](https://github.com/videojs/http-streaming#overridenative) to force Safari to use our playback engine, which will provide quality levels, but it's worth noting that it won't work on iPhones.
