### ISSUE TITLE
How to block the DRM video while sharing the google meet calls

### ISSUE THREAD

**Issue by manikantakch** [videojs/video.js#8516]
### Description

while sharing the google meet The DRM video content is playing as usual so i want to block the DRM content while on google meet calls what is the way to solve this

### Reduced test case

https://googlemeet.in

### Steps to reproduce

1. we are Playing the DRM content using videojs the video is playing fine but
2. when you will go to the google meets and share the screen The DRM content is not blocked the video is playing as usual.
3. So i want to block my DRM video while sharing the screens or some error messages will display as like js player
4. keySystems currently widevine for DRM on Chrome

### What version of Video.js are you using?

v10.2.0

### What browser(s) including version(s) does this occur with?

chrome

### What OS(es) and version(s) does this occur with?

all

**Comment by mister-ben** [comment]
The player (or any javascript) can't detect screen recording in order to blank the video, it happens at a lower level than that. There are platforms that support hardware DRM that can detect screen recording and blank the video, and those that support only software DRM that cannot. The DRM licences you issue specify what level of secure playback is required. You should speak with your DRM vendor about the configuration options available.

**Comment by manikantakch** [comment]
"As we have checked with our provider Chrome supports only L3 licenses, and that's what they were passing. 
if we switch the level of secure playback to L2 or L1 the video is not  playing in chrome (web) and we have check it with Widevine documentation"

can you please check once :- https://github.com/videojs/video.js/issues/8516
