### ISSUE TITLE
Changing audio language changes captions back to English in Safari

### ISSUE THREAD

**Issue by jolson88** [videojs/video.js#8556]
### Description

I have a video where there are both text tracks and audio tracks of a series of languages. On Safari or iOS, the choice of caption language is not being preserved when audio language is changed.

For example, assume we have a video that has subtitles and audio tracks for English (default), Spanish, and Japanese. I play the video, I change the captions to Spanish. After the captions change to Spanish, I change the audio language to Japanese.

**Expected Behavior:** The captions remain to be Spanish. This is the behavior on Chrome and other browsers (we believe when emulatedTracks are used).

**Actual Behavior:** After switching the language to Japanese, the captions also change back to English. 

### Reduced test case

https://codepen.io/Jason-Olson-the-bold/pen/ExMNvPv

### Steps to reproduce

1. Play video
2. Change captions to Spanish
3. Change audio language to Japanese

### What version of Video.js are you using?

8.9.0

### Video.js plugins used.

None

### What browser(s) including version(s) does this occur with?

Safari 17

### What OS(es) and version(s) does this occur with?

Mac Ventura, IOS 16, IOS 17

**Comment by jolson88** [comment]
Was kind of curious if this is possibly at all related to https://github.com/videojs/video.js/issues/8554 as they both involve behaviors that work with emulated tracks but not with the native tracks in Safari/iOS. We are not experts though, so that may be a red-herring.

**Comment by mister-ben** [comment]
There's no code within Video.js to select a text track automatically on audio track change. Since this is Safari it's native playback and native tracks, so this may be Safari trying to honour a user preference or something like that. There's no change of caption track when I try your example on Safari 17 on Sonoma, or on Browserstack's iOS "real devices". Does the same source behave the same on a simple video element on your devices?
